import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";
import {spawnSync} from "node:child_process";
import {AI_VERSION} from "../showdown/choice";
import {buildEvidenceEpoch, LEAGUE_CONFIGURATION_POLICY_VERSION, sha256 as canonicalSha} from "../showdown/evidenceEpoch";
import {validateRegistryDirectory} from "../draft/registrySnapshot";

const fixture = fs.mkdtempSync(path.join(os.tmpdir(), "mythic-ai-pipeline-")), tooling = path.join(fixture, "tooling"), league = path.join(fixture, "league");
try {
  fs.mkdirSync(league, {recursive: true}); const state = path.join(league, "dynasty-state.json"); write(state, {version: 12, completedSeason: 1}); const stat = fs.statSync(state), stateSha = "a".repeat(64), signature = crypto.createHash("sha256").update(`dynasty-state.json\0${stateSha}\0`).digest("hex"), epoch = buildEvidenceEpoch(AI_VERSION, "gen9ou");
  write(path.join(league, ".audit-signature-cache.json"), {schemaVersion: 1, files: {"dynasty-state.json": {sha256: stateSha, size: stat.size, mtimeMs: stat.mtimeMs}}});
  write(path.join(league, "audit-summary.json"), {schemaVersion: 6, inputSignature: signature, fatalCount: 0, completedSeasons: 1, evidenceEpoch: {policySha256: epoch.policySha256, auditedBattles: 1, formalActivationReady: false}}); write(path.join(league, "audit-run-state.json"), {status: "complete"});
  writeStage("decision-dossiers", {healthy: true, anomalies: [], decisions: 10, managers: 2, inputSignature: "s1", sourceAuditSignature: signature, currentPolicySha256: epoch.policySha256, formalDecisionCoverageReady: false, battleCoverage: {representedBattles: 1}}, "build-state.json");
  writeStage("position-value-stage2", {inputSignature: "s2", battles: 2, samples: 20, model: {sha256: "b".repeat(64)}, testImprovement: {vsConstantLogLossPercent: 2}, audit: {healthy: true, formalActivationAllowed: false, issues: []}}, "build-state.json"); write(path.join(tooling, "position-value-stage2", "model.json"), {sha256: "b".repeat(64)});
  write(path.join(tooling, "position-value-corpus-v1", "corpus-manifest.json"), {schemaVersion: 1});
  writeStage("manager-program-v2", {inputSignature: "s3", formalActivationAllowed: false, population: {managers: 2, uniqueBehaviorHashes: 2}, evaluation: {improvementPercent: 1}, audit: {healthy: true, issues: []}}, "build-state.json"); writeGzip(path.join(tooling, "manager-program-v2", "corpus.json.gz"), {signature: "s3", modelSha256: "b".repeat(64)}); writeGzip(path.join(tooling, "manager-program-v2", "programs.json.gz"), {programs: [{evidence: {corpusSignature: "s3", positionModelSha256: "b".repeat(64)}}]});
  const stage3Root = path.join(tooling, "manager-program-v2"), stage4Root = path.join(tooling, "autonomous-research-stage4-delivery-v2"), benchmarkIndex = path.resolve("benchmarks/gen9expanded/index.json"), registryHash = validateRegistryDirectory(path.resolve("data/draft")).hash, benchmark = JSON.parse(fs.readFileSync(benchmarkIndex, "utf8")), formalEpoch = buildEvidenceEpoch(AI_VERSION, benchmark.format, {registryHash, configurationPolicyVersion: LEAGUE_CONFIGURATION_POLICY_VERSION});
  const s4Inputs = {programs: fingerprint(path.join(stage3Root, "programs.json.gz")), corpus: fingerprint(path.join(stage3Root, "corpus.json.gz")), stage3Summary: fingerprint(path.join(stage3Root, "summary.json"))}, s4Signature = jsonSha(s4Inputs);
  writeStage("autonomous-research-stage4-delivery-v2", {inputSignature: s4Signature, formalActivationAllowed: false, managers: 2, completedRounds: 0, experiments: 0, research: {managersAdapted: 0}, audit: {healthy: true, issues: []}}, "run-state.json"); write(path.join(stage4Root, "manifest.json"), {schemaVersion: 1, inputs: s4Inputs, inputSignature: s4Signature, rounds: []}); writeGzip(path.join(stage4Root, "manager-states.json.gz"), []);
  const s5Inputs = {stage4States: fingerprint(path.join(stage4Root, "manager-states.json.gz")), stage4Summary: fingerprint(path.join(stage4Root, "summary.json")), programs: fingerprint(path.join(stage3Root, "programs.json.gz")), positionModel: fingerprint(path.join(tooling, "position-value-stage2", "model.json")), benchmarkIndex: fingerprint(benchmarkIndex)}, s5Signature = canonicalSha(s5Inputs), freezeCore = {schemaVersion: 1, inputs: s5Inputs, inputSignature: s5Signature, evidenceEpoch: {policySha256: formalEpoch.policySha256, registryHash, configurationPolicyVersion: LEAGUE_CONFIGURATION_POLICY_VERSION}, environments: ["balanced", "pressure"], domains: [], gate: {targetCases: 1, minimumCasesPerEnvironment: 1, minimumDecisiveCases: 1, familywiseAlpha: .1, maximumCasesPerBattle: 1, zeroUnresolvedTechnicalFailures: true}}, freeze = {...freezeCore, sha256: canonicalSha(freezeCore)};
  const formalExperiments = {planned: 0, completed: 0, technicalAttempts: 0, unresolvedTechnicalFailures: 0, fallbackSelections: 0, outcomeChanges: 0, uniqueBattlesUsed: 0, reservedBattles: 0}; writeStage("formal-validation-stage5-delivery-v2", {inputSignature: s5Signature, freezeSha256: freeze.sha256, formalValidationCompleted: true, automaticActivationAllowed: false, limitedCanaryEligibleDomains: [], domains: [], sources: {battles: 4}, experiments: formalExperiments, audit: {healthy: true, issues: []}}, "run-state.json"); const freezeFile = path.join(tooling, "formal-validation-stage5-delivery-v2", "freeze.json"); write(freezeFile, freeze); const planCore = {schemaVersion: 1, freezeSha256: freeze.sha256, items: []}, plan = {...planCore, sha256: canonicalSha(planCore)}; write(path.join(tooling, "formal-validation-stage5-delivery-v2", "plan.json"), plan); const resultCore = {schemaVersion: 1, planSha256: plan.sha256, cases: [], technicalAttempts: 0, unresolvedTechnicalFailures: 0, fallbackSelections: 0}; writeGzip(path.join(tooling, "formal-validation-stage5-delivery-v2", "results.json.gz"), {...resultCore, sha256: canonicalSha(resultCore)});
  const healthy = invoke("status"); assert.equal(healthy.evaluation.operationalHealthy, true, JSON.stringify(healthy)); assert.equal(healthy.evaluation.nextStage, null); assert.deepEqual(healthy.evaluation.nextMilestones, ["current-era-evidence", "research-iteration"]); assert.equal(healthy.indexFresh, true);
  write(freezeFile, {...freeze, tamperedGate: true}); const tamperedFreeze = invoke("status"); assert.equal(tamperedFreeze.evaluation.stages.find((value: any) => value.id === "stage5").state, "blocked"); write(freezeFile, freeze); invoke("refresh");
  const formalSummaryFile = path.join(tooling, "formal-validation-stage5-delivery-v2", "summary.json"), formalSummary = JSON.parse(fs.readFileSync(formalSummaryFile, "utf8")); write(formalSummaryFile, {...formalSummary, limitedCanaryEligibleDomains: ["forged-domain"]}); const tamperedSummary = invoke("status"); assert.equal(tamperedSummary.evaluation.stages.find((value: any) => value.id === "stage5").state, "blocked"); write(formalSummaryFile, formalSummary); invoke("refresh");
  const s4ManifestFile = path.join(stage4Root, "manifest.json"), s4SummaryFile = path.join(stage4Root, "summary.json"), s4Summary = JSON.parse(fs.readFileSync(s4SummaryFile, "utf8")); write(s4ManifestFile, {schemaVersion: 1, inputs: {}, inputSignature: canonicalSha({}), rounds: []}); write(s4SummaryFile, {...s4Summary, inputSignature: canonicalSha({})}); const unbound = invoke("status"); assert.equal(unbound.evaluation.stages.find((value: any) => value.id === "stage4").state, "blocked"); write(s4ManifestFile, {schemaVersion: 1, inputs: s4Inputs, inputSignature: s4Signature, rounds: []}); write(s4SummaryFile, s4Summary); invoke("refresh");
  const dossierSummary = path.join(tooling, "decision-dossiers", "summary.json"), dossier = JSON.parse(fs.readFileSync(dossierSummary, "utf8")); write(dossierSummary, {...dossier, sourceAuditSignature: "stale"}); const stale = invoke("status"); assert.equal(stale.evaluation.stages.find((value: any) => value.id === "stage1").state, "blocked"); write(dossierSummary, dossier); invoke("refresh");
  write(path.join(tooling, "autonomous-research-stage4-delivery-v2", "run-state.json"), {status: "failed"}); const failed = invoke("status"); assert.equal(failed.evaluation.nextStage, "stage4"); assert.equal(failed.evaluation.stages.find((value: any) => value.id === "stage5").state, "blocked");
  const resume = invoke("resume", "--dry-run"); assert.deepEqual(resume.planned.map((value: any) => value.stage), ["stage4", "stage5"]);
  const numeric = invoke("run", "--stage", "5", "--force", "--dry-run"); assert.deepEqual(numeric.planned.map((value: any) => value.stage), ["stage5"]);
  write(path.join(tooling, "autonomous-research-stage4-delivery-v2", "run-state.json"), {status: "complete"}); const forced = invoke("run", "--force", "--dry-run"); assert.deepEqual(forced.planned.map((value: any) => value.stage), ["stage1", "stage2", "stage3", "stage4", "stage5"]);
  console.log("AI pipeline CLI smoke passed: compact index, invalidation, downstream blocking, and checkpoint-free resume planning");
} finally { fs.rmSync(fixture, {recursive: true, force: true}); }

function writeStage(name: string, summary: unknown, runName: string): void { const directory = path.join(tooling, name); write(path.join(directory, "summary.json"), summary); write(path.join(directory, runName), {status: "complete"}); }
function invoke(command: string, ...extra: string[]): any { const result = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.resolve("src/cli/aiPipeline.ts"), command, "--root", tooling, "--league", league, ...extra], {cwd: process.cwd(), encoding: "utf8"}); if (result.status !== 0) throw new Error(result.stderr || result.stdout); return JSON.parse(result.stdout); }
function write(file: string, value: unknown): void { fs.mkdirSync(path.dirname(file), {recursive: true}); fs.writeFileSync(file, `${JSON.stringify(value)}\n`, "utf8"); }
function writeGzip(file: string, value: unknown): void { fs.mkdirSync(path.dirname(file), {recursive: true}); fs.writeFileSync(file, zlib.gzipSync(Buffer.from(JSON.stringify(value)))); }
function fingerprint(file: string): {file: string; sha256: string; bytes: number} { const bytes = fs.readFileSync(file); return {file: path.resolve(file), sha256: crypto.createHash("sha256").update(bytes).digest("hex"), bytes: bytes.length}; }
function jsonSha(value: unknown): string { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
