import assert from "node:assert/strict";
import {buildAutonomousResearchAgenda, createAutonomousResearchState, reviewAutonomousResearchRound, summarizeAutonomousResearch, validateAutonomousResearchState, type AutonomousResearchResult} from "../ai/autonomousResearch";
import {noviceManagerProgramV2, validateManagerProgramV2} from "../ai/managerProgramV2";
import {formalMechanismKey} from "../ai/formalValidation";

const program = noviceManagerProgramV2("manager-01", {decisionDossierPolicy: "policy", positionModelSha256: "a".repeat(64), corpusSignature: "b".repeat(64)});
program.rules.push({id: "rule-switch-pressure", domain: "battle", target: "switch", predicates: [{feature: "positionValue", operator: "lt", threshold: 0}], effect: -.08, support: 40, uncertainty: .25, authority: "local-value-observational", evidenceIds: ["sample-1"]});
validateManagerProgramV2(program);
let state = createAutonomousResearchState("manager-01");
const first = buildAutonomousResearchAgenda({program, state, round: 1, feasibleCases: {"rule-switch-pressure": 12}, seed: "research-smoke"});
assert.equal(first.selected?.intent, "test-program-mechanism");
assert.equal(first.selected?.expectedInterventionDirection, "better");
const abundant = buildAutonomousResearchAgenda({program, state, round: 1, feasibleCases: {"rule-switch-pressure": 10000}, seed: "research-smoke"}); assert.equal(abundant.selected?.components.applicability, 1);
const replacement = structuredClone(program); replacement.rules[0].id = "rule-replacement"; replacement.revision = 1; replacement.history.push({revision: 1, hypothesisId: "rule-replacement", target: "switch", predicates: replacement.rules[0].predicates, discoveryGain: .01, validationGain: -.001, accepted: false, reason: "validation-regression", evidenceAuthority: "local-value-observational"}); validateManagerProgramV2(replacement); const replacementAgenda = buildAutonomousResearchAgenda({program: replacement, state, round: 1, feasibleCases: {"rule-replacement": 8}, seed: "research-smoke"}); assert.equal(replacementAgenda.selected?.intent, "replace-rejected-mechanism");
const supportive: AutonomousResearchResult = {questionId: first.selected!.id, managerId: "manager-01", ruleId: first.selected!.ruleId, round: 1, caseId: "case-1", direction: "better", expectedDirection: "better", trajectoryChanged: true, winnerChanged: true, sourceVerified: true, prefixVerified: true, interventionVerified: true, sourceFingerprint: "c".repeat(64)};
state = reviewAutonomousResearchRound(state, first, supportive); validateAutonomousResearchState(state); assert.equal(state.observations[0].supportsHypothesis, true);
const second = buildAutonomousResearchAgenda({program, state, round: 2, feasibleCases: {"rule-switch-pressure": 11}, seed: "research-smoke"}); assert.equal(second.selected?.intent, "replicate-support");
const contradictory: AutonomousResearchResult = {...supportive, questionId: second.selected!.id, round: 2, caseId: "case-2", direction: "worse", sourceFingerprint: "d".repeat(64)};
state = reviewAutonomousResearchRound(state, second, contradictory);
const inconsistent = structuredClone(state); inconsistent.observations[0].supportsHypothesis = false;
assert.throws(() => validateAutonomousResearchState(inconsistent), /Invalid autonomous research observations/);
const third = buildAutonomousResearchAgenda({program, state, round: 3, feasibleCases: {"rule-switch-pressure": 10}, seed: "research-smoke"}); assert.equal(third.selected?.intent, "resolve-contradiction");
assert.equal((summarizeAutonomousResearch([state]) as any).contradictions, 1);
assert.throws(() => reviewAutonomousResearchRound(state, third, {...contradictory, questionId: third.selected!.id, round: 3, caseId: "case-2"}), /Invalid autonomous research result/);
const blocked = buildAutonomousResearchAgenda({program, state, round: 3, feasibleCases: {}, seed: "research-smoke"}); assert.equal(blocked.selected, null); assert.equal(blocked.blockedRules.length, 1);
const mechanismKey = formalMechanismKey(program.rules[0]);
const rejected = buildAutonomousResearchAgenda({program, state, round: 3, feasibleCases: {"rule-switch-pressure": 10}, seed: "research-smoke", formalFeedback: {[mechanismKey]: {mechanismKey, disposition: "rejected", generations: 1, cases: 24, supports: 4, contradictions: 12, neutral: 8, reasons: ["contradicted"]}}});
assert.equal(rejected.selected?.intent, "replace-rejected-mechanism"); assert.equal(rejected.selected?.ruleId, "rule-switch-pressure");
const inconclusive = buildAutonomousResearchAgenda({program, state, round: 3, feasibleCases: {"rule-switch-pressure": 10}, seed: "research-smoke", formalFeedback: {[mechanismKey]: {mechanismKey, disposition: "inconclusive", generations: 1, cases: 24, supports: 5, contradictions: 3, neutral: 16, reasons: ["too few winner-changing interventions"]}}});
assert.equal(inconclusive.selected?.intent, "resolve-formal-inconclusive"); assert.equal(inconclusive.selected?.components.evidenceNeed, .85);
console.log("Autonomous research smoke passed: question generation, feasibility, exact-result validation, replication, contradiction adaptation, and case deduplication");
