import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {spawnSync} from "node:child_process";
import crypto from "node:crypto";
import {benchmarkFamilyDoctor, benchmarkPairClusterId, signBattleFamilyEvidence, type BenchmarkFamilyRegistry, type BenchmarkFamilySchedule} from "../draft/benchmarkFamilies";
import {loadCorpusEvidenceAuthority} from "../draft/corpusEvidenceAuthority";
import {sha256} from "../showdown/evidenceEpoch";

const temporary = fs.mkdtempSync(path.join(os.tmpdir(), "mythic-benchmark-families-")), root = path.join(temporary, "families"), nextRoot = path.join(temporary, "families-v2"), cli = path.resolve("src/cli/benchmarkFamilies.ts");
try {
  const build = spawnSync(process.execPath, [require.resolve("tsx/cli"), cli, "build", "--root", root], {cwd: process.cwd(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024}); assert.equal(build.status, 0, build.stderr);
  const doctor = benchmarkFamilyDoctor(root) as any; assert.equal(doctor.healthy, true); assert.equal(doctor.researchFamilies, 64); assert.equal(doctor.holdoutFamilies, 24); assert.equal(doctor.pairs, 464); assert.equal(doctor.projectedBattles, 2784);
  const registry = read<BenchmarkFamilyRegistry>(path.join(root, "family-registry.json")), schedule = read<BenchmarkFamilySchedule>(path.join(root, "schedule.json")), splitFamilies = new Map<string, Set<string>>(); for (const family of registry.families) splitFamilies.set(family.split, new Set([...(splitFamilies.get(family.split) ?? []), family.id]));
  assert.equal(registry.id, "gen9-independent-family-pool-v1"); assert.equal(registry.families[0].id.startsWith("bf-v1-"), false);
  assert.equal([...splitFamilies.get("train")!].some(id => splitFamilies.get("test")!.has(id)), false); assert.equal(schedule.pairs.filter(pair => pair.split === "train").length, 224); assert.equal(schedule.pairs.filter(pair => pair.split === "validation").length, 120); assert.equal(schedule.pairs.filter(pair => pair.split === "test").length, 120);
  const team = path.join(root, registry.families[0].variants[0].team), original = fs.readFileSync(team); fs.appendFileSync(team, "\n"); assert.equal((benchmarkFamilyDoctor(root) as any).healthy, false); fs.writeFileSync(team, original);
  const nextBuild = spawnSync(process.execPath, [require.resolve("tsx/cli"), cli, "build", "--root", nextRoot, "--generation", "v2"], {cwd: process.cwd(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024}); assert.equal(nextBuild.status, 0, nextBuild.stderr); const nextRegistry = read<BenchmarkFamilyRegistry>(path.join(nextRoot, "family-registry.json")); assert.equal(nextRegistry.id, "gen9-independent-family-pool-v2"); assert.equal(nextRegistry.families.every(family => family.id.startsWith("bf-v2-")), true); assert.equal(nextRegistry.families.some(family => registry.families.some(old => old.id === family.id)), false); assert.notEqual(nextRegistry.sha256, registry.sha256); assert.notEqual(fs.readFileSync(path.join(nextRoot, nextRegistry.families[0].variants[0].team), "utf8"), fs.readFileSync(path.join(root, registry.families[0].variants[0].team), "utf8"));
  const corpus = path.join(temporary, "indexed-corpus"), game = path.join(corpus, "battles", "case-1", "game-0001"), familyIds: [string, string] = ["train-left", "train-right"], evidence = signBattleFamilyEvidence({schemaVersion: 1, version: "benchmark-families-v1", registrySha256: "a".repeat(64), scheduleSha256: "b".repeat(64), pairClusterId: benchmarkPairClusterId("train", familyIds), split: "train", authority: "research", familyIds, environment: "modern-standard", variants: ["base", "configuration-b"]}); write(path.join(game, "benchmark-evidence.json"), evidence); write(path.join(game, "replay-input.json"), {seed: 1}); write(path.join(game, "ai-decisions.json"), []); write(path.join(game, "end.json"), {winner: null}); const entry = {id: "case-1", game: "battles/case-1/game-0001", evidenceSha256: fileSha(path.join(game, "benchmark-evidence.json")), replaySha256: fileSha(path.join(game, "replay-input.json")), decisionsSha256: fileSha(path.join(game, "ai-decisions.json")), endSha256: fileSha(path.join(game, "end.json")), pairClusterId: evidence.pairClusterId}, manifestCore = {schemaVersion: 1, corpusVersion: "position-value-family-corpus-v3-case-index", index: {authority: "research"}, familyDesign: {splitAuthority: "research", registrySha256: "a".repeat(64), scheduleSha256: "b".repeat(64)}, evidenceIndex: [entry], settings: {jobs: 1}, results: {complete: 1, failures: 0}}; write(path.join(corpus, "corpus-manifest.json"), {...manifestCore, sha256: sha256(manifestCore)}); assert.equal(loadCorpusEvidenceAuthority(corpus, "research").cases.size, 1); const originalEvidence = fs.readFileSync(path.join(game, "benchmark-evidence.json")); write(path.join(game, "benchmark-evidence.json"), {...evidence, pairClusterId: "train:forged"}); assert.throws(() => loadCorpusEvidenceAuthority(corpus, "research"), /drifted|signed/); fs.writeFileSync(path.join(game, "benchmark-evidence.json"), originalEvidence);
  console.log("Benchmark family smoke passed: generation-isolated research pools, backward-compatible v1 identities, family-disjoint splits, signatures, and tamper detection");
} finally { fs.rmSync(temporary, {recursive: true, force: true}); }
function read<T>(file: string): T { return JSON.parse(fs.readFileSync(file, "utf8")) as T; }
function write(file: string, value: unknown): void { fs.mkdirSync(path.dirname(file), {recursive: true}); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, "utf8"); }
function fileSha(file: string): string { return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); }
