import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";
import {spawnSync} from "node:child_process";
import {areLineagesRelated, founderCapacity} from "../draft/lineageDiversity";
import {cloneManagerProfile, createNoviceProfiles, materializeManagerProfile} from "../draft/managerProfiles";
import {personalitySimilarity} from "../draft/personalitySimilarity";
import {assessManagerLifecycle} from "../draft/managerLifecycle";
import {applyAcademyDevelopment, buildAcademyEnvironment, createAcademyState, evolveAcademyState} from "../draft/academyEnvironment";
import {managerMarketPreferences, runAcademyTalentMarket} from "../draft/academyTalentMarket";
import {academyFinancialControls, academyFinancialHealth, academyRecoveryRecords, settleAcademyContracts, settleSalaryGuarantees} from "../draft/academyContracts";

const founderA = {lineageId: "founder:a", generation: 0, parentLineageIds: [], founderId: "a", birthSeason: 0, niche: "test", mutations: []};
const childA = {lineageId: "child:a", generation: 1, parentLineageIds: [founderA.lineageId], founderId: "a", birthSeason: 1, niche: "test", mutations: []};
const siblingA = {...childA, lineageId: "sibling:a"};
const founderB = {...founderA, lineageId: "founder:b", founderId: "b"};
assert.equal(founderCapacity(6, 17), 2);
assert(areLineagesRelated({lineage: childA, lineageHistory: [founderA, childA]}, {lineage: siblingA, lineageHistory: [founderA, siblingA]}, 1));
assert(!areLineagesRelated({lineage: childA, lineageHistory: [founderA, childA]}, {lineage: founderB, lineageHistory: [founderB]}, 2));
assert(!areLineagesRelated({lineage: childA, lineageHistory: [founderA, childA]}, {lineage: siblingA, lineageHistory: [founderA, siblingA]}, 0));
const similarityBase = createNoviceProfiles(1)[0], similarityClone = cloneManagerProfile(similarityBase), similarityContrast = cloneManagerProfile(similarityBase);
similarityContrast.traits = {risk: .9, stars: .1, synergy: .9, counter: .1, value: .9, flexibility: .1};
similarityContrast.economics = {starPremium: .9, cashUtility: .1, bidAggression: .9, marketAwareness: .1};
similarityContrast.learning = {rate: .9, exploration: .1, memoryDecay: .2};
similarityContrast.tactics = {...similarityContrast.tactics, aggression: 1, setupBias: -1, pivotBias: 1, recoveryBias: -1, statusBias: 1, teraBias: -1, switchBias: 1};
similarityContrast.preferredRoles = ["hazards", "setup", "priority"];
assert.equal(personalitySimilarity(similarityBase, similarityClone).similarity, 1);
assert(personalitySimilarity(similarityBase, similarityContrast).similarity < .85);
const lifecyclePolicy = {maturitySeasons: 2, fertilityMaxSeasons: 4, retirementMinSeasons: 6, retirementHardSeasons: 8, retirementBasePercent: 25, retirementGrowthPercent: 25};
assert.equal(assessManagerLifecycle(1, lifecyclePolicy, "lifecycle").phase, "juvenile");
assert(assessManagerLifecycle(2, lifecyclePolicy, "lifecycle").parentEligible);
assert.equal(assessManagerLifecycle(5, lifecyclePolicy, "lifecycle").phase, "post-fertility");
assert.equal(assessManagerLifecycle(6, lifecyclePolicy, "lifecycle").retirementProbability, .25);
const forcedRetirement = assessManagerLifecycle(8, lifecyclePolicy, "lifecycle");
assert.equal(forcedRetirement.phase, "forced-retirement");
assert.equal(forcedRetirement.retirementProbability, 1);
assert(forcedRetirement.retires);
assert.equal(forcedRetirement.reason, "hard-limit");
const academyChild = createNoviceProfiles(1)[0], academyTraditionDraft = cloneManagerProfile(academyChild);
academyTraditionDraft.traits = {risk: .8, stars: .7, synergy: .8, counter: .3, value: .7, flexibility: .8};
const academyTradition = materializeManagerProfile(academyTraditionDraft), academyEnvironment = buildAcademyEnvironment("academy-test", "Academy Test", academyTradition);
const academyDeveloped = applyAcademyDevelopment(academyChild, academyEnvironment, .2), academyDisabled = applyAcademyDevelopment(academyChild, academyEnvironment, 0);
assert(academyDeveloped.evidence.similarityAfter > academyDeveloped.evidence.similarityBefore);
assert(academyDeveloped.evidence.strategyProgramUnchanged);
assert(Object.values(academyDeveloped.evidence.parameterDeltas).some(delta => Math.abs(delta) > 1e-9));
assert.equal(personalitySimilarity(academyChild, academyDisabled.profile).similarity, 1);
const academyState = createAcademyState("academy-test", "Academy Test", academyChild);
const evolvedAcademy = evolveAcademyState(academyState, [{childId: "graduate-1", status: "promoted", averageRank: 1, capacity: 6, profile: academyTradition}], 2, .1);
assert.equal(evolvedAcademy.revision, 1);
assert(evolvedAcademy.quality > academyState.quality);
assert.equal(evolvedAcademy.latestEvidence?.cultureModelChildId, "graduate-1");
assert.equal(evolvedAcademy.latestEvidence?.qualityBefore, academyState.quality);
assert(Math.abs(evolvedAcademy.latestEvidence!.budgetBefore + evolvedAcademy.latestEvidence!.grant + evolvedAcademy.latestEvidence!.performanceRevenue - evolvedAcademy.latestEvidence!.spend - evolvedAcademy.latestEvidence!.budgetAfter) < 1e-9);
assert(Math.abs(Object.values(evolvedAcademy.allocations).reduce((sum, value) => sum + value, 0) - 1) < 1e-9);
const unfundedState = createAcademyState("academy-unfunded", "Academy Unfunded", academyChild, 0), unfundedEvolution = evolveAcademyState(unfundedState, [{childId: "graduate-1", status: "promoted", averageRank: 1, capacity: 6, profile: academyTradition}], 2, .1, {grant: 0, maximumSpend: 0, performanceRevenueRate: 0});
assert.equal(unfundedEvolution.latestEvidence?.spend, 0);
assert.equal(unfundedEvolution.quality, unfundedState.quality);
assert.equal(unfundedEvolution.latestEvidence?.cultureModelChildId, undefined);
const otherAcademy = createAcademyState("academy-other", "Academy Other", academyTradition, 30), marketCandidate = {childId: "market-child", childName: "Market Child", rightsHolderId: academyState.academyId, optionYears: 0, annualSalary: 2, contractYears: 0, profile: academyTradition};
const marketRules = {policy: "shadow" as const, consentPolicy: "ignore" as const, consentThreshold: .5, contractPolicy: "ignore" as const, baseSalary: 3, maximumSalary: 10, prepaidSeasons: 1, contractYears: 3, maximumTransactions: 1, signingFee: 10, transferFee: 15, loanFee: 5, transferMinimumFitDelta: .15, loanMinimumFitDelta: .05, freeAgentOptionYears: 3};
const preferences = managerMarketPreferences({...marketCandidate, averageRank: 6, capacity: 6});
assert(Object.values(preferences).every(value => value >= 0 && value <= 1));
assert.equal(preferences.opportunityNeed, 1);
const shadowMarket = runAcademyTalentMarket([marketCandidate], [academyState, otherAcademy], marketRules);
assert.equal(shadowMarket.transactions[0].status, "proposed");
assert.equal(shadowMarket.assignments[marketCandidate.childId].rightsHolderId, academyState.academyId);
assert.deepEqual(shadowMarket.balances, {[academyState.academyId]: 30, [otherAcademy.academyId]: 30});
const activeSigning = runAcademyTalentMarket([marketCandidate], [academyState, otherAcademy], {...marketRules, policy: "active"});
assert.equal(activeSigning.transactions[0].kind, "free-agent");
assert.equal(activeSigning.assignments[marketCandidate.childId].rightsHolderId, otherAcademy.academyId);
assert.equal(activeSigning.assignments[marketCandidate.childId].optionYears, 3);
assert(Math.abs(activeSigning.conservationError) < 1e-9);
const activeTransfer = runAcademyTalentMarket([{...marketCandidate, optionYears: 1}], [academyState, otherAcademy], {...marketRules, policy: "active", transferMinimumFitDelta: -1});
assert.equal(activeTransfer.transactions[0].kind, "transfer");
assert.equal(activeTransfer.budgetBefore - activeTransfer.salaryOutflow, activeTransfer.budgetAfter);
const activeLoan = runAcademyTalentMarket([{...marketCandidate, optionYears: 1}], [academyState, otherAcademy], {...marketRules, policy: "active", transferMinimumFitDelta: 1, loanMinimumFitDelta: -1});
assert.equal(activeLoan.transactions[0].kind, "loan");
assert.equal(activeLoan.assignments[marketCandidate.childId].rightsHolderId, academyState.academyId);
assert.equal(activeLoan.assignments[marketCandidate.childId].developmentAcademyId, otherAcademy.academyId);
const rejectedTransfer = runAcademyTalentMarket([{...marketCandidate, optionYears: 1}], [academyState, otherAcademy], {...marketRules, policy: "active", consentPolicy: "enforce", consentThreshold: 1, transferMinimumFitDelta: -1});
assert.equal(rejectedTransfer.transactions[0].status, "rejected");
assert.equal(rejectedTransfer.assignments[marketCandidate.childId].rightsHolderId, academyState.academyId);
assert.deepEqual(rejectedTransfer.balances, {[academyState.academyId]: 30, [otherAcademy.academyId]: 30});
assert.equal(rejectedTransfer.transactions[0].consent.accepted, false);
const ignoredRejection = runAcademyTalentMarket([{...marketCandidate, optionYears: 1}], [academyState, otherAcademy], {...marketRules, policy: "active", consentPolicy: "ignore", consentThreshold: 1, transferMinimumFitDelta: -1});
assert.equal(ignoredRejection.transactions[0].status, "executed");
assert.equal(ignoredRejection.transactions[0].consent.accepted, false, "Ignore mode must retain evidence that the manager would refuse");
const rejectedContract = runAcademyTalentMarket([{...marketCandidate, optionYears: 1}], [academyState, otherAcademy], {...marketRules, policy: "active", consentPolicy: "ignore", contractPolicy: "enforce", baseSalary: 100, maximumSalary: 1, transferMinimumFitDelta: -1});
assert.equal(rejectedContract.transactions[0].status, "rejected");
assert.equal(rejectedContract.transactions[0].rejectionReason, "contract-gap");
assert.equal(rejectedContract.transactions[0].contract.accepted, false);
assert.deepEqual(rejectedContract.balances, {[academyState.academyId]: 30, [otherAcademy.academyId]: 30});
const ignoredContract = runAcademyTalentMarket([{...marketCandidate, optionYears: 1}], [academyState, otherAcademy], {...marketRules, policy: "active", consentPolicy: "ignore", contractPolicy: "ignore", baseSalary: 100, maximumSalary: 1, transferMinimumFitDelta: -1});
assert.equal(ignoredContract.transactions[0].status, "executed");
assert.equal(ignoredContract.transactions[0].contract.accepted, false);
assert.equal(ignoredContract.transactions[0].annualSalaryAfter, 1);
assert.equal(ignoredContract.salaryOutflow, 1);
const contractCandidate = {childId: "contract-child", childName: "Contract Child", academyId: academyState.academyId, optionYears: 3, annualSalary: 2, contractYears: 3, profile: academyChild};
const contractRules = {policy: "enforce" as const, cycleSeasons: 2, renewalYears: 3, baseSalary: 3, maximumSalary: 10, arbitrationDemandWeight: .6};
const paidContract = settleAcademyContracts([contractCandidate], [academyState], new Set(), contractRules);
assert.equal(paidContract.contracts[0].status, "paid");
assert.equal(paidContract.payrollOutflow, 4);
assert.equal(paidContract.balances[academyState.academyId], 26);
assert(Math.abs(paidContract.conservationError) < 1e-9);
const arbitratedContract = settleAcademyContracts([{...contractCandidate, annualSalary: 20, contractYears: 0}], [academyState], new Set(), {...contractRules, maximumSalary: 100});
assert.equal(arbitratedContract.contracts[0].status, "arbitrated");
assert(arbitratedContract.contracts[0].arbitrationAward! > arbitratedContract.contracts[0].offer);
assert.equal(arbitratedContract.assignments[contractCandidate.childId].contractYears, 3);
const defaultedContract = settleAcademyContracts([{...contractCandidate, annualSalary: 20}], [academyState], new Set(), contractRules);
assert.equal(defaultedContract.contracts[0].status, "defaulted");
assert.equal(defaultedContract.contracts[0].arrears, 10);
assert.equal(defaultedContract.assignments[contractCandidate.childId].optionYears, 0);
assert.equal(defaultedContract.balances[academyState.academyId], 0);
assert.equal(defaultedContract.newDebts[0].amount, 10);
const prepaidContract = settleAcademyContracts([contractCandidate], [academyState], new Set([contractCandidate.childId]), contractRules);
assert.equal(prepaidContract.contracts[0].status, "prepaid");
assert.equal(prepaidContract.payrollOutflow, 0);
assert.equal(prepaidContract.balances[academyState.academyId], 30);
const guaranteedDebt = {academyId: academyState.academyId, childId: "former-manager", childName: "Former Manager", amount: 40, originCycle: 1};
const partialGuarantee = settleSalaryGuarantees([guaranteedDebt], [academyState]);
assert.equal(partialGuarantee.paid, 30);
assert.equal(partialGuarantee.remainingDebts[0].amount, 10);
assert.equal(partialGuarantee.balances[academyState.academyId], 0);
assert(Math.abs(partialGuarantee.conservationError) < 1e-9);
const repaidGuarantee = settleSalaryGuarantees(partialGuarantee.remainingDebts, [academyState]);
assert.equal(repaidGuarantee.paid, 10);
assert.equal(repaidGuarantee.remainingDebts.length, 0);
const insolventHealth = academyFinancialHealth([{...academyState, treasury: 0}], settleSalaryGuarantees([], [academyState]), defaultedContract, 6);
assert.equal(insolventHealth[0].status, "insolvent");
assert.equal(insolventHealth[0].guaranteedDebt, 10);
const financialControls = academyFinancialControls([academyState.academyId, otherAcademy.academyId], insolventHealth, [guaranteedDebt]);
assert.equal(financialControls.find(control => control.academyId === academyState.academyId)?.trusteeship, true);
assert.equal(financialControls.find(control => control.academyId === academyState.academyId)?.spendingMultiplier, 0);
assert.equal(financialControls.find(control => control.academyId === academyState.academyId)?.acquisitionAllowed, false);
assert.equal(financialControls.find(control => control.academyId === otherAcademy.academyId)?.triggerStatus, "healthy");
const boundedControls = academyFinancialControls(["academy-strained", "academy-distressed"], [{...insolventHealth[0], academyId: "academy-strained", status: "strained", guaranteedDebt: 0}, {...insolventHealth[0], academyId: "academy-distressed", status: "distressed", guaranteedDebt: 0}], []);
assert.equal(boundedControls.find(control => control.academyId === "academy-strained")?.spendingMultiplier, .75);
assert.equal(boundedControls.find(control => control.academyId === "academy-strained")?.acquisitionAllowed, true);
assert.equal(boundedControls.find(control => control.academyId === "academy-distressed")?.spendingMultiplier, .4);
assert.equal(boundedControls.find(control => control.academyId === "academy-distressed")?.acquisitionAllowed, false);
const blockedMarket = runAcademyTalentMarket([marketCandidate], [academyState, otherAcademy], {...marketRules, policy: "active", acquisitionBlockedAcademyIds: [academyState.academyId, otherAcademy.academyId]});
assert.equal(blockedMarket.transactions.length, 0);
assert.deepEqual(blockedMarket.balances, {[academyState.academyId]: 30, [otherAcademy.academyId]: 30});
const emergencyMarket = runAcademyTalentMarket([{...marketCandidate, optionYears: 1}], [academyState, otherAcademy], {...marketRules, policy: "active", transferMinimumFitDelta: 1, acquisitionBlockedAcademyIds: [academyState.academyId], emergencySaleAcademyIds: [academyState.academyId], emergencySaleDiscountPercent: 25});
assert.equal(emergencyMarket.emergencySaleCandidates, 1);
assert.equal(emergencyMarket.transactions[0].kind, "transfer");
assert.equal(emergencyMarket.transactions[0].financialIntervention, "emergency-sale");
assert.equal(emergencyMarket.transactions[0].fee, 11.25);
assert(emergencyMarket.balances[academyState.academyId] > 30);
const recoveryCycleOne = academyRecoveryRecords(financialControls, insolventHealth, [], 3);
assert.equal(recoveryCycleOne.find(record => record.academyId === academyState.academyId)?.state, "active");
assert.equal(recoveryCycleOne.find(record => record.academyId === academyState.academyId)?.trusteeshipCycles, 1);
const recoveryCycleTwo = academyRecoveryRecords(financialControls, insolventHealth, recoveryCycleOne, 4);
assert.equal(recoveryCycleTwo.find(record => record.academyId === academyState.academyId)?.consecutiveRecoveryCycles, 2);
const exitPending = academyRecoveryRecords(financialControls, [{...insolventHealth[0], status: "healthy", guaranteedDebt: 0, obligationCoverage: 1, reserveCoverage: 2}], recoveryCycleTwo, 5);
assert.equal(exitPending.find(record => record.academyId === academyState.academyId)?.state, "exit-pending");

const root = process.cwd(), workspace = fs.mkdtempSync(path.join(os.tmpdir(), "mythic-development-league-"));
const source = path.join(workspace, "source"), output = path.join(workspace, "development"), nextOutput = path.join(workspace, "development-next"), debtOutput = path.join(workspace, "development-debt"), retirementOutput = path.join(workspace, "development-retirement");
try {
  const baseline = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(root, "src", "cli", "draftLeagueV12.ts")], {cwd: root, env: {...process.env, V12_OUT: source, V12_SEASONS: "1", V12_MANAGER_LIMIT: "6", V12_PAIRS: "1", V12_POOL_SIZE: "100", V12_AUCTION_LOTS: "10", V12_REGULAR_ROUNDS: "1", V12_MAX_TURNS: "20", V12_MIN_ROSTER: "6", V12_MAX_ROSTER: "6", V12_SEED: "development-league-smoke", V12_EVOLUTION_MODE: "punctuated", V12_EVOLUTION_POLICY: "shadow", V12_EVIDENCE_RETENTION: "compact", V12_EVIDENCE_SAMPLE_RATE: "0"}, encoding: "utf8", maxBuffer: 64 * 1024 * 1024});
  assert.equal(baseline.status, 0, baseline.stderr || baseline.stdout);
  const sourceStatePath = path.join(source, "dynasty-state.json"), sourceHash = digest(fs.readFileSync(sourceStatePath));
  const sourceState = read<any>(sourceStatePath);
  const development = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(root, "src", "cli", "developmentLeague.ts"), "--source", source, "--out", output, "--seasons", "2", "--parent-limit", "6", "--children-per-parent", "1", "--promotion-slots", "1", "--elimination-slots", "1", "--regular-rounds", "1", "--max-turns", "20"], {cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024});
  assert.equal(development.status, 0, development.stderr || development.stdout);
  assert.equal(digest(fs.readFileSync(sourceStatePath)), sourceHash, "Development league must not mutate its major-league source");
  const entrantsDocument = read<any>(path.join(output, "entrants.json"));
  const entrants = entrantsDocument.entrants;
  const summary = read<any>(path.join(output, "development-summary.json"));
  assert(entrantsDocument.academies.every((academy: any) => academy.revision === 0));
  assert(entrantsDocument.academies.every((academy: any) => academy.treasury === 26 && Math.abs(Object.values(academy.allocations).reduce((sum: number, value: any) => sum + value, 0) - 1) < 1e-9));
  assert.equal(entrantsDocument.contracts.payrollOutflow, 24);
  assert.equal(entrantsDocument.contracts.arrears, 0);
  assert(Math.abs(entrantsDocument.contracts.conservationError) < 1e-9);
  assert(entrantsDocument.contracts.contracts.every((contract: any) => contract.status === "paid" && contract.paid === 4));
  assert.equal(summary.academyEvolution.updated, 0);
  assert.equal(entrants.length, 6);
  assert.equal(new Set(entrants.map((entry: any) => entry.childId)).size, 6);
  assert(entrants.every((entry: any) => entry.rightsHolderId === entry.parentId && entry.optionYears === 3));
  assert(entrants.every((entry: any) => entry.parentSource === "major" && entry.generation === 1));
  assert(entrants.every((entry: any) => entry.academy.academyId === entry.rightsHolderId && entry.academy.configuredInfluence === .15 && entry.academy.strategyProgramUnchanged));
  assert(entrants.every((entry: any) => entry.academy.similarityAfter >= entry.academy.similarityBefore));
  for (const entrant of entrants) {
    const parent = sourceState.managers.find((manager: any) => manager.id === entrant.parentId);
    assert(parent);
    assert(entrant.lineage.parentLineageIds.includes(parent.lineage.lineageId));
    assert.notEqual(entrant.childId, parent.lineage.lineageId);
  }
  assert.equal(summary.promoted.length, 1);
  assert.equal(summary.retained.length, 4);
  assert.equal(summary.eliminated.length, 1);
  assert.equal(summary.archive.length, 1);
  assert.equal(summary.promoted.length + summary.retained.length + summary.eliminated.length, 6);
  assert(summary.promoted.every((entry: any) => entry.optionYearsRemaining === 1));
  assert([...summary.promoted, ...summary.retained, ...summary.eliminated].every((entry: any) => entry.contractYearsRemaining === 1));
  assert([...summary.promoted, ...summary.retained, ...summary.eliminated].every((entry: any) => entry.nicheBonus > 0));
  const promotionManifest = read<any>(path.join(output, "promotion-package.json"));
  assert.equal(promotionManifest.candidates, 1);
  const promotionBytes = zlib.gunzipSync(fs.readFileSync(path.join(output, promotionManifest.archive)));
  assert.equal(digest(promotionBytes), promotionManifest.sha256);
  const promotionPackage = JSON.parse(promotionBytes.toString("utf8"));
  assert.equal(promotionPackage.candidates.length, 1);
  assert(promotionPackage.candidates[0].currentProfile);
  assert(fs.existsSync(path.join(output, "development-report.md")));

  const firstLeagueState = read<any>(path.join(output, "league", "dynasty-state.json"));
  const nextDevelopment = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(root, "src", "cli", "developmentLeague.ts"), "--source", source, "--previous", output, "--out", nextOutput, "--seasons", "2", "--capacity", "6", "--parent-limit", "6", "--promotion-slots", "1", "--elimination-slots", "1", "--max-founder-share-percent", "17", "--kinship-depth", "2", "--max-parent-similarity-percent", "0", "--academy-grant-pool", "240", "--academy-market-policy", "active", "--academy-market-consent-policy", "ignore", "--academy-market-contract-policy", "ignore", "--academy-market-max-transactions", "2", "--academy-signing-fee", "0", "--academy-transfer-fee", "0", "--academy-loan-fee", "0", "--academy-transfer-min-fit-percent", "-100", "--regular-rounds", "1", "--max-turns", "20"], {cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024});
  assert.equal(nextDevelopment.status, 0, nextDevelopment.stderr || nextDevelopment.stdout);
  assert.equal(digest(fs.readFileSync(sourceStatePath)), sourceHash, "A later development cycle must also leave the major league untouched");
  const nextEntrantsDocument = read<any>(path.join(nextOutput, "entrants.json"));
  const nextEntrants = nextEntrantsDocument.entrants;
  const nextSummary = read<any>(path.join(nextOutput, "development-summary.json"));
  const priorRetainedIds = new Set(summary.retained.map((entry: any) => entry.childId));
  const departedIds = new Set([...summary.promoted, ...summary.eliminated].map((entry: any) => entry.childId));
  const returning = nextEntrants.filter((entry: any) => entry.origin === "retained");
  const newborn = nextEntrants.filter((entry: any) => entry.origin === "newborn");
  assert.equal(nextEntrantsDocument.cycle, 2);
  assert.equal(nextEntrantsDocument.capacity, 6);
  assert.equal(nextEntrantsDocument.policy.maxFounderCount, 2);
  assert.equal(nextEntrantsDocument.policy.maxParentSimilarityPercent, 0);
  assert(nextEntrantsDocument.diversity.maximumFounderCount <= 2);
  assert(nextEntrantsDocument.diversity.similarityExclusions > 0);
  assert.equal(nextSummary.academyEvolution.alumni, 6);
  assert.equal(nextSummary.academyEvolution.updated, 6);
  assert(nextSummary.academyEvolution.cultureModelsAdopted > 0);
  assert(Math.abs(nextSummary.academyEconomy.totalGrants - 240) < 1e-9);
  assert(Math.abs(nextSummary.academyEconomy.conservationError) < 1e-9);
  assert(Math.abs(Object.values(nextSummary.academyEconomy.spending).reduce((sum: number, value: any) => sum + value, 0) - nextSummary.academyEconomy.totalSpend) < 1e-9);
  assert.equal(nextSummary.talentMarket.transactions.length, 2);
  assert(nextSummary.talentMarket.transactions.every((transaction: any) => transaction.status === "executed"));
  assert(Math.abs(nextSummary.talentMarket.conservationError) < 1e-9);
  assert(nextSummary.talentMarket.salaryOutflow > 0);
  assert(nextSummary.contracts.payrollOutflow > 0);
  assert.equal(nextSummary.contracts.arrears, 0);
  assert(Math.abs(nextSummary.contracts.conservationError) < 1e-9);
  assert.equal(nextSummary.contracts.contracts.filter((contract: any) => contract.status === "prepaid").length, 2);
  assert(nextEntrantsDocument.academies.every((academy: any) => academy.treasury >= 0));
  assert.equal(nextEntrantsDocument.salaryDebts.length, 0);
  assert(nextEntrantsDocument.academyFinancialHealth.every((academy: any) => ["healthy", "strained", "distressed", "insolvent"].includes(academy.status)));
  for (const transaction of nextSummary.talentMarket.transactions) {
    const manager = returning.find((entry: any) => entry.childId === transaction.childId);
    assert(manager?.marketAcademy?.strategyProgramUnchanged);
    assert.equal(manager.developmentAcademyId, transaction.developmentAcademyId);
    assert.equal(manager.rightsHolderId, transaction.rightsHolderAfter);
    assert.equal(manager.annualSalary, transaction.annualSalaryAfter);
  }
  assert(nextEntrantsDocument.academies.some((academy: any) => Math.abs(academy.latestEvidence.qualityAfter - academy.latestEvidence.qualityBefore) > 1e-9));
  const promotedAcademyId = entrants.find((entry: any) => entry.childId === summary.promoted[0].childId).rightsHolderId;
  const eliminatedAcademyId = entrants.find((entry: any) => entry.childId === summary.eliminated[0].childId).rightsHolderId;
  assert(nextEntrantsDocument.academies.find((academy: any) => academy.academyId === promotedAcademyId).latestEvidence.grant > nextEntrantsDocument.academies.find((academy: any) => academy.academyId === eliminatedAcademyId).latestEvidence.grant);
  assert.equal(returning.length, 4);
  assert.equal(newborn.length, 2);
  assert.deepEqual(new Set(returning.map((entry: any) => entry.childId)), priorRetainedIds);
  assert(returning.every((entry: any) => !departedIds.has(entry.childId)));
  assert(returning.every((entry: any) => entry.priorCareer.length === 2 && entry.optionYears === 1));
  for (const entrant of returning) {
    const priorRow = entrants.find((entry: any) => entry.childId === entrant.childId);
    const priorManager = firstLeagueState.managers.find((manager: any) => manager.id === priorRow.slotId);
    assert(priorManager);
    assert.deepEqual(entrant.lineage, priorManager.lineage);
    assert.equal(entrant.priorTitles, priorManager.titles);
    assert.equal(entrant.priorTotalPoints, priorManager.totalPoints);
  }
  assert.equal(nextSummary.cycle, 2);
  assert.equal(nextSummary.capacity, 6);
  assert.equal(nextSummary.returning, 4);
  assert.equal(nextSummary.births, 2);
  assert.equal(nextSummary.developmentParentBirths, 1);
  assert.equal(nextSummary.majorParentBirths, 1);
  assert.equal(nextSummary.academy.developedBirths, 2);
  assert.equal(nextSummary.academy.programsChanged, 0);
  const grandchild = newborn.find((entry: any) => entry.parentSource === "development");
  assert(grandchild, "One bounded birth should come from the highest-ranked retained development parent");
  const grandchildParentEntrant = entrants.find((entry: any) => entry.childId === grandchild.parentId);
  const grandchildParentManager = firstLeagueState.managers.find((manager: any) => manager.id === grandchildParentEntrant?.slotId);
  assert(grandchildParentEntrant && grandchildParentManager);
  assert.equal(grandchild.generation, 2);
  assert.equal(grandchild.lineage.generation, 2);
  assert(grandchild.kinshipExclusions >= 1, "The grandchild's founder must be excluded from second-parent candidates");
  assert(grandchild.lineage.parentLineageIds.includes(grandchildParentManager.lineage.lineageId));
  const currentGrandchildParent = returning.find((entry: any) => entry.childId === grandchild.parentId);
  assert(currentGrandchildParent);
  assert.equal(grandchild.rightsHolderId, currentGrandchildParent.rightsHolderId, "Grandchildren inherit the current post-market rights organization of their development parent");
  assert.equal(grandchild.academy.academyId, grandchild.rightsHolderId, "Grandchildren must be developed by the inherited affiliate organization");
  const grandchildAcademyState = nextEntrantsDocument.academies.find((academy: any) => academy.academyId === grandchild.rightsHolderId);
  assert.equal(grandchild.academy.quality, grandchildAcademyState.quality, "Newborn nurture must use the evolved academy state");
  assert.equal(grandchild.scoutingChance, .05 + grandchildAcademyState.scouting * .3, "Evolved scouting must control second-parent discovery probability");
  const nextLeagueState = read<any>(path.join(nextOutput, "league", "dynasty-state.json"));
  const grandchildManager = nextLeagueState.managers.find((manager: any) => manager.id === grandchild.slotId);
  assert(grandchildManager.lineageHistory.some((lineage: any) => lineage.lineageId === grandchildParentManager.lineage.lineageId));
  assert(grandchildManager.lineageHistory.some((lineage: any) => lineage.lineageId === grandchild.lineage.lineageId));
  const nextResults = [...nextSummary.promoted, ...nextSummary.retained, ...nextSummary.eliminated];
  assert.equal(nextResults.length, 6);
  assert(nextResults.filter((entry: any) => priorRetainedIds.has(entry.childId)).every((entry: any) => entry.developmentSeasons === 4 && entry.optionYearsRemaining === 0 && entry.rightsStatus === "independent"));
  assert(nextResults.filter((entry: any) => entry.origin === "newborn").every((entry: any) => entry.developmentSeasons === 2 && entry.optionYearsRemaining === 1 && entry.rightsStatus === "affiliate"));

  const debtorAcademyId = nextEntrantsDocument.academies[0].academyId;
  nextEntrantsDocument.salaryDebts = [{academyId: debtorAcademyId, childId: "departed-manager", childName: "Departed Manager", amount: 5, originCycle: 1}];
  fs.writeFileSync(path.join(nextOutput, "entrants.json"), `${JSON.stringify(nextEntrantsDocument, null, 2)}\n`, "utf8");
  const debtDevelopment = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(root, "src", "cli", "developmentLeague.ts"), "--source", source, "--previous", nextOutput, "--out", debtOutput, "--seasons", "1", "--capacity", "6", "--parent-limit", "6", "--promotion-slots", "1", "--elimination-slots", "1", "--academy-grant-pool", "0", "--academy-market-policy", "shadow", "--regular-rounds", "1", "--max-turns", "20"], {cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024});
  assert.equal(debtDevelopment.status, 0, debtDevelopment.stderr || debtDevelopment.stdout);
  const debtEntrants = read<any>(path.join(debtOutput, "entrants.json"));
  assert.equal(debtEntrants.salaryGuarantees.payments[0].childId, "departed-manager");
  assert.equal(debtEntrants.salaryGuarantees.payments[0].paid, 5);
  assert.equal(debtEntrants.salaryGuarantees.remainingDebts.length, 0);
  assert(!debtEntrants.salaryDebts.some((debt: any) => debt.childId === "departed-manager"));
  assert(Math.abs(debtEntrants.salaryGuarantees.conservationError) < 1e-9);
  const debtorControl = debtEntrants.academyFinancialControls.find((control: any) => control.academyId === debtorAcademyId);
  assert.equal(debtorControl.triggerStatus, "insolvent");
  assert.equal(debtorControl.trusteeship, true);
  assert.equal(debtorControl.acquisitionAllowed, false);
  assert.equal(debtorControl.spendingMultiplier, 0);
  assert.equal(debtorControl.leadershipAllocationTarget.patience, .7);
  assert(debtEntrants.policy.academyMarket.acquisitionBlockedAcademyIds.includes(debtorAcademyId));
  assert.equal(debtEntrants.academies.find((academy: any) => academy.academyId === debtorAcademyId).latestEvidence.spend, 0);
  assert.equal(debtEntrants.academies.find((academy: any) => academy.academyId === debtorAcademyId).latestEvidence.allocationsBefore.patience, .7);
  const debtorRecovery = debtEntrants.academyRecoveryPlans.find((record: any) => record.academyId === debtorAcademyId);
  assert.equal(debtorRecovery.leadershipAction, "trustee-control");
  assert.equal(debtorRecovery.trusteeshipCycles, 1);
  assert.equal(debtorRecovery.emergencySaleEligible, true);

  const retirementDevelopment = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(root, "src", "cli", "developmentLeague.ts"), "--source", source, "--previous", output, "--out", retirementOutput, "--seasons", "1", "--capacity", "6", "--parent-limit", "6", "--promotion-slots", "1", "--elimination-slots", "1", "--retirement-min-seasons", "2", "--retirement-hard-seasons", "2", "--regular-rounds", "1", "--max-turns", "20"], {cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024});
  assert.equal(retirementDevelopment.status, 0, retirementDevelopment.stderr || retirementDevelopment.stdout);
  const retirementEntrants = read<any>(path.join(retirementOutput, "entrants.json"));
  const retirementSummary = read<any>(path.join(retirementOutput, "development-summary.json"));
  assert.equal(retirementEntrants.lifecycleRetired.length, 4);
  assert.deepEqual(new Set(retirementEntrants.lifecycleRetired.map((entry: any) => entry.childId)), priorRetainedIds);
  assert(retirementEntrants.lifecycleRetired.every((entry: any) => entry.assessment.reason === "hard-limit"));
  assert.equal(retirementEntrants.entrants.length, 6);
  assert(retirementEntrants.entrants.every((entry: any) => entry.origin === "newborn"));
  assert(retirementEntrants.entrants.every((entry: any) => entry.academy.academyId === entry.rightsHolderId));
  assert.equal(retirementSummary.returning, 0);
  assert.equal(retirementSummary.births, 6);
  assert.equal(retirementSummary.lifecycleRetired.length, 4);
  assert.equal(retirementSummary.promoted.length + retirementSummary.retained.length + retirementSummary.eliminated.length, 6);
  assert.equal(retirementSummary.archive.length, 5);
  assert.equal(digest(fs.readFileSync(sourceStatePath)), sourceHash);
  console.log("Development league smoke passed: multi-cohort ecology, lifecycle turnover, academy budgets, and explicit talent-market settlement");
} finally { fs.rmSync(workspace, {recursive: true, force: true}); }

function digest(value: Buffer): string { return crypto.createHash("sha256").update(value).digest("hex"); }
function read<T>(file: string): T { return JSON.parse(fs.readFileSync(file, "utf8")) as T; }
