import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {buildFormalCanaryAdapterRegistry, buildFormalCanaryHandoff, FORMAL_CANARY_ADAPTER_PROTOCOL, verifyFormalCanaryHandoff} from "../ai/formalCanaryControl";
import {evaluateFormalBattleCanary} from "../ai/formalBattleCanaryAdapter";
import {sha256} from "../showdown/evidenceEpoch";

const rule = {id: "rule-1", domain: "battle" as const, target: "switch", effect: -.1, predicates: [{feature: "positionValue", operator: "lt" as const, threshold: 0}], support: 24, uncertainty: .1, authority: "local-value-observational" as const, evidenceIds: ["evidence-1"]};
const domain = {id: "battle-switch__better__positionValue-lt", mechanismKey: "switch__better__positionValue-lt", target: "switch", expectedDirection: "better" as const, adapterProtocol: FORMAL_CANARY_ADAPTER_PROTOCOL, hypotheses: [{managerId: "manager-01", rule}]};
const freezeCore = {schemaVersion: 1, domains: [domain]}, freeze = {...freezeCore, sha256: sha256(freezeCore)};
const summaryCore = {schemaVersion: 1, freezeSha256: freeze.sha256, automaticActivationAllowed: false, limitedCanaryEligibleDomains: [domain.id]}, summary = {...summaryCore, sha256: sha256(summaryCore)};
const blocked = buildFormalCanaryHandoff(freeze, summary); verifyFormalCanaryHandoff(blocked); assert.equal(blocked.status, "adapter-required"); assert.equal(blocked.automaticActivationAllowed, false);
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), "formal-canary-adapter-"));
const implementationFile = path.join(temporary, "adapter.ts"); fs.writeFileSync(implementationFile, "export const adapter = true;\n");
const registry = buildFormalCanaryAdapterRegistry([{id: FORMAL_CANARY_ADAPTER_PROTOCOL, implementationFile, targets: ["switch"]}]);
assert.equal(buildFormalCanaryHandoff(freeze, summary, {adapterRegistry: registry}).status, "execution-ready");
assert.equal(buildFormalCanaryHandoff(freeze, summary).status, "adapter-required", "A freeze protocol declaration alone cannot make an adapter executable");
fs.appendFileSync(implementationFile, "// drift\n"); assert.throws(() => buildFormalCanaryHandoff(freeze, summary, {adapterRegistry: registry}), /Invalid formal canary adapter registration/); fs.writeFileSync(implementationFile, "export const adapter = true;\n");
const actualImplementation = path.resolve(__dirname, "../ai/formalBattleCanaryAdapter.ts"), actualRegistry = buildFormalCanaryAdapterRegistry([{id: FORMAL_CANARY_ADAPTER_PROTOCOL, implementationFile: actualImplementation, targets: ["switch"]}]);
assert.equal(buildFormalCanaryHandoff(freeze, summary, {adapterRegistry: actualRegistry}).status, "execution-ready", "A production adapter must satisfy the signed handoff contract");
assert.deepEqual(evaluateFormalBattleCanary(domain, "manager-01", "switch", {positionValue: -.2}), {applied: true, domainId: domain.id, managerId: "manager-01", ruleId: rule.id, adjustment: -.1, reason: "applied"});
const emptySummaryCore = {...summaryCore, limitedCanaryEligibleDomains: []}, emptySummary = {...emptySummaryCore, sha256: sha256(emptySummaryCore)}; assert.equal(buildFormalCanaryHandoff(freeze, emptySummary).status, "no-candidate");
const secondDomain = {...domain, id: `${domain.id}-second`}, multiFreezeCore = {schemaVersion: 1, domains: [domain, secondDomain]}, multiFreeze = {...multiFreezeCore, sha256: sha256(multiFreezeCore)}, multiSummaryCore = {schemaVersion: 1, freezeSha256: multiFreeze.sha256, automaticActivationAllowed: false, limitedCanaryEligibleDomains: [domain.id, secondDomain.id]}, multiSummary = {...multiSummaryCore, sha256: sha256(multiSummaryCore)};
assert.throws(() => buildFormalCanaryHandoff(multiFreeze, multiSummary, {adapterRegistry: actualRegistry}), /exactly one decision domain/);
const tampered = structuredClone(blocked); tampered.control.seasons = 3; assert.throws(() => verifyFormalCanaryHandoff(tampered), /Invalid formal canary handoff/);
const malformed: any = structuredClone(blocked); malformed.status = "nonsense"; malformed.control.seasons = -9; malformed.sha256 = sha256(Object.fromEntries(Object.entries(malformed).filter(([key]) => key !== "sha256"))); assert.throws(() => verifyFormalCanaryHandoff(malformed), /Invalid formal canary handoff/);
fs.rmSync(temporary, {recursive: true, force: true});
console.log("Formal canary control smoke passed: signed handoff, adapter blocking, bounded execution readiness, and tamper rejection");
