import assert from "node:assert/strict";
import crypto from "node:crypto";
import {assertJointBattleDecisionCorpus, buildJointBattleDecisionCorpus, type JointBattleDecisionObservationV1} from "../ai/jointBattleDecisionCorpus";
import {JOINT_BATTLE_FEATURES, jointBattleKnownMask, type JointBattleCandidateV1} from "../ai/relationalBattlePolicy";

const hash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"), mask = jointBattleKnownMask(JOINT_BATTLE_FEATURES);
function candidate(id: string, actionKind: "move" | "switch"): JointBattleCandidateV1 { const values = Object.fromEntries(JOINT_BATTLE_FEATURES.map(feature => [feature, 0])) as JointBattleCandidateV1["values"]; Object.assign(values, {shortValue: .4, longValue: .3, uncertainty: .2, terminalRisk: .1}); return {id, actionKind, target: id, legal: true, values, knownMask: mask}; }
function row(decisionId: string, candidateId: string, actionKind: "move" | "switch", split: "train" | "validation" | "test", auxiliary = false): JointBattleDecisionObservationV1 { return {decisionId, candidateId, familyId: `${split}-family`, familyClusterId: `${split}-cluster`, environment: "synthetic", split, candidate: candidate(candidateId, actionKind), shortUtility: .4, terminalUtility: 1, uncertainty: .2, terminalRisk: .1, sourceAuthority: "synthetic-test", sourceFingerprint: hash([decisionId, "source"]), branchFingerprint: hash([decisionId, candidateId]), ...(auxiliary ? {legacySwitchAuxiliary: {authority: "switch-v3-auxiliary-training-only", encoderVersion: "relational-switch-encoder-v1", sourceFingerprint: hash([decisionId, "legacy"]), validationEvidenceAllowed: false}} : {})}; }

const rows = [row("train-1", "move 1", "move", "train"), row("train-1", "switch 2", "switch", "train", true), row("validation-1", "move 1", "move", "validation"), row("validation-1", "switch 2", "switch", "validation"), row("test-1", "move 1", "move", "test"), row("test-1", "switch 2", "switch", "test")], corpus = buildJointBattleDecisionCorpus(rows, "synthetic-test");
assert.equal(corpus.activationStatus, "shadow-only"); assert.equal(corpus.formalActivationAllowed, false); assert.equal(corpus.metrics.moveCandidates, 3); assert.equal(corpus.metrics.switchCandidates, 3); assert.equal(corpus.metrics.legacyAuxiliaryCandidates, 1);
const tampered = structuredClone(corpus); tampered.rows[0].terminalUtility = 0; assert.throws(() => assertJointBattleDecisionCorpus(tampered), /signature mismatch/);
const familyLeak = rows.map(value => structuredClone(value)); familyLeak[2].familyId = "train-family"; assert.throws(() => buildJointBattleDecisionCorpus(familyLeak, "synthetic-test"), /family split leakage/);
const legacyValidation = rows.map(value => structuredClone(value)); legacyValidation[3].legacySwitchAuxiliary = {authority: "switch-v3-auxiliary-training-only", encoderVersion: "relational-switch-encoder-v1", sourceFingerprint: hash("legacy-validation"), validationEvidenceAllowed: false}; assert.throws(() => buildJointBattleDecisionCorpus(legacyValidation, "synthetic-test"), /auxiliary training data only/);
const authorityMismatch = rows.map(value => ({...structuredClone(value), sourceAuthority: "signed-research-family" as const})); assert.throws(() => buildJointBattleDecisionCorpus(authorityMismatch, "synthetic-test"), /synthetic authority mismatch/);
console.log("Joint battle decision corpus contract smoke passed");
