import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {buildJointBattleShadowSource, extractJointBattleShadowCorpus, type JointBattleShadowSourceAuthority, type JointBattleShadowSourceCandidateLabel, type JointBattleShadowSourceEntry} from "../ai/jointBattleShadowCorpus";
import {buildProductionShadowSourceAuthorityManifest, productionShadowRecordSchemaSha256} from "../ai/productionShadowSourceAuthority";
import {buildJointBattleDecisionSnapshot, JOINT_BATTLE_FEATURES, jointBattleKnownMask, recommendJointBattleShadow, type JointBattleCandidateV1, type JointBattleDecisionSnapshotV1} from "../ai/relationalBattlePolicy";
import {buildUnifiedDecisionRecord, type UnifiedDecisionRecord} from "../draft/unifiedDecisionRecord";

const token = "build-relational-battle-policy-v1-shadow-corpus", signingAuthority = "synthetic-fixture-authority", root = fs.mkdtempSync(path.join(os.tmpdir(), "joint-shadow-corpus-")), sourceFile = path.join(root, "source.json"), manifestFile = path.join(root, "authority.json"), proposedFile = path.join(root, "proposed.json"), mismatchFile = path.join(root, "mismatch.json"), hashMismatchFile = path.join(root, "hash-mismatch.json"), pathMismatchFile = path.join(root, "path-mismatch.json"), tamperedManifestFile = path.join(root, "tampered-authority.json"), out = path.join(root, "corpus"), missingOut = path.join(root, "missing");
let aliasContainer: string | null = null;
try {
  const closed = entry("closed", "closed-sheet", "train"), open = entry("open", "open-sheet", "validation"), source = buildJointBattleShadowSource([closed, open], "synthetic-test");
  fs.writeFileSync(sourceFile, `${JSON.stringify(source, null, 2)}\n`, "utf8");
  const approved = manifest("approved", source.sha256, out), proposed = manifest("proposed", source.sha256, out), mismatch = manifest("approved", "f".repeat(64), out), hashMismatch = manifest("approved", source.sha256, out, "e".repeat(64)), pathMismatch = manifest("approved", source.sha256, missingOut), tamperedManifest = structuredClone(approved); tamperedManifest.lineage.sourceGeneration = "tampered";
  fs.writeFileSync(manifestFile, `${JSON.stringify(approved, null, 2)}\n`); fs.writeFileSync(proposedFile, `${JSON.stringify(proposed, null, 2)}\n`); fs.writeFileSync(mismatchFile, `${JSON.stringify(mismatch, null, 2)}\n`); fs.writeFileSync(hashMismatchFile, `${JSON.stringify(hashMismatch, null, 2)}\n`); fs.writeFileSync(pathMismatchFile, `${JSON.stringify(pathMismatch, null, 2)}\n`); fs.writeFileSync(tamperedManifestFile, `${JSON.stringify(tamperedManifest, null, 2)}\n`);
  assert.throws(() => buildJointBattleShadowSource([], "synthetic-test"), /empty/);
  assert.throws(() => buildJointBattleShadowSource([{...closed, labels: closed.labels.slice(0, 1)}], "synthetic-test"), /labels are incomplete/);
  assert.throws(() => buildJointBattleShadowSource([closed, {...open, familyId: closed.familyId}], "synthetic-test"), /family crossed information modes/);

  const nestedOut = path.join(root, "nested-output"), nestedSourceFile = path.join(nestedOut, "source.json"), nestedManifestFile = path.join(root, "nested-authority.json");
  fs.mkdirSync(nestedOut); fs.writeFileSync(nestedSourceFile, `${JSON.stringify(source, null, 2)}\n`);
  const nestedApproved = manifest("approved", source.sha256, nestedOut, fileHash(nestedSourceFile), nestedSourceFile); fs.writeFileSync(nestedManifestFile, `${JSON.stringify(nestedApproved, null, 2)}\n`);
  const beforeNestedSource = tree(root);
  assert.equal(invoke("propose", "--input", nestedSourceFile, "--out", nestedOut, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--approval-reference-sha256", nestedApproved.signingAuthority.approvalReferenceSha256, "--source-system", "synthetic-fixture", "--source-generation", "fixture-v1").status, 2, "nested source passed propose");
  assert.equal(invoke("doctor", "--out", nestedOut, "--manifest", nestedManifestFile, ...pins(nestedApproved)).status, 2, "nested source passed doctor");
  assert.deepEqual(tree(root), beforeNestedSource, "nested-source rejection changed files");
  assert.equal(fs.existsSync(path.join(nestedOut, "joint-battle-shadow-corpus.json")), false); assert.equal(fs.existsSync(path.join(nestedOut, ".joint-shadow-corpus.lock")), false);

  const manifestOut = path.join(root, "manifest-output"); fs.mkdirSync(manifestOut);
  const nestedManifestInsideOut = path.join(manifestOut, "authority.json"), manifestInsideOut = manifest("approved", source.sha256, manifestOut); fs.writeFileSync(nestedManifestInsideOut, `${JSON.stringify(manifestInsideOut, null, 2)}\n`);
  const beforeNestedManifest = tree(root);
  assert.equal(invoke("build", "--input", sourceFile, "--manifest", nestedManifestInsideOut, "--out", manifestOut, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(manifestInsideOut)).status, 2, "manifest inside output passed build");
  assert.deepEqual(tree(root), beforeNestedManifest, "nested-manifest rejection changed files");
  assert.equal(fs.existsSync(path.join(manifestOut, "joint-battle-shadow-corpus.json")), false); assert.equal(fs.existsSync(path.join(manifestOut, ".joint-shadow-corpus.lock")), false);

  const aliasTarget = path.join(root, "alias-target"), aliasSourceFile = path.join(aliasTarget, "source.json"); fs.mkdirSync(aliasTarget); fs.writeFileSync(aliasSourceFile, `${JSON.stringify(source, null, 2)}\n`);
  aliasContainer = fs.mkdtempSync(path.join(os.tmpdir(), "joint-shadow-alias-")); const aliasOut = path.join(aliasContainer, "output-alias");
  try { fs.symlinkSync(aliasTarget, aliasOut, process.platform === "win32" ? "junction" : "dir"); }
  catch (error) { const code = (error as NodeJS.ErrnoException).code; if (!["EACCES", "EPERM", "ENOTSUP"].includes(code ?? "")) throw error; console.warn(`SKIP joint shadow physical-alias fixture: ${code}`); }
  if (fs.existsSync(aliasOut)) { const beforeAlias = tree(aliasTarget); assert.equal(invoke("propose", "--input", aliasSourceFile, "--out", aliasOut, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--approval-reference-sha256", approved.signingAuthority.approvalReferenceSha256, "--source-system", "synthetic-fixture", "--source-generation", "fixture-v1").status, 2, "physical output alias wrapped the source"); assert.deepEqual(tree(aliasTarget), beforeAlias, "physical-alias rejection changed target files"); assert.equal(fs.existsSync(path.join(aliasTarget, "joint-battle-shadow-corpus.json")), false); }

  const beforeReadOnly = tree(root);
  const proposedByCli = invoke("propose", "--input", sourceFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--approval-reference-sha256", approved.signingAuthority.approvalReferenceSha256, "--source-system", "synthetic-fixture", "--source-generation", "fixture-v1"); assert.equal(proposedByCli.status, 0); assert.equal(proposedByCli.json.status, "proposed"); assert.equal(proposedByCli.json.input.archiveSha256, fileHash(sourceFile)); assert.equal(proposedByCli.json.prohibitions.trainingAllowed, false);
  const missingStatus = invoke("status", "--out", missingOut); assert.equal(missingStatus.status, 0); assert.equal(missingStatus.json.available, false); assert.equal(missingStatus.json.verificationScope, "not-verified"); assert.equal(missingStatus.json.approvedSourceRecomputed, false); assert.equal(fs.existsSync(missingOut), false);
  const missingDoctor = invoke("doctor", "--out", missingOut, "--manifest", manifestFile, ...pins(approved)); assert.equal(missingDoctor.status, 2); assert.equal(missingDoctor.json.verificationScope, "not-verified"); assert.equal(missingDoctor.json.approvedSourceRecomputed, false); assert.equal(fs.existsSync(missingOut), false);
  const inspected = invoke("inspect", "--input", sourceFile); assert.equal(inspected.status, 0); assert.equal(inspected.json.records, 2); assert.deepEqual(inspected.json.informationModes, {openSheet: 1, closedSheet: 1});
  const inspectedManifest = invoke("inspect", "--manifest", manifestFile); assert.equal(inspectedManifest.status, 0); assert.equal(inspectedManifest.json.status, "approved"); assert.equal(inspectedManifest.json.recordSchemaSha256, productionShadowRecordSchemaSha256()); assert.equal(inspectedManifest.json.trainingAllowed, false);
  assert.equal(invoke("inspect", "--manifest", tamperedManifestFile).status, 2, "tampered authority manifest passed inspect");
  assert.deepEqual(tree(root), beforeReadOnly, "read-only commands changed the fixture tree");

  const noToken = invoke("build", "--input", sourceFile, "--out", out, "--authority", "synthetic-test"); assert.equal(noToken.status, 2); assert.equal(fs.existsSync(out), false);
  const relative = invoke("build", "--input", "relative.json", "--manifest", manifestFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(approved)); assert.equal(relative.status, 2); assert.equal(fs.existsSync(out), false);
  const wrongAuthority = invoke("build", "--input", sourceFile, "--manifest", manifestFile, "--out", out, "--authority", "signed-research-family-corpus", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(approved)); assert.equal(wrongAuthority.status, 2); assert.equal(fs.existsSync(out), false);
  const missingManifest = invoke("build", "--input", sourceFile, "--manifest", path.join(root, "absent.json"), "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(approved)); assert.equal(missingManifest.status, 2); assert.equal(fs.existsSync(out), false);
  const unapproved = invoke("build", "--input", sourceFile, "--manifest", proposedFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(proposed)); assert.equal(unapproved.status, 2); assert.equal(fs.existsSync(out), false);
  const mismatched = invoke("build", "--input", sourceFile, "--manifest", mismatchFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(mismatch)); assert.equal(mismatched.status, 2); assert.equal(fs.existsSync(out), false);
  assert.equal(invoke("build", "--input", sourceFile, "--manifest", hashMismatchFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(hashMismatch)).status, 2); assert.equal(fs.existsSync(out), false);
  assert.equal(invoke("build", "--input", sourceFile, "--manifest", pathMismatchFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(pathMismatch)).status, 2); assert.equal(fs.existsSync(out), false);
  assert.equal(invoke("build", "--input", sourceFile, "--manifest", manifestFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token).status, 2, "missing approval pins were accepted");
  assert.equal(invoke("build", "--input", sourceFile, "--manifest", manifestFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, "--approved-manifest-sha256", "0".repeat(64), "--approval-reference-sha256", approved.signingAuthority.approvalReferenceSha256).status, 2, "wrong manifest pin was accepted");
  assert.equal(invoke("build", "--input", sourceFile, "--manifest", manifestFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, "--approved-manifest-sha256", approved.sha256, "--approval-reference-sha256", "0".repeat(64)).status, 2, "wrong approval-reference pin was accepted");

  fs.mkdirSync(out); fs.writeFileSync(path.join(out, ".joint-shadow-corpus.lock"), `${JSON.stringify({schemaVersion: 1, pid: 2147483647})}\n`); fs.writeFileSync(path.join(out, "joint-battle-shadow-corpus.json.orphan.tmp"), "orphan");
  const built = invoke("build", "--input", sourceFile, "--manifest", manifestFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(approved)); assert.equal(built.status, 0, built.stderr); assert.equal(built.json.status, "complete"); assert.equal(built.json.recoveredTemporaryFiles, 1); assert.equal(built.json.authorityManifestSha256, approved.sha256); assert.equal(built.json.sourceAuthority, "synthetic-test"); assert.equal(built.json.verificationScope, "approved-source-recomputed"); assert.equal(built.json.approvedSourceRecomputed, true); assert.equal(built.json.formalActivationAllowed, false); assert.equal(built.json.routingAllowed, false);
  assert.equal(fs.existsSync(path.join(out, ".joint-shadow-corpus.lock")), false); assert.equal(fs.readdirSync(out).some(name => name.endsWith(".tmp")), false);
  const cached = invoke("build", "--input", sourceFile, "--manifest", manifestFile, "--out", out, "--authority", "synthetic-test", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(approved)); assert.equal(cached.status, 0); assert.equal(cached.json.status, "cached");

  const beforeChecks = tree(root), status = invoke("status", "--out", out), doctor = invoke("doctor", "--out", out, "--manifest", manifestFile, ...pins(approved)), inspectAgain = invoke("inspect", "--input", sourceFile);
  assert.equal(status.status, 0); assert.equal(status.json.verificationScope, "archive-self-check-only"); assert.equal(status.json.approvedSourceRecomputed, false); assert.equal(status.json.sourceAuthority, "synthetic-test");
  assert.equal(doctor.status, 0); assert.equal(doctor.json.verificationScope, "approved-source-recomputed"); assert.equal(doctor.json.approvedSourceRecomputed, true); assert.equal(doctor.json.sourceAuthority, "synthetic-test"); assert.equal(inspectAgain.status, 0); assert.deepEqual(tree(root), beforeChecks, "status/doctor/inspect wrote after corpus creation");
  const archiveFile = path.join(out, "joint-battle-shadow-corpus.json"), originalArchive = fs.readFileSync(archiveFile), originalSource = fs.readFileSync(sourceFile);
  const unavailableSourceFile = `${sourceFile}.unavailable`; fs.renameSync(sourceFile, unavailableSourceFile);
  const beforeUnavailableSourceChecks = tree(root), statusWithoutSource = invoke("status", "--out", out), doctorWithoutSource = invoke("doctor", "--out", out, "--manifest", manifestFile, ...pins(approved));
  assert.equal(statusWithoutSource.status, 0); assert.equal(statusWithoutSource.json.verificationScope, "archive-self-check-only"); assert.equal(statusWithoutSource.json.approvedSourceRecomputed, false); assert.equal(statusWithoutSource.json.sourceAuthority, "synthetic-test");
  assert.equal(doctorWithoutSource.status, 2); assert.equal(doctorWithoutSource.json.verificationScope, "not-verified"); assert.equal(doctorWithoutSource.json.approvedSourceRecomputed, false); assert.deepEqual(tree(root), beforeUnavailableSourceChecks, "status/doctor wrote while the approved source was unavailable"); fs.renameSync(unavailableSourceFile, sourceFile);

  const signedSourceFile = path.join(root, "signed-source.json"), signedManifestFile = path.join(root, "signed-authority.json"), signedOut = path.join(root, "signed-corpus"), signedSource = buildJointBattleShadowSource([entry("signed-closed", "closed-sheet", "train"), entry("signed-open", "open-sheet", "validation")], "signed-research-family-corpus");
  fs.writeFileSync(signedSourceFile, `${JSON.stringify(signedSource, null, 2)}\n`); const signedApproved = manifest("approved", signedSource.sha256, signedOut, fileHash(signedSourceFile), signedSourceFile, "signed-research-family-corpus"); fs.writeFileSync(signedManifestFile, `${JSON.stringify(signedApproved, null, 2)}\n`);
  const signedBuilt = invoke("build", "--input", signedSourceFile, "--manifest", signedManifestFile, "--out", signedOut, "--authority", "signed-research-family-corpus", "--signing-authority", signingAuthority, "--execute-token", token, ...pins(signedApproved)); assert.equal(signedBuilt.status, 0, signedBuilt.stderr); assert.equal(signedBuilt.json.sourceAuthority, "signed-research-family-corpus");
  const beforeSignedChecks = tree(root), signedStatus = invoke("status", "--out", signedOut), signedDoctor = invoke("doctor", "--out", signedOut, "--manifest", signedManifestFile, ...pins(signedApproved));
  assert.equal(signedStatus.json.sourceAuthority, "signed-research-family-corpus"); assert.equal(signedStatus.json.verificationScope, "archive-self-check-only"); assert.equal(signedStatus.json.approvedSourceRecomputed, false);
  assert.equal(signedDoctor.status, 0); assert.equal(signedDoctor.json.sourceAuthority, "signed-research-family-corpus"); assert.equal(signedDoctor.json.verificationScope, "approved-source-recomputed"); assert.equal(signedDoctor.json.approvedSourceRecomputed, true); assert.deepEqual(tree(root), beforeSignedChecks, "signed-research status/doctor wrote files");
  const alternativeSource = buildJointBattleShadowSource([entry("alternative-closed", "closed-sheet", "train"), entry("alternative-open", "open-sheet", "validation")], "synthetic-test"), alternativeArchive = extractJointBattleShadowCorpus(alternativeSource, approved.sha256);
  fs.writeFileSync(archiveFile, `${JSON.stringify(alternativeArchive, null, 2)}\n`);
  const beforeAlternativeArchiveDoctor = tree(root);
  const alternativeArchiveDoctor = invoke("doctor", "--out", out, "--manifest", manifestFile, ...pins(approved)); assert.equal(alternativeArchiveDoctor.status, 2, "structurally valid archive from another source passed doctor"); assert.equal(alternativeArchiveDoctor.json.approvedSourceRecomputed, false); assert.equal(alternativeArchiveDoctor.json.verificationScope, "not-verified");
  assert.deepEqual(tree(root), beforeAlternativeArchiveDoctor, "doctor wrote while rejecting an archive from another source");
  fs.writeFileSync(archiveFile, originalArchive);

  fs.writeFileSync(sourceFile, `${JSON.stringify(alternativeSource, null, 2)}\n`);
  const beforeChangedInputDoctor = tree(root);
  const changedInputDoctor = invoke("doctor", "--out", out, "--manifest", manifestFile, ...pins(approved)); assert.equal(changedInputDoctor.status, 2, "changed approved input passed doctor"); assert.equal(changedInputDoctor.json.approvedSourceRecomputed, false); assert.equal(changedInputDoctor.json.verificationScope, "not-verified");
  assert.deepEqual(tree(root), beforeChangedInputDoctor, "doctor wrote while rejecting changed approved input");
  fs.writeFileSync(sourceFile, originalSource);

  const archive = JSON.parse(originalArchive.toString("utf8")); archive.routingAllowed = true; fs.writeFileSync(archiveFile, JSON.stringify(archive));
  const tamperedStatus = invoke("status", "--out", out), tamperedDoctor = invoke("doctor", "--out", out, "--manifest", manifestFile, ...pins(approved)); assert.equal(tamperedStatus.json.approvedSourceRecomputed, false); assert.equal(tamperedStatus.json.verificationScope, "not-verified"); assert.equal(tamperedDoctor.status, 2, "tampered archive passed doctor"); assert.equal(tamperedDoctor.json.approvedSourceRecomputed, false); assert.equal(tamperedDoctor.json.verificationScope, "not-verified");

  const tamperedSource = JSON.parse(fs.readFileSync(sourceFile, "utf8")); tamperedSource.entries[0].environment = "changed"; fs.writeFileSync(sourceFile, JSON.stringify(tamperedSource));
  const rejectedInspect = invoke("inspect", "--input", sourceFile); assert.equal(rejectedInspect.status, 2, "tampered source passed inspect");
  console.log("Joint battle shadow corpus CLI smoke passed: explicit execution, zero-write inspection, signed extraction, mode isolation, stale-lock recovery, atomic output, and tamper rejection");
} finally { fs.rmSync(root, {recursive: true, force: true}); if (aliasContainer) fs.rmSync(aliasContainer, {recursive: true, force: true}); }

function entry(id: string, informationMode: "open-sheet" | "closed-sheet", split: "train" | "validation"): JointBattleShadowSourceEntry { const snapshot = jointSnapshot(informationMode), recommendation = recommendJointBattleShadow(snapshot), record = decisionRecord(id, snapshot, recommendation); return {record, familyId: `${id}-family`, familyClusterId: `${id}-cluster`, environment: "synthetic-fixture", split, sourceFingerprint: hash([id, "source"]), labels: snapshot.candidates.map(candidate => label(id, candidate.id))}; }
function jointSnapshot(informationMode: "open-sheet" | "closed-sheet"): JointBattleDecisionSnapshotV1 { const candidates = [candidate("move tackle", "move"), candidate("switch 2", "switch")]; return buildJointBattleDecisionSnapshot({informationMode, turn: 4, playerId: "p1", nodes: candidates.map(value => ({id: `candidate:${value.id}`, kind: "candidate", publicLabel: value.id})), edges: [], candidates, legacyFallback: {candidateId: "move tackle", source: "legacy-search", mandatoryWhenAllCandidatesVetoed: true}, modeAuxiliary: {label: "fixture", confidence: .5, authority: "diagnostic-only", routingAllowed: false}}); }
function candidate(id: string, actionKind: "move" | "switch"): JointBattleCandidateV1 { const values = Object.fromEntries(JOINT_BATTLE_FEATURES.map(feature => [feature, 0])) as JointBattleCandidateV1["values"]; Object.assign(values, {shortValue: .5, longValue: .4, uncertainty: .2, terminalRisk: .1}); return {id, actionKind, target: id, legal: true, values, knownMask: jointBattleKnownMask(["shortValue", "longValue", "uncertainty", "terminalRisk"])}; }
function decisionRecord(id: string, snapshot: JointBattleDecisionSnapshotV1, recommendation: ReturnType<typeof recommendJointBattleShadow>): UnifiedDecisionRecord { const open = snapshot.informationMode === "open-sheet"; return buildUnifiedDecisionRecord({decisionId: `${id}:p1:1`, domain: "battle", actor: "p1", ordinal: 1, policy: {id: "legacy-search", version: "fixture"}, information: {mode: snapshot.informationMode, timing: "contemporaneous", activationEligible: true, sources: ["own-private-request", "public-battle-protocol", ...(open ? ["declared-open-team-sheet"] : [])]}, observation: {turn: 4}, options: snapshot.candidates.map(value => ({id: value.id, score: value.values.shortValue})), selected: snapshot.legacyFallback.candidateId, provenance: {jointRelationalSnapshot: snapshot, jointBattleShadow: recommendation}}); }
function label(id: string, candidateId: string): JointBattleShadowSourceCandidateLabel { return {candidateId, shortUtility: .4, terminalUtility: 1, uncertainty: .2, terminalRisk: .1, branchFingerprint: hash([id, candidateId])}; }
function manifest(status: "proposed" | "approved", logicalSourceSha256: string, outputRoot: string, archiveSha256 = fileHash(sourceFile), inputArchive = sourceFile, sourceAuthority: JointBattleShadowSourceAuthority = "synthetic-test") { return buildProductionShadowSourceAuthorityManifest({status, sourceAuthority, lineage: {sourceSystem: "synthetic-fixture", sourceGeneration: "fixture-v1", purpose: "joint-shadow-corpus-extraction-only", parentManifestSha256: null}, recordContract: {version: "unified-decision-record-v1", encoderVersion: "relational-battle-encoder-v1", schemaSha256: productionShadowRecordSchemaSha256()}, isolation: {informationModes: ["closed-sheet", "open-sheet"], familyClusterModeIsolation: true, familySplitIsolation: true}, input: {archive: inputArchive, archiveSha256, logicalSourceSha256}, output: {root: outputRoot, retention: "retain-until-manual-safe-gc", recovery: "stale-lock-and-orphan-temp-only", overwrite: "reject-different-signed-archive"}, signingAuthority: {id: signingAuthority, scheme: "sha256-content-envelope", approvalReferenceSha256: hash(["synthetic-approval"])}}); }
function hash(value: unknown): string { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function fileHash(file: string): string { return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); }
function pins(value: {sha256: string; signingAuthority: {approvalReferenceSha256: string}}): string[] { return ["--approved-manifest-sha256", value.sha256, "--approval-reference-sha256", value.signingAuthority.approvalReferenceSha256]; }
function invoke(...args: string[]): {status: number | null; json: any; stderr: string} { const result = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(process.cwd(), "src", "cli", "jointBattleShadowCorpus.ts"), ...args], {cwd: process.cwd(), encoding: "utf8", maxBuffer: 8 * 1024 * 1024}), raw = result.stdout.trim() ? result.stdout : result.stderr; let json: any = {}; try { json = JSON.parse(raw); } catch {} return {status: result.status, json, stderr: result.stderr}; }
function tree(directory: string): Array<{file: string; size: number; mtimeMs: number; sha256: string}> { const rows: Array<{file: string; size: number; mtimeMs: number; sha256: string}> = []; const visit = (current: string) => { for (const entry of fs.readdirSync(current, {withFileTypes: true})) { const file = path.join(current, entry.name); if (entry.isDirectory()) visit(file); else { const stat = fs.statSync(file); rows.push({file: path.relative(directory, file), size: stat.size, mtimeMs: stat.mtimeMs, sha256: hash(fs.readFileSync(file).toString("base64"))}); } } }; visit(directory); return rows.sort((a, b) => a.file.localeCompare(b.file)); }
