import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {Teams} from "pokemon-showdown";
import {buildPositionValueModel, doctorPositionValue, pairedPositionFeatures, positionFeatures, predictPairedPositionValue} from "../ai/positionValue";
import {createBattleReplayCapsule} from "../showdown/battle";
import {AI_VERSION, DEFAULT_TACTICAL_PROFILE, EMPTY_OPPONENT_MODEL, type PositionSnapshot} from "../showdown/choice";
import {buildEvidenceEpoch, LEAGUE_CONFIGURATION_POLICY_VERSION} from "../showdown/evidenceEpoch";
import {teamStructuresFromReplay} from "../showdown/teamStructure";
import {BENCHMARK_FAMILY_VERSION} from "../draft/benchmarkFamilies";
import {buildRelationalDecisionSnapshot, relationalKnownMask, RELATIONAL_SWITCH_FEATURES} from "../ai/relationalDecision";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "mythic-position-value-")), source = path.join(root, "source"), out = path.join(root, "out");
try {
  let battle = 0;
  for (let cluster = 0; cluster < 60; cluster += 1) for (let replica = 0; replica < 2; replica += 1) {
    const directory = path.join(source, `cluster-${cluster}`, `game-${replica}`), p1Wins = (cluster + replica) % 2 === 0, capsule = createBattleReplayCapsule({schemaVersion: 2, aiVersion: AI_VERSION, format: "gen9ou", teamA: packedTeam(cluster * 2, cluster), teamB: packedTeam(cluster * 2 + 1, cluster), seed: [cluster + 1, replica + 1, 3, 4], maxTurns: 80, idleTimeoutMs: 1000, wallClockTimeoutMs: 5000, ai: "search", openTeamSheets: true, traceAiDecisions: true, aiProfiles: {p1: DEFAULT_TACTICAL_PROFILE, p2: DEFAULT_TACTICAL_PROFILE}, aiOpponentModels: {p1: EMPTY_OPPONENT_MODEL, p2: EMPTY_OPPONENT_MODEL}, evidenceEpoch: buildEvidenceEpoch(AI_VERSION, "gen9ou", {registryHash: "a".repeat(64), configurationPolicyVersion: LEAGUE_CONFIGURATION_POLICY_VERSION})});
    fs.mkdirSync(directory, {recursive: true}); write(path.join(directory, "replay-input.json"), capsule); write(path.join(directory, "end.json"), {winner: p1Wins ? "Team A" : "Team B", ended: true, turns: 12, timeout: false, aiDecisionCount: 4});
    const split = cluster < 40 ? "train" : cluster < 50 ? "validation" : "test", familyIds: [string, string] = [`${split}-family-${cluster % 8}`, `${split}-family-${(cluster + 3) % 8}`]; write(path.join(directory, "benchmark-evidence.json"), {schemaVersion: 1, version: BENCHMARK_FAMILY_VERSION, registrySha256: "b".repeat(64), scheduleSha256: "c".repeat(64), pairClusterId: `${split}:cluster-${cluster}`, split, familyIds, environment: cluster % 2 ? "modern-standard+ordinary-depth" : "combined+unrestricted", variants: ["base", "configuration-b"]});
    const p1 = snapshot(p1Wins), p2 = snapshot(!p1Wins); write(path.join(directory, "ai-decisions.json"), [trace("p1", 1, p1), trace("p2", 2, p2), trace("p1", 3, p1), trace("p2", 4, p2)]); battle += 1;
  }
  const first = buildPositionValueModel(source, out); assert.equal(first.battles, battle); assert.equal(first.audit.healthy, true, JSON.stringify(first.audit.issues)); assert.ok(first.testImprovement.vsConstantLogLossPercent > 0); assert.equal(first.audit.formalActivationAllowed, false); assert.equal(first.evidenceDesign.authority, "signed-family-registry"); assert.equal(first.evidenceDesign.bootstrapUnit, "family-block"); assert.deepEqual(first.evidenceDesign.familyLeakage, []);
  const favorable = snapshot(true), unfavorable = snapshot(false), structure = teamStructuresFromReplay(JSON.parse(fs.readFileSync(path.join(source, "cluster-0", "game-0", "replay-input.json"), "utf8"))); assert.equal(positionFeatures(favorable).length, 34); assert.equal(pairedPositionFeatures(favorable, unfavorable).length, 34); assert.equal(first.representation.structuralFeatures, 22); assert.equal(first.representation.nonConstantStructuralFeatures, 22); assert.equal(first.representation.distinctStructuralColumns, 22); assert.ok(first.representation.highlyCorrelatedStructuralPairs.some(value => value.includes("roleBreadthDelta/roleBreadthLate"))); assert.ok(Number.isFinite(first.selectedStructuralRegularization)); assert.ok(Object.values(structure.p1).every(value => value >= 0 && value <= 1)); assert.ok(Object.values(structure.p2).every(value => value >= 0 && value <= 1)); assert.ok(predictPairedPositionValue(favorable, unfavorable, first.model) > predictPairedPositionValue(unfavorable, favorable, first.model));
  const doctor = doctorPositionValue(out, true) as any; assert.equal(doctor.healthy, true); assert.equal(doctor.verifiedSources, 120);
  const summaryFile = path.join(out, "summary.json"), healthySummary = JSON.parse(fs.readFileSync(summaryFile, "utf8")); write(summaryFile, {...healthySummary, audit: {...healthySummary.audit, healthy: false, issues: [{severity: "error", code: "statistical-gate", message: "fixture gate"}]}}); assert.equal((doctorPositionValue(out, false) as any).healthy, false); write(summaryFile, healthySummary);
  const tamper = path.join(source, "cluster-0", "game-0", "end.json"), original = fs.readFileSync(tamper, "utf8"); fs.appendFileSync(tamper, " "); assert.equal((doctorPositionValue(out, true) as any).healthy, false); fs.writeFileSync(tamper, original, "utf8");
  const second = buildPositionValueModel(source, out); assert.equal(second.reusedSources, 120); assert.equal(second.modelCacheHit, true); assert.equal(second.model.sha256, first.model.sha256);
  console.log("Position value smoke passed: pre-action encoding, battle-cluster splits, calibrated model, signatures, symmetry, source verification, and incremental reuse");
} finally { try { fs.rmSync(root, {recursive: true, force: true}); } catch { /* Windows may retain a transient handle until exit. */ } }

function snapshot(favorable: boolean): PositionSnapshot { const strong = favorable ? {remaining: 6, hpTotal: 5.2, activeHp: .9} : {remaining: 3, hpTotal: 2.1, activeHp: .35}, weak = favorable ? {remaining: 3, hpTotal: 2.1, activeHp: .35} : {remaining: 6, hpTotal: 5.2, activeHp: .9}, side = (value: typeof strong) => ({...value, statusCount: favorable ? 0 : 2, activeStatus: !favorable, positiveBoosts: favorable ? 2 : 0, negativeBoosts: 0, hazards: favorable ? 0 : 2, screens: favorable ? 1 : 0}); return {schemaVersion: 1, encoderVersion: "position-snapshot-v1", turn: 10, own: side(strong), opponent: {...side(weak), statusCount: favorable ? 2 : 0, activeStatus: favorable, positiveBoosts: favorable ? 0 : 2, hazards: favorable ? 2 : 0, screens: favorable ? 0 : 1}, forcedSwitch: false, trapped: false, weather: null, fieldConditions: [], information: {ownHp: "private-request", opponentHp: "public-estimate"}}; }
function trace(playerId: "p1" | "p2", ordinal: number, positionSnapshot: PositionSnapshot): any { const favorable = positionSnapshot.own.remaining > positionSnapshot.opponent.remaining; return {decisionOrdinal: ordinal, turn: 5, playerId, strategy: "search", selected: "move tackle", positionSnapshot, relationalSnapshot: relational(playerId, favorable, ordinal), personalityId: "smoke", opponentModel: {confidence: 0, switchRate: 0, activeSpecies: null, activeMoveSamples: 0, fallbackMoveSamples: 0}, candidates: []}; }
function relational(playerId: "p1" | "p2", favorable: boolean, ordinal: number): ReturnType<typeof buildRelationalDecisionSnapshot> { const count = favorable ? 2 : 1, candidates = Array.from({length: count}, (_, candidateIndex) => { const id = `switch ${candidateIndex + 2}`, values = Object.fromEntries(RELATIONAL_SWITCH_FEATURES.map((feature, featureIndex) => [feature, (favorable ? .2 : .05) + ((featureIndex + 1) * (ordinal + 1) % 11) * .007 + candidateIndex * ((featureIndex % 3) + 1) * .011])) as Record<typeof RELATIONAL_SWITCH_FEATURES[number], number>; return {id, actionKind: "switch" as const, target: `Pokemon ${candidateIndex + 2}`, values, knownMask: relationalKnownMask(RELATIONAL_SWITCH_FEATURES)}; }); return buildRelationalDecisionSnapshot({informationMode: "open-sheet", turn: 5, playerId, nodes: candidates.map(candidate => ({id: `candidate:${candidate.id}`, kind: "candidate" as const, publicLabel: candidate.target})), edges: [], candidates}); }
function packedTeam(profile: number, cluster: number): string {
  const moveSets = [["Stealth Rock", "U-turn", "Earthquake", "Toxic"], ["Rapid Spin", "Recover", "Surf", "Ice Beam"], ["Swords Dance", "Sucker Punch", "Iron Head", "Low Kick"], ["Reflect", "Light Screen", "Volt Switch", "Nuzzle"], ["Spikes", "Roost", "U-turn", "Brave Bird"], ["Nasty Plot", "Shadow Ball", "Flamethrower", "Thunderbolt"], ["Defog", "Will-O-Wisp", "Hex", "Pain Split"], ["Dragon Dance", "Extreme Speed", "Dragon Claw", "Fire Punch"], ["Leech Seed", "Synthesis", "Giga Drain", "Earth Power"], ["Tidy Up", "Bullet Seed", "Rock Blast", "Knock Off"]];
  const species = ["Landorus-Therian", "Starmie", "Corviknight", "Clefable", "Dragapult", "Kingambit", "Rotom-Wash", "Dragonite", "Gholdengo", "Great Tusk", "Rillaboom", "Volcarona"];
  return Teams.pack(Array.from({length: 6}, (_, index) => { const speciesName = species[(profile * 3 + index * (profile % 5 + 1)) % species.length], moves = moveSets[(profile + index * (profile % 4 + 1)) % moveSets.length]; return {name: `${speciesName}-${cluster}-${index}`, species: speciesName, ability: "Pressure", item: "Leftovers", moves, nature: "Serious", evs: {hp: 252, atk: 252, def: 252, spa: 252, spd: 252, spe: 252}, ivs: {hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31}, gender: "", level: 100}; }));
}
function write(file: string, value: unknown): void { fs.writeFileSync(file, `${JSON.stringify(value)}\n`, "utf8"); }
