import assert from "node:assert/strict";
import {incubateProspectiveLineupFeatures} from "../ai/whiteBox/prospectiveLineupIncubator";
import type {LineupHypothesisObservation} from "../ai/whiteBox/lineupHypothesisWorkbench";

function fixture(reverseValidation = false): LineupHypothesisObservation[] { const rows: LineupHypothesisObservation[] = []; for (let season = 1; season <= 3; season++) for (let pair = 0; pair < 12; pair++) { const left = pair * 2 + 1, right = left + 1, leftWins = (pair + season) % 2 === 0; for (const [manager, wins] of [[left, leftWins], [right, !leftWins]] as const) { const aligned = season === 3 && reverseValidation ? !wins : wins, side = manager === left ? 0 : 1; rows.push({seriesId: `s${season}-p${pair}`, season, managerId: `manager-${String(manager).padStart(2, "0")}`, outcome: wins ? "win" : "loss", diagnostics: {"lineup.signalA": aligned ? 1 : side, "lineup.signalB": aligned ? 1 : 1 - side, "lineup.noise": pair % 2}}); } } return rows; }
const result = incubateProspectiveLineupFeatures(fixture(), [], 1000); assert.equal(result.conclusion, "prospective-candidates-ready"); assert.ok(result.metrics.novelPromoted >= 1); assert.ok(result.programs.some(value => value.promoted && value.incrementalValidationEffect >= .02 && value.incrementalComparisons.length === 2 && value.incrementalComparisons.every(comparison => comparison.adjustedQ <= .1))); assert.ok(result.promotedHypotheses.some(value => value.factors.length === 2)); assert.equal(result.activationStatus, "shadow-only");
const reversed = incubateProspectiveLineupFeatures(fixture(true), [], 1000); assert.equal(reversed.conclusion, "no-prospective-candidate-ready"); assert.equal(reversed.metrics.novelPromoted, 0);
const dominatedRows = fixture().map(row => ({...row, diagnostics: {...row.diagnostics, "lineup.signalA": row.outcome === "win" ? 1 : 0}})), dominated = incubateProspectiveLineupFeatures(dominatedRows, [], 1000); assert.ok(dominated.programs.every(program => !program.promoted || !program.factors.some(factor => factor.feature === "lineup.signalA")));
assert.throws(() => incubateProspectiveLineupFeatures(fixture().filter(row => row.season < 3), [], 100), /at least three seasons/);
assert.throws(() => incubateProspectiveLineupFeatures([...fixture(), fixture()[0]], [], 100), /unique season\/series\/manager/);
console.log("Prospective lineup incubator smoke passed: temporal holdout, frozen direction, FDR, and shadow-only promotion");
