import assert from "node:assert/strict";
import crypto from "node:crypto";
import {buildRelationalDecisionSnapshot, assertRelationalDecisionSnapshot, relationalKnownMask, RELATIONAL_SWITCH_FEATURES, type RelationalDecisionCandidateV1} from "../ai/relationalDecision";
import {buildRelationalCounterfactualCorpus, relationalCounterfactualSamples} from "../ai/relationalCounterfactual";
import {assessManagerProgramV3Promotion, evolveManagerProgramV3, managerProgramV3Hash, noviceManagerProgramV3, type RelationalCandidateSampleV3} from "../ai/managerProgramV3";
import {assertRelationalFormalHistory, assertRelationalStage4Submission, buildRelationalCanaryHandoff, buildRelationalFormalHistory, buildRelationalStage4Submission, evaluateRelationalFormalValidation, relationalCanaryRegressionP, updateRelationalResearchGeneration, type RelationalExperimentV3, type RelationalFormalCaseV3} from "../ai/relationalValidation";

const allKnown = relationalKnownMask(RELATIONAL_SWITCH_FEATURES), emptyValues = () => Object.fromEntries(RELATIONAL_SWITCH_FEATURES.map(feature => [feature, 0])) as Record<typeof RELATIONAL_SWITCH_FEATURES[number], number>;
function candidate(id: string, signal: number): RelationalDecisionCandidateV1 { const values = emptyValues(); values.candidateHp = signal; values.safeFollowupBreadth = signal; values.incomingWorst = 1 - signal; return {id, actionKind: "switch", target: id, values, knownMask: allKnown}; }
function sha(value: unknown): string { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }

const snapshot = buildRelationalDecisionSnapshot({informationMode: "closed-sheet", turn: 3, playerId: "p1", nodes: [{id: "own-active", kind: "own-active", publicLabel: "A"}, {id: "opponent-active", kind: "opponent-active", publicLabel: "B"}, {id: "candidate:switch 2", kind: "candidate", publicLabel: "C"}], edges: [{source: "candidate:switch 2", target: "opponent-active", kind: "threatens", value: .4, known: true}], candidates: [candidate("switch 2", .8)]});
assert.doesNotThrow(() => assertRelationalDecisionSnapshot(snapshot));
assert.deepEqual(buildRelationalDecisionSnapshot({informationMode: "closed-sheet", turn: 3, playerId: "p1", nodes: [...snapshot.nodes].reverse(), edges: [...snapshot.edges].reverse(), candidates: [...snapshot.candidates].reverse()}).sha256, snapshot.sha256);
const tampered = structuredClone(snapshot); tampered.candidates[0].values.candidateHp = .1; assert.throws(() => assertRelationalDecisionSnapshot(tampered), /signature mismatch/);
const hidden = candidate("switch 3", .5); hidden.knownMask = relationalKnownMask(RELATIONAL_SWITCH_FEATURES.filter(feature => feature !== "coverageResistance")); hidden.values.coverageResistance = .2; assert.throws(() => buildRelationalDecisionSnapshot({informationMode: "closed-sheet", turn: 1, playerId: "p1", nodes: [{id: "candidate:switch 3", kind: "candidate", publicLabel: "D"}], edges: [], candidates: [hidden]}), /Unknown relational feature/);

const rows = [] as Parameters<typeof buildRelationalCounterfactualCorpus>[0][number][];
for (const [split, offset] of [["train", 0], ["validation", 100], ["test", 200]] as const) for (let decision = 0; decision < 30; decision += 1) for (const [choice, signal] of [["switch 2", .9], ["switch 3", .1]] as const) rows.push({decisionId: `${split}-${decision}`, candidateId: choice, familyId: `${split}-family-${decision % 10}`, clusterId: `${split}-cluster-${decision}`, environment: decision % 2 ? "modern" : "combined", split, candidate: candidate(choice, signal), relationValues: {"edges.takes-response": [1 - signal, 1 - signal / 2]}, incumbentSearchScore: choice === "switch 2" ? 0 : 1, shortUtility: signal, terminalUtility: signal > .5 ? 1 : 0, sourceFingerprint: sha([split, offset, decision]), branchFingerprint: sha([split, offset, decision, choice])});
const corpus = buildRelationalCounterfactualCorpus(rows, {modelSha256: "a".repeat(64), evaluationSha256: "b".repeat(64), authority: "synthetic-test", vsLegacyLogLossPercent: 1, bootstrapProbabilityBetterThanLegacy: 1}), samples = relationalCounterfactualSamples(corpus), evidence = {encoderVersion: snapshot.encoderVersion, corpusSignature: corpus.sha256, familySplitSignature: sha(samples.map(sample => [sample.familyId, sample.split]))};
const population = Array.from({length: 30}, (_, index) => noviceManagerProgramV3(`manager-${index + 1}`, evidence));
const evolved = population.map((program, index) => evolveManagerProgramV3({program, discovery: samples.filter(sample => sample.split === "train"), validation: samples.filter(sample => sample.split === "validation"), population, seed: `manager-${index}`, generations: 48}).program);
assert.equal(evolved.every(program => program.rules.length <= 16), true);
assert.equal(new Set(evolved.map(program => sha(program.rules.map(rule => [rule.conditions, rule.terms])))).size > 1, true, "blank managers should evolve different relational programs");
assert.equal(evolved.some(program => program.rules.some(rule => [...rule.conditions, ...rule.terms].some(expression => expression.path.startsWith("edges.")))), true, "blank managers never discovered a relational edge program");
const best = evolved.map(program => ({program, promotion: assessManagerProgramV3Promotion(program, samples.filter(sample => sample.split === "test"), program.managerId, 200)})).sort((a, b) => b.promotion.accuracyGain - a.promotion.accuracyGain)[0];
assert.equal(best.promotion.eligible, true, JSON.stringify(best.promotion));

const programHash = managerProgramV3Hash(best.program), experiments: RelationalExperimentV3[] = [];
for (let index = 0; index < 12; index += 1) { const common = {managerId: best.program.managerId, programHash, sourceFingerprint: sha(["stage4", index]), familyClusterId: `stage4-${index}`, environment: index % 2 ? "modern" : "combined", shortDelta: .1, terminalDelta: 0 as const, technicalFailure: null}; experiments.push({id: `single-${index}`, level: "single-action", applications: 1, evaluations: 1, ...common}, {id: `continuation-${index}`, level: "continuation-program", applications: 2, evaluations: 5, ...common}); }
const submission = buildRelationalStage4Submission({program: best.program, ancestorSourceFingerprints: rows.map(row => row.sourceFingerprint), ancestorFamilyClusterIds: rows.map(row => row.clusterId), novel: true, supportingManagers: ["manager-a", "manager-b"], experiments}); assert.equal(submission.eligible, true, submission.reasons.join(","));
const semanticTamperCore = {...submission, experiments: submission.experiments.map((value, index) => index ? value : {...value, terminalDelta: -1 as const})}; delete (semanticTamperCore as Partial<typeof semanticTamperCore>).sha256; const semanticTamper = {...semanticTamperCore, sha256: sha(semanticTamperCore)}; assert.throws(() => assertRelationalStage4Submission(semanticTamper), /Invalid relational Stage-4 submission/);
const formalCases: RelationalFormalCaseV3[] = Array.from({length: 24}, (_, index) => ({id: `formal-${index}`, programHash, clusterId: `formal-cluster-${index}`, environment: index % 2 ? "modern" : "combined", sourceFingerprint: sha(["formal", index]), baselineUtility: 0, interventionUtility: 1, technicalFailure: null}));
const formal = evaluateRelationalFormalValidation([submission], formalCases)[0]; assert.equal(formal.eligible, true, formal.reasons.join(","));
const handoff = buildRelationalCanaryHandoff(submission, formal, sha(formalCases)); assert.equal(handoff.seasons, 2); assert.equal(handoff.applicationRate, .1); assert.equal(handoff.domain, "switch");
let generation = updateRelationalResearchGeneration(null, "no-candidate", "a".repeat(64)); assert.equal(generation.frozen, false); generation = updateRelationalResearchGeneration(generation, "falsified", "b".repeat(64)); assert.equal(generation.frozen, true); assert.equal(generation.counterexampleAtlasRequired, true);
const campaign = {id: "1".repeat(64), sourceIdentitySha256: "2".repeat(64), sourceAuthoritySha256: "3".repeat(64), archiveFile: "campaigns/one.json", archiveSha256: "4".repeat(64), programHashes: [programHash], completedAt: new Date(0).toISOString()}, formalHistory = buildRelationalFormalHistory([campaign]); assert.doesNotThrow(() => assertRelationalFormalHistory(formalHistory)); const reusedHistory = buildRelationalFormalHistory([campaign, {...campaign, id: "5".repeat(64), archiveFile: "campaigns/two.json", archiveSha256: "6".repeat(64)}]); assert.throws(() => assertRelationalFormalHistory(reusedHistory), /formal history/);
assert.equal(relationalCanaryRegressionP(4, 1), .1875); assert.equal(relationalCanaryRegressionP(8, 2), .054688);
const leaking = [...formalCases]; leaking[0] = {...leaking[0], sourceFingerprint: submission.ancestorSourceFingerprints[0]}; assert.equal(evaluateRelationalFormalValidation([submission], leaking)[0].eligible, false);
const clusterLeaking = [...formalCases]; clusterLeaking[0] = {...clusterLeaking[0], clusterId: submission.ancestorFamilyClusterIds[0]}; assert.equal(evaluateRelationalFormalValidation([submission], clusterLeaking)[0].eligible, false);
assert.equal(assessManagerProgramV3Promotion(best.program, samples.filter(sample => sample.split === "test"), "unqualified-teacher", 200, false).eligible, false);

console.log("Relational Manager V3 smoke passed: signed representation, masks, isolated corpus, autonomous programs, Stage 4/5 gates, and canary handoff");
