import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {archiveStageGeneration, auditStageGenerationArchives, gcStageGenerationArchives, prepareStageGeneration} from "../draft/stageGeneration";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "mythic-stage-generation-")), interrupted = fs.mkdtempSync(path.join(os.tmpdir(), "mythic-stage-interrupted-"));
try {
  fs.writeFileSync(path.join(root, "manifest.json"), "old"); fs.mkdirSync(path.join(root, "case-cache")); fs.writeFileSync(path.join(root, "case-cache", "case.json"), "old"); fs.writeFileSync(path.join(root, ".stage.lock"), "retained");
  const archived = archiveStageGeneration(root, "a".repeat(64), [".stage.lock"]);
  assert.deepEqual(archived.moved, ["case-cache", "manifest.json"]); assert.equal(fs.readFileSync(path.join(root, ".stage.lock"), "utf8"), "retained"); assert.equal(fs.readFileSync(path.join(archived.directory, "manifest.json"), "utf8"), "old"); assert.ok(fs.existsSync(path.join(archived.directory, "archive-manifest.json")));
  fs.writeFileSync(path.join(root, "manifest.json"), "new"); const second = archiveStageGeneration(root, "a".repeat(64), [".stage.lock"]); assert.notEqual(second.directory, archived.directory);
  fs.writeFileSync(path.join(root, "summary.json"), "orphan"); assert.throws(() => prepareStageGeneration({rootDirectory: root, anchorName: "manifest.json", inputSignature: "b".repeat(64), retainedNames: [".stage.lock"], replaceStale: false, validateAnchor: () => { throw new Error("unreachable"); }}), /missing manifest\.json/);
  const orphan = prepareStageGeneration({rootDirectory: root, anchorName: "manifest.json", inputSignature: "b".repeat(64), retainedNames: [".stage.lock"], replaceStale: true, validateAnchor: () => { throw new Error("unreachable"); }}); assert.ok(orphan); assert.deepEqual(orphan.moved, ["summary.json"]); assert.equal(fs.readFileSync(path.join(orphan.directory, "summary.json"), "utf8"), "orphan");

  const interruptedTarget = path.join(interrupted, "archive", "generation-interrupted"); fs.mkdirSync(interruptedTarget, {recursive: true}); fs.writeFileSync(path.join(interruptedTarget, "first.json"), "first"); fs.writeFileSync(path.join(interrupted, "second.json"), "second");
  fs.writeFileSync(path.join(interruptedTarget, "archive-manifest.json"), `${JSON.stringify({schemaVersion: 1, inputSignature: "c".repeat(64), archivedAt: new Date().toISOString(), state: "moving", planned: ["first.json", "second.json"], moved: ["first.json"]})}\n`);
  const recovered = prepareStageGeneration({rootDirectory: interrupted, anchorName: "manifest.json", inputSignature: "c".repeat(64), replaceStale: true, validateAnchor: () => { throw new Error("unreachable"); }}); assert.equal(recovered?.directory, interruptedTarget); assert.deepEqual(recovered?.moved, ["first.json", "second.json"]); assert.equal(fs.readFileSync(path.join(interruptedTarget, "second.json"), "utf8"), "second"); assert.equal(JSON.parse(fs.readFileSync(path.join(interruptedTarget, "archive-manifest.json"), "utf8")).state, "complete");
  const conflictTarget = path.join(interrupted, "archive", "generation-conflict"); fs.mkdirSync(conflictTarget, {recursive: true}); fs.writeFileSync(path.join(conflictTarget, "failures.json"), "old"); fs.writeFileSync(path.join(interrupted, "failures.json"), "new"); fs.writeFileSync(path.join(conflictTarget, "archive-manifest.json"), `${JSON.stringify({schemaVersion: 1, inputSignature: "d".repeat(64), archivedAt: new Date().toISOString(), sourceRoot: interrupted, state: "moving", planned: ["failures.json"], moved: ["failures.json"]})}\n`); prepareStageGeneration({rootDirectory: interrupted, anchorName: "manifest.json", inputSignature: "d".repeat(64), replaceStale: true, validateAnchor: () => { throw new Error("unreachable"); }}); assert.equal(fs.readFileSync(path.join(conflictTarget, "failures.json"), "utf8"), "old"); assert.equal(fs.readFileSync(path.join(conflictTarget, "recovery-controls", "failures.json"), "utf8"), "new");
  const dryGc = gcStageGenerationArchives(root, {budgetBytes: Number.MAX_SAFE_INTEGER, maxGenerations: 2, apply: false}); assert.equal(dryGc.removed.length, 1); assert.equal(auditStageGenerationArchives(root).entries.length, 3); const appliedGc = gcStageGenerationArchives(root, {budgetBytes: Number.MAX_SAFE_INTEGER, maxGenerations: 2, apply: true}); assert.equal(appliedGc.removed.length, 1); assert.equal(auditStageGenerationArchives(root).entries.length, 2); const retainNewest = gcStageGenerationArchives(root, {budgetBytes: 0, maxGenerations: 1, apply: false}); assert.equal(retainNewest.projectedGenerations, 1); assert.equal(retainNewest.removed.length, 1);
  console.log("Stage generation smoke passed: journals recover conflicts, orphaned anchors archive, and bounded GC removes only complete old generations");
} finally { fs.rmSync(root, {recursive: true, force: true}); fs.rmSync(interrupted, {recursive: true, force: true}); }
