import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import {spawnSync} from "node:child_process";
import {AI_PIPELINE_VERSION, evaluatePipeline, repairPreflightBlockers, type PipelineEvaluation, type PipelineStageId, type PipelineStageSnapshot} from "../ai/pipelineControl";
import {evaluateFormalValidation} from "../ai/formalValidation";
import {POSITION_FEATURE_VERSION} from "../ai/positionValue";
import {AI_VERSION} from "../showdown/choice";
import {buildEvidenceEpoch, LEAGUE_CONFIGURATION_POLICY_VERSION, sha256 as canonicalSha} from "../showdown/evidenceEpoch";
import {acquireNamedRunLock} from "../draft/runLock";
import {validateRegistryDirectory} from "../draft/registrySnapshot";

const args = process.argv.slice(2), command = args[0] && !args[0].startsWith("--") ? args[0] : "status", root = process.cwd();
const tooling = path.resolve(option("--root", "output/tooling")), league = path.resolve(option("--league", "output/official-era-03/league")), out = path.resolve(option("--out", path.join(tooling, "ai-pipeline-stage6")));
const roots = {
  stage1: path.resolve(option("--decision-dossiers", path.join(tooling, "decision-dossiers"))),
  stage2: path.resolve(option("--position-value", path.join(tooling, "position-value-stage2"))),
  corpus: path.resolve(option("--position-corpus", path.join(tooling, "position-value-corpus-v1"))),
  stage3: path.resolve(option("--manager-program-v2", path.join(tooling, "manager-program-v2"))),
  stage4: path.resolve(option("--autonomous-research", path.join(tooling, "autonomous-research-stage4-delivery-v2"))),
  stage5: path.resolve(option("--formal-validation", path.join(tooling, "formal-validation-stage5-delivery-v2"))),
};

interface WatchEntry {file: string; bytes: number; mtimeMs: number; sha256: string}
interface PipelineIndex {schemaVersion: 1; version: typeof AI_PIPELINE_VERSION; generatedAt: string; roots: Record<string, string>; watched: WatchEntry[]; evaluation: PipelineEvaluation; signature: string}
interface DoctorDetail {stage: PipelineStageId; command: string; exitCode: number; elapsedMs: number; healthy: boolean; verifiedSources: number; result: unknown; stderr?: string}

async function main(): Promise<void> {
  fs.mkdirSync(out, {recursive: true});
  if (command === "status") print(compact(loadOrRefresh()));
  else if (command === "doctor") { const value = doctor(args.includes("--deep") || args.includes("--verify-sources"), args.includes("--verify-sources")); print(value); if (!value.healthy) process.exitCode = 2; }
  else if (command === "run") print(run(false));
  else if (command === "resume") print(run(true));
  else if (command === "report") print(writeReport(loadOrRefresh()));
  else if (command === "inspect") print(inspect(stageOption("--stage")));
  else if (command === "refresh") print(compact(refresh()));
  else throw new Error("Usage: npm run ai-pipeline -- <status|doctor|run|resume|report|inspect|refresh> [--deep|--verify-sources|--dry-run]");
}

function refresh(): PipelineIndex {
  const watched = watchFiles().filter(fs.existsSync).map(fingerprint), snapshots = buildSnapshots(), evaluation = evaluatePipeline(snapshots);
  const core = {schemaVersion: 1 as const, version: AI_PIPELINE_VERSION as typeof AI_PIPELINE_VERSION, generatedAt: new Date().toISOString(), roots: {tooling, league, ...roots}, watched, evaluation};
  const index: PipelineIndex = {...core, signature: digest(core)}; atomicJson(path.join(out, "index.json"), index); atomicJson(path.join(out, "status.json"), compact(index)); fs.writeFileSync(path.join(out, "report.md"), markdown(index), "utf8");
  atomicJson(path.join(out, "token-budget.json"), {schemaVersion: 1, statusBytes: Buffer.byteLength(JSON.stringify(compact(index))), estimatedStatusTokens: Math.ceil(Buffer.byteLength(JSON.stringify(compact(index))) / 4), detailedStages: 6}); return index;
}

function loadOrRefresh(): PipelineIndex { const index = optional<PipelineIndex>(path.join(out, "index.json")); return index && validIndex(index) && indexFresh(index) ? index : refresh(); }

function buildSnapshots(): PipelineStageSnapshot[] {
  const audit = optional<any>(path.join(league, "audit-summary.json")), auditRun = optional<any>(path.join(league, "audit-run-state.json")), auditSignature = formalAuditSignature(), currentPolicy = buildEvidenceEpoch(AI_VERSION, "gen9ou").policySha256;
  const s1 = optional<any>(path.join(roots.stage1, "summary.json")), s1Run = optional<any>(path.join(roots.stage1, "build-state.json"));
  const s2 = optional<any>(path.join(roots.stage2, "summary.json")), s2Run = optional<any>(path.join(roots.stage2, "build-state.json")), s2Model = optional<any>(path.join(roots.stage2, "model.json"));
  const s3 = optional<any>(path.join(roots.stage3, "summary.json")), s3Run = optional<any>(path.join(roots.stage3, "build-state.json")), s3Corpus = optionalGzip<any>(path.join(roots.stage3, "corpus.json.gz")), s3Programs = optionalGzip<any>(path.join(roots.stage3, "programs.json.gz"));
  const s4 = optional<any>(path.join(roots.stage4, "summary.json")), s4Run = optional<any>(path.join(roots.stage4, "run-state.json")), s4Manifest = optional<any>(path.join(roots.stage4, "manifest.json"));
  const s5 = optional<any>(path.join(roots.stage5, "summary.json")), s5Run = optional<any>(path.join(roots.stage5, "run-state.json")), s5Freeze = optional<any>(path.join(roots.stage5, "freeze.json")), s5Plan = optional<any>(path.join(roots.stage5, "plan.json")), s5Results = optionalGzip<any>(path.join(roots.stage5, "results.json.gz"));
  const s5BenchmarkTeams = formalBenchmarkTeamBindings(s5Freeze), s5SummaryBinding = formalSummaryProjectionHealthy(s5, s5Freeze, s5Plan, s5Results);
  const s1Binding = Boolean(s1?.sourceAuditSignature && s1.sourceAuditSignature === audit?.inputSignature && s1.currentPolicySha256 === currentPolicy), s2Binding = Boolean(s2Model?.sha256 && s2?.model?.sha256 === s2Model.sha256), s3Binding = Boolean(s3Corpus?.signature === s3?.inputSignature && Array.isArray(s3Programs?.programs) && s3Programs.programs.every((program: any) => program.evidence?.corpusSignature === s3Corpus.signature && program.evidence?.positionModelSha256 === s3Corpus.modelSha256)), s4Binding = Boolean(s4Manifest?.inputSignature === s4?.inputSignature && digest(s4Manifest?.inputs) === s4Manifest?.inputSignature && inputFingerprintsHealthy(s4Manifest?.inputs, ["programs", "corpus", "stage3Summary"], [], stage4InputFiles()) && stage4RoundsHealthy(s4Manifest)), s5Binding = Boolean(signedCoreHealthy(s5Freeze) && s5Freeze?.sha256 === s5?.freezeSha256 && s5Freeze?.inputSignature === s5?.inputSignature && inputFingerprintsHealthy(s5Freeze?.inputs, ["stage4States", "stage4Summary", "programs", "positionModel", "benchmarkIndex"], ["benchmarkTeam:"], stage5InputFiles()) && s5BenchmarkTeams.healthy && s5SummaryBinding && formalEvidenceContextHealthy(s5Freeze) && s5Plan?.freezeSha256 === s5Freeze?.sha256 && s5Results?.planSha256 === s5Plan?.sha256 && signedCoreHealthy(s5Plan) && signedCoreHealthy(s5Results));
  const issue = (condition: boolean, code: string, message: string, severity: "error" | "warning" = "warning") => condition ? [{severity, code, message}] : [];
  return [
    {id: "stage0", name: "Evidence era and self-audit", dependencies: [], artifactAvailable: Boolean(audit && auditRun && auditSignature.available), runStatus: auditRun?.status ?? null, semanticHealthy: Boolean(audit?.schemaVersion === 6 && Number(audit?.fatalCount ?? 1) === 0 && audit?.evidenceEpoch?.policySha256 === currentPolicy && auditSignature.matches), authority: "evidence-policy", authorityReady: audit?.evidenceEpoch?.formalActivationReady === true, inputSignature: audit?.inputSignature ?? null, metrics: {completedSeasons: Number(audit?.completedSeasons ?? 0), auditedBattles: Number(audit?.evidenceEpoch?.auditedBattles ?? 0), formalActivationReady: audit?.evidenceEpoch?.formalActivationReady === true}, issues: [...issue(Boolean(audit) && audit?.evidenceEpoch?.formalActivationReady !== true, "formal-era-coverage-pending", "Latest league season is not fully covered by current formal evidence") ]},
    {id: "stage1", name: "Decision dossiers", dependencies: ["stage0"], artifactAvailable: Boolean(s1), runStatus: s1Run?.status ?? null, semanticHealthy: Boolean(s1?.healthy === true && Array.isArray(s1?.anomalies) && !s1.anomalies.length && s1Binding), authority: "historical-observational", authorityReady: s1?.formalDecisionCoverageReady === true && s1Binding, inputSignature: s1?.inputSignature ?? null, metrics: {decisions: Number(s1?.decisions ?? 0), managers: Number(s1?.managers ?? 0), representedBattles: Number(s1?.battleCoverage?.representedBattles ?? 0), formalDecisionCoverageReady: s1?.formalDecisionCoverageReady === true}, issues: [...issue(Boolean(s1) && !s1Binding, "decision-dossier-binding", "Decision dossiers are not bound to the current league audit and evidence policy", "error"), ...issue(Boolean(s1) && s1?.formalDecisionCoverageReady !== true, "formal-dossier-coverage-pending", "Decision dossiers are complete but current-era formal coverage is unavailable")]},
    {id: "stage2", name: "Position value", dependencies: ["stage1"], artifactAvailable: Boolean(s2 && s2Model), runStatus: s2Run?.status ?? null, semanticHealthy: Boolean(s2?.audit?.healthy === true && s2?.audit?.formalActivationAllowed === false && s2Binding), authority: "shadow-only", authorityReady: false, inputSignature: s2?.inputSignature ?? null, metrics: {battles: Number(s2?.battles ?? 0), samples: Number(s2?.samples ?? 0), improvementVsConstantPercent: Number(s2?.testImprovement?.vsConstantLogLossPercent ?? 0)}, issues: [...normalizeIssues(s2?.audit?.issues), ...issue(Boolean(s2) && !s2Binding, "position-model-binding", "Position-value summary is not bound to the retained model", "error")]},
    {id: "stage3", name: "Manager program V2", dependencies: ["stage1", "stage2"], artifactAvailable: Boolean(s3 && s3Corpus && s3Programs), runStatus: s3Run?.status ?? null, semanticHealthy: Boolean(s3?.audit?.healthy === true && s3?.formalActivationAllowed === false && s3Binding), authority: "shadow-only", authorityReady: false, inputSignature: s3?.inputSignature ?? null, metrics: {managers: Number(s3?.population?.managers ?? 0), uniqueBehaviors: Number(s3?.population?.uniqueBehaviorHashes ?? 0), testImprovementPercent: Number(s3?.evaluation?.improvementPercent ?? 0)}, issues: [...normalizeIssues(s3?.audit?.issues), ...issue(Boolean(s3) && !s3Binding, "manager-program-binding", "Manager programs, corpus, and position model are not bound", "error")]},
    {id: "stage4", name: "Autonomous research", dependencies: ["stage3"], artifactAvailable: Boolean(s4 && s4Manifest), runStatus: s4Run?.status ?? null, semanticHealthy: Boolean(s4?.audit?.healthy === true && s4?.formalActivationAllowed === false && s4Binding), authority: "shadow-only", authorityReady: false, inputSignature: s4?.inputSignature ?? null, metrics: {managers: Number(s4?.managers ?? 0), rounds: Number(s4?.completedRounds ?? 0), experiments: Number(s4?.experiments ?? 0), adaptedManagers: Number(s4?.research?.managersAdapted ?? 0)}, issues: [...normalizeIssues(s4?.audit?.issues), ...issue(Boolean(s4) && !s4Binding, "autonomous-research-binding", "Stage-4 manifest inputs or summary binding drifted", "error")]},
    {id: "stage5", name: "Formal validation", dependencies: ["stage4"], artifactAvailable: Boolean(s5 && s5Freeze), runStatus: s5Run?.status ?? null, semanticHealthy: Boolean(s5?.audit?.healthy === true && s5?.formalValidationCompleted === true && s5?.automaticActivationAllowed === false && s5Binding), authority: "validation-only", authorityReady: s5BenchmarkTeams.bound && Array.isArray(s5?.limitedCanaryEligibleDomains) && s5.limitedCanaryEligibleDomains.length > 0, inputSignature: s5?.inputSignature ?? null, metrics: {experiments: Number(s5?.experiments?.completed ?? 0), sourceBattles: Number(s5?.sources?.battles ?? 0), limitedCanaryEligibleDomains: s5?.limitedCanaryEligibleDomains ?? []}, issues: [...normalizeIssues(s5?.audit?.issues), ...issue(Boolean(s5) && !s5Binding, "formal-validation-binding", "Stage-5 freeze inputs or summary binding drifted", "error"), ...issue(Boolean(s5Freeze) && !s5BenchmarkTeams.bound, "legacy-benchmark-team-freeze", "Historical freeze lacks per-team benchmark fingerprints; rebuild before canary authority"), ...issue(Boolean(s5) && !(s5?.limitedCanaryEligibleDomains?.length), "no-limited-canary-domain", "Formal validation completed, but no decision domain passed the limited-canary gate")]},
  ];
}

function doctor(deep: boolean, verifySources: boolean): Record<string, unknown> {
  const started = Date.now(), index = refresh(), details: DoctorDetail[] = [];
  if (deep) for (const spec of specialistCommands(verifySources)) details.push(runDoctor(spec.stage, spec.file, spec.args));
  const sharedSources = verifySources ? verifySharedCorpusSources() : {healthy: true, verifiedSources: 0, issues: [] as string[]}, specialistFailures = details.filter(value => !value.healthy), healthy = index.evaluation.operationalHealthy && !specialistFailures.length && sharedSources.healthy;
  if (deep) atomicGzip(path.join(out, "doctor-details.json.gz"), {schemaVersion: 1, version: AI_PIPELINE_VERSION, verifySources, details});
  const result = {schemaVersion: 1, version: AI_PIPELINE_VERSION, indexSignature: index.signature, healthy, mode: verifySources ? "full-source" : deep ? "deep" : "quick", elapsedMs: Date.now() - started, operationalHealthy: index.evaluation.operationalHealthy, researchComplete: index.evaluation.researchComplete, formalActivationReady: index.evaluation.formalActivationReady, limitedCanaryEligibleDomains: index.evaluation.limitedCanaryEligibleDomains, stages: index.evaluation.stages.map(stage => ({id: stage.id, state: stage.state, authority: stage.authority, authorityReady: stage.authorityReady})), blockers: index.evaluation.blockers, warnings: index.evaluation.warnings, sharedSources, specialists: details.map(value => ({stage: value.stage, healthy: value.healthy, exitCode: value.exitCode, elapsedMs: value.elapsedMs, verifiedSources: value.verifiedSources}))};
  atomicJson(path.join(out, "doctor.json"), result); const detailFile = path.join(out, "doctor-details.json.gz"), detailBytes = fs.existsSync(detailFile) ? fs.statSync(detailFile).size : 0; atomicJson(path.join(out, "doctor-token-budget.json"), {schemaVersion: 1, mode: result.mode, summaryBytes: Buffer.byteLength(JSON.stringify(result)), estimatedSummaryTokens: Math.ceil(Buffer.byteLength(JSON.stringify(result)) / 4), compressedDetailBytes: detailBytes}); return result;
}

function run(resume: boolean): Record<string, unknown> {
  const before = loadOrRefresh(), prior = optional<any>(path.join(out, "run-state.json")), explicitStage = optionalStage("--stage"), dryRun = args.includes("--dry-run"), force = args.includes("--force");
  let from = explicitStage ?? optionalStage("--from") ?? (force ? "stage1" : resume && prior?.currentStage ? normalizeStage(prior.currentStage) : before.evaluation.nextStage), to = explicitStage ?? optionalStage("--to") ?? "stage5";
  if (from === "stage0") from = "stage1"; const selected = from ? stageRange(from, to) : [], planned = selected.filter(stage => force || before.evaluation.stages.find(value => value.id === stage)?.state !== "complete");
  if (!dryRun) { const preflight = doctor(true, false) as any, blockers = repairPreflightBlockers(preflight, planned[0] ?? null); if (blockers.length) throw new Error(`AI pipeline repair preflight failed: ${blockers.join("; ")}. Inspect ${path.join(out, "doctor.json")}`); }
  if (!from) return {status: "complete", noOp: true, message: "All stages are operationally complete", evaluation: compact(before).evaluation};
  if (dryRun) return {status: "dry-run", from, to, force, planned: planned.map(stage => ({stage, command: executionCommand(stage)})), skipped: selected.filter(stage => !planned.includes(stage))};
  if (!planned.length) return {status: "complete", noOp: true, selected, message: "Selected stages are already complete"};
  const lock = acquireNamedRunLock(out, ".ai-pipeline.lock", {command: resume ? "resume" : "run", from, to}); const started = Date.now(), items: Array<{stage: PipelineStageId; status: string; elapsedMs?: number}> = [];
  try {
    for (const stage of planned) {
      const current = refresh().evaluation, dependencies = current.stages.find(value => value.id === stage)!.dependencies; if (dependencies.some(dependency => current.stages.find(value => value.id === dependency)?.state !== "complete")) throw new Error(`${stage} dependencies are not complete`);
      atomicJson(path.join(out, "run-state.json"), {schemaVersion: 1, version: AI_PIPELINE_VERSION, status: "running", currentStage: stage, items, startedAt: new Date(started).toISOString()}); const spec = executionCommand(stage), stageStarted = Date.now(), result = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(root, spec.file), ...spec.args], {cwd: root, stdio: "inherit"});
      if (result.error || result.status !== 0) throw result.error ?? new Error(`${stage} exited ${result.status}`); const refreshed = refresh().evaluation, delivered = refreshed.stages.find(value => value.id === stage); if (delivered?.state !== "complete") throw new Error(`${stage} exited successfully but remained ${delivered?.state ?? "missing"}`); items.push({stage, status: "complete", elapsedMs: Date.now() - stageStarted});
    }
    const after = refresh(); atomicJson(path.join(out, "run-state.json"), {schemaVersion: 1, version: AI_PIPELINE_VERSION, status: "complete", currentStage: null, items, elapsedMs: Date.now() - started}); return {status: "complete", items, evaluation: compact(after).evaluation};
  } catch (error) { const failure = {stage: items.length < planned.length ? planned[items.length] : null, message: error instanceof Error ? error.message : String(error)}; atomicJson(path.join(out, "run-state.json"), {schemaVersion: 1, version: AI_PIPELINE_VERSION, status: "failed", currentStage: failure.stage, items, elapsedMs: Date.now() - started, failure}); throw error; }
  finally { lock.release(); }
}

function executionCommand(stage: PipelineStageId): {file: string; args: string[]} {
  if (stage === "stage1") return {file: "src/cli/decisionDossiers.ts", args: ["build", "--league", league, "--out", roots.stage1]};
  if (stage === "stage2") return {file: "src/cli/positionValue.ts", args: ["build", "--source", roots.corpus, "--out", roots.stage2]};
  if (stage === "stage3") return {file: "src/cli/managerProgramV2.ts", args: ["build", "--out", roots.stage3, "--dossiers", roots.stage1, "--position-value", roots.stage2, "--corpus", roots.corpus]};
  if (stage === "stage4") return {file: "src/cli/autonomousResearch.ts", args: ["cycle", "--replace-stale", "--out", roots.stage4, "--manager-programs", roots.stage3, "--source-corpus", roots.corpus, "--rounds", "6"]};
  if (stage === "stage5") return {file: "src/cli/formalValidation.ts", args: ["cycle", "--replace-stale", "--out", roots.stage5, "--autonomous-research", roots.stage4, "--manager-programs", roots.stage3, "--position-value", roots.stage2]};
  throw new Error("Stage 0 is audited, not rebuilt by the research pipeline");
}

function specialistCommands(verify: boolean): Array<{stage: PipelineStageId; file: string; args: string[]}> { const flag = verify ? ["--verify-sources"] : []; return [
  {stage: "stage0", file: "src/cli/leagueControl.ts", args: ["doctor", "--out", league]},
  {stage: "stage1", file: "src/cli/decisionDossiers.ts", args: ["doctor", "--out", roots.stage1, ...flag]},
  {stage: "stage2", file: "src/cli/positionValue.ts", args: ["doctor", "--out", roots.stage2]},
  {stage: "stage3", file: "src/cli/managerProgramV2.ts", args: ["doctor", "--out", roots.stage3, "--dossiers", roots.stage1, "--position-value", roots.stage2, "--corpus", roots.corpus]},
  {stage: "stage4", file: "src/cli/autonomousResearch.ts", args: ["doctor", "--out", roots.stage4, "--manager-programs", roots.stage3, "--source-corpus", roots.corpus]},
  {stage: "stage5", file: "src/cli/formalValidation.ts", args: ["doctor", "--out", roots.stage5, "--autonomous-research", roots.stage4, "--manager-programs", roots.stage3, "--position-value", roots.stage2, ...flag]},
]; }

function runDoctor(stage: PipelineStageId, file: string, childArgs: string[]): DoctorDetail { const started = Date.now(), result = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(root, file), ...childArgs], {cwd: root, encoding: "utf8", maxBuffer: 32 * 1024 * 1024}), parsed = parseJson(result.stdout); return {stage, command: `${file} ${childArgs.join(" ")}`, exitCode: result.status ?? 1, elapsedMs: Date.now() - started, healthy: !result.error && result.status === 0 && (parsed as any)?.healthy !== false, verifiedSources: Number((parsed as any)?.verifiedSources ?? 0), result: parsed, ...(result.stderr ? {stderr: result.stderr.slice(-4096)} : {})}; }
function verifySharedCorpusSources(): {healthy: boolean; verifiedSources: number; issues: string[]} {
  const stage2 = optionalGzip<any>(path.join(roots.stage2, "source-cache.json.gz")), stage3 = optionalGzip<any>(path.join(roots.stage3, "corpus.json.gz")), stage4 = optionalGzip<any>(path.join(roots.stage4, "frontier.json.gz")), issues: string[] = [];
  if (!stage2?.sources || !stage3?.sourceFingerprints || !Array.isArray(stage4?.rows)) return {healthy: false, verifiedSources: 0, issues: ["shared source archives are missing"]};
  const stage4BySource = new Map<string, any>(); for (const row of stage4.rows) { const prior = stage4BySource.get(row.relative); if (prior && (prior.decisionsSha256 !== row.decisionsSha256 || prior.replaySha256 !== row.replaySha256 || prior.sourceFingerprint !== row.sourceFingerprint)) issues.push(`Stage 4 has conflicting fingerprints: ${row.relative}`); else stage4BySource.set(row.relative, row); }
  const keys = [...new Set([...Object.keys(stage2.sources), ...Object.keys(stage3.sourceFingerprints), ...stage4BySource.keys()])].sort();
  for (const relative of keys) {
    try {
      if (!stage2.sources[relative] || !stage3.sourceFingerprints[relative] || !stage4BySource.has(relative)) throw new Error("stage source inventories differ");
      const decisionFile = path.join(roots.corpus, ...relative.split("/")), game = path.dirname(decisionFile), replayFile = path.join(game, "replay-input.json"), endFile = path.join(game, "end.json"), decisionBytes = fs.readFileSync(decisionFile), replayBytes = fs.readFileSync(replayFile), endBytes = fs.readFileSync(endFile), decisionSha = digestBytes(decisionBytes), replaySha = digestBytes(replayBytes), endSha = digestBytes(endBytes);
      const stage2Fingerprint = canonicalSha({featureVersion: stage2.featureVersion ?? POSITION_FEATURE_VERSION, decision: decisionSha, replay: replaySha, end: endSha}), stage3Fingerprint = digestBytes(Buffer.concat([decisionBytes, endBytes])), row = stage4BySource.get(relative);
      if (stage2.sources[relative].fingerprint !== stage2Fingerprint) throw new Error("Stage-2 fingerprint drift"); if (stage3.sourceFingerprints[relative] !== stage3Fingerprint) throw new Error("Stage-3 fingerprint drift"); if (row.decisionsSha256 !== decisionSha || row.replaySha256 !== replaySha || row.sourceFingerprint !== digest([replaySha, decisionSha])) throw new Error("Stage-4 fingerprint drift");
    } catch (error) { issues.push(`${relative}: ${error instanceof Error ? error.message : String(error)}`); }
  }
  return {healthy: !issues.length, verifiedSources: keys.length, issues: issues.slice(0, 100)};
}
function inspect(stage: PipelineStageId): Record<string, unknown> { const index = loadOrRefresh(), value = index.evaluation.stages.find(item => item.id === stage)!; return {stage: value, watched: index.watched.filter(item => stageWatchFiles(stage).includes(item.file)), command: stage === "stage0" ? null : executionCommand(stage)}; }
function compact(index: PipelineIndex): Record<string, any> { return {schemaVersion: 1, version: index.version, generatedAt: index.generatedAt, indexSignature: index.signature, indexFresh: indexFresh(index), evaluation: {operationalHealthy: index.evaluation.operationalHealthy, researchComplete: index.evaluation.researchComplete, formalActivationReady: index.evaluation.formalActivationReady, limitedCanaryEligibleDomains: index.evaluation.limitedCanaryEligibleDomains, nextStage: index.evaluation.nextStage, nextMilestones: index.evaluation.nextMilestones, stages: index.evaluation.stages.map(stage => ({id: stage.id, name: stage.name, state: stage.state, authority: stage.authority, authorityReady: stage.authorityReady, metrics: stage.metrics})), blockers: index.evaluation.blockers, warnings: index.evaluation.warnings}}; }
function writeReport(index: PipelineIndex): Record<string, unknown> { const file = path.join(out, "report.md"); fs.writeFileSync(file, markdown(index), "utf8"); return {report: file, operationalHealthy: index.evaluation.operationalHealthy, researchComplete: index.evaluation.researchComplete, formalActivationReady: index.evaluation.formalActivationReady}; }
function markdown(index: PipelineIndex): string { const value = index.evaluation; return `# AI Pipeline Stage 6\n\n- Operational health: ${value.operationalHealthy ? "healthy" : "blocked"}\n- Research chain complete: ${value.researchComplete ? "yes" : "no"}\n- Formal activation ready: ${value.formalActivationReady ? "yes" : "no"}\n- Limited-canary domains: ${value.limitedCanaryEligibleDomains.length ? value.limitedCanaryEligibleDomains.join(", ") : "none"}\n- Next repair stage: ${value.nextStage ?? "none"}\n- Next product milestones: ${value.nextMilestones.join(", ") || "none"}\n\n| Stage | State | Authority | Authority ready |\n|---|---|---|---|\n${value.stages.map(stage => `| ${stage.id}: ${stage.name} | ${stage.state} | ${stage.authority} | ${stage.authorityReady ? "yes" : "no"} |`).join("\n")}\n\n## Warnings\n\n${value.warnings.length ? value.warnings.map(row => `- ${row.stage}/${row.code}: ${row.message}`).join("\n") : "- None"}\n`;
}

function watchFiles(): string[] {
  const stage4Manifest = optional<any>(path.join(roots.stage4, "manifest.json")), stage4RoundFiles = Array.isArray(stage4Manifest?.rounds) ? stage4Manifest.rounds.flatMap((round: any) => [path.join(roots.stage4, String(round.plan ?? "")), path.join(roots.stage4, String(round.results ?? ""))]) : [], implementationFiles = ["package.json", "package-lock.json", "tsconfig.json", "src/showdown/choice.ts", "src/showdown/battle.ts", "src/showdown/mechanics.ts", "src/showdown/evidenceEpoch.ts", "src/draft/decisionDossierStore.ts", "src/ai/positionValue.ts", "src/ai/managerProgramV2.ts", "src/ai/autonomousResearch.ts", "src/ai/formalValidation.ts", "src/ai/pipelineControl.ts", "src/cli/decisionDossiers.ts", "src/cli/positionValue.ts", "src/cli/managerProgramV2.ts", "src/cli/autonomousResearch.ts", "src/cli/formalValidation.ts", "src/cli/aiPipeline.ts"].map(file => path.join(root, file));
  const files = (["audit-summary.json", "audit-run-state.json", ".audit-signature-cache.json", "dynasty-state.json"].map(name => path.join(league, name))).concat([path.join(roots.stage1, "summary.json"), path.join(roots.stage1, "build-state.json"), path.join(roots.stage1, "decision-dossiers.sqlite"), path.join(roots.stage2, "summary.json"), path.join(roots.stage2, "build-state.json"), path.join(roots.stage2, "model.json"), path.join(roots.stage2, "source-cache.json.gz"), path.join(roots.corpus, "corpus-manifest.json"), path.join(roots.stage3, "summary.json"), path.join(roots.stage3, "build-state.json"), path.join(roots.stage3, "corpus.json.gz"), path.join(roots.stage3, "programs.json.gz"), path.join(roots.stage4, "summary.json"), path.join(roots.stage4, "run-state.json"), path.join(roots.stage4, "manifest.json"), path.join(roots.stage4, "manager-states.json.gz"), path.join(roots.stage4, "frontier.json.gz"), ...stage4RoundFiles, path.join(roots.stage5, "summary.json"), path.join(roots.stage5, "run-state.json"), path.join(roots.stage5, "freeze.json"), path.join(roots.stage5, "plan.json"), path.join(roots.stage5, "results.json.gz"), path.join(roots.stage5, "frontier.json.gz"), ...["balanced", "pressure"].map(environment => path.join(roots.stage5, "sources", environment, "manifest.json")), ...findRuntimeFiles(path.join(root, "data/draft")), ...findRuntimeFiles(path.join(root, "benchmarks/gen9expanded")), ...implementationFiles]); return [...new Set(files.map(file => path.resolve(file)))];
}
function stageWatchFiles(stage: PipelineStageId): string[] { const index = Number(stage.slice(-1)); return watchFiles().filter(file => index === 0 ? file.startsWith(league) || file.endsWith("evidenceEpoch.ts") : file.startsWith((roots as any)[`stage${index}`] ?? "")); }
function validIndex(index: PipelineIndex): boolean { const {signature, ...core} = index; return index.schemaVersion === 1 && index.version === AI_PIPELINE_VERSION && digest(core) === signature; }
function indexFresh(index: PipelineIndex): boolean { return index.watched.every(entry => { try { const stat = fs.statSync(entry.file); return stat.size === entry.bytes && Math.abs(stat.mtimeMs - entry.mtimeMs) < 1; } catch { return false; } }) && watchFiles().filter(fs.existsSync).length === index.watched.length; }
function formalAuditSignature(): {available: boolean; matches: boolean} { const summary = optional<any>(path.join(league, "audit-summary.json")), cache = optional<any>(path.join(league, ".audit-signature-cache.json")), stateFile = path.join(league, "dynasty-state.json"); if (!summary || cache?.schemaVersion !== 1 || !cache.files || !fs.existsSync(stateFile)) return {available: false, matches: false}; const hash = crypto.createHash("sha256"); for (const key of Object.keys(cache.files).sort()) hash.update(`${key}\0${cache.files[key].sha256}\0`); const stat = fs.statSync(stateFile), state = cache.files["dynasty-state.json"]; return {available: true, matches: summary.inputSignature === hash.digest("hex") && state?.size === stat.size && Math.abs(state?.mtimeMs - stat.mtimeMs) < 1}; }
function normalizeIssues(value: unknown): PipelineStageSnapshot["issues"] { return Array.isArray(value) ? value.filter(item => item && ["error", "warning"].includes(item.severity) && item.code && item.message) : []; }
function inputFingerprintsHealthy(value: unknown, requiredKeys: readonly string[], allowedPrefixes: readonly string[] = [], expectedFiles: Record<string, string> = {}): boolean { if (!value || typeof value !== "object") return false; const inputs = value as Record<string, any>, keys = Object.keys(inputs); if (requiredKeys.some(key => !keys.includes(key)) || keys.some(key => !requiredKeys.includes(key) && !allowedPrefixes.some(prefix => key.startsWith(prefix))) || Object.entries(expectedFiles).some(([key, file]) => path.resolve(inputs[key]?.file ?? "") !== path.resolve(file))) return false; return Object.values(inputs).every(entry => entry?.file && fs.existsSync(entry.file) && fs.statSync(entry.file).size === entry.bytes && shaFile(entry.file) === entry.sha256); }
function stage4InputFiles(): Record<string, string> { return {programs: path.join(roots.stage3, "programs.json.gz"), corpus: path.join(roots.stage3, "corpus.json.gz"), stage3Summary: path.join(roots.stage3, "summary.json")}; }
function stage5InputFiles(): Record<string, string> { return {stage4States: path.join(roots.stage4, "manager-states.json.gz"), stage4Summary: path.join(roots.stage4, "summary.json"), programs: path.join(roots.stage3, "programs.json.gz"), positionModel: path.join(roots.stage2, "model.json"), benchmarkIndex: path.join(root, "benchmarks/gen9expanded/index.json")}; }
function formalBenchmarkTeamBindings(freeze: any): {bound: boolean; healthy: boolean} {
  const inputs = freeze?.inputs; if (!inputs || typeof inputs !== "object") return {bound: false, healthy: false}; const keys = Object.keys(inputs).filter(key => key.startsWith("benchmarkTeam:")).sort(); if (!keys.length) return {bound: false, healthy: true};
  try { const indexEntry = inputs.benchmarkIndex, index = JSON.parse(fs.readFileSync(indexEntry.file, "utf8")) as {benchmarks: Array<{id: string; team: string}>}, base = path.dirname(indexEntry.file), expected = index.benchmarks.map((benchmark, position) => [`benchmarkTeam:${String(position + 1).padStart(3, "0")}:${benchmark.id}`, path.resolve(base, benchmark.team)] as const); if (JSON.stringify(keys) !== JSON.stringify(expected.map(([key]) => key).sort())) return {bound: true, healthy: false}; for (const [key, file] of expected) if (path.resolve(inputs[key]?.file ?? "") !== file) return {bound: true, healthy: false}; const set = Object.fromEntries(keys.map(key => [key, inputs[key]])); return {bound: true, healthy: freeze.benchmarkTeamSetSha256 === canonicalSha(set)}; } catch { return {bound: true, healthy: false}; }
}
function formalSummaryProjectionHealthy(summary: any, freeze: any, plan: any, results: any): boolean { try { if (!summary || !freeze || !plan || !results || summary.sha256 && !signedCoreHealthy(summary)) return false; const domains = evaluateFormalValidation(freeze.domains.map((domain: any) => domain.id), results.cases, freeze.environments, freeze.gate), eligible = domains.filter((domain: any) => domain.disposition === "limited-canary-eligible").map((domain: any) => domain.domainId), reserved = plan.items.flatMap((item: any) => [item.sourceFingerprint, ...item.fallbacks.map((fallback: any) => fallback.sourceFingerprint)]), expectedExperiments = {planned: plan.items.length, completed: results.cases.length - results.unresolvedTechnicalFailures, technicalAttempts: results.technicalAttempts, unresolvedTechnicalFailures: results.unresolvedTechnicalFailures, fallbackSelections: results.fallbackSelections, outcomeChanges: results.cases.filter((result: any) => result.outcomeChanged).length, uniqueBattlesUsed: new Set(results.cases.map((result: any) => result.sourceFingerprint)).size, reservedBattles: reserved.length}; return JSON.stringify(summary.domains) === JSON.stringify(domains) && JSON.stringify(summary.limitedCanaryEligibleDomains) === JSON.stringify(eligible) && JSON.stringify(summary.experiments) === JSON.stringify(expectedExperiments); } catch { return false; } }
function formalEvidenceContextHealthy(freeze: any): boolean { try { const registryHash = validateRegistryDirectory(path.join(root, "data/draft")).hash, format = String(optional<any>(path.join(root, "benchmarks/gen9expanded/index.json"))?.format ?? ""), epoch = buildEvidenceEpoch(AI_VERSION, format, {registryHash, configurationPolicyVersion: LEAGUE_CONFIGURATION_POLICY_VERSION}); return freeze?.evidenceEpoch?.registryHash === registryHash && freeze?.evidenceEpoch?.configurationPolicyVersion === LEAGUE_CONFIGURATION_POLICY_VERSION && freeze?.evidenceEpoch?.policySha256 === epoch.policySha256; } catch { return false; } }
function findRuntimeFiles(directory: string): string[] { const result: string[] = []; if (!fs.existsSync(directory)) return result; const stack = [directory]; while (stack.length) { const current = stack.pop()!; for (const entry of fs.readdirSync(current, {withFileTypes: true})) { const target = path.join(current, entry.name); if (entry.isDirectory()) stack.push(target); else if (entry.isFile()) result.push(target); } } return result; }
function stage4RoundsHealthy(manifest: any): boolean { return Array.isArray(manifest?.rounds) && manifest.rounds.every((round: any, index: number) => round?.round === index + 1 && [[round.plan, round.planSha256], [round.results, round.resultsSha256]].every(([relative, expected]) => { const file = path.join(roots.stage4, String(relative ?? "")); return /^[a-f0-9]{64}$/i.test(String(expected ?? "")) && fs.existsSync(file) && shaFile(file) === expected; })); }
function signedCoreHealthy(value: any): boolean { if (!value || typeof value !== "object" || !/^[a-f0-9]{64}$/i.test(String(value.sha256 ?? ""))) return false; const {sha256, ...core} = value; return canonicalSha(core) === sha256; }
function stageRange(from: PipelineStageId, to: PipelineStageId): PipelineStageId[] { const all: PipelineStageId[] = ["stage1", "stage2", "stage3", "stage4", "stage5"], start = all.indexOf(from), end = all.indexOf(to); if (start < 0 || end < start) throw new Error(`Invalid pipeline range: ${from}..${to}`); return all.slice(start, end + 1); }
function optionalStage(name: string): PipelineStageId | null { const value = option(name, ""); return value ? normalizeStage(value) : null; }
function stageOption(name: string): PipelineStageId { const value = optionalStage(name); if (!value) throw new Error(`${name} is required`); return value; }
function normalizeStage(value: unknown): PipelineStageId { const raw = String(value).toLowerCase(), normalized = /^[0-5]$/.test(raw) ? `stage${raw}` : raw.replace(/^s/, "stage"); if (!/^stage[0-5]$/.test(normalized)) throw new Error(`Invalid pipeline stage: ${value}`); return normalized as PipelineStageId; }
function fingerprint(file: string): WatchEntry { const stat = fs.statSync(file); return {file: path.resolve(file), bytes: stat.size, mtimeMs: stat.mtimeMs, sha256: shaFile(file)}; }
function parseJson(text: string): unknown { const start = text.indexOf("{"); if (start < 0) return {output: text.trim()}; try { return JSON.parse(text.slice(start)); } catch { return {output: text.trim()}; } }
function shaFile(file: string): string { return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); }
function digestBytes(value: Buffer): string { return crypto.createHash("sha256").update(value).digest("hex"); }
function digest(value: unknown): string { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function atomicJson(file: string, value: unknown): void { atomicBuffer(file, Buffer.from(`${JSON.stringify(value, null, 2)}\n`)); }
function atomicGzip(file: string, value: unknown): void { atomicBuffer(file, zlib.gzipSync(Buffer.from(JSON.stringify(value)), {level: 9})); }
function atomicBuffer(file: string, bytes: Buffer): void { fs.mkdirSync(path.dirname(file), {recursive: true}); const temporary = `${file}.${process.pid}.${crypto.randomBytes(3).toString("hex")}.tmp`; fs.writeFileSync(temporary, bytes); fs.renameSync(temporary, file); }
function optional<T>(file: string): T | null { try { return JSON.parse(fs.readFileSync(file, "utf8")) as T; } catch { return null; } }
function optionalGzip<T>(file: string): T | null { try { return JSON.parse(zlib.gunzipSync(fs.readFileSync(file)).toString("utf8")) as T; } catch { return null; } }
function option(name: string, fallback: string): string { const index = args.indexOf(name); return index >= 0 ? args[index + 1] ?? fallback : fallback; }
function print(value: unknown): void { console.log(JSON.stringify(value, null, 2)); }

main().catch(error => { console.error(error instanceof Error ? error.stack ?? error.message : error); process.exitCode = 1; });
