import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {auditCausalOutcomeBoundary, auditProspectiveBoundaryProxies, type CausalBoundaryCase, type ProspectiveBoundaryCase} from "../ai/whiteBox/causalBoundaryAudit";

const args = process.argv.slice(2), root = process.cwd(), registryFile = path.resolve(option("--import-registry", "output/tooling/manager-mechanism-ledgers/import-registry.json")), out = path.resolve(option("--out", "output/tooling/causal-boundary-audit")), permutations = integerOption("--permutations", 10000, 100, 100000);
const seasonSourceValue = option("--season-source", ""), seasonSource = seasonSourceValue ? path.resolve(seasonSourceValue) : null, registry = read<any>(registryFile), records = Object.entries<any>(registry.imports ?? {}), studies = new Map<string, any>(), itemByEvidence = new Map<string, any>();
for (const record of records.map(([, value]) => value)) { const study = path.resolve(root, String(record.study)); if (!studies.has(study)) studies.set(study, read<any>(path.join(study, "causal-manifest.json"))); }
const cases: CausalBoundaryCase[] = [];
for (const [importKey, record] of records) { const separator = importKey.indexOf(":"); if (separator < 1) throw new Error(`Invalid imported experiment key: ${importKey}`); const mechanismId = importKey.slice(0, separator), choiceId = importKey.slice(separator + 1), study = path.resolve(root, String(record.study)), item = (studies.get(study).items ?? []).find((value: any) => String(value.id) === choiceId); if (!item || item.status !== "complete") throw new Error(`Imported experiment source is unavailable: ${importKey}`); itemByEvidence.set(importKey, item); cases.push({evidenceId: importKey, managerId: String(item.managerId), mechanismId, season: Number(item.season), sourceOutcome: item.sourceOutcome, effect: item.result.direction === "better" ? 1 : item.result.direction === "worse" ? -1 : 0}); }
const result = auditCausalOutcomeBoundary(cases, permutations), prospectiveProxyScreen = seasonSource ? auditProspectiveBoundaryProxies(deriveProspectiveCases(cases, itemByEvidence, seasonSource), permutations) : null, artifact = {...result, prospectiveProxyScreen}; fs.mkdirSync(out, {recursive: true}); fs.writeFileSync(path.join(out, "causal-boundary-audit.json"), `${JSON.stringify(artifact, null, 2)}\n`, "utf8"); fs.writeFileSync(path.join(out, "causal-boundary-audit.md"), `# Causal boundary audit\n\n- Conclusion: ${result.conclusion}\n- Direction: ${result.direction}\n- Decision-time available: ${result.decisionTimeAvailable}\n- Activation eligible: ${result.activationEligible}\n- Cases/managers/mechanisms/seasons: ${result.metrics.cases}/${result.metrics.managers}/${result.metrics.mechanisms}/${result.metrics.seasons}\n- Source-loss/source-win mean: ${result.metrics.lossMean}/${result.metrics.winMean}\n- Difference: ${result.metrics.effectDifference}\n- Stratified permutation p: ${result.metrics.stratifiedPermutationP}\n- Matched-manager sign permutation p: ${result.metrics.managerSignPermutationP}\n- Prospective proxy screen: ${prospectiveProxyScreen?.conclusion ?? "not-run"}\n\nThe source outcome is known only after the lineup decision. This retrospective boundary cannot activate a policy. Prospective proxies are exploratory and also remain activation-ineligible.\n`, "utf8"); const compact = {conclusion: result.conclusion, direction: result.direction, decisionTimeAvailable: result.decisionTimeAvailable, activationEligible: result.activationEligible, metrics: result.metrics, byMechanism: result.byMechanism, leaveOneMechanismOut: result.leaveOneMechanismOut, prospectiveProxyScreen, activationStatus: result.activationStatus}; fs.writeFileSync(path.join(out, "token-budget.json"), `${JSON.stringify({compactBytes: Buffer.byteLength(JSON.stringify(compact)), estimatedCompactTokens: Math.ceil(Buffer.byteLength(JSON.stringify(compact)) / 3.5)}, null, 2)}\n`, "utf8"); console.log(JSON.stringify(compact, null, 2));
function deriveProspectiveCases(cases: CausalBoundaryCase[], items: Map<string, any>, source: string): ProspectiveBoundaryCase[] { const marker = read<any>(path.join(source, "source-cache.json")), leagues = new Map<number, any[]>(); for (const season of [...new Set(cases.map(value => value.season))]) { const relative = `season-${String(season).padStart(2, "0")}/season.json`, file = path.join(source, relative); if (!fs.existsSync(file) || marker.evidence?.[relative] !== hash(file)) throw new Error(`Season source cache integrity failure: ${relative}`); leagues.set(season, read<any>(file).league); } return cases.map(value => { const item = items.get(value.evidenceId), league = leagues.get(value.season)!, seriesId = String(item.decisionId).split(":")[1], current = league.find(entry => entry.id === seriesId), round = current?.round ?? Number.POSITIVE_INFINITY, prior = league.filter(entry => (entry.left === value.managerId || entry.right === value.managerId) && entry.round < round).sort((left, right) => left.round - right.round), history = prior.map(entry => { const own = entry.left === value.managerId ? entry.leftPairs : entry.rightPairs, opponent = entry.left === value.managerId ? entry.rightPairs : entry.leftPairs; return own > opponent ? "win" : own < opponent ? "loss" : "draw"; }).filter(outcome => outcome !== "draw"), lastThree = history.slice(-3), lossRate = (values: string[]) => values.filter(outcome => outcome === "loss").length / values.length; return {...value, previousLoss: history.length ? history.at(-1) === "loss" : undefined, recentThreeLossRateHigh: history.length >= 2 ? lossRate(lastThree) >= .5 : undefined, seasonLossRateHigh: history.length ? lossRate(history) >= .5 : undefined}; }); }
function hash(file: string): string { return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); }
function read<T>(file: string): T { return JSON.parse(fs.readFileSync(file, "utf8")) as T; }
function option(name: string, fallback: string): string { const index = args.indexOf(name); return index >= 0 ? args[index + 1] ?? fallback : fallback; }
function integerOption(name: string, fallback: number, minimum: number, maximum: number): number { const value = Number(option(name, String(fallback))); if (!Number.isInteger(value) || value < minimum || value > maximum) throw new Error(`Invalid ${name}`); return value; }
