import fs from "node:fs";
import path from "node:path";
import {evaluateLineupAssistGate} from "../ai/whiteBox/lineup";
import {evaluateWhiteBoxCounterfactualBatch,whiteBoxCounterfactualBatchMarkdown,type WhiteBoxCounterfactualSample} from "../ai/whiteBox/counterfactualBatch";

const args=process.argv.slice(2),sampler=path.resolve(option("--sampler","output/whitebox-lineup-sampler-01")),out=path.resolve(option("--out",path.join(sampler,"assist-audit"))),manifest=read<any>(path.join(sampler,"sampler-manifest.json")),directories=[...manifest.existing,...manifest.seeds.filter((entry:any)=>entry.status==="complete"&&entry.experiment).map((entry:any)=>entry.experiment)],cases=directories.map(audit),approved=cases.filter(entry=>entry.gate.recommended),reasonCounts=count(cases.flatMap(entry=>entry.gate.hardRejections));fs.mkdirSync(out,{recursive:true});const samples=approved.map(entry=>entry.sample),batch=samples.length?evaluateWhiteBoxCounterfactualBatch(samples,10):null,summary={schemaVersion:1,total:cases.length,approved:approved.length,blocked:cases.length-approved.length,reasonCounts,cases:cases.map(({sample,...entry})=>entry),approvedBatch:batch};fs.writeFileSync(path.join(out,"lineup-assist-audit.json"),`${JSON.stringify(summary,null,2)}\n`,"utf8");const report=["# 白箱阵容 Assist 门禁审计","",`- 全部/通过/拦截：${cases.length}/${approved.length}/${cases.length-approved.length}`,`- 拦截原因：${Object.entries(reasonCounts).map(([key,value])=>`${key}:${value}`).join("、")||"无"}`,"",...(batch?[whiteBoxCounterfactualBatchMarkdown(batch)]:["没有通过门禁的配对样本。",""])].join("\n");fs.writeFileSync(path.join(out,"lineup-assist-audit.md"),report,"utf8");console.log(JSON.stringify({total:cases.length,approved:approved.length,blocked:cases.length-approved.length,reasonCounts,promotion:batch?.promotion??"no-approved-samples",metrics:batch?.metrics??null,report:path.join(out,"lineup-assist-audit.md")},null,2));
function audit(directory:string){const summary=read<any>(path.join(directory,"counterfactual-summary.json")),state=read<any>(path.join(directory,"incumbent","dynasty-state.json")),found=findTrace(path.join(directory,"whitebox"),summary.decisionId),incumbent=found.candidates.find((entry:any)=>entry.id===found.comparison.incumbent),selected=found.candidates.find((entry:any)=>entry.id===found.comparison.shadow),gate=evaluateLineupAssistGate(incumbent,selected),sample:WhiteBoxCounterfactualSample={seed:state.seed,caseId:summary.decisionId,prefixVerified:Boolean(summary.prefixVerified),comparison:summary.comparison};return{seed:state.seed,decisionId:summary.decisionId,gate,sample};}
function findTrace(root:string,target:string):any{for(const entry of fs.readdirSync(root,{withFileTypes:true}).filter(entry=>entry.isDirectory()&&/^season-\d+$/.test(entry.name))){const file=path.join(root,entry.name,"decision-ledger.json");if(!fs.existsSync(file))continue;for(const record of read<any>(file).records??[]){const trace=record.context?.whiteBoxLineupExperiment?.trace;if(trace?.decisionId===target)return trace;}}throw new Error(`Missing lineup experiment trace: ${target}`);}
function count(values:string[]):Record<string,number>{return Object.fromEntries([...new Set(values)].sort().map(value=>[value,values.filter(entry=>entry===value).length]));}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?args[index+1]??fallback:fallback;}function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}
