import fs from "node:fs";
import path from "node:path";
import {auditBattleCandidateFrontier,battleFrontierDigest} from "../ai/whiteBox/battleCandidateFrontier";

const args=process.argv.slice(2),source=path.resolve(required("--source")),out=path.resolve(option("--out","output/tooling/battle-candidate-frontier")),examplesPerManager=integer("--examples-per-manager",3,0,100000);
const audit=auditBattleCandidateFrontier(source,{examplesPerManagerMechanism:examplesPerManager}),summary={schemaVersion:1,activationStatus:audit.activationStatus,evidenceStatus:audit.evidenceStatus,coverage:audit.coverage,mechanisms:audit.mechanisms,examplesPerManager:examplesPerManager===0?"all":examplesPerManager,sha256:battleFrontierDigest(audit),estimatedSummaryTokens:Math.ceil(Buffer.byteLength(JSON.stringify({coverage:audit.coverage,mechanisms:audit.mechanisms}))/4)};
const titles:Record<string,string>={"alternate-move":"Test a different reasonable move","alternate-switch":"Test a different reasonable switch","move-to-switch":"Test switching on a reasonable move frontier","switch-to-move":"Test attacking on a reasonable switch frontier"};
const researchOptions={schemaVersion:1,activationStatus:"shadow-only",evidenceStatus:"observational-candidate-frontier",hypotheses:audit.mechanisms.map(value=>({id:value.id,title:titles[value.mechanism],observationalCandidate:false,researchEligible:true,evidenceStatus:"observational-candidate-frontier",causalConclusion:null,coverage:{managers:value.managers,opportunities:value.opportunities,exactTies:value.exactTies}}))};
fs.mkdirSync(out,{recursive:true});write(path.join(out,"battle-candidate-frontier.json"),audit);write(path.join(out,"research-options.json"),researchOptions);write(path.join(out,"summary.json"),summary);fs.writeFileSync(path.join(out,"summary.md"),`# Battle Candidate Frontier\n\n- Decisions/comparisons: ${audit.coverage.decisions}/${audit.coverage.comparisons}\n- Incumbent-shadow agreements: ${audit.coverage.agreements}/${audit.coverage.comparisons}\n- Decisions with a reasonable alternative frontier: ${audit.coverage.frontierDecisions}\n- Managers: ${audit.coverage.managers}\n- Mechanisms: ${audit.mechanisms.map(value=>`${value.mechanism}=${value.opportunities}`).join(", ")}\n\nThis is an observational research menu. It neither selects a manager hypothesis nor authorizes a live action.\n`,"utf8");console.log(JSON.stringify(summary,null,2));
function write(file:string,value:unknown):void{const temporary=`${file}.${process.pid}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,"utf8");fs.renameSync(temporary,file);}
function required(name:string):string{const value=option(name,"");if(!value)throw new Error(`Missing ${name}`);return value;}
function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?String(args[index+1]??fallback):fallback;}
function integer(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`Invalid ${name}`);return value;}
