import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";

const args=process.argv.slice(2),directory=path.resolve(required("--workbench")),planFile=path.resolve(required("--plan")),out=path.resolve(required("--out")),runOption=option("--run",""),runDirectory=runOption?path.resolve(runOption):null,issues:string[]=[];
const manifest=read<any>(path.join(directory,"manifest.json")),plan=read<any>(planFile);
const sourceArtifactFile=path.resolve(String(manifest.inputs?.frontier?.file??"")),sourceArtifact=fs.existsSync(sourceArtifactFile)?read<any>(sourceArtifactFile):null,sourceRoot=path.resolve(String(sourceArtifact?.source??process.cwd()));
if(manifest.schemaVersion!==1||manifest.activationStatus!=="shadow-only")issues.push("invalid-workbench-manifest");
if(plan.schemaVersion!==1||plan.activationStatus!=="shadow-only"||plan.evidenceStatus!=="manager-selected-research-only"||plan.authority!=="no-activation-authority")issues.push("invalid-research-plan");
for(const input of [manifest.inputs?.frontier,manifest.inputs?.baseOptions,...Object.values(manifest.inputs?.implementation??{}),...(manifest.inputs?.researchInputs??[]).flatMap((value:any)=>[value.plan,value.summary])])verifyFingerprint(input,"workbench-input");
for(const input of Object.values(manifest.outputs??{}))verifyFingerprint(input as any,"workbench-output");
if(sha(Buffer.from(canonical(manifest.inputs)))!==manifest.inputSetSha256)issues.push("workbench-input-set-signature-drift");
for(const input of [plan.frontier,plan.agendas,...(plan.excludedPlans??[])])verifyPlanFingerprint(input);
const planningFile=path.resolve(String(plan.frontier?.file??"")),planning=fs.existsSync(planningFile)?read<any>(planningFile):null;if(!planning||planning.activationStatus!=="shadow-only"||planning.validity?.activationAllowed!==false||!Array.isArray(planning.managerMechanisms))issues.push("invalid-planning-frontier");
const rows=new Map<string,any>();for(const row of planning?.managerMechanisms??[]){const mechanismId=String(row.mechanismId??`battle-frontier-${row.mechanism}-v1`),key=`${row.managerId}|${mechanismId}`;if(rows.has(key))issues.push(`duplicate-planning-row:${key}`);rows.set(key,row);}
const priorPhysical=new Set<string>();for(const excluded of plan.excludedPlans??[]){const prior=read<any>(path.resolve(String(excluded.file)));for(const item of prior.items??[])if(item.status==="ready"){const key=physicalKey(item,path.resolve(String(item.game)));if(priorPhysical.has(key))issues.push(`duplicate-prior-physical-case:${item.id}`);priorPhysical.add(key);}}
const currentPhysical=new Set<string>(),plannedByManager=new Map<string,any>();for(const item of plan.items??[]){if(item.status!=="ready"&&item.status!=="deferred"){issues.push(`invalid-plan-item-status:${item.managerId}`);continue;}if(plannedByManager.has(String(item.managerId)))issues.push(`multiple-plan-items-for-manager:${item.managerId}`);plannedByManager.set(String(item.managerId),item);if(item.status!=="ready")continue;const physical=physicalKey(item,path.resolve(String(item.game)));if(priorPhysical.has(physical))issues.push(`reused-prior-physical-case:${item.id}`);if(currentPhysical.has(physical))issues.push(`duplicate-current-physical-case:${item.id}`);currentPhysical.add(physical);
  const row=rows.get(`${item.managerId}|${item.mechanismId}`),example=(row?.examples??[]).find((value:any)=>physicalKey({managerId:item.managerId,...value},path.resolve(sourceRoot,String(value.game)))===physical);if(!row||!example)issues.push(`plan-item-absent-from-frontier:${item.id}`);else if(String(item.mechanismId).startsWith("battle-context-")&&(!row.condition||example.context?.[row.condition.axis]!==row.condition.value))issues.push(`conditional-membership-drift:${item.id}`);
}
const agendas=readArchive<any>(path.resolve(String(plan.agendas?.file??"")));for(const agenda of agendas){const mechanismId=String(agenda.selected?.mechanismId??"");if(!mechanismId.startsWith("battle-frontier-")&&!mechanismId.startsWith("battle-context-"))continue;const item=plannedByManager.get(String(agenda.managerId));if(!item||item.mechanismId!==mechanismId)issues.push(`agenda-plan-mismatch:${agenda.managerId}`);}for(const item of plan.items??[])if(!agendas.some((agenda:any)=>agenda.managerId===item.managerId&&agenda.selected?.mechanismId===item.mechanismId))issues.push(`plan-agenda-mismatch:${item.managerId}`);
const readyItems=(plan.items??[]).filter((value:any)=>value.status==="ready"),ready=readyItems.length,deferred=(plan.items??[]).filter((value:any)=>value.status==="deferred").length,execution=runDirectory?auditExecution(runDirectory,readyItems):null,summary={schemaVersion:1,activationStatus:"shadow-only",valid:issues.length===0,ready,deferred,priorPhysicalCases:priorPhysical.size,currentPhysicalCases:currentPhysical.size,conditionalCases:readyItems.filter((value:any)=>String(value.mechanismId).startsWith("battle-context-")).length,inputFingerprints:Object.keys(manifest.outputs??{}).length+2+Object.keys(manifest.inputs?.implementation??{}).length+(manifest.inputs?.researchInputs??[]).length*2,...(execution?{execution}:{}),issues,estimatedTokens:Math.ceil(Buffer.byteLength(JSON.stringify({valid:issues.length===0,ready,deferred,execution,issues}))/4)};
fs.mkdirSync(out,{recursive:true});write(path.join(out,"summary.json"),summary);console.log(JSON.stringify(summary,null,2));if(issues.length)process.exitCode=1;

function verifyFingerprint(input:any,label:string):void{if(!input?.file||!input?.sha256||!Number.isInteger(input?.bytes)){issues.push(`${label}-fingerprint-missing`);return;}const file=path.resolve(String(input.file));if(!fs.existsSync(file)){issues.push(`${label}-missing:${input.file}`);return;}const bytes=fs.readFileSync(file);if(bytes.length!==input.bytes||sha(bytes)!==input.sha256)issues.push(`${label}-drift:${input.file}`);}
function verifyPlanFingerprint(input:any):void{if(!input?.file||!input?.sha256){issues.push("plan-input-fingerprint-missing");return;}const file=path.resolve(String(input.file));if(!fs.existsSync(file)){issues.push(`plan-input-missing:${input.file}`);return;}if(sha(fs.readFileSync(file))!==input.sha256)issues.push(`plan-input-drift:${input.file}`);}
function auditExecution(run:string,readyItems:any[]):{status:string;completed:number;results:number;capsules:number;studies:number}{const stateFile=path.join(run,"battle-frontier-run.json"),summaryFile=path.join(run,"battle-frontier-summary.json");if(!fs.existsSync(stateFile)||!fs.existsSync(summaryFile)){issues.push("execution-artifacts-missing");return{status:"missing",completed:0,results:0,capsules:0,studies:0};}const state=read<any>(stateFile),result=read<any>(summaryFile),readyIds=new Set(readyItems.map(value=>String(value.id))),stateIds=new Set((state.items??[]).map((value:any)=>String(value.id))),resultIds=new Set((result.results??[]).map((value:any)=>String(value.id)));if(state.status!=="complete"||state.plan?.sha256!==sha(fs.readFileSync(planFile))||(state.items??[]).some((value:any)=>value.status!=="complete")||stateIds.size!==readyIds.size||[...readyIds].some(id=>!stateIds.has(id)))issues.push("execution-state-plan-drift");if(result.status!=="complete"||result.evidenceStatus!=="manager-selected-research-only"||result.authority!=="no-activation-authority"||resultIds.size!==readyIds.size||[...readyIds].some(id=>!resultIds.has(id)))issues.push("execution-summary-plan-drift");let capsules=0;for(const item of readyItems){const file=path.join(run,"runs",String(item.id),"counterfactual-summary.json");if(!fs.existsSync(file)){issues.push(`execution-capsule-missing:${item.id}`);continue;}const capsule=read<any>(file);if(capsule.sourceVerified!==true||capsule.prefixVerified!==true||capsule.evidenceStatus!=="manager-selected-research-only"||capsule.activationAllowed!==false||capsule.intervention?.decisionOrdinal!==item.decisionOrdinal||capsule.intervention?.selected!==item.alternative)issues.push(`execution-capsule-drift:${item.id}`);else capsules+=1;}let studies=0;const studyIds=new Set<string>(),studyRoot=path.join(run,"studies");if(fs.existsSync(studyRoot))for(const entry of fs.readdirSync(studyRoot,{withFileTypes:true})){if(!entry.isDirectory())continue;const causal=path.join(studyRoot,entry.name,"causal-manifest.json");if(!fs.existsSync(causal)){issues.push(`execution-study-missing:${entry.name}`);continue;}const value=read<any>(causal);for(const item of value.items??[]){const id=String(item.id);if(!readyIds.has(id))issues.push(`execution-study-orphan:${id}`);if(studyIds.has(id))issues.push(`execution-study-duplicate:${id}`);studyIds.add(id);}studies+=1;}if(studyIds.size!==readyIds.size||[...readyIds].some(id=>!studyIds.has(id)))issues.push("execution-study-coverage-drift");return{status:String(state.status),completed:(state.items??[]).filter((value:any)=>value.status==="complete").length,results:(result.results??[]).length,capsules,studies};}
function physicalKey(value:any,game:string):string{return canonical({managerId:String(value.managerId),game:path.resolve(game).replaceAll("\\","/").toLowerCase(),decisionOrdinal:Number(value.decisionOrdinal),side:String(value.side),selected:String(value.selected),alternative:String(value.alternative)});}
function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}function readArchive<T>(file:string):T[]{const bytes=fs.readFileSync(file),value=JSON.parse(file.endsWith(".gz")?zlib.gunzipSync(bytes).toString("utf8"):bytes.toString("utf8"));if(!Array.isArray(value))throw new Error(`Invalid archive: ${file}`);return value as T[];}function write(file:string,value:unknown):void{const temporary=`${file}.${process.pid}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,"utf8");fs.renameSync(temporary,file);}function sha(value:Buffer):string{return crypto.createHash("sha256").update(value).digest("hex");}function canonical(value:unknown):string{if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object"){const record=value as Record<string,unknown>;return`{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`;}return JSON.stringify(value);}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?String(args[index+1]??fallback):fallback;}function required(name:string):string{const value=option(name,"");if(!value)throw new Error(`Missing ${name}`);return value;}
