import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";

interface SoakSummary {status: string; violations: string[]; warnings: string[]; aggregate: {averageInsolventAcademies: number; averageGuaranteedDebt: number; averagePersonalitySimilarity: number; totalBirths: number; totalEmergencySaleCandidates: number; totalEmergencySales: number; totalMarketTransactions: number; maximumDebt: number}; final: {distinctFounders: number; distinctStyles: number; meanPersonalitySimilarity: number; guaranteedDebt: number; academyCount?: number; population?: number; treasuryTotal: number; healthy: number; insolvent: number}}
interface Profile {id: string; academyGrantPool: number; academySigningFee: number; academyMarketOfferPercent: number; academyEmergencySaleDiscountPercent: number}

const args = process.argv.slice(2), root = process.cwd(), source = path.resolve(option("--source", "output/test-v12-smoke")), baselineDirectory = path.resolve(option("--baseline", "output/development-ecology-baseline-v1")), out = path.resolve(option("--out", "output/development-ecology-calibration-v1"));
const cycles = integerOption("--cycles", 12, 2, 100), capacity = integerOption("--capacity", 6, 6, 30);
const profiles: Profile[] = [
  {id: "grant105-offer110", academyGrantPool: 105, academySigningFee: 8, academyMarketOfferPercent: 110, academyEmergencySaleDiscountPercent: 35},
  {id: "grant105-offer115", academyGrantPool: 105, academySigningFee: 8, academyMarketOfferPercent: 115, academyEmergencySaleDiscountPercent: 35},
  {id: "grant105-offer120", academyGrantPool: 105, academySigningFee: 8, academyMarketOfferPercent: 120, academyEmergencySaleDiscountPercent: 35},
];
prepareOutput();
const baseline = read<SoakSummary>(path.join(baselineDirectory, "summary.json")), results = [{profile: {id: "current-baseline", academyGrantPool: 120, academySigningFee: 10, academyMarketOfferPercent: 100, academyEmergencySaleDiscountPercent: 25}, summary: baseline, output: baselineDirectory}];
for (const profile of profiles) {
  const profileOut = path.join(out, profile.id), command = [require.resolve("tsx/cli"), path.join(root, "src", "cli", "developmentLeagueSoak.ts"), "--source", source, "--out", profileOut, "--cycles", String(cycles), "--seasons-per-cycle", "1", "--capacity", String(capacity), "--retention", "compact", "--academy-grant-pool", String(profile.academyGrantPool), "--academy-signing-fee", String(profile.academySigningFee), "--academy-market-offer-percent", String(profile.academyMarketOfferPercent), "--academy-emergency-sale-discount-percent", String(profile.academyEmergencySaleDiscountPercent), "--force"];
  const run = spawnSync(process.execPath, command, {cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024});
  if (run.status !== 0) throw new Error(`Calibration profile ${profile.id} failed:\n${run.stderr || run.stdout}`);
  const summary = read<SoakSummary>(path.join(profileOut, "summary.json")); results.push({profile, summary, output: profileOut});
  console.log(`Calibration ${profile.id}: ${summary.status}, warnings ${summary.warnings.length}, deals ${summary.aggregate.totalMarketTransactions}, treasury ${(summary.final.treasuryTotal / capacity).toFixed(1)}`);
}
const ranked = results.map(result => ({...result, score: score(result.summary, capacity)})).sort((a, b) => a.score - b.score || a.profile.id.localeCompare(b.profile.id));
const comparison = {schemaVersion: 1, createdAt: new Date().toISOString(), source, cycles, capacity, scoring: {hardViolation: 1_000_000, advisoryWarning: 1_000, marketDealDeficit: 20, treasuryOutsideRange10To60: 2, averageInsolvency: 10, note: "Warnings dominate ranking; treasury is penalized only outside the healthy 10-60 average range; lower score is better and does not automatically promote a profile."}, recommendation: ranked[0].profile.id, ranked: ranked.map((result, index) => ({rank: index + 1, profile: result.profile, score: result.score, status: result.summary.status, violations: result.summary.violations, warnings: result.summary.warnings, aggregate: result.summary.aggregate, final: result.summary.final, output: result.output}))};
writeJson(path.join(out, "comparison.json"), comparison); fs.writeFileSync(path.join(out, "report.md"), report(comparison), "utf8");
console.log(JSON.stringify({recommendation: comparison.recommendation, output: out, ranking: comparison.ranked.map(result => ({rank: result.rank, id: result.profile.id, score: result.score, warnings: result.warnings.length}))}, null, 2));

function score(summary: SoakSummary, population: number): number { const targetDeals = Math.ceil(cycles / 3), marketDeficit = Math.max(0, targetDeals - summary.aggregate.totalMarketTransactions), averageTreasury = summary.final.treasuryTotal / (summary.final.academyCount ?? summary.final.population ?? population), treasuryPenalty = averageTreasury > 60 ? (averageTreasury - 60) * 2 : averageTreasury < 10 ? (10 - averageTreasury) * 2 : 0; return summary.violations.length * 1_000_000 + summary.warnings.length * 1_000 + marketDeficit * 20 + treasuryPenalty + summary.aggregate.averageInsolventAcademies * 10; }
function report(value: any): string { return `# Development ecology calibration v1\n\nRecommended experimental profile: **${value.recommendation}**\n\nThis is a ranking for further validation, not an automatic production promotion. Lower score is better; hard violations and advisory warnings dominate the score.\n\n| Rank | Profile | Grant | Signing fee | Offer | Emergency discount | Status | Warnings | Deals | Emergency candidates / sales | Avg treasury | Avg insolvency | Similarity | Score |\n|---:|---|---:|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|\n${value.ranked.map((result: any) => `| ${result.rank} | ${result.profile.id} | ${result.profile.academyGrantPool} | ${result.profile.academySigningFee} | ${result.profile.academyMarketOfferPercent}% | ${result.profile.academyEmergencySaleDiscountPercent}% | ${result.status} | ${result.warnings.length} | ${result.aggregate.totalMarketTransactions} | ${result.aggregate.totalEmergencySaleCandidates} / ${result.aggregate.totalEmergencySales} | ${(result.final.treasuryTotal / (result.final.academyCount ?? result.final.population ?? value.capacity)).toFixed(1)} | ${result.aggregate.averageInsolventAcademies.toFixed(2)} | ${result.aggregate.averagePersonalitySimilarity.toFixed(3)} | ${result.score.toFixed(1)} |`).join("\n")}\n\n## Warning details\n\n${value.ranked.map((result: any) => `- **${result.profile.id}**: ${result.warnings.length ? result.warnings.join(", ") : "none"}`).join("\n")}\n`; }
function prepareOutput(): void { if (!fs.existsSync(out)) { fs.mkdirSync(out, {recursive: true}); return; } if (!args.includes("--force")) throw new Error(`Calibration output exists: ${out}; pass --force to replace it`); const resolved = path.resolve(out); if (path.parse(resolved).root === resolved || resolved === root || resolved === source || source.startsWith(`${resolved}${path.sep}`)) throw new Error(`Unsafe calibration output: ${resolved}`); fs.rmSync(resolved, {recursive: true, force: true}); fs.mkdirSync(resolved, {recursive: true}); }
function option(name: string, fallback: string): string { const index = args.indexOf(name); return index >= 0 ? args[index + 1] ?? fallback : fallback; }
function integerOption(name: string, fallback: number, min: number, max: number): number { const value = Number(option(name, String(fallback))); if (!Number.isInteger(value) || value < min || value > max) throw new Error(`${name} must be ${min}..${max}`); return value; }
function read<T>(file: string): T { return JSON.parse(fs.readFileSync(file, "utf8")) as T; }
function writeJson(file: string, value: unknown): void { fs.mkdirSync(path.dirname(file), {recursive: true}); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, "utf8"); }
