import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {compareWhiteBoxBranches} from "../ai/whiteBox/counterfactual";
import {evaluateWhiteBoxBidApproval, WHITE_BOX_BID_COUNTERFACTUAL_POLICY} from "../ai/whiteBox/bidApproval";
import {evaluatePortfolioBidCounterfactual, loadPortfolioBidReplayCapsule, portfolioAwardSignature} from "../ai/whiteBox/portfolioBidCounterfactual";
import {createRegistrySnapshot} from "../draft/registrySnapshot";
import {loadDynastyState} from "../draft/dynastyStateStore";
import {materializeHistoricalReplayCheckpoint, planHistoricalReplaySegments} from "../draft/historicalRuntimeCheckpoint";

interface DynastyState {seed:string;completedSeason:number;settings:Record<string,number|string|boolean|undefined>;fingerprint:{registryHash:string};registry?:{revision:string;snapshot:string};decisionRecords?:Array<{decision?:string;context?:{season?:number}}>}

const args=process.argv.slice(2),root=process.cwd(),source=path.resolve(required("--source")),out=path.resolve(option("--out","output/whitebox-bid-counterfactual"));
const managerId=required("--manager"),decisionId=required("--decision-id"),interventionSeason=integerOption("--season",1,1,1000),followupSeasons=integerOption("--followup-seasons",1,0,3);
const resume=args.includes("--resume");
const sourceState=loadDynastyState<DynastyState>(path.join(source,"dynasty-state.json")),finalSeason=interventionSeason+followupSeasons;
if(sourceState.completedSeason<interventionSeason)throw new Error(`Source has not completed auction season ${interventionSeason}`);
const transitionSeasons=historicalReplayTransitionSeasons(sourceState.decisionRecords??[]);
const reusableBranches=resume&&["control","experiment"].every(name=>fs.existsSync(path.join(out,name,"dynasty-state.json"))),requiresHistoricalRuntime=transitionSeasons.some(season=>season<=Math.min(finalSeason,sourceState.completedSeason)),historicalSegments=requiresHistoricalRuntime&&!reusableBranches?planHistoricalReplaySegments(source,interventionSeason,finalSeason):[],historicalReplay=historicalSegments[0]??null;
const auctionMode=String(sourceState.settings.auctionMode??"sequential"),sourceBid=findSourceBid(),portfolioCapsule=auctionMode==="portfolio"?loadPortfolioBidReplayCapsule(source,interventionSeason):null,portfolioEvaluation=portfolioCapsule?evaluatePortfolioBidCounterfactual(portfolioCapsule,decisionId):null;
const approval=portfolioEvaluation??evaluateWhiteBoxBidApproval({auctionMode,bidderId:managerId,incumbentWinnerId:sourceBid.winnerId,highestCompetingBid:sourceBid.highestCompetingBid,trace:sourceBid.bid.whiteBox});
if(portfolioEvaluation?portfolioEvaluation.status!=="executable":!(approval as ReturnType<typeof evaluateWhiteBoxBidApproval>).recommended)throw new Error(`Source bid is not admitted: ${approval.reasons.join(",")}`);
prepareOutput();
const controlDir=path.join(out,"control"),experimentDir=path.join(out,"experiment");
runOrReuse(controlDir,false);verifyPrefix(controlDir,Math.min(finalSeason,sourceState.completedSeason));
runOrReuse(experimentDir,true);verifyPrefix(experimentDir,interventionSeason-1);
const intervention=findIntervention(experimentDir);
if(portfolioCapsule&&portfolioEvaluation)verifyPortfolioIsolation(experimentDir,portfolioCapsule,portfolioEvaluation.candidateAwards!);else verifyAuctionIsolation(experimentDir);
const controlState=read<any>(path.join(controlDir,"dynasty-state.json")),experimentState=read<any>(path.join(experimentDir,"dynasty-state.json"));
const comparison=compareWhiteBoxBranches(managerId,interventionSeason,controlState,experimentState),affectedManagerIds=portfolioEvaluation?.affectedManagerIds??(sourceBid.winnerId&&sourceBid.winnerId!==managerId?[managerId,sourceBid.winnerId]:[managerId]),affectedComparisons=affectedManagerIds.map(id=>compareWhiteBoxBranches(id,interventionSeason,controlState,experimentState)),displacedComparison=sourceBid.winnerId&&sourceBid.winnerId!==managerId?affectedComparisons.find(entry=>entry.managerId===sourceBid.winnerId)??null:null;
const summary={schemaVersion:1,source,caseId:decisionId,domain:"auction",auctionMode,policy:WHITE_BOX_BID_COUNTERFACTUAL_POLICY,interventionSeason,followupSeasons,historicalRuntime:historicalReplay?{runtimeId:historicalReplay.runtimeId,sourceCompletedSeason:historicalReplay.sourceCompletedSeason,segments:historicalSegments.map(segment=>({firstSeason:segment.firstSeason,lastSeason:segment.lastSeason,runtimeId:segment.runtimeId}))}:null,sourceTraceVerified:true,prefixVerified:true,auctionPrefixVerified:true,approval,intervention,affectedManagerIds,affectedComparisons,displacedManagerId:auctionMode==="sequential"?sourceBid.winnerId:null,comparison,displacedComparison};
write(path.join(out,"counterfactual-summary.json"),summary);fs.writeFileSync(path.join(out,"counterfactual-report.md"),markdown(summary),"utf8");
console.log(JSON.stringify({caseId:decisionId,managerId,auctionMode,incumbentBid:approval.incumbentBid,candidateBid:approval.candidateBid,affectedManagerIds,delta:comparison.delta,report:path.join(out,"counterfactual-report.md")},null,2));

function findSourceBid():{record:any;bid:any;winnerId:string|null;highestCompetingBid:number}{const file=path.join(source,`season-${String(interventionSeason).padStart(2,"0")}`,"decision-ledger.json");if(!fs.existsSync(file))throw new Error(`Missing source auction ledger: ${file}`);const records=read<any>(file).records??[],matches:any[]=[];for(const record of records.filter((entry:any)=>entry.stage==="auction")){for(const bid of record.context?.bids??[]){const bidder=bid.manager??bid.managerId;if(bidder===managerId&&bid.whiteBox?.decisionId===decisionId)matches.push({record,bid});}}if(matches.length!==1)throw new Error(`Expected one source bid ${decisionId} for ${managerId}; found ${matches.length}`);const bids=matches[0].record.context.bids??[],winner=[...bids].filter((entry:any)=>Number(entry.bid)>0).sort((left:any,right:any)=>Number(right.bid)-Number(left.bid))[0]??null,highestCompetingBid=Math.max(0,...bids.filter((entry:any)=>(entry.manager??entry.managerId)!==managerId).map((entry:any)=>Number(entry.bid)||0));return{...matches[0],winnerId:winner?.manager??winner?.managerId??null,highestCompetingBid};}
function historicalReplayTransitionSeasons(records:NonNullable<DynastyState["decisionRecords"]>):number[]{const seasons:number[]=[];let pending=false;for(const record of records){if(["显式采用联盟代码升级","采用新的魔改配置版本","迁移旧联盟并冻结魔改配置"].includes(String(record.decision??""))){pending=true;continue;}const season=Number(record.context?.season);if(pending&&record.decision?.startsWith("启动王朝第")&&Number.isInteger(season)){seasons.push(season);pending=false;}}return seasons;}
function runOrReuse(directory:string,experiment:boolean):void{if(!fs.existsSync(directory)){run(directory,experiment);return;}if(!resume)throw new Error(`Counterfactual branch already exists: ${directory}`);const stateFile=path.join(directory,"dynasty-state.json");if(!fs.existsSync(stateFile)||Number(read<any>(stateFile).completedSeason)!==finalSeason)throw new Error(`Cannot resume incomplete counterfactual branch: ${directory}`);}
function run(directory:string,experiment:boolean):void{
  const replay=historicalReplay?materializeHistoricalReplayCheckpoint(source,interventionSeason,directory):null;
  if(!replay){runSegment(directory,experiment,root,registrySourceFor(directory),undefined,finalSeason,false);return;}
  for(const segment of historicalSegments)runSegment(directory,experiment,segment.runtimeWorkspace,replay.registrySource,segment.nodePath,segment.lastSeason,true,segment.firstSeason<=interventionSeason&&interventionSeason<=segment.lastSeason);
}
function runSegment(directory:string,experiment:boolean,runtimeRoot:string,registrySource:string,nodePath:string|undefined,throughSeason:number,resumeBranch:boolean,containsIntervention=true):void{const settings=sourceState.settings,env={...process.env,...(nodePath?{NODE_PATH:nodePath}:{}),V12_OUT:directory,V12_SEED:sourceState.seed,V12_SEASONS:String(throughSeason),V12_RESUME:resumeBranch?"true":"false",V12_ALLOW_CODE_UPGRADE:resumeBranch?"true":"false",V12_MANAGER_LIMIT:String(settings.managerLimit),V12_PAIRS:String(settings.pairs),V12_POOL_SIZE:String(settings.poolSize),V12_AUCTION_LOTS:String(settings.auctionLots),V12_REGULAR_ROUNDS:String(settings.regularRounds),V12_MAX_TURNS:String(settings.maxTurns),V12_MIN_ROSTER:String(settings.minRoster??6),V12_MAX_ROSTER:String(settings.maxRoster??10),V12_BASE_CASH:String(settings.baseBudget??40),V12_AUCTION_MODE:String(settings.auctionMode??"sequential"),V12_REGISTRY_SOURCE:registrySource,V12_REGISTRY_REVISION:sourceState.registry?.revision??"bid-counterfactual",V12_STRATEGY_PROGRAM_OPERATOR:String(settings.strategyProgramOperator??"observed-boundary-v1"),V12_EVOLUTION_MODE:String(settings.evolutionMode??"punctuated"),V12_EVOLUTION_POLICY:String(settings.evolutionPolicy??"shadow"),V12_EVOLUTION_MAX_BURSTS:String(settings.evolutionMaxBursts??2),V12_EVOLUTION_MIN_CANDIDATES:String(settings.evolutionMinCandidates??4),V12_EVOLUTION_MAX_CANDIDATES:String(settings.evolutionMaxCandidates??8),V12_EVIDENCE_RETENTION:"compact",V12_EVIDENCE_SAMPLE_RATE:"0",V4_BID_COUNTERFACTUAL_POLICY:experiment&&containsIntervention?WHITE_BOX_BID_COUNTERFACTUAL_POLICY:"",V4_BID_COUNTERFACTUAL_TARGET:experiment&&containsIntervention?decisionId:""};const script=path.join(runtimeRoot,"src","cli","draftLeagueV12.ts"),result=spawnSync(process.execPath,[require.resolve("tsx/cli"),script],{cwd:runtimeRoot,env,encoding:"utf8",maxBuffer:64*1024*1024});if(result.status!==0)throw new Error(`${experiment?"Experiment":"Control"} bid branch failed through season ${throughSeason}:\n${result.stderr||result.stdout}`);}
function registrySourceFor(directory:string):string{const snapshot=sourceState.registry?.snapshot?path.resolve(source,sourceState.registry.snapshot):"";if(snapshot&&fs.existsSync(path.join(snapshot,"registry-manifest.json")))return snapshot;const restored=createRegistrySnapshot(path.resolve("data/draft"),path.join(directory,"config-snapshots"),sourceState.registry?.revision);if(restored.hash!==sourceState.fingerprint.registryHash)throw new Error("Source registry snapshot is missing and the current registry hash does not match");return restored.directory;}
function verifyPrefix(actualRoot:string,seasons:number):void{for(let season=1;season<=seasons;season+=1){const name=`season-${String(season).padStart(2,"0")}`,expected=essential(read<any>(path.join(source,name,"season.json"))),actual=essential(read<any>(path.join(actualRoot,name,"season.json")));if(digest(expected)!==digest(actual))throw new Error(`Replayed ${name} does not match source prefix`);}}
function findIntervention(directory:string):any{const records=read<any>(path.join(directory,`season-${String(interventionSeason).padStart(2,"0")}`,"decision-ledger.json")).records??[],matches:any[]=[];for(const record of records.filter((entry:any)=>entry.stage==="auction"))for(const bid of record.context?.bids??[])if(bid.bidExperiment?.target===decisionId)matches.push(bid.bidExperiment);if(matches.length!==1)throw new Error(`Expected exactly one bid intervention; found ${matches.length}`);const value=matches[0];if(value.policy!==WHITE_BOX_BID_COUNTERFACTUAL_POLICY||value.incumbentBid!==approval.incumbentBid||value.candidateBid!==approval.candidateBid)throw new Error("Executed bid intervention does not match source approval");return value;}
function verifyAuctionIsolation(directory:string):void{const name=`season-${String(interventionSeason).padStart(2,"0")}`,sourceAuctions=(read<any>(path.join(source,name,"decision-ledger.json")).records??[]).filter((record:any)=>record.stage==="auction"),experimentAuctions=(read<any>(path.join(directory,name,"decision-ledger.json")).records??[]).filter((record:any)=>record.stage==="auction"),sourceIndex=sourceAuctions.findIndex((record:any)=>(record.context?.bids??[]).some((bid:any)=>bid.whiteBox?.decisionId===decisionId)),experimentIndex=experimentAuctions.findIndex((record:any)=>(record.context?.bids??[]).some((bid:any)=>bid.bidExperiment?.target===decisionId));if(sourceIndex<0||sourceIndex!==experimentIndex)throw new Error("Bid intervention auction position drifted from source");for(let index=0;index<sourceIndex;index+=1)if(digest(sourceAuctions[index])!==digest(experimentAuctions[index]))throw new Error(`Auction prefix drifted before target lot ${sourceIndex+1}`);const sourceRecord=auctionComparable(sourceAuctions[sourceIndex],false),experimentRecord=auctionComparable(experimentAuctions[experimentIndex],true);if(digest(sourceRecord)!==digest(experimentRecord))throw new Error("Target auction changed beyond the admitted bid");const winner=[...(experimentAuctions[experimentIndex].context?.bids??[])].filter((bid:any)=>Number(bid.bid)>0).sort((left:any,right:any)=>Number(right.bid)-Number(left.bid))[0];if((winner?.manager??winner?.managerId)!==managerId)throw new Error("Admitted ceiling bid did not win the replayed target auction");}
function verifyPortfolioIsolation(directory:string,sourceCapsule:ReturnType<typeof loadPortfolioBidReplayCapsule>,candidateAwards:NonNullable<ReturnType<typeof evaluatePortfolioBidCounterfactual>["candidateAwards"]>):void{const experimentCapsule=loadPortfolioBidReplayCapsule(directory,interventionSeason);if(JSON.stringify(sourceCapsule.assetIds)!==JSON.stringify(experimentCapsule.assetIds)||JSON.stringify(sourceCapsule.limits)!==JSON.stringify(experimentCapsule.limits)||sourceCapsule.seed!==experimentCapsule.seed)throw new Error("Portfolio replay inputs drifted outside the target bid");const sourceInputs=sourceCapsule.bids.map(bid=>({managerId:bid.managerId,assetId:bid.assetId,bid:bid.bid,utility:bid.utility,whiteBox:bid.whiteBox})).sort((a,b)=>a.whiteBox.decisionId.localeCompare(b.whiteBox.decisionId)),experimentInputs=experimentCapsule.bids.map(bid=>({managerId:bid.managerId,assetId:bid.assetId,bid:bid.whiteBox.decisionId===decisionId?sourceBid.bid.bid:bid.bid,utility:bid.utility,whiteBox:bid.whiteBox})).sort((a,b)=>a.whiteBox.decisionId.localeCompare(b.whiteBox.decisionId));if(digest(sourceInputs)!==digest(experimentInputs))throw new Error("Portfolio experiment changed more than one submitted bid");if(portfolioAwardSignature(experimentCapsule.awards)!==portfolioAwardSignature(candidateAwards))throw new Error("Portfolio experiment allocation does not match the admitted solver branch");const name=`season-${String(interventionSeason).padStart(2,"0")}`,sourceRecords=read<any>(path.join(source,name,"decision-ledger.json")).records??[],experimentRecords=read<any>(path.join(directory,name,"decision-ledger.json")).records??[],sourcePrefix=sourceRecords.slice(0,sourceRecords.findIndex((record:any)=>record.stage==="auction")),experimentPrefix=experimentRecords.slice(0,experimentRecords.findIndex((record:any)=>record.stage==="auction"));if(digest(sourcePrefix)!==digest(experimentPrefix))throw new Error("Portfolio pre-auction ledger prefix drifted");}
function auctionComparable(record:any,experiment:boolean):any{return{stage:record.stage,actor:record.actor,decision:record.decision,context:{lot:record.context?.lot,family:record.context?.family,assetId:record.context?.assetId,nominator:record.context?.nominator,referencePrice:record.context?.referencePrice,budgets:record.context?.budgets,bids:(record.context?.bids??[]).map((bid:any)=>({manager:bid.manager??bid.managerId,bid:experiment&&bid.bidExperiment?.target===decisionId?bid.bidExperiment.incumbentBid:bid.bid,ceiling:bid.ceiling,whiteBox:bid.whiteBox})).sort((left:any,right:any)=>String(left.manager).localeCompare(String(right.manager)))},alternatives:record.alternatives};}
function essential(value:any):any{return{season:value.season,champion:value.champion,standings:value.standings,transactions:value.transactions,validity:value.validity};}
function markdown(value:typeof summary):string{const context="highestCompetingBid" in value.approval?`Source competing high bid: ${value.approval.highestCompetingBid}`:`Portfolio award changes: ${value.approval.changes.length}`;return`# Isolated white-box bid counterfactual\n\n- Decision / manager: \`${value.caseId}\` / ${managerId}\n- Auction mode / policy: ${value.auctionMode} / \`${value.policy}\`\n- Incumbent / candidate bid: ${value.approval.incumbentBid} / ${value.approval.candidateBid}\n- ${context}\n- Affected managers: ${value.affectedManagerIds.join(", ")}\n- Prefix verified: ${value.prefixVerified}\n- Bidder points / rank / titles / cash delta: ${value.comparison.delta.totalPoints} / ${value.comparison.delta.finalRank??"n/a"} / ${value.comparison.delta.titles} / ${value.comparison.delta.cash}\n\nThe branch changes one retained bid to its audited ceiling. Sequential mode verifies the single target auction; portfolio mode reruns and verifies the complete constrained allocation. This is causal evidence for review, not automatic activation.\n`;}
function prepareOutput():void{if(out===source||source.startsWith(`${out}${path.sep}`)||out.startsWith(`${source}${path.sep}`))throw new Error("Counterfactual output must be separate from its source");if(fs.existsSync(out)){if(!resume)throw new Error(`Counterfactual output exists: ${out}`);return;}fs.mkdirSync(out,{recursive:true});}
function digest(value:any):string{return crypto.createHash("sha256").update(stable(value)).digest("hex");}function stable(value:any):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);}
function write(file:string,value:unknown):void{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`,"utf8");}function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?args[index+1]??fallback:fallback;}function required(name:string):string{const value=option(name,"").trim();if(!value)throw new Error(`Missing ${name}`);return value;}function integerOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}
