import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";

type CycleStatus = "promoted" | "retained" | "eliminated" | "retired" | "absent";
interface ScreenCase {caseId: string; childId: string; childName: string; academyId: string; incumbentStatus: string; candidateSalary: number; affectedChildIds: string[]; payrollDelta: number; arrearsDelta: number; academyBalanceDelta: number; competitiveReplayStatus: string}
interface ScreenArtifact {source: {entrantsPath: string; sha256: string; cycle: number}; cases: ScreenCase[]}
interface EntrantsArtifact {cycle: number; capacity: number; previous?: string; source: {root: string; season: number; seed: string}; policy: any; contracts: any; entrants: any[]; academies: any[]; academyFinancialHealth: any[]; salaryDebts: any[]}
interface SummaryArtifact {cycle: number; seasons: number; promoted: any[]; retained: any[]; eliminated: any[]; lifecycleRetired: any[]; contracts: any}

const args = process.argv.slice(2), root = process.cwd();
const source = path.resolve(required("--source")), screensPath = path.resolve(required("--screens")), out = path.resolve(required("--out"));
const retention = option("--retention", "summary");
if (retention !== "summary" && retention !== "branches") throw new Error("--retention must be summary or branches");
if (fs.existsSync(out)) throw new Error("Counterfactual output already exists; choose a new --out directory");
const entrantsPath = path.join(source, "entrants.json"), sourceBytes = fs.readFileSync(entrantsPath), sourceHash = digest(sourceBytes);
const sourceEntrants = read<EntrantsArtifact>(entrantsPath), sourceSummary = read<SummaryArtifact>(path.join(source, "development-summary.json")), screens = read<ScreenArtifact>(screensPath);
if (path.resolve(screens.source.entrantsPath) !== entrantsPath || screens.source.sha256 !== sourceHash || screens.source.cycle !== sourceEntrants.cycle) throw new Error("Contract screen is not bound to the selected development source");
const eligible = screens.cases.filter(value => value.competitiveReplayStatus === "eligible-retained-source").sort((a, b) => a.caseId.localeCompare(b.caseId));
if (!eligible.length) throw new Error("Contract screen has no eligible retained source");
const requested = option("--case-id", ""), selected = requested ? eligible.find(value => value.caseId === requested) : eligible[blindIndex(sourceHash, eligible.length)];
if (!selected) throw new Error("Requested contract case is not an eligible retained source");
if (!sourceEntrants.previous) throw new Error("Contract counterfactual requires a prior development cycle");
const majorState = path.join(path.resolve(sourceEntrants.source.root), "dynasty-state.json"), majorHash = digest(fs.readFileSync(majorState));
fs.mkdirSync(out, {recursive: false});
const experimentSource = path.join(out, "experiment-source"), controlFollowup = path.join(out, "control-followup"), experimentFollowup = path.join(out, "experiment-followup");
runDevelopment(experimentSource, path.resolve(sourceEntrants.previous), selected.childId);
const experimentEntrants = read<EntrantsArtifact>(path.join(experimentSource, "entrants.json")), experimentSummary = read<SummaryArtifact>(path.join(experimentSource, "development-summary.json"));
validateInterventionSource(sourceEntrants, sourceSummary, experimentEntrants, experimentSummary, selected);
compact(experimentSource);
const sourceFinalState = read<{sha256: string; managers: number}>(path.join(source, "development-final-state.json")), experimentFinalState = read<{sha256: string; managers: number}>(path.join(experimentSource, "development-final-state.json"));
if (sourceFinalState.sha256 !== experimentFinalState.sha256 || sourceFinalState.managers !== experimentFinalState.managers) throw new Error("Contract intervention failed to reproduce the complete source manager state");
runDevelopment(controlFollowup, source);
compact(controlFollowup);
runDevelopment(experimentFollowup, experimentSource);
compact(experimentFollowup);
if (digest(fs.readFileSync(majorState)) !== majorHash) throw new Error("Academy contract counterfactual mutated the major-league source");
const controlEntrants = read<EntrantsArtifact>(path.join(controlFollowup, "entrants.json")), controlSummary = read<SummaryArtifact>(path.join(controlFollowup, "development-summary.json"));
const candidateEntrants = read<EntrantsArtifact>(path.join(experimentFollowup, "entrants.json")), candidateSummary = read<SummaryArtifact>(path.join(experimentFollowup, "development-summary.json"));
const controlOutcome = outcome(controlSummary, selected.childId), candidateOutcome = outcome(candidateSummary, selected.childId);
const controlAcademy = academyOutcome(controlEntrants, selected.academyId), candidateAcademy = academyOutcome(candidateEntrants, selected.academyId);
const branchArtifacts = {experimentSource: artifactSummary(experimentSource), controlFollowup: artifactSummary(controlFollowup), experimentFollowup: artifactSummary(experimentFollowup)};
const removableBytes = [experimentSource, controlFollowup, experimentFollowup].reduce((sum, directory) => sum + directoryBytes(directory), 0);
if (retention === "summary") pruneBranches([experimentSource, controlFollowup, experimentFollowup]);
const result = {schemaVersion: 1, hypothesis: "academy-manager-accepts-offer-followup-v1", selection: {method: requested ? "explicit-case-id" : "source-hash-blind-index", eligibleCases: eligible.length, caseId: selected.caseId, childId: selected.childId, childName: selected.childName, academyId: selected.academyId}, source: {directory: source, cycle: sourceEntrants.cycle, entrantsSha256: sourceHash, majorStateSha256: majorHash}, intervention: {action: "accept-offer", incumbentStatus: selected.incumbentStatus, sourceSalary: sourceEntrants.contracts.contracts.find((value: any) => value.childId === selected.childId)?.salaryAfter, candidateSalary: selected.candidateSalary, affectedChildIds: selected.affectedChildIds, payrollDelta: selected.payrollDelta, arrearsDelta: selected.arrearsDelta, academyBalanceDelta: selected.academyBalanceDelta}, validation: {sourceCompetitionReproduced: true, sourceFinalManagersReproduced: true, oneExperiment: true, exactAffectedContracts: true, majorSourceImmutable: true}, branchArtifacts, retention: {mode: retention, removedBytes: retention === "summary" ? removableBytes : 0}, followup: {cycle: controlSummary.cycle, control: controlOutcome, experiment: candidateOutcome, delta: metricDelta(controlOutcome, candidateOutcome), academyControl: controlAcademy, academyExperiment: candidateAcademy, academyDelta: academyDelta(controlAcademy, candidateAcademy)}, conclusion: classify(controlOutcome, candidateOutcome), activationStatus: "shadow-only"};
write(path.join(out, "academy-contract-counterfactual.json"), result);
fs.writeFileSync(path.join(out, "academy-contract-counterfactual.md"), report(result), "utf8");
console.log(JSON.stringify({out, selected: result.selection, followup: result.followup, conclusion: result.conclusion, activationStatus: result.activationStatus}, null, 2));

function runDevelopment(target: string, previous: string, intervention?: string): void {
  const p = sourceEntrants.policy, economy = p.academyEconomy, market = p.academyMarket, lifecycle = p.lifecycle, rules = sourceEntrants.contracts.replayRules;
  const command = ["--source", path.resolve(sourceEntrants.source.root), "--previous", previous, "--out", target, "--capacity", String(sourceEntrants.capacity), "--parent-limit", String(sourceEntrants.capacity), "--seasons", String(sourceSummary.seasons), "--promotion-slots", String(sourceSummary.promoted.length), "--elimination-slots", String(sourceSummary.eliminated.length), "--regular-rounds", option("--regular-rounds", "1"), "--max-turns", option("--max-turns", "40"), "--development-parent-percent", String(p.developmentParentPercent), "--max-founder-share-percent", String(p.maxFounderSharePercent), "--kinship-depth", String(p.kinshipDepth), "--max-parent-similarity-percent", String(p.maxParentSimilarityPercent), "--academy-influence-percent", String(p.academyInfluencePercent), "--academy-evolution-percent", String(p.academyEvolutionPercent), "--academy-initial-budget", String(economy.initialBudget), "--academy-grant-pool", String(economy.grantPool), "--academy-grant-load-percent", String(economy.grantLoadPercent), "--academy-grant-debt-percent", String(economy.grantDebtPercent), "--academy-payroll-reserve-percent", String(economy.payrollReservePercent), "--academy-max-cycle-spend", String(economy.maximumCycleSpend), "--academy-performance-revenue", String(economy.performanceRevenueRate), "--academy-market-policy", String(market.policy), "--academy-market-consent-policy", String(market.consentPolicy), "--academy-market-consent-threshold-percent", String(Math.round(market.consentThreshold * 100)), "--academy-market-contract-policy", String(market.contractPolicy), "--academy-market-base-salary", String(rules.baseSalary), "--academy-market-max-salary", String(rules.maximumSalary), "--academy-market-offer-percent", String(Math.round(market.offerMultiplier * 100)), "--academy-contract-years", String(rules.renewalYears), "--academy-arbitration-demand-percent", String(Math.round(rules.arbitrationDemandWeight * 100)), "--academy-market-max-transactions", String(market.maximumTransactions), "--academy-signing-fee", String(market.signingFee), "--academy-transfer-fee", String(market.transferFee), "--academy-loan-fee", String(market.loanFee), "--academy-emergency-sale-discount-percent", String(market.emergencySaleDiscountPercent), "--academy-transfer-min-fit-percent", String(Math.round(market.transferMinimumFitDelta * 100)), "--academy-loan-min-fit-percent", String(Math.round(market.loanMinimumFitDelta * 100)), "--maturity-seasons", String(lifecycle.maturitySeasons), "--fertility-max-seasons", String(lifecycle.fertilityMaxSeasons), "--retirement-min-seasons", String(lifecycle.retirementMinSeasons), "--retirement-hard-seasons", String(lifecycle.retirementHardSeasons), "--retirement-base-percent", String(lifecycle.retirementBasePercent), "--retirement-growth-percent", String(lifecycle.retirementGrowthPercent)];
  if (intervention) command.push("--academy-contract-accept-offer-child", intervention);
  run("src/cli/developmentLeague.ts", command, `development cycle ${path.basename(target)}`);
}
function compact(target: string): void { run("src/cli/compactDevelopmentLeague.ts", ["--source", target, "--prune-league"], `compact ${path.basename(target)}`); }
function artifactSummary(directory: string): any { const finalState = read<{sha256: string}>(path.join(directory, "development-final-state.json")); return {entrantsSha256: digest(fs.readFileSync(path.join(directory, "entrants.json"))), summarySha256: digest(fs.readFileSync(path.join(directory, "development-summary.json"))), finalManagersSha256: finalState.sha256}; }
function pruneBranches(directories: string[]): void { for (const directory of directories) { const resolved = path.resolve(directory); if (path.dirname(resolved) !== out || !resolved.startsWith(`${out}${path.sep}`)) throw new Error("Counterfactual retention escaped its output directory"); fs.rmSync(resolved, {recursive: true, force: true}); } }
function directoryBytes(directory: string): number { return fs.readdirSync(directory, {withFileTypes: true}).reduce((sum, entry) => sum + (entry.isDirectory() ? directoryBytes(path.join(directory, entry.name)) : entry.isFile() ? fs.statSync(path.join(directory, entry.name)).size : 0), 0); }
function run(file: string, command: string[], label: string): void { const result = spawnSync(process.execPath, [require.resolve("tsx/cli"), path.join(root, file), ...command], {cwd: root, encoding: "utf8", maxBuffer: 64 * 1024 * 1024}); if (result.status !== 0) throw new Error(`${label} failed:\n${result.stderr || result.stdout}`); }
function validateInterventionSource(controlEntrants: EntrantsArtifact, controlSummary: SummaryArtifact, candidateEntrants: EntrantsArtifact, candidateSummary: SummaryArtifact, selected: ScreenCase): void {
  if (candidateEntrants.cycle !== controlEntrants.cycle || JSON.stringify(competitionRows(candidateSummary)) !== JSON.stringify(competitionRows(controlSummary))) throw new Error("Contract intervention changed or failed to reproduce source competition");
  if (JSON.stringify(candidateSummary.lifecycleRetired.map(value => value.childId).sort()) !== JSON.stringify(controlSummary.lifecycleRetired.map(value => value.childId).sort())) throw new Error("Contract intervention changed source lifecycle retirements");
  const experiment = candidateEntrants.contracts.experiment;
  if (!experiment || experiment.childId !== selected.childId || experiment.action !== "accept-offer") throw new Error("Contract intervention ledger is missing or incorrect");
  const changed = controlEntrants.contracts.contracts.filter((value: any, index: number) => JSON.stringify(value) !== JSON.stringify(candidateEntrants.contracts.contracts[index])).map((value: any) => value.childId).sort();
  if (JSON.stringify(changed) !== JSON.stringify([...selected.affectedChildIds].sort())) throw new Error("Contract intervention changed an unexpected contract set");
  const target = candidateEntrants.contracts.contracts.find((value: any) => value.childId === selected.childId);
  if (target?.status !== "renewed" || Math.abs(target.salaryAfter - selected.candidateSalary) > 1e-8) throw new Error("Contract intervention target outcome does not match the screen");
  for (const [actual, expected, label] of [[candidateEntrants.contracts.payrollOutflow - controlEntrants.contracts.payrollOutflow, selected.payrollDelta, "payroll"], [candidateEntrants.contracts.arrears - controlEntrants.contracts.arrears, selected.arrearsDelta, "arrears"], [(candidateEntrants.contracts.balances[selected.academyId] ?? 0) - (controlEntrants.contracts.balances[selected.academyId] ?? 0), selected.academyBalanceDelta, "academy balance"]] as const) if (Math.abs(actual - expected) > 1e-8) throw new Error(`Contract intervention ${label} delta does not match the screen`);
}
function competitionRows(summary: SummaryArtifact): any[] { return ([...summary.promoted.map(value => ({...value, cycleStatus: "promoted"})), ...summary.retained.map(value => ({...value, cycleStatus: "retained"})), ...summary.eliminated.map(value => ({...value, cycleStatus: "eliminated"}))]).map(value => ({childId: value.childId, cycleStatus: value.cycleStatus, fitness: value.fitness, nicheBonus: value.nicheBonus, titles: value.titles, totalPoints: value.totalPoints, averageRank: value.averageRank})).sort((a, b) => a.childId.localeCompare(b.childId)); }
function outcome(summary: SummaryArtifact, childId: string): any { for (const [status, rows] of [["promoted", summary.promoted], ["retained", summary.retained], ["eliminated", summary.eliminated], ["retired", summary.lifecycleRetired]] as const) { const row = rows.find((value: any) => value.childId === childId); if (row) return {status: status as CycleStatus, cyclePoints: row.cyclePoints ?? null, totalPoints: row.totalPoints ?? null, averageRank: row.averageRank ?? null, titles: row.titles ?? null, annualSalary: row.annualSalary ?? null, contractYearsRemaining: row.contractYearsRemaining ?? null}; } return {status: "absent" as CycleStatus, cyclePoints: null, totalPoints: null, averageRank: null, titles: null, annualSalary: null, contractYearsRemaining: null}; }
function academyOutcome(entrants: EntrantsArtifact, academyId: string): any { const academy = entrants.academies.find(value => value.academyId === academyId), health = entrants.academyFinancialHealth.find(value => value.academyId === academyId); return {treasury: academy?.treasury ?? null, health: health?.status ?? null, guaranteedDebt: entrants.salaryDebts.filter(value => value.academyId === academyId).reduce((sum, value) => sum + value.amount, 0), payrollPaid: health?.payrollPaid ?? null, newArrears: health?.newArrears ?? null}; }
function metricDelta(control: any, experiment: any): any { return {sameStatus: control.status === experiment.status, cyclePoints: numericDelta(control.cyclePoints, experiment.cyclePoints), totalPoints: numericDelta(control.totalPoints, experiment.totalPoints), averageRankImprovement: control.averageRank === null || experiment.averageRank === null ? null : control.averageRank - experiment.averageRank, titles: numericDelta(control.titles, experiment.titles)}; }
function academyDelta(control: any, experiment: any): any { return {treasury: numericDelta(control.treasury, experiment.treasury), guaranteedDebt: numericDelta(control.guaranteedDebt, experiment.guaranteedDebt), payrollPaid: numericDelta(control.payrollPaid, experiment.payrollPaid), newArrears: numericDelta(control.newArrears, experiment.newArrears), sameHealth: control.health === experiment.health}; }
function numericDelta(control: number | null, experiment: number | null): number | null { return control === null || experiment === null ? null : experiment - control; }
function classify(control: any, experiment: any): string { if (control.status !== experiment.status) return `status-change:${control.status}-to-${experiment.status}`; const delta = metricDelta(control, experiment); if ((delta.titles ?? 0) > 0 || (delta.cyclePoints ?? 0) > 0 || (delta.averageRankImprovement ?? 0) > 0) return "competitive-better"; if ((delta.titles ?? 0) < 0 || (delta.cyclePoints ?? 0) < 0 || (delta.averageRankImprovement ?? 0) < 0) return "competitive-worse"; return "competitive-neutral"; }
function report(value: any): string { return `# Academy contract counterfactual\n\nSelected ${value.selection.childName} by ${value.selection.method}. The source competition reproduced exactly and only the screened contract set changed. Follow-up conclusion: **${value.conclusion}**. This single case remains shadow-only.\n\n| Branch | Status | Cycle points | Average rank | Titles | Salary | Contract years | Academy treasury | Academy health | Guaranteed debt |\n|---|---|---:|---:|---:|---:|---:|---:|---|---:|\n| Control | ${value.followup.control.status} | ${value.followup.control.cyclePoints ?? "n/a"} | ${value.followup.control.averageRank ?? "n/a"} | ${value.followup.control.titles ?? "n/a"} | ${value.followup.control.annualSalary ?? "n/a"} | ${value.followup.control.contractYearsRemaining ?? "n/a"} | ${value.followup.academyControl.treasury ?? "n/a"} | ${value.followup.academyControl.health ?? "n/a"} | ${value.followup.academyControl.guaranteedDebt ?? "n/a"} |\n| Experiment | ${value.followup.experiment.status} | ${value.followup.experiment.cyclePoints ?? "n/a"} | ${value.followup.experiment.averageRank ?? "n/a"} | ${value.followup.experiment.titles ?? "n/a"} | ${value.followup.experiment.annualSalary ?? "n/a"} | ${value.followup.experiment.contractYearsRemaining ?? "n/a"} | ${value.followup.academyExperiment.treasury ?? "n/a"} | ${value.followup.academyExperiment.health ?? "n/a"} | ${value.followup.academyExperiment.guaranteedDebt ?? "n/a"} |\n`;
}
function blindIndex(hash: string, length: number): number { return Number.parseInt(digest(Buffer.from(`${hash}:academy-contract-followup-v1`)).slice(0, 12), 16) % length; }
function digest(bytes: Buffer): string { return crypto.createHash("sha256").update(bytes).digest("hex"); }
function read<T>(file: string): T { return JSON.parse(fs.readFileSync(file, "utf8")) as T; }
function write(file: string, value: unknown): void { fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, "utf8"); }
function option(name: string, fallback: string): string { const index = args.indexOf(name); return index >= 0 ? args[index + 1] ?? fallback : fallback; }
function required(name: string): string { const value = option(name, "").trim(); if (!value) throw new Error(`Missing ${name}`); return value; }
