import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {compareWhiteBoxBranches} from "../ai/whiteBox/counterfactual";
import {createRegistrySnapshot} from "../draft/registrySnapshot";
import type {ProgramDecisionGroup,ProgramOpportunitySnapshot} from "../draft/strategyProgramOpportunity";

interface DynastyState {seed:string;completedSeason:number;settings:Record<string,number|string|boolean|undefined>;fingerprint:{registryHash:string};registry?:{revision:string;snapshot:string}}

const args=process.argv.slice(2),root=process.cwd(),source=path.resolve(required("--source")),out=path.resolve(option("--out","output/program-decision-counterfactual"));
const decisionId=required("--decision-id"),managerId=required("--manager"),candidateId=required("--candidate"),interventionSeason=integerOption("--season",1,1,100),followupSeasons=integerOption("--followup",1,0,3);
const sourceState=read<DynastyState>(path.join(source,"dynasty-state.json")),finalSeason=sourceState.completedSeason+followupSeasons;
if(interventionSeason>sourceState.completedSeason)throw new Error("Intervention season must exist in the source dynasty");
const decision=sourceDecision();
if(decision.entrypoint!=="acquire"&&decision.entrypoint!=="lineup")throw new Error(`Decision ${decisionId} is not a supported single-selection decision`);
if(decision.selectedIds.length!==1)throw new Error(`Decision ${decisionId} is not single-selection`);
if(candidateId===decision.selectedIds[0])throw new Error("Counterfactual candidate is already the incumbent selection");
if(!decision.candidates.some(candidate=>candidate.id===candidateId))throw new Error(`Candidate ${candidateId} is not retained in decision ${decisionId}`);
prepareOutput();
const controlDir=path.join(out,"control"),experimentDir=path.join(out,"experiment");
run(controlDir,false);run(experimentDir,true);
verifyPrefix(controlDir,sourceState.completedSeason);verifyPrefix(experimentDir,interventionSeason-1);
const intervention=findIntervention(experimentDir);
const controlState=read<any>(path.join(controlDir,"dynasty-state.json")),experimentState=read<any>(path.join(experimentDir,"dynasty-state.json"));
const comparison=compareWhiteBoxBranches(managerId,interventionSeason,controlState,experimentState),direction=competitiveDirection(comparison.delta);
const incumbent=decision.candidates.find(candidate=>candidate.id===decision.selectedIds[0])!,candidate=decision.candidates.find(entry=>entry.id===candidateId)!;
const summary={schemaVersion:1,source,seed:sourceState.seed,decision:{id:decisionId,entrypoint:decision.entrypoint,managerId,season:interventionSeason,incumbent,candidate},followupSeasons,finalSeason,prefixVerified:true,intervention,comparison,direction};
write(path.join(out,"counterfactual-summary.json"),summary);fs.writeFileSync(path.join(out,"counterfactual-report.md"),markdown(summary),"utf8");
console.log(JSON.stringify({decisionId,entrypoint:decision.entrypoint,managerId,direction,delta:comparison.delta,report:path.join(out,"counterfactual-report.md")},null,2));

function sourceDecision():ProgramDecisionGroup{const file=path.join(source,`season-${String(interventionSeason).padStart(2,"0")}`,"program-opportunities.json");if(!fs.existsSync(file))throw new Error(`Missing source decision evidence: ${file}`);const snapshot=read<ProgramOpportunitySnapshot>(file),manager=snapshot.managers.find(entry=>entry.managerId===managerId),matches=(manager?.decisions??[]).filter(entry=>entry.id===decisionId);if(matches.length!==1)throw new Error(`Expected exactly one source decision ${decisionId} for ${managerId}, found ${matches.length}`);return matches[0];}
function run(directory:string,experiment:boolean):void{const settings=sourceState.settings,registrySource=registrySourceFor(directory),env={...process.env,V12_OUT:directory,V12_SEED:sourceState.seed,V12_SEASONS:String(finalSeason),V12_RESUME:"false",V12_MANAGER_LIMIT:String(settings.managerLimit),V12_PAIRS:String(settings.pairs),V12_POOL_SIZE:String(settings.poolSize),V12_AUCTION_LOTS:String(settings.auctionLots),V12_REGULAR_ROUNDS:String(settings.regularRounds),V12_MAX_TURNS:String(settings.maxTurns),V12_MIN_ROSTER:String(settings.minRoster??6),V12_MAX_ROSTER:String(settings.maxRoster??10),V12_BASE_CASH:String(settings.baseBudget??40),V12_REGISTRY_SOURCE:registrySource,V12_REGISTRY_REVISION:sourceState.registry?.revision??"program-decision-counterfactual",V12_STRATEGY_PROGRAM_OPERATOR:String(settings.strategyProgramOperator??"observed-boundary-v1"),V12_EVOLUTION_MODE:String(settings.evolutionMode??"punctuated"),V12_EVOLUTION_POLICY:String(settings.evolutionPolicy??"shadow"),V12_EVOLUTION_MAX_BURSTS:String(settings.evolutionMaxBursts??2),V12_EVOLUTION_MIN_CANDIDATES:String(settings.evolutionMinCandidates??4),V12_EVOLUTION_MAX_CANDIDATES:String(settings.evolutionMaxCandidates??8),V12_EVIDENCE_RETENTION:"compact",V12_EVIDENCE_SAMPLE_RATE:"0",V4_PROGRAM_DECISION_POLICY:experiment?"forced-alternative-experiment":"",V4_PROGRAM_DECISION_TARGET:experiment?decisionId:"",V4_PROGRAM_DECISION_CANDIDATE:experiment?candidateId:""};const result=spawnSync(process.execPath,[require.resolve("tsx/cli"),path.join(root,"src","cli","draftLeagueV12.ts")],{cwd:root,env,encoding:"utf8",maxBuffer:64*1024*1024});if(result.status!==0)throw new Error(`${experiment?"Experiment":"Control"} program-decision branch failed:\n${result.stderr||result.stdout}`);}
function registrySourceFor(directory:string):string{const snapshot=sourceState.registry?.snapshot?path.resolve(source,sourceState.registry.snapshot):"";if(snapshot&&fs.existsSync(path.join(snapshot,"registry-manifest.json")))return snapshot;const restored=createRegistrySnapshot(path.resolve("data/draft"),path.join(directory,"config-snapshots"),sourceState.registry?.revision);if(restored.hash!==sourceState.fingerprint.registryHash)throw new Error("Source registry snapshot is missing and the current registry hash does not match");return restored.directory;}
function verifyPrefix(actualRoot:string,seasons:number):void{for(let season=1;season<=seasons;season+=1){const name=`season-${String(season).padStart(2,"0")}`,expected=essential(read<any>(path.join(source,name,"season.json"))),actual=essential(read<any>(path.join(actualRoot,name,"season.json")));if(digest(expected)!==digest(actual))throw new Error(`Replayed ${name} does not match source prefix`);}}
function findIntervention(runRoot:string):any{const file=path.join(runRoot,`season-${String(interventionSeason).padStart(2,"0")}`,"decision-ledger.json"),records=read<any>(file).records??[],matches=records.filter((record:any)=>record.actor===managerId&&record.context?.programDecisionExperiment?.decisionId===decisionId);if(matches.length!==1)throw new Error(`Expected one executed intervention, found ${matches.length}`);const value=matches[0].context.programDecisionExperiment;if(value.incumbentId!==decision.selectedIds[0]||value.candidateId!==candidateId)throw new Error("Executed intervention does not match source evidence");return value;}
function competitiveDirection(delta:any):"better"|"neutral"|"worse"{if(delta.titles!==0)return delta.titles>0?"better":"worse";if(delta.totalPoints!==0)return delta.totalPoints>0?"better":"worse";if(delta.finalRank!==null&&delta.finalRank!==0)return delta.finalRank<0?"better":"worse";return"neutral";}
function essential(value:any):any{return{season:value.season,champion:value.champion,standings:value.standings,transactions:value.transactions,validity:value.validity};}
function markdown(value:typeof summary):string{return`# Isolated program-decision counterfactual\n\n- Decision: \`${value.decision.id}\`\n- Entrypoint / manager: ${value.decision.entrypoint} / ${value.decision.managerId}\n- Incumbent: \`${value.decision.incumbent.id}\` (${value.decision.incumbent.score})\n- Forced alternative: \`${value.decision.candidate.id}\` (${value.decision.candidate.score})\n- Intervention / final season: ${value.decision.season} / ${value.finalSeason}\n- Prefix verified: ${value.prefixVerified}\n- Competitive direction: **${value.direction}**\n- Points / rank / titles / cash delta: ${value.comparison.delta.totalPoints} / ${value.comparison.delta.finalRank??"n/a"} / ${value.comparison.delta.titles} / ${value.comparison.delta.cash}\n\nThis record labels one observed alternative under a matched replay. It is local causal evidence, not permission to activate a strategy program.\n`;}
function prepareOutput():void{if(fs.existsSync(out))throw new Error(`Counterfactual output exists: ${out}`);if(out===source||source.startsWith(`${out}${path.sep}`)||out.startsWith(`${source}${path.sep}`))throw new Error("Counterfactual output must be separate from its source");fs.mkdirSync(out,{recursive:true});}
function digest(value:any):string{return crypto.createHash("sha256").update(stable(value)).digest("hex");}function stable(value:any):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);}
function write(file:string,value:unknown):void{fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`,"utf8");}function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?args[index+1]??fallback:fallback;}function required(name:string):string{const value=option(name,"");if(!value)throw new Error(`Missing required option: ${name}`);return value;}function integerOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}
