import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {compareWhiteBoxBranches,whiteBoxBranchMarkdown} from "../ai/whiteBox/counterfactual";

const args=process.argv.slice(2),root=process.cwd(),source=path.resolve(required("--source")),out=path.resolve(option("--out","output/whitebox-lineup-counterfactual")),decisionId=required("--decision-id"),managerId=required("--manager"),season=integerOption("--season",1,1,20),band=numberOption("--band",.5,0,5),styleLimit=numberOption("--style-limit",3,0,5),styleScale=numberOption("--style-scale",1.1,0,2),sourceState=read<any>(path.join(source,"dynasty-state.json"));
if(fs.existsSync(out)){if(!args.includes("--force"))throw new Error(`Counterfactual output exists: ${out}`);const resolved=path.resolve(out);if(path.parse(resolved).root===resolved||resolved===root||resolved===source||source.startsWith(`${resolved}${path.sep}`))throw new Error(`Unsafe counterfactual target: ${resolved}`);fs.rmSync(resolved,{recursive:true,force:true});}fs.mkdirSync(out,{recursive:true});const incumbentDir=path.join(out,"incumbent"),whiteboxDir=path.join(out,"whitebox");run(incumbentDir,false);run(whiteboxDir,true);verifyPrefix(source,incumbentDir,sourceState.completedSeason);verifyPrefix(source,whiteboxDir,season-1);assertIntervention(whiteboxDir,decisionId);const incumbent=read<any>(path.join(incumbentDir,"dynasty-state.json")),whitebox=read<any>(path.join(whiteboxDir,"dynasty-state.json")),comparison=compareWhiteBoxBranches(managerId,season,incumbent,whitebox),summary={schemaVersion:1,source,decisionId,managerId,season,band,styleLimit,styleScale,prefixVerified:true,comparison};fs.writeFileSync(path.join(out,"counterfactual-summary.json"),`${JSON.stringify(summary,null,2)}\n`,"utf8");fs.writeFileSync(path.join(out,"counterfactual-report.md"),whiteBoxBranchMarkdown(comparison),"utf8");console.log(JSON.stringify({decisionId,managerId,prefixVerified:true,comparison,report:path.join(out,"counterfactual-report.md")},null,2));
function run(directory:string,whitebox:boolean):void{const settings=sourceState.settings,registry=sourceState.registry,registrySource=registry?.snapshot?path.resolve(source,registry.snapshot):path.resolve(option("--registry","data/draft")),env={...process.env,V12_OUT:directory,V12_SEED:sourceState.seed,V12_SEASONS:String(sourceState.completedSeason),V12_RESUME:"false",V12_MANAGER_LIMIT:String(settings.managerLimit),V12_PAIRS:String(settings.pairs),V12_POOL_SIZE:String(settings.poolSize),V12_AUCTION_LOTS:String(settings.auctionLots),V12_REGULAR_ROUNDS:String(settings.regularRounds),V12_MAX_TURNS:String(settings.maxTurns),V12_MIN_ROSTER:String(settings.minRoster??6),V12_MAX_ROSTER:String(settings.maxRoster??10),V12_BASE_CASH:String(settings.baseBudget??40),V12_REGISTRY_SOURCE:registrySource,V12_REGISTRY_REVISION:registry?.revision??"lineup-counterfactual",V12_EVIDENCE_RETENTION:"compact",V4_LINEUP_POLICY:whitebox?"whitebox-experiment":"incumbent",V4_LINEUP_POLICY_TARGET:whitebox?decisionId:"",V4_LINEUP_BAND:String(band),V4_LINEUP_STYLE_LIMIT:String(styleLimit),V4_LINEUP_STYLE_SCALE:String(styleScale)};const result=spawnSync(process.execPath,[require.resolve("tsx/cli"),path.join(root,"src","cli","draftLeagueV12.ts")],{cwd:root,env,encoding:"utf8",maxBuffer:64*1024*1024});if(result.status!==0)throw new Error(`${whitebox?"White-box":"Incumbent"} lineup branch failed:\n${result.stderr||result.stdout}`);}
function assertIntervention(runRoot:string,target:string):void{let found=false;for(const entry of fs.readdirSync(runRoot,{withFileTypes:true}).filter(entry=>entry.isDirectory()&&/^season-\d+$/.test(entry.name))){const file=path.join(runRoot,entry.name,"decision-ledger.json");if(!fs.existsSync(file))continue;for(const record of read<any>(file).records??[])if(record.context?.policy==="whitebox-experiment"&&record.context?.whiteBoxLineupExperiment?.trace?.decisionId===target)found=true;}if(!found)throw new Error(`Lineup intervention was not executed: ${target}`);}
function verifyPrefix(expectedRoot:string,actualRoot:string,seasons:number):void{for(let index=1;index<=seasons;index++){const name=`season-${String(index).padStart(2,"0")}`,expected=essential(read<any>(path.join(expectedRoot,name,"season.json"))),actual=essential(read<any>(path.join(actualRoot,name,"season.json")));if(digest(expected)!==digest(actual))throw new Error(`Replayed ${name} does not match source prefix`);}}
function essential(value:any):any{return{season:value.season,champion:value.champion,standings:value.standings,transactions:value.transactions,validity:value.validity};}
function digest(value:any):string{return crypto.createHash("sha256").update(stable(value)).digest("hex");}function stable(value:any):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);}
function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?args[index+1]??fallback:fallback;}function required(name:string):string{const index=args.indexOf(name),value=index>=0?args[index+1]:undefined;if(!value)throw new Error(`Missing required option: ${name}`);return value;}function integerOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}function numberOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isFinite(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}
