import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {compareWhiteBoxBranches,whiteBoxBranchMarkdown} from "../ai/whiteBox/counterfactual";
import {readLineupLocalOutcome} from "../ai/whiteBox/programDecisionLocalOutcome";
import {loadDynastyState} from "../draft/dynastyStateStore";
import {materializeHistoricalDynastyBoundary, materializeHistoricalReplayCheckpoint, materializeSpawnWorkingDirectory, planHistoricalReplaySegments} from "../draft/historicalRuntimeCheckpoint";

const args=process.argv.slice(2),source=path.resolve(required("--source")),out=path.resolve(option("--out","output/whitebox-lineup-counterfactual")),decisionId=required("--decision-id"),managerId=required("--manager"),candidateId=option("--candidate-id",""),season=integerOption("--season",1,1,1000),followupSeasons=integerOption("--followup-seasons",0,0,10),band=numberOption("--band",.5,0,5),styleLimit=numberOption("--style-limit",3,0,5),styleScale=numberOption("--style-scale",1.1,0,2),reuseSourceControl=args.includes("--reuse-source-control"),sourceState=loadDynastyState<any>(path.join(source,"dynasty-state.json")),finalSeason=season+followupSeasons;
if(sourceState.completedSeason<finalSeason)throw new Error(`Source has only completed season ${sourceState.completedSeason}; requested through ${finalSeason}`);
if(fs.existsSync(out)){if(!args.includes("--force"))throw new Error(`Counterfactual output exists: ${out}`);const resolved=path.resolve(out);if(path.parse(resolved).root===resolved||resolved===source||source.startsWith(`${resolved}${path.sep}`))throw new Error(`Unsafe counterfactual target: ${resolved}`);fs.rmSync(resolved,{recursive:true,force:true});}fs.mkdirSync(out,{recursive:true});
const segments=planHistoricalReplaySegments(source,season,finalSeason),incumbentDir=path.join(out,"incumbent"),whiteboxDir=path.join(out,"whitebox");
if(reuseSourceControl)materializeHistoricalDynastyBoundary(source,finalSeason,incumbentDir);else run(incumbentDir,false);run(whiteboxDir,true);verifyPrefix(source,incumbentDir,finalSeason);verifyPrefix(source,whiteboxDir,season-1);assertIntervention(whiteboxDir,decisionId);
const incumbent=loadDynastyState<any>(path.join(incumbentDir,"dynasty-state.json")),whitebox=loadDynastyState<any>(path.join(whiteboxDir,"dynasty-state.json")),comparison=compareWhiteBoxBranches(managerId,season,incumbent,whitebox),controlBattleRoot=reuseSourceControl?source:incumbentDir,localOutcome=readLineupLocalOutcome(controlBattleRoot,whiteboxDir,season,decisionId,managerId),summary={schemaVersion:2,source,controlBattleSource:reuseSourceControl?source:null,decisionId,managerId,season,followupSeasons,band,styleLimit,styleScale,interventionMode:candidateId?"forced-candidate":"whitebox-rescore",candidateId:candidateId||null,historicalRuntime:{segments:segments.map(segment=>({firstSeason:segment.firstSeason,lastSeason:segment.lastSeason,runtimeId:segment.runtimeId}))},prefixVerified:true,localOutcome,comparison};
fs.writeFileSync(path.join(out,"counterfactual-summary.json"),`${JSON.stringify(summary,null,2)}\n`,"utf8");fs.writeFileSync(path.join(out,"counterfactual-report.md"),`${whiteBoxBranchMarkdown(comparison)}\n## Local series\n\n- Series: ${localOutcome.seriesId}\n- Direction: ${localOutcome.direction}\n- Pair-margin delta: ${localOutcome.delta.pairMargin}\n- Game-margin delta: ${localOutcome.delta.gameMargin}\n`,"utf8");console.log(JSON.stringify({decisionId,managerId,prefixVerified:true,localOutcome,delta:comparison.delta,report:path.join(out,"counterfactual-report.md")},null,2));
function run(directory:string,whitebox:boolean):void{const replay=materializeHistoricalReplayCheckpoint(source,season,directory);for(const segment of segments)runSegment(directory,whitebox,segment,replay.registrySource);}
function runSegment(directory:string,whitebox:boolean,segment:any,registrySource:string):void{const settings=sourceState.settings,containsIntervention=segment.firstSeason<=season&&season<=segment.lastSeason,forced=whitebox&&containsIntervention&&Boolean(candidateId),env={...process.env,NODE_PATH:segment.nodePath,V12_OUT:directory,V12_SEED:sourceState.seed,V12_SEASONS:String(segment.lastSeason),V12_RESUME:"true",V12_ALLOW_CODE_UPGRADE:"true",V12_MANAGER_LIMIT:String(settings.managerLimit),V12_PAIRS:String(settings.pairs),V12_POOL_SIZE:String(settings.poolSize),V12_AUCTION_LOTS:String(settings.auctionLots),V12_REGULAR_ROUNDS:String(settings.regularRounds),V12_MAX_TURNS:String(settings.maxTurns),V12_MIN_ROSTER:String(settings.minRoster??6),V12_MAX_ROSTER:String(settings.maxRoster??10),V12_BASE_CASH:String(settings.baseBudget??40),V12_AUCTION_MODE:String(settings.auctionMode??"sequential"),V12_REGISTRY_SOURCE:registrySource,V12_REGISTRY_REVISION:sourceState.registry?.revision??"lineup-counterfactual",V12_STRATEGY_PROGRAM_OPERATOR:String(settings.strategyProgramOperator??"observed-boundary-v1"),V12_EVOLUTION_MODE:String(settings.evolutionMode??"punctuated"),V12_EVOLUTION_POLICY:String(settings.evolutionPolicy??"shadow"),V12_EVOLUTION_MAX_BURSTS:String(settings.evolutionMaxBursts??2),V12_EVOLUTION_MIN_CANDIDATES:String(settings.evolutionMinCandidates??4),V12_EVOLUTION_MAX_CANDIDATES:String(settings.evolutionMaxCandidates??8),V12_EVIDENCE_RETENTION:"compact",V4_LINEUP_POLICY:whitebox&&containsIntervention&&!forced?"whitebox-experiment":"incumbent",V4_LINEUP_POLICY_TARGET:whitebox&&containsIntervention&&!forced?decisionId:"",V4_LINEUP_BAND:String(band),V4_LINEUP_STYLE_LIMIT:String(styleLimit),V4_LINEUP_STYLE_SCALE:String(styleScale),V4_PROGRAM_DECISION_POLICY:forced?"forced-alternative-experiment":"",V4_PROGRAM_DECISION_TARGET:forced?decisionId:"",V4_PROGRAM_DECISION_CANDIDATE:forced?candidateId:""},working=materializeSpawnWorkingDirectory(segment.runtimeWorkspace);let result;try{result=spawnSync(process.execPath,[require.resolve("tsx/cli"),path.join(segment.runtimeWorkspace,"src","cli","draftLeagueV12.ts")],{cwd:working.cwd,env,encoding:"utf8",maxBuffer:64*1024*1024});}finally{working.cleanup();}if(result.status!==0){const detail=[`status=${String(result.status)}`,`signal=${String(result.signal)}`,`cwd=${segment.runtimeWorkspace}`,`cwdExists=${fs.existsSync(segment.runtimeWorkspace)}`,result.error?`spawnError=${result.error.name}: ${result.error.message}`:"spawnError=none",result.stderr?`stderr:\n${result.stderr.slice(-12000)}`:"stderr=<empty>",result.stdout?`stdout:\n${result.stdout.slice(-12000)}`:"stdout=<empty>"].join("\n");throw new Error(`${whitebox?"White-box":"Incumbent"} lineup branch failed through season ${segment.lastSeason}:\n${detail}`);}}
function assertIntervention(runRoot:string,target:string):void{let found=false;for(const entry of fs.readdirSync(runRoot,{withFileTypes:true}).filter(entry=>entry.isDirectory()&&/^season-\d+$/.test(entry.name))){const file=path.join(runRoot,entry.name,"decision-ledger.json");if(!fs.existsSync(file))continue;for(const record of read<any>(file).records??[]){const whitebox=record.context?.policy==="whitebox-experiment"&&record.context?.whiteBoxLineupExperiment?.trace?.decisionId===target,forced=record.context?.policy==="forced-alternative-experiment"&&record.context?.programDecisionExperiment?.decisionId===target;if(whitebox||forced)found=true;}}if(!found)throw new Error(`Lineup intervention was not executed: ${target}`);}
function verifyPrefix(expectedRoot:string,actualRoot:string,seasons:number):void{for(let index=1;index<=seasons;index++){const name=`season-${String(index).padStart(2,"0")}`,expected=essential(read<any>(path.join(expectedRoot,name,"season.json"))),actual=essential(read<any>(path.join(actualRoot,name,"season.json")));if(digest(expected)!==digest(actual))throw new Error(`Replayed ${name} does not match source prefix`);}}
function essential(value:any):any{return{season:value.season,champion:value.champion,standings:value.standings,transactions:value.transactions,validity:value.validity};}
function digest(value:any):string{return crypto.createHash("sha256").update(stable(value)).digest("hex");}function stable(value:any):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`;return JSON.stringify(value);}
function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?args[index+1]??fallback:fallback;}function required(name:string):string{const index=args.indexOf(name),value=index>=0?args[index+1]:undefined;if(!value)throw new Error(`Missing required option: ${name}`);return value;}function integerOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}function numberOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isFinite(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}
