import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {discoverBattleConditionalMechanisms,type CompletedBattleResearchCase} from "../ai/whiteBox/battleConditionalWorkbench";
import {acquireNamedRunLock} from "../draft/runLock";

const args=process.argv.slice(2),frontierFile=path.resolve(required("--frontier")),roots=required("--research-roots").split(",").filter(Boolean).map(value=>path.resolve(value)),baseOptionsFile=path.resolve(required("--base-options")),out=path.resolve(required("--out"));
if(new Set(roots.map(value=>normalized(value))).size!==roots.length)throw new Error("Duplicate conditional research root");
const frontier=read<any>(frontierFile),baseOptions=read<any>(baseOptionsFile);
if(frontier.schemaVersion!==1||frontier.contextSchemaVersion!==1||frontier.activationStatus!=="shadow-only"||frontier.evidenceStatus!=="observational-candidate-frontier"||frontier.validity?.activationAllowed!==false||!Array.isArray(frontier.managerMechanisms)||Number(frontier.coverage?.truncatedManagerMechanisms)!==0)throw new Error("Conditional discovery requires a complete, versioned shadow battle frontier");
if(baseOptions.schemaVersion!==1||baseOptions.activationStatus!=="shadow-only"||!Array.isArray(baseOptions.hypotheses)||!Array.isArray(baseOptions.dispositions))throw new Error("Invalid base battle research options");
const cases:CompletedBattleResearchCase[]=[],caseIds=new Set<string>(),physicalCases=new Set<string>(),researchInputs:any[]=[];
for(const root of roots){
  const planFile=path.join(root,"battle-frontier-research-plan.json"),summaryFile=path.join(root,"run","battle-frontier-summary.json"),plan=read<any>(planFile),summary=read<any>(summaryFile);
  if(plan.schemaVersion!==1||plan.activationStatus!=="shadow-only"||plan.evidenceStatus!=="manager-selected-research-only"||plan.authority!=="no-activation-authority"||!Array.isArray(plan.items))throw new Error(`Invalid battle research plan: ${root}`);
  if(summary.schemaVersion!==1||summary.activationStatus!=="shadow-only"||summary.evidenceStatus!=="manager-selected-research-only"||summary.authority!=="no-activation-authority"||summary.status!=="complete"||!Array.isArray(summary.results))throw new Error(`Invalid complete battle research summary: ${root}`);
  const items=new Map<string,any>();for(const item of plan.items){if(item.status!=="ready"){if(item.status!=="deferred"||!item.managerId||!item.mechanismId||!item.reason)throw new Error(`Invalid deferred plan item: ${root}`);continue;}const id=String(item.id??"");if(!id||items.has(id))throw new Error(`Duplicate or missing ready plan item id: ${root}/${id}`);items.set(id,item);}
  for(const result of summary.results){const id=String(result.id),item=items.get(id);if(!item)throw new Error(`Research result is absent from its plan: ${root}/${id}`);if(caseIds.has(id))throw new Error(`Duplicate conditional research case id: ${id}`);if(String(item.managerId)!==String(result.managerId)||String(item.mechanismId)!==String(result.mechanismId)||!["better","neutral","worse"].includes(result.direction))throw new Error(`Battle research result drift: ${root}/${id}`);
    const game=path.resolve(String(item.game)),physical=physicalKey(item,game);if(physicalCases.has(physical))throw new Error(`Duplicate physical conditional research case: ${id}`);caseIds.add(id);physicalCases.add(physical);cases.push({id,managerId:String(result.managerId),mechanismId:String(result.mechanismId),game,decisionOrdinal:Number(item.decisionOrdinal),side:String(item.side),selected:String(item.selected),alternative:String(item.alternative),direction:result.direction});
  }
  researchInputs.push({root:relative(root),plan:fingerprint(planFile),summary:fingerprint(summaryFile)});
}
const parameters={minimumCases:integer("--minimum-cases",3,2,1000),minimumManagers:integer("--minimum-managers",3,2,100),minimumDecisive:integer("--minimum-decisive",1,1,1000),maximumPerMechanism:integer("--maximum-per-mechanism",4,1,20),minimumBoundaryJaccard:numberOption("--minimum-boundary-jaccard",.5,.1,1)},retired=(baseOptions.dispositions??[]).filter((value:any)=>value.status==="retired").map((value:any)=>String(value.mechanismId)),workbench=discoverBattleConditionalMechanisms(frontier,cases,{excludedMechanismIds:retired,...parameters});
const caseCorpus=cases.map(value=>({...value,game:normalized(value.game)})).sort((a,b)=>a.id.localeCompare(b.id)),provenance={schemaVersion:1,frontier:fingerprint(frontierFile),baseOptions:fingerprint(baseOptionsFile),researchInputs,parameters,implementation:{cli:fingerprint(path.join(process.cwd(),"src/cli/discoverBattleConditionalMechanisms.ts")),workbench:fingerprint(path.join(process.cwd(),"src/ai/whiteBox/battleConditionalWorkbench.ts")),contextClassifier:fingerprint(path.join(process.cwd(),"src/ai/whiteBox/battleCandidateFrontier.ts"))},caseCorpusSha256:sha(Buffer.from(canonical(caseCorpus)))};
const planningRows=[...(frontier.managerMechanisms??[]),...workbench.managerMechanisms],rowMechanismId=(value:any)=>String(value.mechanismId??`battle-frontier-${value.mechanism}-v1`),availableManagerIds=(mechanismId:string)=>[...new Set(planningRows.filter((row:any)=>rowMechanismId(row)===mechanismId&&(row.examples??[]).some((example:any)=>!physicalCases.has(physicalKey({managerId:row.managerId,...example},path.resolve(frontier.source,String(example.game)))))).map((row:any)=>String(row.managerId)))].sort(),hypotheses=[...(baseOptions.hypotheses??[]).map((value:any)=>({...value,evidenceStatus:"post-deployment-exploratory"})),...workbench.hypotheses].map(value=>({...value,eligibleManagerIds:availableManagerIds(String(value.id))})),menu={schemaVersion:1,activationStatus:"shadow-only",evidenceStatus:"post-deployment-exploratory",validity:workbench.validity,provenance,hypotheses,conditionalWorkbench:{inputs:workbench.inputs,candidates:workbench.candidates,validity:workbench.validity},dispositions:baseOptions.dispositions??[]},planningFrontier={schemaVersion:1,activationStatus:"shadow-only",evidenceStatus:"post-deployment-exploratory",validity:workbench.validity,provenance,managerMechanisms:planningRows};
const summary={schemaVersion:1,activationStatus:"shadow-only",...workbench.inputs,conditionalHypotheses:workbench.hypotheses.length,managerMechanisms:workbench.managerMechanisms.length,byBase:Object.fromEntries([...new Set(workbench.candidates.map(value=>value.baseMechanismId))].sort().map(id=>[id,workbench.candidates.filter(value=>value.baseMechanismId===id).length])),inputSetSha256:sha(Buffer.from(canonical(provenance))),estimatedTokens:Math.ceil(Buffer.byteLength(JSON.stringify({inputs:workbench.inputs,candidates:workbench.candidates.map(value=>({id:value.mechanismId,cases:value.cases,better:value.better,neutral:value.neutral,worse:value.worse}))}))/4)};
fs.mkdirSync(out,{recursive:true});const lock=acquireNamedRunLock(out,".battle-conditional-discovery.lock",{workflow:"battle-conditional-discovery",inputs:provenance});
try{const optionsFile=path.join(out,"research-options.json"),planningFile=path.join(out,"planning-frontier.json"),workbenchFile=path.join(out,"conditional-workbench.json"),summaryFile=path.join(out,"summary.json");write(optionsFile,menu);write(planningFile,planningFrontier);write(workbenchFile,{...workbench,provenance});write(summaryFile,summary);write(path.join(out,"manifest.json"),{schemaVersion:1,activationStatus:"shadow-only",inputSetSha256:summary.inputSetSha256,inputs:provenance,outputs:{researchOptions:fingerprint(optionsFile),planningFrontier:fingerprint(planningFile),conditionalWorkbench:fingerprint(workbenchFile),summary:fingerprint(summaryFile)}});console.log(JSON.stringify(summary,null,2));}finally{lock.release();}

function physicalKey(value:any,game:string):string{return canonical({managerId:String(value.managerId),game:normalized(game),decisionOrdinal:Number(value.decisionOrdinal),side:String(value.side),selected:String(value.selected),alternative:String(value.alternative)});}
function fingerprint(file:string):{file:string;sha256:string;bytes:number}{const bytes=fs.readFileSync(file);return{file:relative(file),sha256:sha(bytes),bytes:bytes.length};}
function relative(value:string):string{return path.relative(process.cwd(),value).replaceAll("\\","/");}function normalized(value:string):string{return path.resolve(value).replaceAll("\\","/").toLowerCase();}
function sha(value:Buffer):string{return crypto.createHash("sha256").update(value).digest("hex");}function canonical(value:unknown):string{if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object"){const record=value as Record<string,unknown>;return`{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`;}return JSON.stringify(value);}
function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}function write(file:string,value:unknown):void{const temporary=`${file}.${process.pid}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,"utf8");fs.renameSync(temporary,file);}function required(name:string):string{const value=option(name,"");if(!value)throw new Error(`Missing ${name}`);return value;}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?String(args[index+1]??fallback):fallback;}function integer(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`Invalid ${name}`);return value;}function numberOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isFinite(value)||value<min||value>max)throw new Error(`Invalid ${name}`);return value;}
