import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {validateLineupHypothesisRegistry, type LineupAuditHypothesis, type LineupHypothesisRegistry} from "../ai/whiteBox/lineupHypothesisWorkbench";

const args = process.argv.slice(2), root = process.cwd();
const registryFile = path.resolve(required("--registry")), auditFile = path.resolve(required("--audit")), study = path.resolve(required("--study")), heterogeneityFile = path.resolve(required("--heterogeneity"));
const parentId = required("--parent"), signal = required("--signal"), out = path.resolve(required("--out")), id = required("--id"), title = option("--title", "Scoped lineup recovery candidate");
const registry = validateLineupHypothesisRegistry(read<LineupHypothesisRegistry>(registryFile)), baseAudit = read<any>(auditFile), heterogeneity = read<any>(heterogeneityFile), causalSummaryFile = path.join(study, "causal-summary.json"), causalManifestFile = path.join(study, "causal-manifest.json"), causalSummary = read<any>(causalSummaryFile), causalManifest = read<any>(causalManifestFile);
if (heterogeneity.evidenceStatus !== "post-hoc-exploratory" || heterogeneity.activationStatus !== "shadow-only") throw new Error("Heterogeneity evidence is not eligible for scope freezing");
const proposal = heterogeneity.proposals?.find((value: any) => value.signal === signal); if (!proposal) throw new Error(`Requested signal is not a frozen-scope proposal: ${signal}`);
if (!signal.startsWith("incumbent.lineup.") && !signal.startsWith("delta.lineup.")) throw new Error("Only lineup diagnostic incumbent/delta signals may define a runtime scope");
if (causalSummary.hypothesisId !== parentId || causalSummary.completed !== 24 || causalSummary.failed !== 0 || causalSummary.activationStatus !== "shadow-only") throw new Error("Parent causal study is incomplete or mismatched");
const parent = registry.hypotheses.find(value => value.id === parentId); if (!parent) throw new Error(`Parent hypothesis is missing: ${parentId}`);
if (registry.hypotheses.some(value => value.id === id) || !/^[a-z0-9-]+-v\d+$/.test(id)) throw new Error(`Invalid or duplicate scoped hypothesis id: ${id}`);
const discoveryFinalSeason = Math.max(...causalManifest.items.map((value: any) => Number(value.season))), source = signal.startsWith("delta.") ? "delta" as const : "incumbent" as const, feature = signal.slice(signal.indexOf("lineup."));
const applicability = [{source, feature, ...(proposal.operator === "at-most" ? {maximum: Number(proposal.threshold)} : {minimum: Number(proposal.threshold)})}];
const scoped: LineupAuditHypothesis = {id, title, rationale: `Post-hoc heterogeneity in ${parentId} suggested a predecision scope. The scope is frozen before future seasons and remains research-only.`, stage: "scoped-causal-candidate", minimumRepresentationVersion: parent.minimumRepresentationVersion, combine: parent.combine, factors: parent.factors.map(value => ({...value})), scope: ["predecision-scoped-lineups"], guardrails: parent.guardrails.map(value => ({...value})), applicability, discoveryEvidence: {kind: "post-hoc-causal-heterogeneity", auditSha256: hash(heterogeneityFile), parentHypothesisId: parentId, discoveryFinalSeason}};
const hypotheses = registry.hypotheses.map(value => value.id === parentId ? {...value, stage: "causal-complete" as const, causalEvidence: {study: path.relative(root, study).replaceAll("\\", "/"), better: Number(causalSummary.metrics.better), neutral: Number(causalSummary.metrics.neutral), worse: Number(causalSummary.metrics.worse), conclusion: String(causalSummary.conclusion)}} : value).concat(scoped);
const nextRegistry = validateLineupHypothesisRegistry({schemaVersion: 1, activationStatus: "shadow-only", hypotheses}), findings = (baseAudit.findings ?? []).map((value: any) => value.id === parentId ? {...value, observationalCandidate: false, researchEligible: false, causalConclusion: causalSummary.conclusion, nextAction: "Retain as reviewed causal evidence; global activation rejected."} : value);
findings.push({id, title, registeredStage: scoped.stage, auditStage: scoped.stage, observationalCandidate: false, researchEligible: true, evidenceStatus: "post-hoc-scope-frozen-for-future-causal-validation", parentHypothesisId: parentId, discoveryFinalSeason, nextAction: "Use only seasons after discoveryFinalSeason for a new manager-unique causal study."});
fs.mkdirSync(out, {recursive: true}); write(path.join(out, "scoped-registry.json"), nextRegistry); write(path.join(out, "scoped-audit.json"), {...baseAudit, activationStatus: "shadow-only", findings});
const freeze = {schemaVersion: 1, activationStatus: "shadow-only", hypothesisId: id, parentHypothesisId: parentId, applicability, discoveryFinalSeason, discovery: {heterogeneity: fingerprint(heterogeneityFile), causalSummary: fingerprint(causalSummaryFile), causalManifest: fingerprint(causalManifestFile)}, selectedEvidence: proposal, nextEvidenceRule: {minimumFirstSeason: discoveryFinalSeason + 1, requiredCases: 24, requiredManagers: 20}};
write(path.join(out, "scope-freeze.json"), freeze); console.log(JSON.stringify({status: "frozen", ...freeze, registry: path.join(out, "scoped-registry.json"), audit: path.join(out, "scoped-audit.json")}, null, 2));
function required(name: string): string { const value = option(name, ""); if (!value) throw new Error(`${name} is required`); return value; }
function option(name: string, fallback: string): string { const index = args.indexOf(name); return index >= 0 ? args[index + 1] ?? fallback : fallback; }
function read<T>(file: string): T { return JSON.parse(fs.readFileSync(file, "utf8")) as T; }
function write(file: string, value: unknown): void { const temporary = `${file}.${process.pid}.tmp`; fs.writeFileSync(temporary, `${JSON.stringify(value, null, 2)}\n`, "utf8"); fs.renameSync(temporary, file); }
function hash(file: string): string { return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); }
function fingerprint(file: string): {file: string; sha256: string; bytes: number} { return {file: path.relative(root, file).replaceAll("\\", "/"), sha256: hash(file), bytes: fs.statSync(file).size}; }
