import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {AI_VERSION} from "../showdown/choice";
import {buildEvidenceEpoch} from "../showdown/evidenceEpoch";

const args=process.argv.slice(2),discoveryFile=path.resolve(required("--discovery")),planFile=path.resolve(required("--plan")),out=path.resolve(required("--out")),discovery=read<any>(discoveryFile),plan=read<any>(planFile);
if(discovery.schemaVersion!==1||discovery.activationStatus!=="shadow-only"||discovery.evidenceStatus!=="manager-selected-research-only"||discovery.authority!=="no-activation-authority"||discovery.status!=="complete")throw new Error("Invalid battle frontier discovery result");
if(plan.schemaVersion!==1||plan.evidenceStatus!=="manager-selected-research-only"||plan.authority!=="no-activation-authority")throw new Error("Invalid battle frontier discovery plan");
const currentPolicySha256=buildEvidenceEpoch(AI_VERSION,"gen9ou").policySha256;if(plan.executionStatus!=="ready"||plan.evidenceEpoch?.policySha256!==currentPolicySha256||Number(plan.evidenceEpoch?.blockedCases)!==0||discovery.evidenceEpoch?.policySha256!==currentPolicySha256)throw new Error("Battle frontier discovery is outside the current evidence epoch");
const candidates=(discovery.byMechanism??[]).filter((value:any)=>Number(value.better)>=2&&Number(value.worse)===0);if(candidates.length!==1)throw new Error(`Expected exactly one discovery mechanism for holdout, found ${candidates.length}`);
const mechanismId=String(candidates[0].mechanismId),discoveryItems=(plan.items??[]).filter((value:any)=>value.status==="ready"&&value.mechanismId===mechanismId),excludedReplayHashes=[...new Set(discoveryItems.map((value:any)=>String(value.replaySha256)))].sort();
const freeze={schemaVersion:1,activationStatus:"shadow-only",evidenceStatus:"prospective-independent-holdout",authority:"no-activation-authority",evidenceEpoch:{policySha256:currentPolicySha256,formalActivationAllowed:true},frozenAt:new Date().toISOString(),mechanismId,discovery:{result:path.relative(process.cwd(),discoveryFile).replaceAll("\\","/"),resultSha256:shaFile(discoveryFile),plan:path.relative(process.cwd(),planFile).replaceAll("\\","/"),planSha256:shaFile(planFile),cases:Number(candidates[0].cases),better:Number(candidates[0].better),neutral:Number(candidates[0].neutral),worse:Number(candidates[0].worse)},exclusions:{replayInputSha256:excludedReplayHashes,discoveryManagers:[...new Set(discoveryItems.map((value:any)=>String(value.managerId)))].sort()},sampling:{targetCases:30,minimumIndependentBattleSeeds:10,maximumCasesPerBattleSeed:1,selection:"manager-chosen-mechanism; minimum rational cost among prospectively generated legal reasonable alternatives",stopOnFirstTechnicalFailure:true},successGate:{minimumOutcomeChangingPairs:10,minimumDirectionalSeedClusters:5,maximumOneSidedImprovementP:0.1,requireBetterThanWorse:true,zeroRuleErrors:true,zeroSourceDrift:true,zeroPrefixDrift:true},failureRules:["Any source or prefix drift blocks the holdout.","A formal-size batch with no outcome changes rejects the mechanism.","Insufficient opportunity coverage remains inconclusive and does not relax the gate.","Discovery cases cannot contribute to holdout statistics.","Every holdout source must have a signed expansion completion after frozenAt."],sha256:""};freeze.sha256=sha(Buffer.from(canonical({...freeze,sha256:undefined})));
fs.mkdirSync(out,{recursive:true});write(path.join(out,"battle-frontier-holdout-freeze.json"),freeze);write(path.join(out,"summary.json"),{schemaVersion:1,activationStatus:"shadow-only",mechanismId,targetCases:freeze.sampling.targetCases,minimumIndependentBattleSeeds:freeze.sampling.minimumIndependentBattleSeeds,excludedDiscoveryCases:discoveryItems.length,sha256:freeze.sha256,estimatedTokens:Math.ceil(Buffer.byteLength(JSON.stringify({mechanismId,targetCases:30,minimumIndependentBattleSeeds:10,excludedDiscoveryCases:discoveryItems.length}))/4)});console.log(JSON.stringify({mechanismId,targetCases:30,minimumIndependentBattleSeeds:10,excludedDiscoveryCases:discoveryItems.length,sha256:freeze.sha256,out},null,2));
function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}function shaFile(file:string):string{return sha(fs.readFileSync(file));}function sha(bytes:Buffer):string{return crypto.createHash("sha256").update(bytes).digest("hex");}
function canonical(value:unknown):string{if(value===undefined)return"undefined";if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object"){const record=value as Record<string,unknown>;return`{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`;}return JSON.stringify(value);}
function write(file:string,value:unknown):void{const temporary=`${file}.${process.pid}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,"utf8");fs.renameSync(temporary,file);}function required(name:string):string{const value=option(name,"");if(!value)throw new Error(`Missing ${name}`);return value;}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?String(args[index+1]??fallback):fallback;}
