import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type {BattleInput} from "../showdown/battle";
import {loadTeam} from "../showdown/team";
import {validateRegistryDirectory} from "../draft/registrySnapshot";
import {LEAGUE_CONFIGURATION_POLICY_VERSION, sha256} from "../showdown/evidenceEpoch";
import {acquireNamedRunLock} from "../draft/runLock";
import {recommendedBattleWorkers, runBattleWorkerPoolSettled} from "../draft/battleWorkerPool";
import {BENCHMARK_FAMILY_VERSION, signBattleFamilyEvidence, verifyBattleFamilyEvidence, verifyFamilyRegistry, verifyFamilySchedule, type BenchmarkBattleEvidence, type BenchmarkFamilyRegistry, type BenchmarkFamilySchedule} from "../draft/benchmarkFamilies";

interface BenchmarkIndex {id: string; format: string; familyRegistry?: string; schedule?: string; authority?: string; benchmarks: Array<{id: string; team: string; archetype?: string; familyId?: string; split?: string; environment?: string}>}
interface TeamDefinition {id: string; familyId: string; archetype?: string; split?: string; environment?: string; variants: Array<{id: string; packed: string; sha256: string}>}
interface PairDefinition {id: string; split?: "train" | "validation" | "test" | "holdout"; leftFamilyId: string; rightFamilyId: string}
interface CorpusDesign {teams: TeamDefinition[]; pairs: PairDefinition[]; registry?: BenchmarkFamilyRegistry; schedule?: BenchmarkFamilySchedule; authority?: "research" | "formal-holdout-only"; root: string}

const args = process.argv.slice(2), indexFile = path.resolve(option("--index", "benchmarks/gen9expanded/index.json")), out = path.resolve(option("--out", "output/tooling/position-value-corpus-v1"));
const concurrency = integer("--concurrency", recommendedBattleWorkers(90), 1, 64), maxTurns = integer("--max-turns", 80, 10, 500), managerCount = integer("--manager-count", 0, 0, 30), registry = path.resolve(option("--registry", "data/draft"));

async function main(): Promise<void> {
  const started = Date.now(); fs.mkdirSync(out, {recursive: true}); const lock = acquireNamedRunLock(out, ".position-corpus.lock", {indexFile, concurrency});
  try {
    const index = JSON.parse(fs.readFileSync(indexFile, "utf8")) as BenchmarkIndex, design = loadDesign(index), seeds = args.includes("--seeds") ? integer("--seeds", 2, 1, 20) : design.schedule?.settings.seeds ?? 2, seedStart = integer("--seed-start", 1, 1, 10000), registrySnapshot = validateRegistryDirectory(registry), profilePool: ReadonlyArray<Record<string, string | number>> = managerCount ? Array.from({length: managerCount}, (_, index) => ({id: `manager-${String(index + 1).padStart(2, "0")}`})) : profiles, teamById = new Map(design.teams.map(team => [team.familyId, team]));
    const jobs: Array<{id: string; pair: PairDefinition; seed: number; orientation: number; directory: string; familyIds: [string, string]; variantIds: [string, string]; packed: [string, string]}> = [];
    for (const pair of design.pairs) for (let seed = seedStart; seed < seedStart + seeds; seed += 1) for (let orientation = 0; orientation < 2; orientation += 1) {
      const left = requiredTeam(teamById, pair.leftFamilyId), right = requiredTeam(teamById, pair.rightFamilyId), leftVariant = selectVariant(left, pair.id, seed, orientation), rightVariant = selectVariant(right, pair.id, seed, orientation + 7), ordered = orientation ? [[right, rightVariant], [left, leftVariant]] as const : [[left, leftVariant], [right, rightVariant]] as const, id = `${pair.id}--s${seed}--o${orientation + 1}`, directory = design.schedule ? path.join(out, "battles", pair.split!, pair.id, `seed-${String(seed).padStart(2, "0")}`, orientation ? "right-p1" : "left-p1") : path.join(out, "battles", pair.id, `seed-${String(seed).padStart(2, "0")}`, orientation ? "right-p1" : "left-p1");
      jobs.push({id, pair, seed, orientation, directory, familyIds: [ordered[0][0].familyId, ordered[1][0].familyId], variantIds: [ordered[0][1].id, ordered[1][1].id], packed: [ordered[0][1].packed, ordered[1][1].packed]});
    }
    const results: Array<{id: string; status: "generated" | "reused"; winner?: string | null; turns?: number}> = [], failures: Array<{id: string; message: string}> = [], pending: Array<{job: typeof jobs[number]; input: BattleInput}> = [];
    for (const job of jobs) {
      const game = path.join(job.directory, "game-0001"); fs.mkdirSync(game, {recursive: true}); if (design.registry) writeEvidence(game, job, design, teamById);
      const required = ["replay-input.json", "ai-decisions.json", "end.json", ...(design.registry ? ["benchmark-evidence.json"] : [])], existing = required.every(file => fs.existsSync(path.join(game, file)));
      if (existing) { results.push({id: job.id, status: "reused"}); continue; }
      const profileIndex = hashInt(`${job.id}:p1`) % profilePool.length, opponentIndex = hashInt(`${job.id}:p2`) % profilePool.length, profile = profilePool[profileIndex], opponentProfile = profilePool[opponentIndex === profileIndex ? (opponentIndex + 1) % profilePool.length : opponentIndex];
      pending.push({job, input: {format: index.format, teamA: job.packed[0], teamB: job.packed[1], seed: `position-value:${index.id}:${job.id}`, gameIndex: 0, outDir: job.directory, maxTurns, idleTimeoutMs: 10000, wallClockTimeoutMs: 60000, ai: "search", openTeamSheets: true, traceAiDecisions: true, artifactMode: "full", aiProfiles: {p1: profile, p2: opponentProfile}, evidenceContext: {registryHash: registrySnapshot.hash, configurationPolicyVersion: LEAGUE_CONFIGURATION_POLICY_VERSION}}});
    }
    let completed = results.length; const outcomes = await runBattleWorkerPoolSettled(pending.map(value => value.input), concurrency, {onComplete: () => { completed += 1; if (completed % Math.max(1, concurrency) === 0 || completed === jobs.length) atomic(path.join(out, "run-state.json"), {schemaVersion: 1, status: "running", completed, total: jobs.length, workers: concurrency, elapsedMs: Date.now() - started}); }});
    for (let index = 0; index < outcomes.length; index += 1) { const outcome = outcomes[index], job = pending[index].job; if (outcome.ok) results.push({id: job.id, status: "generated", winner: outcome.result.winner, turns: outcome.result.turns}); else failures.push({id: job.id, message: outcome.error}); }
    const evidenceIndex = design.registry ? buildEvidenceIndex(jobs, out) : [];
    const manifestCore = {schemaVersion: 1, corpusVersion: design.registry ? "position-value-family-corpus-v3-case-index" : "position-value-corpus-v1", index: {file: indexFile, id: index.id, format: index.format, authority: index.authority ?? null, teams: design.teams.map(team => ({id: team.id, familyId: team.familyId, split: team.split ?? null, environment: team.environment ?? null, archetype: team.archetype ?? null, variants: team.variants.map(variant => ({id: variant.id, teamSha256: variant.sha256}))}))}, familyDesign: design.registry ? {version: BENCHMARK_FAMILY_VERSION, registrySha256: design.registry.sha256, scheduleSha256: design.schedule?.sha256 ?? formalPairingSha(design), independentFamilies: design.teams.length, independentPairs: design.pairs.length, splitAuthority: design.authority, repetitionUnit: "seed-and-orientation"} : null, evidenceIndex, registry: {source: registry, hash: registrySnapshot.hash}, configurationPolicyVersion: LEAGUE_CONFIGURATION_POLICY_VERSION, settings: {seeds, seedStart, orientations: 2, maxTurns, jobs: jobs.length, workers: concurrency, execution: "persistent-battle-worker-pool", managerCount, managerInitialization: managerCount ? "neutral-identities" : "fixture-profiles"}, results: {complete: results.length, generated: results.filter(result => result.status === "generated").length, reused: results.filter(result => result.status === "reused").length, failures: failures.length}, elapsedMs: Date.now() - started};
    const manifest = {...manifestCore, sha256: sha256(manifestCore)}; atomic(path.join(out, "corpus-manifest.json"), manifest); atomic(path.join(out, "failures.json"), {schemaVersion: 1, failures}); atomic(path.join(out, "run-state.json"), {schemaVersion: 1, status: failures.length ? "failed" : "complete", completed: results.length, total: jobs.length, workers: concurrency, elapsedMs: Date.now() - started, failures: failures.length}); console.log(JSON.stringify(args.includes("--verbose") ? manifest : {status: failures.length ? "failed" : "complete", corpusVersion: manifest.corpusVersion, familyDesign: manifest.familyDesign, settings: manifest.settings, results: manifest.results, elapsedMs: manifest.elapsedMs, peakOutput: path.join(out, "corpus-manifest.json"), sha256: manifest.sha256}, null, 2)); if (failures.length) process.exitCode = 2;
  } finally { lock.release(); }
}

function loadDesign(index: BenchmarkIndex): CorpusDesign {
  const base = path.dirname(indexFile);
  if (index.familyRegistry) {
    const registryFile = path.resolve(base, index.familyRegistry), familyRoot = path.dirname(registryFile), registryValue = JSON.parse(fs.readFileSync(registryFile, "utf8")) as BenchmarkFamilyRegistry; verifyFamilyRegistry(registryValue, familyRoot);
    if (index.schedule) { const scheduleValue = JSON.parse(fs.readFileSync(path.resolve(base, index.schedule), "utf8")) as BenchmarkFamilySchedule; verifyFamilySchedule(scheduleValue, registryValue); if (index.authority !== "research") throw new Error("Scheduled family corpus requires research authority"); const teams = familyTeams(registryValue, familyRoot, family => family.split !== "holdout"); return {teams, pairs: scheduleValue.pairs, registry: registryValue, schedule: scheduleValue, authority: "research", root: familyRoot}; }
    if (index.authority !== "formal-holdout-only") throw new Error("Unscheduled family corpus requires formal-holdout-only authority"); const teams = familyTeams(registryValue, familyRoot, family => family.split === "holdout"), pairs: PairDefinition[] = []; for (let left = 0; left < teams.length; left += 1) for (let right = left + 1; right < teams.length; right += 1) pairs.push({id: `holdout-${[teams[left].id, teams[right].id].sort().join("--")}`, split: "holdout", leftFamilyId: teams[left].familyId, rightFamilyId: teams[right].familyId}); return {teams, pairs, registry: registryValue, authority: "formal-holdout-only", root: familyRoot};
  }
  const teams = index.benchmarks.map(entry => { const loaded = loadTeam(path.join(base, entry.team)); return {id: entry.id, familyId: entry.familyId ?? entry.id, archetype: entry.archetype, split: entry.split, environment: entry.environment, variants: [{id: "base", packed: loaded.packed, sha256: sha256(loaded.packed)}]}; }), pairs: PairDefinition[] = [];
  for (let left = 0; left < teams.length; left += 1) for (let right = left + 1; right < teams.length; right += 1) pairs.push({id: `${teams[left].id}--${teams[right].id}`, leftFamilyId: teams[left].familyId, rightFamilyId: teams[right].familyId}); return {teams, pairs, root: base};
}
function writeEvidence(game: string, job: {pair: PairDefinition; familyIds: [string, string]; variantIds: [string, string]}, design: CorpusDesign, teams: Map<string, TeamDefinition>): void { const left = requiredTeam(teams, job.familyIds[0]), right = requiredTeam(teams, job.familyIds[1]), value = signBattleFamilyEvidence({schemaVersion: 1, version: BENCHMARK_FAMILY_VERSION, registrySha256: design.registry!.sha256, scheduleSha256: design.schedule?.sha256 ?? formalPairingSha(design), pairClusterId: `${job.pair.split}:${job.pair.id}`, split: job.pair.split!, authority: design.authority, familyIds: job.familyIds, environment: [left.environment, right.environment].sort().join("+"), variants: job.variantIds}); atomic(path.join(game, "benchmark-evidence.json"), value); }
function buildEvidenceIndex(jobs: Array<{id: string; directory: string}>, root: string): Array<{id: string; game: string; evidenceSha256: string; replaySha256: string; decisionsSha256: string; endSha256: string; pairClusterId: string}> { return jobs.flatMap(job => { const game = path.join(job.directory, "game-0001"), evidenceFile = path.join(game, "benchmark-evidence.json"), replay = path.join(game, "replay-input.json"), decisions = path.join(game, "ai-decisions.json"), end = path.join(game, "end.json"); if (![evidenceFile, replay, decisions, end].every(fs.existsSync)) return []; const evidence = JSON.parse(fs.readFileSync(evidenceFile, "utf8")) as BenchmarkBattleEvidence; verifyBattleFamilyEvidence(evidence); return [{id: job.id, game: path.relative(root, game).replaceAll("\\", "/"), evidenceSha256: shaFile(evidenceFile), replaySha256: shaFile(replay), decisionsSha256: shaFile(decisions), endSha256: shaFile(end), pairClusterId: evidence.pairClusterId}]; }).sort((left, right) => left.id.localeCompare(right.id)); }
function familyTeams(registryValue: BenchmarkFamilyRegistry, familyRoot: string, include: (family: BenchmarkFamilyRegistry["families"][number]) => boolean): TeamDefinition[] { return registryValue.families.filter(include).map(family => ({id: family.id, familyId: family.id, archetype: family.archetype, split: family.split, environment: family.environment, variants: family.variants.map(variant => ({id: variant.id, packed: loadTeam(path.join(familyRoot, ...variant.team.split("/"))).packed, sha256: variant.sha256}))})); }
function formalPairingSha(design: CorpusDesign): string { return sha256({authority: design.authority, registrySha256: design.registry?.sha256, pairs: design.pairs}); }
function requiredTeam(teams: Map<string, TeamDefinition>, id: string): TeamDefinition { const value = teams.get(id); if (!value) throw new Error(`Unknown benchmark family: ${id}`); return value; }
function selectVariant(team: TeamDefinition, pairId: string, seed: number, salt: number): TeamDefinition["variants"][number] { return team.variants[hashInt(`${pairId}:${team.familyId}:${seed}:${salt}`) % team.variants.length]; }
const profiles = [{id: "neutral"}, {id: "pressure", aggression: .5, setupBias: .25, expectedWeight: .7, downsideWeight: .2, worstWeight: .1}, {id: "risk-aware", aggression: -.2, recoveryBias: .35, expectedWeight: .4, downsideWeight: .35, worstWeight: .25}, {id: "mobility", pivotBias: .5, switchBias: .25, statusBias: .15}] as const;
function option(name: string, fallback: string): string { const index = args.indexOf(name); return index >= 0 ? args[index + 1] ?? fallback : fallback; }
function integer(name: string, fallback: number, minimum: number, maximum: number): number { const value = Number(option(name, String(fallback))); if (!Number.isInteger(value) || value < minimum || value > maximum) throw new Error(`${name} must be ${minimum}..${maximum}`); return value; }
function hashInt(value: string): number { return Number.parseInt(crypto.createHash("sha256").update(value).digest("hex").slice(0, 12), 16); }
function shaFile(file: string): string { return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); }
function atomic(file: string, value: unknown): void { const temporary = `${file}.${process.pid}.tmp`; fs.mkdirSync(path.dirname(file), {recursive: true}); fs.writeFileSync(temporary, `${JSON.stringify(value, null, 2)}\n`, "utf8"); fs.renameSync(temporary, file); }
main().catch(error => { console.error(error); process.exitCode = 1; });
