import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import crypto from "node:crypto";
import {incubateProspectiveLineupFeatures} from "../ai/whiteBox/prospectiveLineupIncubator";
import {validateLineupHypothesisRegistry, type LineupHypothesisObservation, type LineupHypothesisRegistry} from "../ai/whiteBox/lineupHypothesisWorkbench";

const args = process.argv.slice(2), root = process.cwd();
const source = path.resolve(option("--source", "output/tooling/shadow-lineup-representation-v3-efficiency/lineup-representation-study-samples.json.gz"));
const registryFile = path.resolve(option("--registry", "data/lineup-audit-hypotheses.json"));
const out = path.resolve(option("--out", "output/tooling/prospective-lineup-incubator"));
const permutations = integerOption("--permutations", 10000, 100, 100000);
const archive = JSON.parse(zlib.gunzipSync(fs.readFileSync(source)).toString("utf8")), registry = validateLineupHypothesisRegistry(read<LineupHypothesisRegistry>(registryFile));
const observations: LineupHypothesisObservation[] = (archive.rows ?? []).map((row: any) => { const selected = (row.candidates ?? []).find((candidate: any) => String(candidate.id) === String(row.comparison?.incumbent)); if (!selected?.diagnostics) throw new Error(`Selected lineup diagnostics missing: ${row.season}/${row.managerId}/${row.seriesId}`); return {seriesId: String(row.seriesId), season: Number(row.season), managerId: String(row.managerId), outcome: row.outcome, diagnostics: selected.diagnostics}; });
const result = incubateProspectiveLineupFeatures(observations, registry.hypotheses, permutations), provenance = {source: path.relative(root, source), sourceSha256: hash(source), registry: path.relative(root, registryFile), registrySha256: hash(registryFile)}, compact = {conclusion: result.conclusion, activationStatus: result.activationStatus, discoverySeasons: result.discoverySeasons, validationSeason: result.validationSeason, metrics: result.metrics, featureCandidates: result.findings.filter(value => value.promoted).map(value => ({feature: value.feature, direction: value.direction, registered: value.registered, discoveryEffect: value.discoveryEffect, validationEffect: value.validationEffect, validationMeanDelta: value.validationMeanDelta, q: value.adjustedQ})), programCandidates: result.programs.filter(value => value.promoted).map(value => ({id: value.id, factors: value.factors, registered: value.registered, discoveryEffect: value.discoveryEffect, validationEffect: value.validationEffect, validationMeanDelta: value.validationMeanDelta, referenceFeature: value.referenceFeature, incrementalValidationEffect: value.incrementalValidationEffect, q: value.adjustedQ, incrementalQ: value.adjustedIncrementalQ})), promotedHypotheses: result.promotedHypotheses, provenance};
fs.mkdirSync(out, {recursive: true}); write(path.join(out, "prospective-lineup-incubator.json"), {...result, provenance}); write(path.join(out, "summary.json"), compact); fs.writeFileSync(path.join(out, "prospective-lineup-incubator.md"), markdown(result), "utf8"); write(path.join(out, "token-budget.json"), {summaryBytes: Buffer.byteLength(JSON.stringify(compact)), estimatedSummaryTokens: Math.ceil(Buffer.byteLength(JSON.stringify(compact)) / 3.5), fullAuditBytes: fs.statSync(path.join(out, "prospective-lineup-incubator.json")).size}); console.log(JSON.stringify(compact, null, 2));

function markdown(value: ReturnType<typeof incubateProspectiveLineupFeatures>): string { return ["# Prospective Lineup Incubator", "", `- Conclusion: ${value.conclusion}`, `- Activation: ${value.activationStatus}`, `- Discovery seasons: ${value.discoverySeasons.join(", ")}`, `- Validation season: ${value.validationSeason}`, `- Features/programs: ${value.metrics.features}/${value.metrics.programs}`, `- Promoted features/programs/novel: ${value.metrics.promotedFeatures}/${value.metrics.promotedPrograms}/${value.metrics.novelPromoted}`, "", "## Single features", "", "| Feature | Direction | Discovery | Validation | Aligned | p | q | Registered | Promoted |", "|---|---|---:|---:|---:|---:|---:|---|---|", ...value.findings.map(item => `| ${item.feature} | ${item.direction} | ${item.discoveryEffect} | ${item.validationEffect} | ${(item.validationWinnerAlignedRate * 100).toFixed(1)}% | ${item.validationP} | ${item.adjustedQ} | ${item.registered} | ${item.promoted} |`), "", "## Two-factor programs", "", "| Program | Discovery | Validation | Reference | Incremental | q | Incremental q | Registered | Promoted |", "|---|---:|---:|---|---:|---:|---:|---|---|", ...value.programs.map(item => `| ${item.id} | ${item.discoveryEffect} | ${item.validationEffect} | ${item.referenceFeature} | ${item.incrementalValidationEffect} | ${item.adjustedQ} | ${item.adjustedIncrementalQ} | ${item.registered} | ${item.promoted} |`), "", "Directions, scaling, and each program's reference constituent are frozen in the discovery seasons. Programs must significantly improve on that constituent in the held-out season after multiple-comparison correction. Promotion creates only a shadow causal question; it never changes lineup weights or manager preferences.", ""].join("\n"); }
function read<T>(file: string): T { return JSON.parse(fs.readFileSync(file, "utf8")) as T; }
function write(file: string, value: unknown): void { fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, "utf8"); }
function hash(file: string): string { return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); }
function option(name: string, fallback: string): string { const index = args.indexOf(name); return index >= 0 ? args[index + 1] ?? fallback : fallback; }
function integerOption(name: string, fallback: number, minimum: number, maximum: number): number { const value = Number(option(name, String(fallback))); if (!Number.isInteger(value) || value < minimum || value > maximum) throw new Error(`${name} must be ${minimum}..${maximum}`); return value; }
