import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import {buildLineupHypothesisCausalPlan, validateLineupHypothesisRegistry, type LineupHypothesisCandidateRow, type LineupHypothesisRegistry, type ManagerExperimentEvidence} from "../ai/whiteBox/lineupHypothesisWorkbench";
import {validateManagerMechanismLedger, type ManagerMechanismLedger} from "../ai/managerMechanismLedger";
import {validateManagerResearchAgenda, type ManagerResearchAgenda} from "../ai/managerResearchAgenda";

const args = process.argv.slice(2), root = process.cwd();
const source = path.resolve(option("--source", "output/tooling/shadow-lineup-representation-v3-efficiency/lineup-representation-study-samples.json.gz"));
const registryFile = path.resolve(option("--registry", "data/lineup-audit-hypotheses.json"));
const auditFile = path.resolve(option("--audit", "output/tooling/shadow-lineup-hypotheses/lineup-hypothesis-audit.json"));
const personalReplication = args.includes("--personal-replication"), hypothesisId = option("--hypothesis", "lineup-role-compression-v1"), requested = integerOption("--requested", 24, personalReplication ? 1 : 6, 30, !personalReplication), minimumScoreDelta = numberOption("--minimum-score-delta", .02, .001, .5);
const maximumResearchRank = integerOption("--maximum-research-rank", 0, 0, 63, false);
const out = path.resolve(option("--out", `output/tooling/shadow-lineup-hypotheses/plans/${hypothesisId}`));
const mechanismLedgerFile = path.resolve(option("--mechanism-ledgers", "output/tooling/manager-mechanism-ledgers/manager-mechanism-ledgers.json.gz"));
const researchAgendaFile = path.resolve(option("--research-agendas", "output/tooling/manager-research-agendas/research-agendas.json.gz"));
const importRegistryFile = path.resolve(option("--import-registry", "output/tooling/manager-mechanism-ledgers/import-registry.json"));
const registry = validateLineupHypothesisRegistry(read<LineupHypothesisRegistry>(registryFile)), hypothesis = registry.hypotheses.find(entry => entry.id === hypothesisId);
if (!hypothesis) throw new Error(`Unknown lineup hypothesis: ${hypothesisId}`);
const audit = read<any>(auditFile), finding = audit.findings?.find((entry: any) => entry.id === hypothesisId);
if (!finding?.observationalCandidate && !(personalReplication && hypothesis.stage === "causal-complete")) throw new Error(`Hypothesis has not passed observational screening: ${hypothesisId}`);
const archive = JSON.parse(zlib.gunzipSync(fs.readFileSync(source)).toString("utf8"));
const rows: LineupHypothesisCandidateRow[] = (archive.rows ?? []).map((row: any) => ({season: Number(row.season), managerId: String(row.managerId), seriesId: String(row.seriesId), outcome: row.outcome, incumbentId: String(row.comparison?.incumbent ?? ""), candidates: (row.candidates ?? []).map((candidate: any) => ({id: String(candidate.id), diagnostics: candidate.diagnostics}))}));
const managerEvidence = args.includes("--ignore-personal-evidence") || !fs.existsSync(mechanismLedgerFile) ? undefined : loadManagerEvidence(mechanismLedgerFile, hypothesisId, fs.existsSync(researchAgendaFile) ? researchAgendaFile : undefined, fs.existsSync(importRegistryFile) ? importRegistryFile : undefined);
const plan = buildLineupHypothesisCausalPlan(rows, hypothesis, requested, minimumScoreDelta, managerEvidence, {allowReviewedReplication: personalReplication, maximumResearchPreferenceRank: maximumResearchRank});
fs.mkdirSync(out, {recursive: true}); write(path.join(out, "causal-plan.json"), {...plan, source: path.relative(root, source), registry: path.relative(root, registryFile), audit: path.relative(root, auditFile), personalEvidence: managerEvidence ? {archive: path.relative(root, mechanismLedgerFile), sha256: crypto.createHash("sha256").update(fs.readFileSync(mechanismLedgerFile)).digest("hex"), researchAgendas: fs.existsSync(researchAgendaFile) ? {archive: path.relative(root, researchAgendaFile), sha256: crypto.createHash("sha256").update(fs.readFileSync(researchAgendaFile)).digest("hex")} : null, priorExperiments: fs.existsSync(importRegistryFile) ? {archive: path.relative(root, importRegistryFile), sha256: crypto.createHash("sha256").update(fs.readFileSync(importRegistryFile)).digest("hex")} : null} : null});
fs.writeFileSync(path.join(out, "causal-plan.md"), `# ${hypothesis.title} causal plan\n\n- Hypothesis: \`${hypothesis.id}\`\n- Activation: ${plan.activationStatus}\n- Opportunity policy: ${plan.opportunityPolicy}\n- Selected / eligible choices: ${plan.selected.length} / ${plan.availableChoices}\n- Independent managers: ${plan.coverage.managers}\n- Seasons: ${Object.entries(plan.coverage.seasons).map(([season, count]) => `S${season}=${count}`).join(", ")}\n- Source wins / losses: ${plan.coverage.sourceOutcomes.win} / ${plan.coverage.sourceOutcomes.loss}\n- First-choice research requests selected: ${plan.opportunityCoverage?.selectedFirstChoiceRequests}\n- Managers without prior mechanism evidence: ${plan.opportunityCoverage?.selectedWithoutMechanismEvidence}\n- Prior total attempts among selected: ${plan.opportunityCoverage?.selectedPriorTotalAttempts.minimum}/${plan.opportunityCoverage?.selectedPriorTotalAttempts.mean}/${plan.opportunityCoverage?.selectedPriorTotalAttempts.maximum} min/mean/max\n- Minimum composite-score delta: ${plan.minimumScoreDelta}\n- Guardrails: ${hypothesis.guardrails.map(guardrail => `${guardrail.feature}[${guardrail.minimumDelta ?? "-inf"},${guardrail.maximumDelta ?? "+inf"}]`).join(", ")}\n\nThis is a predeclared shadow experiment plan. Manager research preference affects opportunity allocation only; it does not activate a lineup preference or select by expected battle outcome.\n`, "utf8");
console.log(JSON.stringify({hypothesis: plan.hypothesisId, causalScope: plan.causalScope, selected: plan.selected.length, availableChoices: plan.availableChoices, availableManagers: plan.availableManagers, coverage: plan.coverage, opportunityPolicy: plan.opportunityPolicy, opportunityCoverage: plan.opportunityCoverage, activationStatus: plan.activationStatus, plan: path.join(out, "causal-plan.json")}, null, 2));
function loadManagerEvidence(file: string, mechanismId: string, agendaFile?: string, importFile?: string): Map<string, ManagerExperimentEvidence> { const values = JSON.parse(zlib.gunzipSync(fs.readFileSync(file)).toString("utf8")) as ManagerMechanismLedger[], result = new Map<string, ManagerExperimentEvidence>(), agendas = agendaFile ? JSON.parse(zlib.gunzipSync(fs.readFileSync(agendaFile)).toString("utf8")) as ManagerResearchAgenda[] : []; if (!Array.isArray(values) || !Array.isArray(agendas)) throw new Error("Invalid manager mechanism or research agenda archive"); for (const agenda of agendas) validateManagerResearchAgenda(agenda); const agendaByManager = new Map(agendas.map(value => [value.managerId, value])), priorByManager = new Map<string, string[]>(); if (importFile) { const imports = read<any>(importFile).imports ?? {}; for (const key of Object.keys(imports)) { const prefix = `${mechanismId}:`; if (!key.startsWith(prefix)) continue; const choiceId = key.slice(prefix.length), managerId = choiceId.split(":")[1]; if (!managerId) throw new Error(`Invalid prior experiment id: ${choiceId}`); const ids = priorByManager.get(managerId) ?? []; ids.push(choiceId); priorByManager.set(managerId, ids); } } for (const ledger of values) { validateManagerMechanismLedger(ledger); const agenda = agendaByManager.get(ledger.managerId), preference = agenda?.ranked.findIndex(value => value.mechanismId === mechanismId); result.set(ledger.managerId, {mechanismAttempts: ledger.mechanisms[mechanismId]?.attempts ?? 0, totalAttempts: Object.values(ledger.mechanisms).reduce((sum, entry) => sum + entry.attempts, 0), researchPreferenceRank: preference !== undefined && preference >= 0 ? preference : agendas.length ? 64 : 0, priorChoiceIds: [...new Set(priorByManager.get(ledger.managerId) ?? [])].sort()}); } return result; }
function read<T>(file: string): T { return JSON.parse(fs.readFileSync(file, "utf8")) as T; }
function write(file: string, value: unknown): void { fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, "utf8"); }
function option(name: string, fallback: string): string { const index = args.indexOf(name); return index >= 0 ? args[index + 1] ?? fallback : fallback; }
function integerOption(name: string, fallback: number, minimum: number, maximum: number, multipleOfSix = true): number { const value = Number(option(name, String(fallback))); if (!Number.isInteger(value) || value < minimum || value > maximum || (multipleOfSix && value % 6 !== 0)) throw new Error(`${name} must be ${multipleOfSix ? "a multiple of six " : "an integer "}within ${minimum}..${maximum}`); return value; }
function numberOption(name: string, fallback: number, minimum: number, maximum: number): number { const value = Number(option(name, String(fallback))); if (!Number.isFinite(value) || value < minimum || value > maximum) throw new Error(`${name} must be ${minimum}..${maximum}`); return value; }
