import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import {classifyReplayEvidence} from "../draft/evidenceEpochAudit";
import {AI_VERSION} from "../showdown/choice";
import {buildEvidenceEpoch} from "../showdown/evidenceEpoch";

const args=process.argv.slice(2),source=path.resolve(required("--source")),frontierFile=path.resolve(required("--frontier")),freezeFile=path.resolve(required("--freeze")),out=path.resolve(required("--out")),frontier=read<any>(frontierFile),freeze=read<any>(freezeFile);
if(frontier.schemaVersion!==1||frontier.activationStatus!=="shadow-only"||frontier.evidenceStatus!=="observational-candidate-frontier")throw new Error("Invalid prospective battle frontier");
if(freeze.schemaVersion!==1||freeze.activationStatus!=="shadow-only"||freeze.evidenceStatus!=="prospective-independent-holdout"||freeze.authority!=="no-activation-authority"||!Number.isFinite(Date.parse(freeze.frozenAt)))throw new Error("Invalid battle frontier holdout freeze");
const currentPolicySha256=buildEvidenceEpoch(AI_VERSION,"gen9ou").policySha256;
const mechanismId=String(freeze.mechanismId),mechanism=mechanismId.replace(/^battle-frontier-/,"").replace(/-v1$/,"") ,managerIds=[...(freeze.exclusions?.discoveryManagers??[])].map(String).sort(),target=Number(freeze.sampling?.targetCases),excluded=new Set<string>(freeze.exclusions?.replayInputSha256??[]),rows=new Map<string,any[]>((frontier.managerMechanisms??[]).filter((value:any)=>value.mechanism===mechanism).map((value:any)=>[String(value.managerId),value.examples??[]]));
if(!Number.isInteger(target)||target<1||!managerIds.length)throw new Error("Invalid frozen holdout sampling rules");
const selected:any[]=[],used=new Set<string>(),indices=new Map(managerIds.map(value=>[value,0]));let progress=true;
while(selected.length<target&&progress){progress=false;for(const managerId of managerIds){const examples:any[]=rows.get(managerId)??[];let index=indices.get(managerId)??0;while(index<examples.length){const example=examples[index++],game=path.resolve(source,String(example.game)),replayFile=path.join(game,"replay-input.json");if(!fs.existsSync(replayFile))continue;const replaySha256=shaFile(replayFile);if(excluded.has(replaySha256)||used.has(replaySha256))continue;const item=freezeItem(managerId,mechanismId,example,game,replaySha256);selected.push(item);used.add(replaySha256);progress=true;break;}indices.set(managerId,index);if(selected.length>=target)break;}}
const epochBlocked=selected.filter(value=>value.evidenceEpoch?.formalActivationAllowed!==true),executionStatus=freeze.evidenceEpoch?.policySha256!==currentPolicySha256||epochBlocked.length?"blocked-evidence-epoch":selected.length===target?"ready":"blocked-insufficient-opportunities",plan={schemaVersion:1,activationStatus:"shadow-only",evidenceStatus:"manager-selected-research-only",holdoutEvidenceStatus:"prospective-independent-holdout",authority:"no-activation-authority",executionStatus,evidenceEpoch:{policySha256:currentPolicySha256,eligibleCases:selected.length-epochBlocked.length,blockedCases:epochBlocked.length},source,freeze:{file:path.relative(process.cwd(),freezeFile).replaceAll("\\","/"),sha256:shaFile(freezeFile),protocolSha256:freeze.sha256},frontier:{file:path.relative(process.cwd(),frontierFile).replaceAll("\\","/"),sha256:shaFile(frontierFile)},selectionPolicy:"frozen-manager-mechanism-round-robin-minimum-rational-cost-one-case-per-battle-seed",ready:selected.length,deferred:target-selected.length,items:selected};
fs.mkdirSync(out,{recursive:true});write(path.join(out,"battle-frontier-holdout-plan.json"),plan);write(path.join(out,"summary.json"),{schemaVersion:1,activationStatus:"shadow-only",executionStatus,targetCases:target,ready:selected.length,deferred:target-selected.length,managers:Object.fromEntries(managerIds.map(id=>[id,selected.filter(value=>value.managerId===id).length])),independentBattleSeeds:used.size,estimatedTokens:Math.ceil(Buffer.byteLength(JSON.stringify({executionStatus,targetCases:target,ready:selected.length,deferred:target-selected.length,independentBattleSeeds:used.size}))/4)});console.log(JSON.stringify({executionStatus,targetCases:target,ready:selected.length,deferred:target-selected.length,managers:Object.fromEntries(managerIds.map(id=>[id,selected.filter(value=>value.managerId===id).length])),independentBattleSeeds:used.size,out},null,2));

function freezeItem(managerId:string,mechanismId:string,example:any,game:string,replaySha256:string):any{const decisionFile=evidenceFile(game,"ai-decisions.json"),traces=read<any[]>(decisionFile),trace=traces.find(value=>Number(value.decisionOrdinal)===Number(example.decisionOrdinal));if(!trace||trace.personalityId!==managerId||trace.selected!==example.selected||!trace.whiteBoxShadow?.trace?.candidates?.some((value:any)=>value.id===example.alternative&&value.eligible!==false&&value.reasonable===true&&value.finalScore!==null))throw new Error(`Prospective frontier example drifted: ${managerId}/${example.game}/${example.decisionOrdinal}`);const provenance=expansionProvenance(game),classified=classifyReplayEvidence(path.join(game,"replay-input.json")),identity={managerId,mechanismId,game:path.relative(process.cwd(),game).replaceAll("\\","/"),decisionOrdinal:Number(example.decisionOrdinal),side:example.side,selected:example.selected,alternative:example.alternative,replaySha256,decisionsSha256:shaFile(decisionFile),provenance,evidenceEpoch:{policySha256:classified.policySha256,contentSha256:classified.contentSha256,compatibility:classified.compatibility,formalActivationAllowed:classified.formalActivationAllowed}};return{...identity,id:sha(Buffer.from(canonical(identity))).slice(0,24),status:"ready",rationalCost:Number(example.rationalCost),styleDelta:Number(example.styleDelta)};}
function expansionProvenance(game:string):any{let directory=game;while(true){const file=path.join(directory,"battle-shadow-expansion-manifest.json");if(fs.existsSync(file)){const manifest=read<any>(file),run=(manifest.runs??[]).find((value:any)=>value.status==="complete"&&path.resolve(String(value.directory))===game),completedAt=String(run?.completedAt??"");if(!run||!Number.isFinite(Date.parse(completedAt))||Date.parse(completedAt)<=Date.parse(freeze.frozenAt))throw new Error(`Holdout source was not generated after the freeze: ${game}`);return{manifest:path.relative(process.cwd(),file).replaceAll("\\","/"),manifestSha256:shaFile(file),runId:String(run.id),completedAt};}const parent=path.dirname(directory);if(parent===directory)break;directory=parent;}throw new Error(`Holdout source lacks an expansion manifest: ${game}`);}
function evidenceFile(directory:string,name:string):string{const plain=path.join(directory,name),gzip=`${plain}.gz`;if(fs.existsSync(plain))return plain;if(fs.existsSync(gzip))return gzip;throw new Error(`Missing ${name}[.gz]: ${directory}`);}function read<T>(file:string):T{const bytes=fs.readFileSync(file),text=file.endsWith(".gz")?zlib.gunzipSync(bytes).toString("utf8"):bytes.toString("utf8");return JSON.parse(text) as T;}
function shaFile(file:string):string{return sha(fs.readFileSync(file));}function sha(bytes:Buffer):string{return crypto.createHash("sha256").update(bytes).digest("hex");}function canonical(value:unknown):string{if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object"){const record=value as Record<string,unknown>;return`{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`;}return JSON.stringify(value);}
function write(file:string,value:unknown):void{const temporary=`${file}.${process.pid}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,"utf8");fs.renameSync(temporary,file);}function required(name:string):string{const value=option(name,"");if(!value)throw new Error(`Missing ${name}`);return value;}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?String(args[index+1]??fallback):fallback;}
