import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {acquireNamedRunLock} from "../draft/runLock";
import {AI_VERSION} from "../showdown/choice";
import {buildEvidenceEpoch, classifyEvidenceEpoch, type EvidenceEpoch} from "../showdown/evidenceEpoch";

type Status="pending"|"running"|"complete"|"failed";
const args=process.argv.slice(2),planFile=path.resolve(required("--plan")),out=path.resolve(required("--out")),maxLaunches=integer("--max-launches",5,1,1000),resume=args.includes("--resume"),plan=read<any>(planFile);
if(plan.schemaVersion!==1||plan.activationStatus!=="shadow-only"||plan.evidenceStatus!=="manager-selected-research-only"||plan.authority!=="no-activation-authority")throw new Error("Invalid battle frontier research plan");
if(plan.executionStatus!=="ready")throw new Error(`Battle frontier plan is not executable: ${plan.executionStatus??"missing-evidence-epoch"}`);
if(plan.evidenceEpoch?.policySha256!==buildEvidenceEpoch(AI_VERSION,"gen9ou").policySha256||Number(plan.evidenceEpoch?.blockedCases)!==0)throw new Error("Battle frontier plan evidence epoch is stale or blocked");
verifyPlanInputs();
fs.mkdirSync(out,{recursive:true});const stateFile=path.join(out,"battle-frontier-run.json"),lock=acquireNamedRunLock(out,".battle-frontier-research.lock",{workflow:"battle-frontier-research",plan:planFile});
let phase="prepare",current:string|null=null;
try{
  const prior=fs.existsSync(stateFile)?read<any>(stateFile):null;if(prior&&!resume&&prior.status!=="complete")throw new Error("Battle frontier run exists; use --resume");
  const priorBy=new Map((prior?.items??[]).map((value:any)=>[value.id,value]));
  const items=(plan.items??[]).filter((value:any)=>value.status==="ready").map((value:any)=>({...value,status:completed(path.join(out,"runs",value.id),value)?"complete":((priorBy.get(value.id) as any)?.status==="failed"?"failed":"pending") as Status}));
  if(items.some((value:any)=>value.status==="failed"))throw new Error("A prior research case failed; inspect state before retrying in a new output directory");
  write(stateFile,snapshot("running",items));let launched=0;
  for(const item of items){if(item.status==="complete")continue;if(launched>=maxLaunches)break;current=item.id;phase=`run:${item.id}`;item.status="running";write(stateFile,snapshot("running",items));
    verifyFrozen(item);const directory=path.join(out,"runs",item.id),result=spawnSync(process.execPath,[require.resolve("tsx/cli"),path.join(process.cwd(),"src/cli/counterfactualWhiteBoxBattle.ts"),"--source-game",path.resolve(item.game),"--out",directory,"--decision-ordinal",String(item.decisionOrdinal),"--research-alternative",String(item.alternative)],{cwd:process.cwd(),encoding:"utf8",maxBuffer:64*1024*1024});
    if(result.status!==0){item.status="failed";write(stateFile,snapshot("failed",items,[diagnostic(result,item.id)]));throw new Error(diagnostic(result,item.id).message);}
    if(!completed(directory,item))throw new Error(`Battle frontier case did not verify: ${item.id}`);item.status="complete";launched+=1;write(stateFile,snapshot("running",items));
  }
  const complete=items.filter((value:any)=>value.status==="complete").length,status=complete===items.length?"complete":"budget-stop";phase=status;current=null;write(stateFile,snapshot(status,items));writeSummary(items,status);console.log(JSON.stringify({status,completed:complete,pending:items.length-complete,launched,total:items.length,out},null,2));
}catch(error){if(fs.existsSync(stateFile)){const state=read<any>(stateFile),memory=process.memoryUsage();write(stateFile,{...state,status:"failed",phase,current,memory:{rss:memory.rss,heapUsed:memory.heapUsed,heapTotal:memory.heapTotal},failures:[...(state.failures??[]),{message:error instanceof Error?error.message:String(error)}],updatedAt:new Date().toISOString()});}throw error;}finally{lock.release();}

function writeSummary(items:any[],status:string):void{const results=items.filter(value=>value.status==="complete").map(value=>{const summary=read<any>(path.join(out,"runs",value.id,"counterfactual-summary.json")),side=summary.intervention.playerId,own=side==="p1"?"Team A":"Team B",left=score(summary.incumbent.winner,own),right=score(summary.whitebox.winner,own),direction=right>left?"better":right<left?"worse":"neutral";return{id:value.id,managerId:value.managerId,mechanismId:value.mechanismId,direction,outcomeChanged:left!==right,season:Number(String(value.game).match(/season-(\d+)/)?.[1]??0),sourceOutcome:left===1?"win":left===0.5?"draw":"loss",rationalCost:Number(value.rationalCost??0)};});
  const metrics={completed:results.length,better:results.filter(value=>value.direction==="better").length,neutral:results.filter(value=>value.direction==="neutral").length,worse:results.filter(value=>value.direction==="worse").length,outcomeChanges:results.filter(value=>value.outcomeChanged).length};
  const byMechanism=[...new Set(results.map(value=>value.mechanismId))].sort().map(mechanismId=>{const rows=results.filter(value=>value.mechanismId===mechanismId);return{mechanismId,cases:rows.length,better:rows.filter(value=>value.direction==="better").length,neutral:rows.filter(value=>value.direction==="neutral").length,worse:rows.filter(value=>value.direction==="worse").length};});
  write(path.join(out,"battle-frontier-summary.json"),{schemaVersion:1,activationStatus:"shadow-only",evidenceStatus:"manager-selected-research-only",authority:"no-activation-authority",status,evidenceEpoch:plan.evidenceEpoch,metrics,byMechanism,results});writeCompatibilityStudies(results);write(path.join(out,"token-budget.json"),{schemaVersion:1,estimatedSummaryTokens:Math.ceil(Buffer.byteLength(JSON.stringify({status,metrics,byMechanism}))/4),detailedCases:results.length});
}
function writeCompatibilityStudies(results:any[]):void{for(const mechanismId of [...new Set(results.map(value=>String(value.mechanismId)))].sort()){const rows=results.filter(value=>value.mechanismId===mechanismId),better=rows.filter(value=>value.direction==="better").length,worse=rows.filter(value=>value.direction==="worse").length,directory=path.join(out,"studies",mechanismId),conclusion=better>=2&&worse===0?"candidate-for-independent-holdout":"personal-results-only";fs.mkdirSync(directory,{recursive:true});write(path.join(directory,"causal-summary.json"),{schemaVersion:1,activationStatus:"shadow-only",hypothesisId:mechanismId,conclusion,completed:rows.length,failed:0,metrics:{cases:rows.length,better,neutral:rows.length-better-worse,worse,games:rows.length,actionDivergences:rows.length,outcomeChanges:rows.filter(value=>value.outcomeChanged).length}});write(path.join(directory,"causal-manifest.json"),{schemaVersion:1,activationStatus:"shadow-only",hypothesisId:mechanismId,items:rows.map(value=>({id:value.id,managerId:value.managerId,season:value.season,status:"complete",sourceOutcome:value.sourceOutcome,scoreDelta:-value.rationalCost,result:{direction:value.direction,causal:{games:1,actionDivergences:1,outcomeChanges:value.outcomeChanged?1:0}}}))});}}
function verifyFrozen(item:any):void{const game=path.resolve(item.game),replay=path.join(game,"replay-input.json"),decisions=fs.existsSync(path.join(game,"ai-decisions.json"))?path.join(game,"ai-decisions.json"):path.join(game,"ai-decisions.json.gz");if(shaFile(replay)!==item.replaySha256||shaFile(decisions)!==item.decisionsSha256)throw new Error(`Frozen battle source drifted: ${item.id}`);const capsule=read<any>(replay),epoch=capsule?.input?.evidenceEpoch as EvidenceEpoch|undefined,expected=epoch?buildEvidenceEpoch(AI_VERSION,epoch.content.format,{registryHash:epoch.content.registryHash,configurationPolicyVersion:epoch.content.configurationPolicyVersion}):buildEvidenceEpoch(AI_VERSION,"gen9ou"),classification=classifyEvidenceEpoch(epoch,expected);if(classification.compatibility!=="exact-compatible"||!classification.formalActivationAllowed||epoch?.epochSha256!==item.evidenceEpoch?.epochSha256)throw new Error(`Frozen battle source evidence epoch is not activation-compatible: ${item.id}`);if(plan.holdoutEvidenceStatus==="prospective-independent-holdout"){const provenance=item.provenance,file=path.resolve(String(provenance?.manifest??""));if(!provenance?.manifestSha256||!fs.existsSync(file)||shaFile(file)!==provenance.manifestSha256)throw new Error(`Frozen holdout provenance drifted: ${item.id}`);const manifest=read<any>(file),run=(manifest.runs??[]).find((value:any)=>String(value.id)===provenance.runId);if(!run||run.status!=="complete"||path.resolve(String(run.directory))!==game||String(run.completedAt)!==provenance.completedAt)throw new Error(`Frozen holdout expansion run drifted: ${item.id}`);}}
function verifyPlanInputs():void{const holdout=plan.holdoutEvidenceStatus==="prospective-independent-holdout",inputs=holdout?[plan.frontier,plan.freeze]:[plan.frontier,plan.agendas,...(plan.excludedPlans??[])];for(const input of inputs){if(!input?.file||!input?.sha256)throw new Error("Battle frontier plan input fingerprint is missing");const file=path.resolve(String(input.file));if(!fs.existsSync(file)||shaFile(file)!==input.sha256)throw new Error(`Battle frontier plan input drifted: ${file}`);}}
function completed(directory:string,item:any):boolean{const file=path.join(directory,"counterfactual-summary.json");if(!fs.existsSync(file))return false;const value=read<any>(file);return value.sourceVerified===true&&value.prefixVerified===true&&value.evidenceStatus==="manager-selected-research-only"&&value.activationAllowed===false&&value.intervention?.decisionOrdinal===item.decisionOrdinal&&value.intervention?.selected===item.alternative;}
function snapshot(status:string,items:any[],failures:any[]=[]):any{return{schemaVersion:1,activationStatus:"shadow-only",evidenceStatus:"manager-selected-research-only",status,phase,current,plan:{file:planFile,sha256:shaFile(planFile)},items,failures,updatedAt:new Date().toISOString()};}
function diagnostic(result:ReturnType<typeof spawnSync>,id:string):{caseId:string;message:string}{return{caseId:id,message:`Battle frontier case ${id} failed: status=${result.status??"null"} signal=${result.signal??"none"} spawnError=${result.error?`${result.error.name}: ${result.error.message}`:"none"}\n${String(result.stderr||result.stdout||"<empty child output>")}`};}
function score(winner:string|null,own:string):number{return winner===own?1:winner===null?0.5:0;}
function shaFile(file:string):string{return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");}function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}
function write(file:string,value:unknown):void{fs.mkdirSync(path.dirname(file),{recursive:true});const temporary=`${file}.${process.pid}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,"utf8");fs.renameSync(temporary,file);}
function required(name:string):string{const value=option(name,"");if(!value)throw new Error(`Missing ${name}`);return value;}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?String(args[index+1]??fallback):fallback;}function integer(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`Invalid ${name}`);return value;}
