import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {evaluateWhiteBoxCounterfactualBatch,whiteBoxCounterfactualBatchMarkdown,type WhiteBoxCounterfactualSample} from "../ai/whiteBox/counterfactualBatch";
import {scanWhiteBoxOpportunities,whiteBoxOpportunityMarkdown} from "../ai/whiteBox/opportunity";
import {compactWhiteBoxRun,type WhiteBoxRetentionTrace} from "../ai/whiteBox/retention";
import {whiteBoxProductionEvidenceMinimum,whiteBoxSamplingProgress} from "../ai/whiteBox/sampling";

interface SeedRun {seed:string;status:"no-difference"|"ineligible"|"complete"|"failed";baseline:string;experiment?:string;cases:number;eligibleCases?:number;durationMs:number;retention?:WhiteBoxRetentionTrace[];error?:string}
interface Manifest {schemaVersion:1;config:{targetSamples:number;minimumSeeds:number;maximumOutputMb:number;band:number;styleLimit:number;styleScale:number;requireAssistGate?:true};existing:string[];seeds:SeedRun[]}
const args=process.argv.slice(2),root=process.cwd(),out=path.resolve(option("--out","output/whitebox-lineup-sampler")),targetSamples=integerOption("--target-samples",10,1,100),minimumSeeds=integerOption("--minimum-seeds",5,1,targetSamples),maximumOutputMb=integerOption("--max-output-mb",1024,50,102400),band=numberOption("--band",.5,0,5),styleLimit=numberOption("--style-limit",3,0,5),styleScale=numberOption("--style-scale",1.1,0,2),requireAssistGate=args.includes("--require-assist-gate"),existing=option("--existing","").split(",").map(value=>value.trim()).filter(Boolean).map(value=>path.resolve(value)),candidateSeeds=option("--seeds",Array.from({length:24},(_,index)=>`whitebox-lineup-auto-${String(index+1).padStart(2,"0")}`).join(",")).split(",").map(value=>value.trim()).filter(Boolean),manifestFile=path.join(out,"sampler-manifest.json"),config={targetSamples,minimumSeeds,maximumOutputMb,band,styleLimit,styleScale,...(requireAssistGate?{requireAssistGate:true as const}:{})};fs.mkdirSync(out,{recursive:true});let manifest:Manifest=fs.existsSync(manifestFile)?read<Manifest>(manifestFile):{schemaVersion:1,config,existing:[],seeds:[]};if(JSON.stringify(manifest.config)!==JSON.stringify(config))throw new Error("Lineup sampler configuration differs from existing manifest; use a new output directory");manifest.existing=[...new Set([...manifest.existing,...existing])];save();
if(args.includes("--run"))for(const seed of candidateSeeds){
  if(manifest.seeds.some(entry=>entry.seed===seed))continue;const progress=whiteBoxSamplingProgress(loadSamples().map(sample=>sample.seed),targetSamples,minimumSeeds);if(progress.complete)break;if(directorySize(out)/1048576>maximumOutputMb)throw new Error(`Lineup sampler output exceeded ${maximumOutputMb} MB`);
  const started=Date.now(),seedRoot=path.join(out,"seeds",safe(seed)),baseline=path.join(seedRoot,"baseline"),experiment=path.join(seedRoot,"experiment");
  try{
    if(fs.existsSync(seedRoot))throw new Error(`Untracked seed directory exists: ${seedRoot}`);runBaseline(seed,baseline);const opportunity=scanWhiteBoxOpportunities([baseline],[{id:"cautious",band,styleLimit,styleScale}]);fs.writeFileSync(path.join(seedRoot,"opportunity-summary.json"),`${JSON.stringify(opportunity,null,2)}\n`,"utf8");fs.writeFileSync(path.join(seedRoot,"opportunity-report.md"),whiteBoxOpportunityMarkdown(opportunity),"utf8");const cases=opportunity.scenarios[0].cases;
    if(!cases.length){const retention=compact([baseline]);manifest.seeds.push({seed,status:"no-difference",baseline,cases:0,durationMs:Date.now()-started,retention});save();process.stdout.write(`lineup sampler ${seed}: no cautious difference\n`);continue;}
    const eligible=requireAssistGate?cases.filter(entry=>entry.assistGate?.recommended):cases;if(!eligible.length){const retention=compact([baseline]);manifest.seeds.push({seed,status:"ineligible",baseline,cases:cases.length,eligibleCases:0,durationMs:Date.now()-started,retention});save();process.stdout.write(`lineup sampler ${seed}: ${cases.length} differences blocked by assist gate\n`);continue;}
    const selected=eligible[0];runCounterfactual(baseline,experiment,selected);const retention=compact([baseline,path.join(experiment,"incumbent"),path.join(experiment,"whitebox")]);manifest.seeds.push({seed,status:"complete",baseline,experiment,cases:cases.length,eligibleCases:eligible.length,durationMs:Date.now()-started,retention});save();process.stdout.write(`lineup sampler ${seed}: paired ${selected.decisionId}\n`);
  }catch(error){manifest.seeds.push({seed,status:"failed",baseline,cases:0,durationMs:Date.now()-started,error:error instanceof Error?error.message:String(error)});save();throw error;}
}
const samples=loadSamples(),progress=whiteBoxSamplingProgress(samples.map(sample=>sample.seed),targetSamples,minimumSeeds);let promotion="no-samples";if(samples.length){const batch=evaluateWhiteBoxCounterfactualBatch(samples,whiteBoxProductionEvidenceMinimum(targetSamples));promotion=batch.promotion;fs.writeFileSync(path.join(out,"counterfactual-batch.json"),`${JSON.stringify(batch,null,2)}\n`,"utf8");fs.writeFileSync(path.join(out,"counterfactual-batch.md"),whiteBoxCounterfactualBatchMarkdown(batch),"utf8");}const result={promotion,progress,attemptedSeeds:manifest.seeds.length,noDifference:manifest.seeds.filter(entry=>entry.status==="no-difference").length,ineligible:manifest.seeds.filter(entry=>entry.status==="ineligible").length,failed:manifest.seeds.filter(entry=>entry.status==="failed").length,outputMb:round(directorySize(out)/1048576),manifest:manifestFile};fs.writeFileSync(path.join(out,"sampler-summary.json"),`${JSON.stringify(result,null,2)}\n`,"utf8");console.log(JSON.stringify(result,null,2));
function runBaseline(seed:string,directory:string):void{run([path.join(root,"src","cli","draftLeagueV12.ts")],{...process.env,V12_OUT:directory,V12_SEED:seed,V12_SEASONS:"1",V12_RESUME:"false",V12_MANAGER_LIMIT:option("--managers","8"),V12_PAIRS:option("--pairs","2"),V12_POOL_SIZE:option("--pool","140"),V12_AUCTION_LOTS:option("--auction-lots","16"),V12_REGULAR_ROUNDS:option("--rounds","3"),V12_MAX_TURNS:option("--max-turns","80"),V12_MIN_ROSTER:"8",V12_MAX_ROSTER:"8",V12_REGISTRY_SOURCE:path.resolve(option("--registry","data/draft")),V12_REGISTRY_REVISION:`whitebox-lineup-sampler:${seed}`,V12_EVIDENCE_RETENTION:"compact",V4_WHITEBOX_FULL_LINEUP_TRACE:"true"},`Baseline ${seed}`);}
function runCounterfactual(source:string,destination:string,selected:{decisionId:string;actor:string}):void{run([path.join(root,"src","cli","counterfactualWhiteBoxLineup.ts"),"--source",source,"--out",destination,"--decision-id",selected.decisionId,"--manager",selected.actor,"--season","1","--band",String(band),"--style-limit",String(styleLimit),"--style-scale",String(styleScale)],process.env,"Lineup counterfactual");}
function run(cliArgs:string[],env:NodeJS.ProcessEnv,label:string):void{const result=spawnSync(process.execPath,[require.resolve("tsx/cli"),...cliArgs],{cwd:root,env:{...env},encoding:"utf8",maxBuffer:64*1024*1024});if(result.status!==0)throw new Error(`${label} failed:\n${result.stderr||result.stdout}`);}
function loadSamples():WhiteBoxCounterfactualSample[]{return[...manifest.existing,...manifest.seeds.filter(entry=>entry.status==="complete"&&entry.experiment).map(entry=>entry.experiment!)].map(directory=>{const summary=read<any>(path.join(directory,"counterfactual-summary.json")),state=read<any>(path.join(directory,"incumbent","dynasty-state.json")),comparison=summary.comparison;return{seed:state.seed,caseId:summary.decisionId??`${comparison.managerId}@${comparison.interventionSeason}`,prefixVerified:Boolean(summary.prefixVerified),comparison};});}
function compact(directories:string[]):WhiteBoxRetentionTrace[]{const traces=directories.map(directory=>compactWhiteBoxRun(directory));return traces;}
function save():void{fs.writeFileSync(manifestFile,`${JSON.stringify(manifest,null,2)}\n`,"utf8");}function directorySize(directory:string):number{if(!fs.existsSync(directory))return 0;let total=0;for(const entry of fs.readdirSync(directory,{withFileTypes:true})){const target=path.join(directory,entry.name);total+=entry.isDirectory()?directorySize(target):fs.statSync(target).size;}return total;}function safe(value:string):string{return value.replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"seed";}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?args[index+1]??fallback:fallback;}function integerOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}function numberOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isFinite(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}function round(value:number):number{return Math.round(value*100)/100;}
