import fs from "node:fs";
import path from "node:path";
import {evaluatePortfolioBidCounterfactual, loadPortfolioBidReplayCapsule, portfolioAwardSignature, precheckPortfolioBids} from "../ai/whiteBox/portfolioBidCounterfactual";

const args=process.argv.slice(2),source=path.resolve(required("--source")),state=read<any>(path.join(source,"dynasty-state.json")),season=integerOption("--season",Number(state.completedSeason),1,1000),maximumCandidates=integerOption("--max-candidates",10,1,100),out=path.resolve(option("--out","output/portfolio-bid-screen"));
if(fs.existsSync(out))throw new Error(`Portfolio bid screen output exists: ${out}`);fs.mkdirSync(out,{recursive:true});
const capsule=loadPortfolioBidReplayCapsule(source,season),prechecks=precheckPortfolioBids(capsule),screenable=prechecks.filter(entry=>entry.status==="screenable"),selected=screenable.slice(0,maximumCandidates),started=Date.now(),results=[];
for(const precheck of selected){const evaluation=evaluatePortfolioBidCounterfactual(capsule,precheck.decisionId);results.push({...evaluation,candidateAwardSignature:evaluation.candidateAwards?portfolioAwardSignature(evaluation.candidateAwards):null,candidateAwards:undefined});process.stdout.write(`${precheck.decisionId}: ${evaluation.status}, changes ${evaluation.changes.length}\n`);}
const summary={schemaVersion:1,source,season,sourceVerified:true,sourceHash:capsule.sourceHash,assets:capsule.assetIds.length,bids:capsule.bids.length,sourceAwards:capsule.awards.length,precheck:{screenable:screenable.length,archiveOnly:prechecks.length-screenable.length,reasonCounts:count(prechecks.flatMap(entry=>entry.reasons))},evaluated:results.length,executable:results.filter(entry=>entry.status==="executable").length,unchanged:results.filter(entry=>entry.reasons.includes("portfolio-allocation-unchanged")).length,durationMs:Date.now()-started,results};
write(path.join(out,"portfolio-bid-screen.json"),summary);fs.writeFileSync(path.join(out,"portfolio-bid-screen.md"),markdown(summary),"utf8");console.log(JSON.stringify({season,screenable:summary.precheck.screenable,evaluated:summary.evaluated,executable:summary.executable,unchanged:summary.unchanged,durationMs:summary.durationMs,report:path.join(out,"portfolio-bid-screen.md")},null,2));

function markdown(value:typeof summary):string{return`# Portfolio bid counterfactual screen\n\n- Source season: ${value.season}\n- Source reconstruction: ${value.sourceVerified?"verified":"failed"}\n- Assets / positive bids / awards: ${value.assets} / ${value.bids} / ${value.sourceAwards}\n- Cheap-screen candidates: ${value.precheck.screenable}\n- Fully evaluated: ${value.evaluated}\n- Allocation-changing: ${value.executable}\n- Solver-confirmed unchanged: ${value.unchanged}\n- Solver time: ${(value.durationMs/1000).toFixed(1)} seconds\n\nEvery evaluated case changes one retained submitted bid to its audited ceiling and reruns the complete constrained portfolio solver. No result activates production behavior.\n`;}
function count(values:string[]):Record<string,number>{const result:Record<string,number>={};for(const value of values)result[value]=(result[value]??0)+1;return Object.fromEntries(Object.entries(result).sort(([a],[b])=>a.localeCompare(b)));}
function write(file:string,value:unknown):void{fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`,"utf8");}function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}function option(name:string,fallback:string):string{const index=args.indexOf(name);return index>=0?args[index+1]??fallback:fallback;}function required(name:string):string{const value=option(name,"").trim();if(!value)throw new Error(`Missing ${name}`);return value;}function integerOption(name:string,fallback:number,min:number,max:number):number{const value=Number(option(name,String(fallback)));if(!Number.isInteger(value)||value<min||value>max)throw new Error(`${name} must be ${min}..${max}`);return value;}
