import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import type {AiDecisionTrace, PositionSnapshot} from "../showdown/choice";
import {canonicalJson, sha256} from "../showdown/evidenceEpoch";
import {classifyReplayEvidence} from "../draft/evidenceEpochAudit";
import {acquireNamedRunLock} from "../draft/runLock";
import {loadBattleFamilyEvidence, type BenchmarkBattleEvidence} from "../draft/benchmarkFamilies";
import {teamStructuresFromReplay, type TeamStructureSnapshot} from "../showdown/teamStructure";
import {assertRelationalDecisionSnapshot, relationalKnown, type RelationalDecisionSnapshotV1, type RelationalSwitchFeature} from "./relationalDecision";

export const POSITION_VALUE_MODEL_VERSION = "position-value-logistic-v2.7-dynamic-relational-context";
export const POSITION_FEATURE_VERSION = "position-features-v6-dynamic-relational-context";
export const LEGACY_POSITION_FEATURE_COUNT = 12;
export const POSITION_FEATURES = ["remainingDelta", "hpDelta", "activeHpDelta", "statusDelta", "activeStatusDelta", "boostDelta", "hazardDelta", "screenDelta", "forcedSwitch", "trapped", "remainingLate", "hpLate", "roleBreadthDelta", "roleCompressionDelta", "structuralSinglePointDelta", "answerRedundancyDelta", "blindSpotResilienceDelta", "opponentStructureResponseDelta", "opponentStructureLoadDelta", "roleBreadthLate", "roleCompressionLate", "structuralSinglePointLate", "answerRedundancyLate", "blindSpotResilienceLate", "opponentStructureResponseLate", "opponentStructureLoadLate", "switchOptionBreadth", "switchHpMean", "switchSafetyBest", "switchSafetyMean", "switchOutputCeiling", "switchKoCeiling", "switchRoleRedundancy", "switchFollowupCeiling"] as const;
export type PositionFeature = typeof POSITION_FEATURES[number];

export interface PositionValueSample {
  id: string; battleId: string; clusterId: string; source: string; playerId: "p1" | "p2"; ordinal: number; turn: number; label: 0 | 1; weight: number; split: "train" | "validation" | "test"; features: number[]; familyIds?: [string, string]; environment?: string;
}

export interface PositionValueModel {
  schemaVersion: 1; version: typeof POSITION_VALUE_MODEL_VERSION; featureVersion: typeof POSITION_FEATURE_VERSION; features: readonly PositionFeature[]; coefficients: number[]; regularization: number; structuralRegularization: number; trainedSamples: number; trainedBattles: number; trainingSignature: string; sha256: string;
}

export interface PositionValueMetrics {samples: number; battles: number; clusters: number; brier: number; logLoss: number; accuracy: number; ece: number; meanPrediction: number; positiveRate: number}
export interface PositionValueSummary {
  schemaVersion: 1; generatedAt: string; sourceRoot: string; sources: number; reusedSources: number; modelCacheHit: boolean; battles: number; samples: number; skipped: Record<string, number>; split: Record<string, {samples: number; battles: number; clusters: number}>; selectedRegularization: number; selectedStructuralRegularization: number; metrics: Record<string, {model: PositionValueMetrics; constant: PositionValueMetrics; material: PositionValueMetrics; legacy: PositionValueMetrics}>; testByPhase: Record<"early" | "mid" | "late", {model: PositionValueMetrics; constant: PositionValueMetrics; material: PositionValueMetrics; legacy: PositionValueMetrics}>; testByEnvironment: Record<string, {model: PositionValueMetrics; constant: PositionValueMetrics; material: PositionValueMetrics; legacy: PositionValueMetrics}>; testImprovement: {vsConstantLogLossPercent: number; vsMaterialLogLossPercent: number; vsLegacyLogLossPercent: number; brierDeltaVsConstant: number; bootstrapProbabilityBetterThanConstant: number; bootstrapProbabilityBetterThanMaterial: number; bootstrapProbabilityBetterThanLegacy: number}; evidenceDesign: {authority: "legacy-pair-hash" | "signed-family-registry"; families: number; familiesBySplit: Record<string, number>; familyLeakage: string[]; environments: string[]; bootstrapUnit: "pair-cluster" | "family-block"}; representation: {features: number; structuralFeatures: number; nonConstantStructuralFeatures: number; distinctStructuralColumns: number; maximumAbsoluteStructuralCorrelation: number; highlyCorrelatedStructuralPairs: string[]; structuralFeatureRanges: Record<string, {minimum: number; maximum: number}>}; audit: {healthy: boolean; activationStatus: "shadow-only"; formalActivationAllowed: false; issues: Array<{severity: "error" | "warning"; code: string; message: string}>; symmetryMaximumError: number}; model: PositionValueModel; inputSignature: string; elapsedMs: number; peakRssBytes: number; artifacts: {model: string; samples: string; summary: string; report: string; cache: string; failures: string}; sha256: string
}

interface CachedSource {fingerprint: string; samples: Omit<PositionValueSample, "weight" | "split">[]; battleId: string; clusterId: string; split?: PositionValueSample["split"]; familyIds?: [string, string]; environment?: string; skip?: string}
interface PositionCache {schemaVersion: 1; featureVersion: string; sources: Record<string, CachedSource>}

export function positionFeatures(snapshot: PositionSnapshot, structure?: TeamStructureSnapshot, relational?: RelationalDecisionSnapshotV1): number[] {
  const own = snapshot.own, opponent = snapshot.opponent, progress = Math.min(1, snapshot.turn / 40);
  const remainingDelta = (own.remaining - opponent.remaining) / 6, hpDelta = (own.hpTotal - opponent.hpTotal) / 6;
  const structural = [structure?.roleBreadth ?? 0, structure?.roleCompression ?? 0, structure?.structuralSinglePoints ?? 0, structure?.answerRedundancy ?? 0, structure?.blindSpotResilience ?? 0, structure?.opponentStructureResponse ?? 0, structure?.opponentStructureLoad ?? 0];
  return [remainingDelta, hpDelta, own.activeHp - opponent.activeHp, (opponent.statusCount - own.statusCount) / 6, Number(opponent.activeStatus) - Number(own.activeStatus), (own.positiveBoosts - own.negativeBoosts - opponent.positiveBoosts + opponent.negativeBoosts) / 12, (opponent.hazards - own.hazards) / 5, (own.screens - opponent.screens) / 3, snapshot.forcedSwitch ? -1 : 0, snapshot.trapped ? -1 : 0, remainingDelta * progress, hpDelta * progress, ...structural, ...structural.map(value => value * progress), ...relationalPositionContext(relational)].map(round);
}

export function pairedPositionFeatures(own: PositionSnapshot, opponent: PositionSnapshot, ownStructure?: TeamStructureSnapshot, opponentStructure?: TeamStructureSnapshot, ownRelational?: RelationalDecisionSnapshotV1, opponentRelational?: RelationalDecisionSnapshotV1): number[] { const left = positionFeatures(own, ownStructure, ownRelational), right = positionFeatures(opponent, opponentStructure, opponentRelational); return left.map((value, index) => round((value - right[index]) / 2)); }
export function predictPairedPositionValue(own: PositionSnapshot, opponent: PositionSnapshot, model: PositionValueModel, ownStructure?: TeamStructureSnapshot, opponentStructure?: TeamStructureSnapshot, ownRelational?: RelationalDecisionSnapshotV1, opponentRelational?: RelationalDecisionSnapshotV1): number { return sigmoid(dot(pairedPositionFeatures(own, opponent, ownStructure, opponentStructure, ownRelational, opponentRelational), model.coefficients)); }
export function validPositionSummarySignature(summary: PositionValueSummary): boolean { const {sha256: signature, ...core} = summary; return /^[a-f0-9]{64}$/.test(signature) && sha256(core) === signature; }

function relationalPositionContext(snapshot?: RelationalDecisionSnapshotV1): number[] {
  const candidates = snapshot?.candidates.filter(candidate => candidate.actionKind === "switch") ?? [];
  const values = (feature: RelationalSwitchFeature): number[] => candidates.filter(candidate => relationalKnown(candidate.knownMask, feature)).map(candidate => candidate.values[feature]);
  const hp = values("candidateHp"), output = values("bestOutput"), ko = values("koProbability"), redundancy = values("roleRedundancy"), followup = values("safeFollowupBreadth");
  const safety = candidates.flatMap(candidate => ["entryKoRisk", "incomingWorst", "priorityKoRisk"].every(feature => relationalKnown(candidate.knownMask, feature as RelationalSwitchFeature)) ? [1 - Math.max(candidate.values.entryKoRisk, candidate.values.incomingWorst, candidate.values.priorityKoRisk)] : []);
  return [Math.min(1, candidates.length / 5), mean(hp), maximum(safety), mean(safety), maximum(output), maximum(ko), mean(redundancy), maximum(followup)];
}

export function buildPositionValueModel(sourceRoot: string, outputDirectory: string): PositionValueSummary {
  const started = Date.now(), root = path.resolve(sourceRoot), out = path.resolve(outputDirectory); fs.mkdirSync(out, {recursive: true});
  const lock = acquireNamedRunLock(out, ".position-value.lock", {command: "build", sourceRoot: root}), cacheFile = path.join(out, "source-cache.json.gz"), failureFile = path.join(out, "failures.json");
  let phase = "scan", peakRssBytes = process.memoryUsage().rss;
  atomic(path.join(out, "build-state.json"), {schemaVersion: 1, status: "running", phase, startedAt: new Date(started).toISOString(), peakRssBytes});
  try {
    const prior = optionalGzip<PositionCache>(cacheFile), next: PositionCache = {schemaVersion: 1, featureVersion: POSITION_FEATURE_VERSION, sources: {}}, samples: PositionValueSample[] = [], skipped: Record<string, number> = {}, files = findDecisionFiles(root); let reusedSources = 0, scannedSources = 0;
    for (const file of files) {
      const relative = rel(root, file), game = path.dirname(file), replay = existing(game, ["replay-input.json", "replay-input.json.gz"]), end = existing(game, ["end.json", "end.json.gz"]), familyEvidence = loadBattleFamilyEvidence(game), fingerprint = sourceFingerprint(file, replay, end, familyEvidence);
      let cached = prior?.schemaVersion === 1 && prior.featureVersion === POSITION_FEATURE_VERSION ? prior.sources[relative] : undefined;
      if (cached?.fingerprint === fingerprint) reusedSources += 1;
      else cached = inspectSource(root, file, replay, end, fingerprint, familyEvidence);
      next.sources[relative] = cached;
      if (cached.skip) skipped[cached.skip] = (skipped[cached.skip] ?? 0) + 1;
      else samples.push(...cached.samples.map(sample => ({...sample, weight: 0, split: cached!.split ?? splitForCluster(sample.clusterId)})));
      peakRssBytes = Math.max(peakRssBytes, process.memoryUsage().rss);
      scannedSources += 1; if (scannedSources % 100 === 0 || scannedSources === files.length) atomic(path.join(out, "build-state.json"), {schemaVersion: 1, status: "running", phase: "scan", scannedSources, totalSources: files.length, reusedSources, samples: samples.length, elapsedMs: Date.now() - started, peakRssBytes});
    }
    const inputSignature = sha256(Object.entries(next.sources).sort().map(([source, value]) => [source, value.fingerprint]));
    phase = "weight"; atomic(path.join(out, "build-state.json"), {schemaVersion: 1, status: "running", phase, scannedSources, totalSources: files.length, reusedSources, samples: samples.length, elapsedMs: Date.now() - started, peakRssBytes}); validateFeatureSamples(samples); weightSamples(samples);
    const priorSummary = optionalJson<PositionValueSummary>(path.join(out, "summary.json")), priorModel = optionalJson<PositionValueModel>(path.join(out, "model.json"));
    if (reusedSources === files.length && priorSummary?.inputSignature === inputSignature && validPositionSummarySignature(priorSummary) && priorModel?.version === POSITION_VALUE_MODEL_VERSION && priorModel.featureVersion === POSITION_FEATURE_VERSION && priorSummary.model.sha256 === priorModel.sha256) {
      const {sha256: _priorSha, ...priorCore} = priorSummary, summaryCore = {...priorCore, generatedAt: new Date().toISOString(), reusedSources, modelCacheHit: true, elapsedMs: Date.now() - started, peakRssBytes}, summary: PositionValueSummary = {...summaryCore, sha256: sha256(summaryCore)}; writeGzip(cacheFile, next); atomic(path.join(out, "summary.json"), summary); atomic(failureFile, {schemaVersion: 1, failures: []}); atomic(path.join(out, "build-state.json"), {schemaVersion: 1, status: "complete", phase: "cache-hit", elapsedMs: summary.elapsedMs, peakRssBytes}); return summary;
    }
    phase = "train"; atomic(path.join(out, "build-state.json"), {schemaVersion: 1, status: "running", phase, samples: samples.length, elapsedMs: Date.now() - started, peakRssBytes}); const training = samples.filter(sample => sample.split === "train"), validation = samples.filter(sample => sample.split === "validation"), test = samples.filter(sample => sample.split === "test");
    if (!training.length || !validation.length || !test.length) throw new Error("Position corpus does not populate all train/validation/test splits");
    const legacyCandidates = [0, .001, .01, .05, .1].map(regularization => fit(training, regularization, LEGACY_POSITION_FEATURE_COUNT)), legacySelected = legacyCandidates.sort((left, right) => metrics(validation, sample => score(sample, left)).logLoss - metrics(validation, sample => score(sample, right)).logLoss)[0];
    const candidates = [.001, .01, .05, .1, .5].map(structuralRegularization => fit(training, legacySelected.regularization, POSITION_FEATURES.length, structuralRegularization));
    const selected = candidates.sort((left, right) => metrics(validation, sample => score(sample, left)).logLoss - metrics(validation, sample => score(sample, right)).logLoss)[0];
    const trainingSignature = sha256(samples.map(sample => [sample.id, sample.split, sample.label, sample.weight, sample.features]));
    const modelCore = {schemaVersion: 1 as const, version: POSITION_VALUE_MODEL_VERSION as typeof POSITION_VALUE_MODEL_VERSION, featureVersion: POSITION_FEATURE_VERSION as typeof POSITION_FEATURE_VERSION, features: POSITION_FEATURES, coefficients: selected.coefficients.map(round), regularization: selected.regularization, structuralRegularization: selected.structuralRegularization, trainedSamples: training.length, trainedBattles: new Set(training.map(sample => sample.battleId)).size, trainingSignature};
    const model: PositionValueModel = {...modelCore, sha256: sha256(modelCore)};
    phase = "audit"; atomic(path.join(out, "build-state.json"), {schemaVersion: 1, status: "running", phase, samples: samples.length, elapsedMs: Date.now() - started, peakRssBytes});
    const bySplit = Object.fromEntries((["train", "validation", "test"] as const).map(name => { const subset = samples.filter(sample => sample.split === name); return [name, {model: metrics(subset, sample => score(sample, model)), constant: metrics(subset, () => .5), material: metrics(subset, materialScore), legacy: metrics(subset, sample => score(sample, legacySelected))}]; })) as PositionValueSummary["metrics"];
    const testByPhase = Object.fromEntries((["early", "mid", "late"] as const).map(phaseName => { const subset = test.filter(sample => turnPhase(sample.turn) === phaseName); return [phaseName, {model: metrics(subset, sample => score(sample, model)), constant: metrics(subset, () => .5), material: metrics(subset, materialScore), legacy: metrics(subset, sample => score(sample, legacySelected))}]; })) as PositionValueSummary["testByPhase"];
    const environments = [...new Set(test.map(sample => sample.environment).filter((value): value is string => Boolean(value)))].sort(), testByEnvironment = Object.fromEntries(environments.map(environment => { const subset = test.filter(sample => sample.environment === environment); return [environment, {model: metrics(subset, sample => score(sample, model)), constant: metrics(subset, () => .5), material: metrics(subset, materialScore), legacy: metrics(subset, sample => score(sample, legacySelected))}]; })) as PositionValueSummary["testByEnvironment"];
    const evidenceDesign = describeEvidenceDesign(samples), bootstrap = bootstrapComparison(test, model, legacySelected, 500), testMetrics = bySplit.test, structuralFeatureRanges = featureRanges(samples, LEGACY_POSITION_FEATURE_COUNT), nonConstantStructuralFeatures = Object.values(structuralFeatureRanges).filter(value => value.maximum - value.minimum > 1e-9).length, independence = featureIndependence(samples, LEGACY_POSITION_FEATURE_COUNT);
    const issues: PositionValueSummary["audit"]["issues"] = [], split = splitCounts(samples), battles = new Set(samples.map(sample => sample.battleId)).size, clusters = new Set(samples.map(sample => sample.clusterId)).size;
    if (battles < 80) issues.push({severity: "error", code: "insufficient-battles", message: `${battles}/80 battles`});
    if (clusters < 20 || split.test.clusters < 4) issues.push({severity: "error", code: "insufficient-clusters", message: `${clusters} total clusters; ${split.test.clusters} test clusters`});
    if (testMetrics.model.logLoss >= testMetrics.constant.logLoss) issues.push({severity: "error", code: "no-constant-improvement", message: "Model does not improve test log loss over 0.5"});
    if (testMetrics.model.logLoss >= testMetrics.material.logLoss) issues.push({severity: "warning", code: "no-material-improvement", message: "Model does not improve test log loss over the fixed material baseline"});
    if (evidenceDesign.authority === "signed-family-registry" && percentImprovement(testMetrics.material.logLoss, testMetrics.model.logLoss) < 1.5) issues.push({severity: "error", code: "weak-material-effect", message: "Family-held-out log loss improvement over material is below 1.5%"});
    if (bootstrap.material < .9) issues.push({severity: "error", code: "weak-material-bootstrap", message: `P(model better than material) ${bootstrap.material} is below 0.9`});
    if (evidenceDesign.familyLeakage.length) issues.push({severity: "error", code: "family-split-leakage", message: evidenceDesign.familyLeakage.join(", ")});
    if (evidenceDesign.authority === "signed-family-registry" && Object.values(testByEnvironment).filter(value => value.model.logLoss < value.material.logLoss).length < 2) issues.push({severity: "error", code: "insufficient-environment-replication", message: "Model does not beat material in at least two held-out environment pairs"});
    if (!nonConstantStructuralFeatures) issues.push({severity: "error", code: "missing-structural-variation", message: "Structural context features have no observed variation"});
    if (independence.distinctColumns !== POSITION_FEATURES.length - LEGACY_POSITION_FEATURE_COUNT) issues.push({severity: "error", code: "duplicate-structural-columns", message: `${independence.distinctColumns}/${POSITION_FEATURES.length - LEGACY_POSITION_FEATURE_COUNT} structural columns are distinct`});
    if (independence.highlyCorrelatedPairs.length) issues.push({severity: "warning", code: "correlated-structural-columns", message: `Highly correlated structural pairs: ${independence.highlyCorrelatedPairs.join(", ")}`});
    else if (bootstrap.legacy < .5 || testMetrics.model.logLoss >= testMetrics.legacy.logLoss) issues.push({severity: "warning", code: "no-legacy-improvement", message: `Structural model does not yet improve untouched log loss over the 12-feature model (P=${bootstrap.legacy})`});
    if (testMetrics.model.ece > .08) issues.push({severity: "error", code: "calibration-error", message: `Test ECE ${testMetrics.model.ece} exceeds 0.08`});
    const symmetryMaximumError = symmetryError(model); if (symmetryMaximumError > 1e-12) issues.push({severity: "error", code: "symmetry", message: `Perspective symmetry error ${symmetryMaximumError}`});
    if (model.coefficients[0] < 0 || model.coefficients[1] < 0) issues.push({severity: "error", code: "material-monotonicity", message: "Learned remaining or HP coefficient is negative"});
    if (Math.abs(testMetrics.model.meanPrediction - testMetrics.model.positiveRate) > .03) issues.push({severity: "error", code: "population-calibration-bias", message: `Mean prediction ${testMetrics.model.meanPrediction} differs from outcome rate ${testMetrics.model.positiveRate}`});
    for (const [phaseName, value] of Object.entries(testByPhase)) { if (value.model.samples >= 200 && value.model.logLoss >= value.constant.logLoss) issues.push({severity: "error", code: `phase-${phaseName}-constant`, message: `${phaseName} test log loss does not beat constant`}); else if (value.model.samples >= 200 && value.model.logLoss > value.material.logLoss * 1.02) issues.push({severity: "error", code: `phase-${phaseName}-material-regression`, message: `${phaseName} test log loss regresses over material by more than 2%`}); else if (value.model.samples >= 200 && value.model.logLoss >= value.material.logLoss) issues.push({severity: "warning", code: `phase-${phaseName}-material`, message: `${phaseName} test log loss does not beat material baseline`}); }
    const artifacts = {model: path.join(out, "model.json"), samples: path.join(out, "samples.json.gz"), summary: path.join(out, "summary.json"), report: path.join(out, "report.md"), cache: cacheFile, failures: failureFile};
    const summaryCore = {schemaVersion: 1 as const, generatedAt: new Date().toISOString(), sourceRoot: root, sources: files.length, reusedSources, modelCacheHit: false, battles, samples: samples.length, skipped, split, selectedRegularization: model.regularization, selectedStructuralRegularization: model.structuralRegularization, metrics: bySplit, testByPhase, testByEnvironment, testImprovement: {vsConstantLogLossPercent: percentImprovement(testMetrics.constant.logLoss, testMetrics.model.logLoss), vsMaterialLogLossPercent: percentImprovement(testMetrics.material.logLoss, testMetrics.model.logLoss), vsLegacyLogLossPercent: percentImprovement(testMetrics.legacy.logLoss, testMetrics.model.logLoss), brierDeltaVsConstant: round(testMetrics.model.brier - testMetrics.constant.brier), bootstrapProbabilityBetterThanConstant: bootstrap.constant, bootstrapProbabilityBetterThanMaterial: bootstrap.material, bootstrapProbabilityBetterThanLegacy: bootstrap.legacy}, evidenceDesign, representation: {features: POSITION_FEATURES.length, structuralFeatures: POSITION_FEATURES.length - LEGACY_POSITION_FEATURE_COUNT, nonConstantStructuralFeatures, distinctStructuralColumns: independence.distinctColumns, maximumAbsoluteStructuralCorrelation: independence.maximumAbsoluteCorrelation, highlyCorrelatedStructuralPairs: independence.highlyCorrelatedPairs, structuralFeatureRanges}, audit: {healthy: !issues.some(issue => issue.severity === "error"), activationStatus: "shadow-only" as const, formalActivationAllowed: false as const, issues, symmetryMaximumError}, model, inputSignature, elapsedMs: Date.now() - started, peakRssBytes, artifacts}, summary: PositionValueSummary = {...summaryCore, sha256: sha256(summaryCore)};
    writeGzip(cacheFile, next); writeGzip(artifacts.samples, {schemaVersion: 1, featureVersion: POSITION_FEATURE_VERSION, samples}); atomic(artifacts.model, model); atomic(artifacts.summary, summary); atomic(failureFile, {schemaVersion: 1, failures: []}); fs.writeFileSync(artifacts.report, report(summary), "utf8"); atomic(path.join(out, "build-state.json"), {schemaVersion: 1, status: "complete", phase: "complete", elapsedMs: summary.elapsedMs, peakRssBytes});
    return summary;
  } catch (error) { const failure = {phase, message: error instanceof Error ? error.message : String(error)}; atomic(failureFile, {schemaVersion: 1, failures: [failure]}); atomic(path.join(out, "build-state.json"), {schemaVersion: 1, status: "failed", phase, peakRssBytes: Math.max(peakRssBytes, process.memoryUsage().rss), failure}); throw error; }
  finally { lock.release(); }
}

export function doctorPositionValue(outputDirectory: string, verifySources = false): Record<string, unknown> {
  const out = path.resolve(outputDirectory), summary = optionalJson<PositionValueSummary>(path.join(out, "summary.json")), model = optionalJson<PositionValueModel>(path.join(out, "model.json")), issues: Array<{severity: "error" | "warning"; code: string; message: string}> = [];
  if (!summary || !model) return {available: false, healthy: false, issues: [{severity: "error", code: "missing-artifacts", message: "Position value artifacts are missing"}]};
  if (!validPositionSummarySignature(summary)) issues.push({severity: "error", code: "summary-signature", message: "Position value summary signature mismatch"});
  const {sha256: _hash, ...core} = model; if (sha256(core) !== model.sha256) issues.push({severity: "error", code: "model-signature", message: "Model signature mismatch"});
  if (model.version !== POSITION_VALUE_MODEL_VERSION || model.featureVersion !== POSITION_FEATURE_VERSION || JSON.stringify(model.features) !== JSON.stringify(POSITION_FEATURES) || model.coefficients.length !== POSITION_FEATURES.length) issues.push({severity: "error", code: "model-representation", message: "Model does not use the current structural feature contract"});
  if (summary.model.sha256 !== model.sha256) issues.push({severity: "error", code: "summary-binding", message: "Summary and model differ"});
  if (summary.representation?.structuralFeatures !== POSITION_FEATURES.length - LEGACY_POSITION_FEATURE_COUNT || summary.representation?.nonConstantStructuralFeatures < 1 || summary.representation?.distinctStructuralColumns !== POSITION_FEATURES.length - LEGACY_POSITION_FEATURE_COUNT) issues.push({severity: "error", code: "structural-representation", message: "Structural feature coverage is missing, constant, or duplicated"});
  if (summary.evidenceDesign?.authority === "signed-family-registry" && (summary.evidenceDesign.familyLeakage.length || summary.evidenceDesign.bootstrapUnit !== "family-block")) issues.push({severity: "error", code: "family-evidence-design", message: "Signed family corpus lost split isolation or family-block inference"});
  if (summary.audit.formalActivationAllowed) issues.push({severity: "error", code: "activation-authority", message: "Stage-2 benchmark model must remain shadow-only"});
  let verifiedSources = 0;
  if (verifySources) { const cache = optionalGzip<PositionCache>(path.join(out, "source-cache.json.gz")); if (!cache) issues.push({severity: "error", code: "missing-cache", message: "Source cache is missing"}); else for (const [relative, cached] of Object.entries(cache.sources)) { const file = path.join(summary.sourceRoot, ...relative.split("/")), game = path.dirname(file), replay = existing(game, ["replay-input.json", "replay-input.json.gz"]), end = existing(game, ["end.json", "end.json.gz"]), familyEvidence = loadBattleFamilyEvidence(game); if (!fs.existsSync(file)) issues.push({severity: "error", code: "missing-source", message: relative}); else if (sourceFingerprint(file, replay, end, familyEvidence) !== cached.fingerprint) issues.push({severity: "error", code: "source-hash", message: `Source or companion changed: ${relative}`}); verifiedSources += 1; } }
  const combinedIssues = [...summary.audit.issues, ...issues];
  return {available: true, healthy: !combinedIssues.some(issue => issue.severity === "error"), verifiedSources, model: {version: model.version, sha256: model.sha256, features: model.features.length}, corpus: {sources: summary.sources, battles: summary.battles, samples: summary.samples}, evaluation: summary.testImprovement, activationStatus: summary.audit.activationStatus, issues: combinedIssues};
}

function inspectSource(root: string, file: string, replay: string | null, end: string | null, fingerprint: string, familyEvidence: BenchmarkBattleEvidence | null): CachedSource {
  const relative = rel(root, file); if (familyEvidence?.split === "holdout") return {fingerprint, samples: [], battleId: "", clusterId: familyEvidence.pairClusterId, familyIds: [...familyEvidence.familyIds].sort() as [string, string], environment: familyEvidence.environment, skip: "formal-holdout-excluded"};
  const design = familyEvidence ? {clusterId: familyEvidence.pairClusterId, split: familyEvidence.split as PositionValueSample["split"], familyIds: [...familyEvidence.familyIds].sort() as [string, string], environment: familyEvidence.environment} : null; if (!replay || !end) return {fingerprint, samples: [], battleId: "", clusterId: design?.clusterId ?? "", split: design?.split, familyIds: design?.familyIds, environment: design?.environment, skip: "missing-companion"};
  try {
    const traces = read<any[]>(file), terminal = read<any>(end), capsule = read<any>(replay), evidence = classifyReplayEvidence(replay);
    if (!terminal.ended || !["Team A", "Team B"].includes(terminal.winner)) return {fingerprint, samples: [], battleId: capsule.sha256 ?? "", clusterId: "", skip: "non-binary-outcome"};
    if (evidence.compatibility !== "exact-compatible") return {fingerprint, samples: [], battleId: capsule.sha256 ?? "", clusterId: "", skip: `evidence-${evidence.compatibility}`};
    const battleId = String(capsule.sha256), teams = [sha256(capsule.input.teamA), sha256(capsule.input.teamB)].sort(), clusterId = design?.clusterId ?? sha256(teams), structures = teamStructuresFromReplay(capsule);
    const values: CachedSource["samples"] = [], byTurn = new Map<number, Partial<Record<"p1" | "p2", {trace: AiDecisionTrace; ordinal: number}>>>();
    for (let index = 0; index < traces.length; index += 1) { const trace = traces[index] as AiDecisionTrace; if (!trace.positionSnapshot || trace.positionSnapshot.encoderVersion !== "position-snapshot-v1") continue; if (trace.relationalSnapshot) assertRelationalDecisionSnapshot(trace.relationalSnapshot); const pair = byTurn.get(trace.turn) ?? {}; if (!pair[trace.playerId]) pair[trace.playerId] = {trace, ordinal: trace.decisionOrdinal ?? index + 1}; byTurn.set(trace.turn, pair); }
    for (const [turn, pair] of byTurn) { if (!pair.p1 || !pair.p2) continue; const canonical = pairedPositionFeatures(pair.p1.trace.positionSnapshot!, pair.p2.trace.positionSnapshot!, structures.p1, structures.p2, pair.p1.trace.relationalSnapshot, pair.p2.trace.relationalSnapshot);
      for (const playerId of ["p1", "p2"] as const) { const ordinal = pair[playerId]!.ordinal, ownTeam = playerId === "p1" ? "Team A" : "Team B"; values.push({id: sha256({battleId, playerId, turn, paired: true}).slice(0, 24), battleId, clusterId, source: relative, playerId, ordinal, turn, label: terminal.winner === ownTeam ? 1 : 0, features: playerId === "p1" ? canonical : canonical.map(value => -value), familyIds: design?.familyIds, environment: design?.environment}); }
    }
    return values.length ? {fingerprint, samples: values, battleId, clusterId, split: design?.split, familyIds: design?.familyIds, environment: design?.environment} : {fingerprint, samples: [], battleId, clusterId, split: design?.split, familyIds: design?.familyIds, environment: design?.environment, skip: "missing-position-snapshots"};
  } catch { return {fingerprint, samples: [], battleId: "", clusterId: "", skip: "invalid-source"}; }
}

function fit(samples: PositionValueSample[], regularization: number, featureCount: number, structuralRegularization = regularization): {coefficients: number[]; regularization: number; structuralRegularization: number} {
  const coefficients = Array(featureCount).fill(0), totalWeight = samples.reduce((sum, sample) => sum + sample.weight, 0);
  for (let iteration = 0; iteration < 2500; iteration += 1) { const gradient = Array(coefficients.length).fill(0); for (const sample of samples) { const error = sigmoid(dot(coefficients, sample.features)) - sample.label; for (let index = 0; index < gradient.length; index += 1) gradient[index] += sample.weight * error * sample.features[index]; } const rate = .8 / Math.sqrt(1 + iteration / 100); for (let index = 0; index < coefficients.length; index += 1) { const penalty = index < LEGACY_POSITION_FEATURE_COUNT ? regularization : structuralRegularization; coefficients[index] -= rate * (gradient[index] / totalWeight + penalty * coefficients[index]); } }
  if (coefficients.some(value => !Number.isFinite(value))) throw new Error(`Position fit diverged for ${featureCount} features at regularization ${regularization}`);
  return {coefficients, regularization, structuralRegularization};
}
function score(sample: PositionValueSample, model: {coefficients: number[]}): number { return sigmoid(dot(model.coefficients, sample.features)); }
function materialScore(sample: PositionValueSample): number { return sigmoid(sample.features[0] * 2.2 + sample.features[1] * 1.4 + sample.features[2] * .35); }
function turnPhase(turn: number): "early" | "mid" | "late" { return turn <= 10 ? "early" : turn <= 30 ? "mid" : "late"; }
function metrics(samples: PositionValueSample[], predict: (sample: PositionValueSample) => number): PositionValueMetrics { let weight = 0, brier = 0, logLoss = 0, correct = 0, prediction = 0, positive = 0; const bins = Array.from({length: 10}, () => ({weight: 0, prediction: 0, positive: 0})); for (const sample of samples) { const p = clamp(predict(sample), 1e-9, 1 - 1e-9), w = sample.weight; weight += w; brier += w * (p - sample.label) ** 2; logLoss -= w * (sample.label * Math.log(p) + (1 - sample.label) * Math.log(1 - p)); correct += w * Number((p >= .5 ? 1 : 0) === sample.label); prediction += w * p; positive += w * sample.label; const bin = bins[Math.min(9, Math.floor(p * 10))]; bin.weight += w; bin.prediction += w * p; bin.positive += w * sample.label; } const ece = bins.reduce((sum, bin) => sum + (bin.weight ? bin.weight / weight * Math.abs(bin.prediction / bin.weight - bin.positive / bin.weight) : 0), 0); return {samples: samples.length, battles: new Set(samples.map(sample => sample.battleId)).size, clusters: new Set(samples.map(sample => sample.clusterId)).size, brier: round(brier / weight), logLoss: round(logLoss / weight), accuracy: round(correct / weight), ece: round(ece), meanPrediction: round(prediction / weight), positiveRate: round(positive / weight)}; }
function weightSamples(samples: PositionValueSample[]): void { const groups = new Map<string, PositionValueSample[]>(); for (const sample of samples) { const key = `${sample.battleId}:${sample.playerId}`; groups.set(key, [...(groups.get(key) ?? []), sample]); } for (const group of groups.values()) for (const sample of group) sample.weight = round(.5 / group.length); }
function validateFeatureSamples(samples: PositionValueSample[]): void { for (const sample of samples) if (sample.features.length !== POSITION_FEATURES.length || sample.features.some(value => !Number.isFinite(value))) throw new Error(`Invalid position feature vector: ${sample.id}`); }
function splitForCluster(clusterId: string): PositionValueSample["split"] { const bucket = Number.parseInt(clusterId.slice(0, 8), 16) % 100; return bucket < 70 ? "train" : bucket < 85 ? "validation" : "test"; }
function splitCounts(samples: PositionValueSample[]): PositionValueSummary["split"] { return Object.fromEntries((["train", "validation", "test"] as const).map(split => { const subset = samples.filter(sample => sample.split === split); return [split, {samples: subset.length, battles: new Set(subset.map(sample => sample.battleId)).size, clusters: new Set(subset.map(sample => sample.clusterId)).size}]; })) as PositionValueSummary["split"]; }
function grouped(samples: PositionValueSample[]): PositionValueSample[][] { const groups = new Map<string, PositionValueSample[]>(); for (const sample of samples) groups.set(sample.clusterId, [...(groups.get(sample.clusterId) ?? []), sample]); return [...groups.values()]; }
function bootstrapComparison(samples: PositionValueSample[], model: PositionValueModel, legacy: {coefficients: number[]}, iterations: number): {constant: number; material: number; legacy: number} {
  let constant = 0, material = 0, legacyWins = 0, state = 0x51f15e; const random = () => { state = (Math.imul(state, 1664525) + 1013904223) >>> 0; return state / 0x100000000; }, clusters = grouped(samples).map(cluster => ({familyIds: cluster[0].familyIds, model: totalLogLoss(cluster, item => score(item, model)), constant: totalLogLoss(cluster, () => .5), material: totalLogLoss(cluster, materialScore), legacy: totalLogLoss(cluster, item => score(item, legacy))})), families = [...new Set(samples.flatMap(sample => sample.familyIds ?? []))].sort(), familyMode = families.length >= 4 && samples.every(sample => sample.familyIds?.length === 2);
  for (let iteration = 0; iteration < iterations; iteration += 1) {
    let modelLoss = 0, constantLoss = 0, materialLoss = 0, legacyLoss = 0;
    if (familyMode) {
      const counts = new Map<string, number>(); for (let draw = 0; draw < families.length; draw += 1) { const family = families[Math.floor(random() * families.length)]; counts.set(family, (counts.get(family) ?? 0) + 1); }
      for (const cluster of clusters) { const familyIds = cluster.familyIds!, repetitions = (counts.get(familyIds[0]) ?? 0) * (counts.get(familyIds[1]) ?? 0); modelLoss += cluster.model * repetitions; constantLoss += cluster.constant * repetitions; materialLoss += cluster.material * repetitions; legacyLoss += cluster.legacy * repetitions; }
    } else for (let draw = 0; draw < clusters.length; draw += 1) { const cluster = clusters[Math.floor(random() * clusters.length)]; modelLoss += cluster.model; constantLoss += cluster.constant; materialLoss += cluster.material; legacyLoss += cluster.legacy; }
    if (modelLoss < constantLoss) constant += 1; if (modelLoss < materialLoss) material += 1; if (modelLoss < legacyLoss) legacyWins += 1;
  }
  return {constant: round(constant / iterations), material: round(material / iterations), legacy: round(legacyWins / iterations)};
}
function totalLogLoss(samples: readonly PositionValueSample[], predictor: (sample: PositionValueSample) => number): number { let total = 0; for (const sample of samples) { const probability = clamp(predictor(sample), 1e-7, 1 - 1e-7); total += sample.weight * -(sample.label * Math.log(probability) + (1 - sample.label) * Math.log(1 - probability)); } return total; }
function describeEvidenceDesign(samples: PositionValueSample[]): PositionValueSummary["evidenceDesign"] {
  const familyMode = samples.length > 0 && samples.every(sample => sample.familyIds?.length === 2), familySplits = new Map<string, Set<string>>();
  for (const sample of samples) for (const family of sample.familyIds ?? []) familySplits.set(family, new Set([...(familySplits.get(family) ?? []), sample.split]));
  const familyLeakage = [...familySplits.entries()].filter(([, splits]) => splits.size > 1).map(([family, splits]) => `${family}:${[...splits].sort().join("/")}`).sort(), familiesBySplit = Object.fromEntries((["train", "validation", "test"] as const).map(split => [split, new Set(samples.filter(sample => sample.split === split).flatMap(sample => sample.familyIds ?? [])).size]));
  return {authority: familyMode ? "signed-family-registry" : "legacy-pair-hash", families: familySplits.size, familiesBySplit, familyLeakage, environments: [...new Set(samples.map(sample => sample.environment).filter((value): value is string => Boolean(value)))].sort(), bootstrapUnit: familyMode ? "family-block" : "pair-cluster"};
}
function symmetryError(model: PositionValueModel): number { let maximum = 0; for (let index = 0; index < 100; index += 1) { const vector = POSITION_FEATURES.map((_, feature) => Math.sin((index + 1) * (feature + 3)) * .8), p = sigmoid(dot(vector, model.coefficients)), inverse = sigmoid(dot(vector.map(value => -value), model.coefficients)); maximum = Math.max(maximum, Math.abs(1 - p - inverse)); } return maximum; }
function percentImprovement(baseline: number, value: number): number { return round((baseline - value) / baseline * 100); }
function featureRanges(samples: PositionValueSample[], start: number): Record<string, {minimum: number; maximum: number}> {
  return Object.fromEntries(POSITION_FEATURES.slice(start).map((feature, offset) => {
    let minimum = Number.POSITIVE_INFINITY, maximum = Number.NEGATIVE_INFINITY;
    for (const sample of samples) { const value = sample.features[start + offset]; if (value < minimum) minimum = value; if (value > maximum) maximum = value; }
    return [feature, {minimum: samples.length ? minimum : 0, maximum: samples.length ? maximum : 0}];
  }));
}
function featureIndependence(samples: PositionValueSample[], start: number): {distinctColumns: number; maximumAbsoluteCorrelation: number; highlyCorrelatedPairs: string[]} {
  const columns = POSITION_FEATURES.slice(start).map((feature, offset) => ({feature, values: samples.map(sample => sample.features[start + offset])})), signatures = new Set(columns.map(column => sha256(column.values))), highlyCorrelatedPairs: string[] = []; let maximumAbsoluteCorrelation = 0;
  for (let left = 0; left < columns.length; left += 1) for (let right = left + 1; right < columns.length; right += 1) { const value = Math.abs(correlation(columns[left].values, columns[right].values)); maximumAbsoluteCorrelation = Math.max(maximumAbsoluteCorrelation, value); if (value >= .995) highlyCorrelatedPairs.push(`${columns[left].feature}/${columns[right].feature}=${round(value)}`); }
  return {distinctColumns: signatures.size, maximumAbsoluteCorrelation: round(maximumAbsoluteCorrelation), highlyCorrelatedPairs};
}
function correlation(left: number[], right: number[]): number { const leftMean = left.reduce((sum, value) => sum + value, 0) / Math.max(1, left.length), rightMean = right.reduce((sum, value) => sum + value, 0) / Math.max(1, right.length); let numerator = 0, leftSquare = 0, rightSquare = 0; for (let index = 0; index < left.length; index += 1) { const x = left[index] - leftMean, y = right[index] - rightMean; numerator += x * y; leftSquare += x * x; rightSquare += y * y; } return leftSquare > 0 && rightSquare > 0 ? numerator / Math.sqrt(leftSquare * rightSquare) : 0; }
function mean(values: readonly number[]): number { return values.reduce((sum, value) => sum + value, 0) / Math.max(1, values.length); }
function maximum(values: readonly number[]): number { return values.length ? Math.max(...values) : 0; }
function dot(left: readonly number[], right: readonly number[]): number { return left.reduce((sum, value, index) => sum + value * right[index], 0); }
function sigmoid(value: number): number { return value >= 0 ? 1 / (1 + Math.exp(-value)) : Math.exp(value) / (1 + Math.exp(value)); }
function round(value: number): number { return Math.round(value * 1e6) / 1e6; }
function clamp(value: number, minimum: number, maximum: number): number { return Math.max(minimum, Math.min(maximum, value)); }
function findDecisionFiles(root: string): string[] { const result: string[] = []; walk(root, file => { if (/ai-decisions\.json(?:\.gz)?$/.test(file)) result.push(file); }); return result.sort(); }
function walk(directory: string, visit: (file: string) => void): void { if (!fs.existsSync(directory)) return; for (const entry of fs.readdirSync(directory, {withFileTypes: true})) { const target = path.join(directory, entry.name); if (entry.isDirectory()) walk(target, visit); else visit(target); } }
function existing(directory: string, names: string[]): string | null { for (const name of names) { const file = path.join(directory, name); if (fs.existsSync(file)) return file; } return null; }
function read<T>(file: string): T { const raw = fs.readFileSync(file); return JSON.parse(file.endsWith(".gz") ? zlib.gunzipSync(raw).toString("utf8") : raw.toString("utf8")) as T; }
function optionalJson<T>(file: string): T | null { try { return read<T>(file); } catch { return null; } }
function optionalGzip<T>(file: string): T | null { return optionalJson<T>(file); }
function writeGzip(file: string, value: unknown): void { const temporary = `${file}.${process.pid}.tmp`; fs.writeFileSync(temporary, zlib.gzipSync(`${JSON.stringify(value)}\n`)); fs.renameSync(temporary, file); }
function atomic(file: string, value: unknown): void { const temporary = `${file}.${process.pid}.tmp`; fs.writeFileSync(temporary, `${JSON.stringify(value, null, 2)}\n`, "utf8"); fs.renameSync(temporary, file); }
function fileHash(file: string): string { return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex"); }
function sourceFingerprint(file: string, replay: string | null, end: string | null, familyEvidence: BenchmarkBattleEvidence | null): string { return sha256({featureVersion: POSITION_FEATURE_VERSION, decision: fileHash(file), replay: replay ? fileHash(replay) : null, end: end ? fileHash(end) : null, familyEvidence}); }
function rel(root: string, file: string): string { return path.relative(root, file).replaceAll("\\", "/"); }
function report(summary: PositionValueSummary): string { const test = summary.metrics.test; return [`# Position Value Stage 2`, "", `- Sources/battles/samples: ${summary.sources}/${summary.battles}/${summary.samples}`, `- Evidence authority / families / bootstrap: ${summary.evidenceDesign.authority}/${summary.evidenceDesign.families}/${summary.evidenceDesign.bootstrapUnit}`, `- Family train/validation/test: ${summary.evidenceDesign.familiesBySplit.train}/${summary.evidenceDesign.familiesBySplit.validation}/${summary.evidenceDesign.familiesBySplit.test}; leakage ${summary.evidenceDesign.familyLeakage.length}`, `- Features / structural / varying / distinct structural: ${summary.representation.features}/${summary.representation.structuralFeatures}/${summary.representation.nonConstantStructuralFeatures}/${summary.representation.distinctStructuralColumns}`, `- Base / structural regularization: ${summary.selectedRegularization}/${summary.selectedStructuralRegularization}`, `- Maximum absolute structural correlation: ${summary.representation.maximumAbsoluteStructuralCorrelation}`, `- Train/validation/test clusters: ${summary.split.train.clusters}/${summary.split.validation.clusters}/${summary.split.test.clusters}`, `- Test log loss: model ${test.model.logLoss}, legacy ${test.legacy.logLoss}, constant ${test.constant.logLoss}, material ${test.material.logLoss}`, `- Test Brier: model ${test.model.brier}, constant ${test.constant.brier}, material ${test.material.brier}`, `- Test ECE: ${test.model.ece}`, `- Early/mid/late test log loss: ${summary.testByPhase.early.model.logLoss}/${summary.testByPhase.mid.model.logLoss}/${summary.testByPhase.late.model.logLoss}`, `- Environment pairs beating material: ${Object.values(summary.testByEnvironment).filter(value => value.model.logLoss < value.material.logLoss).length}/${Object.keys(summary.testByEnvironment).length}`, `- Log-loss improvement vs constant/material/legacy: ${summary.testImprovement.vsConstantLogLossPercent}%/${summary.testImprovement.vsMaterialLogLossPercent}%/${summary.testImprovement.vsLegacyLogLossPercent}%`, `- Bootstrap P(better): constant ${summary.testImprovement.bootstrapProbabilityBetterThanConstant}, material ${summary.testImprovement.bootstrapProbabilityBetterThanMaterial}, legacy ${summary.testImprovement.bootstrapProbabilityBetterThanLegacy}`, `- Structural audit: ${summary.audit.healthy ? "pass" : "blocked"}`, `- Activation: shadow-only`, "", ...summary.audit.issues.map(issue => `- [${issue.severity.toUpperCase()}] ${issue.code}: ${issue.message}`), "", "The model estimates pre-action win probability from visible position state and public pre-battle team structure. It does not consume the selected action, candidate scores, personality parameters, or terminal information.", ""].join("\n"); }
