import crypto from "node:crypto";
import {RELATIONAL_ENCODER_VERSION} from "./relationalDecision";
import {managerProgramV3Hash, validateManagerProgramV3, type ManagerProgramV3} from "./managerProgramV3";

export const RELATIONAL_VALIDATION_VERSION = "relational-validation-v1" as const;
export interface RelationalExperimentV3 {
  id: string; level: "single-action" | "continuation-program"; managerId: string; programHash: string; sourceFingerprint: string; familyClusterId: string; environment: string; shortDelta: number; terminalDelta: -1 | 0 | 1; applications: number; evaluations: number; technicalFailure: string | null;
}
export interface RelationalStage4SubmissionV3 {
  schemaVersion: 1; version: typeof RELATIONAL_VALIDATION_VERSION; authority: "stage4-research-only"; domain: "switch"; program: ManagerProgramV3; programHash: string; encoderVersion: typeof RELATIONAL_ENCODER_VERSION; maximumControlledDecisions: 5; ancestorSourceFingerprints: string[]; ancestorFamilyClusterIds: string[]; novel: boolean; supportingManagers: string[]; experiments: RelationalExperimentV3[]; eligible: boolean; reasons: string[]; sha256: string;
}
export interface RelationalFormalCaseV3 {id: string; programHash: string; clusterId: string; environment: string; sourceFingerprint: string; baselineUtility: 0 | .5 | 1; interventionUtility: 0 | .5 | 1; technicalFailure: string | null}
export interface RelationalFormalResultV3 {programHash: string; cases: number; clusters: number; environments: string[]; decisive: number; wins: number; losses: number; neutral: number; rawP: number; holmP: number; environmentConsistent: boolean; eligible: boolean; reasons: string[]}
export interface RelationalCanaryHandoffV3 {schemaVersion: 1; version: typeof RELATIONAL_VALIDATION_VERSION; authority: "controlled-canary-only"; domain: "switch"; seasons: 2; applicationRate: .1; programHash: string; encoderVersion: typeof RELATIONAL_ENCODER_VERSION; maximumControlledDecisions: 5; ancestorSourceFingerprints: string[]; ancestorFamilyClusterIds: string[]; formalEvidenceSha256: string; sha256: string}
export interface RelationalResearchCycleRecord {id: string; archiveFile: string; archiveSha256: string; sourceFingerprints: string[]; familyClusterIds: string[]; programHashes: string[]; eligible: number; completedAt: string}
export interface RelationalResearchCycleHistory {schemaVersion: 2; encoderVersion: typeof RELATIONAL_ENCODER_VERSION; cycles: RelationalResearchCycleRecord[]; sha256: string}
export interface RelationalResearchGenerationState {schemaVersion: 2; encoderVersion: typeof RELATIONAL_ENCODER_VERSION; historySha256: string; completedIndependentCycles: number; failedCycles: number; frozen: boolean; freezeReason: string | null; counterexampleAtlasRequired: boolean; sha256: string}
export interface RelationalFormalCampaignRecord {id: string; sourceIdentitySha256: string; sourceAuthoritySha256: string; archiveFile: string; archiveSha256: string; programHashes: string[]; completedAt: string}
export interface RelationalFormalHistory {schemaVersion: 1; encoderVersion: typeof RELATIONAL_ENCODER_VERSION; campaigns: RelationalFormalCampaignRecord[]; sha256: string}

export function buildRelationalStage4Submission(input: Omit<RelationalStage4SubmissionV3, "schemaVersion" | "version" | "authority" | "domain" | "programHash" | "encoderVersion" | "maximumControlledDecisions" | "eligible" | "reasons" | "sha256">): RelationalStage4SubmissionV3 {
  validateManagerProgramV3(input.program); const programHash = managerProgramV3Hash(input.program), experiments = input.experiments.map(value => ({...value})), ancestors = [...new Set(input.ancestorSourceFingerprints)].sort(), ancestorClusters = [...new Set(input.ancestorFamilyClusterIds)].sort(), supportingManagers = [...new Set(input.supportingManagers)].sort();
  const semantic = {programHash, ancestorSourceFingerprints: ancestors, ancestorFamilyClusterIds: ancestorClusters, novel: input.novel, supportingManagers, experiments}, reasons = relationalStage4Reasons(semantic);
  const core = {schemaVersion: 1 as const, version: RELATIONAL_VALIDATION_VERSION, authority: "stage4-research-only" as const, domain: "switch" as const, program: structuredClone(input.program), programHash, encoderVersion: RELATIONAL_ENCODER_VERSION, maximumControlledDecisions: 5 as const, ancestorSourceFingerprints: ancestors, ancestorFamilyClusterIds: ancestorClusters, novel: input.novel, supportingManagers, experiments, eligible: !reasons.length, reasons}; const result = {...core, sha256: digest(core)}; assertRelationalStage4Submission(result); return result;
}

export function assertRelationalStage4Submission(value: RelationalStage4SubmissionV3): void { const {sha256, ...core} = value, reasons = relationalStage4Reasons(value); if (value.schemaVersion !== 1 || value.version !== RELATIONAL_VALIDATION_VERSION || value.authority !== "stage4-research-only" || value.domain !== "switch" || value.encoderVersion !== RELATIONAL_ENCODER_VERSION || value.maximumControlledDecisions !== 5 || managerProgramV3Hash(value.program) !== value.programHash || digest(core) !== sha256 || value.eligible !== !value.reasons.length || JSON.stringify(value.reasons) !== JSON.stringify(reasons) || JSON.stringify(value.supportingManagers) !== JSON.stringify([...new Set(value.supportingManagers)].sort()) || JSON.stringify(value.ancestorSourceFingerprints) !== JSON.stringify([...new Set(value.ancestorSourceFingerprints)].sort()) || JSON.stringify(value.ancestorFamilyClusterIds) !== JSON.stringify([...new Set(value.ancestorFamilyClusterIds)].sort())) throw new Error("Invalid relational Stage-4 submission"); }

export function evaluateRelationalFormalValidation(submissions: readonly RelationalStage4SubmissionV3[], cases: readonly RelationalFormalCaseV3[], options: {minimumClusters?: number; minimumEnvironments?: number; minimumDecisive?: number} = {}): RelationalFormalResultV3[] {
  submissions.forEach(assertRelationalStage4Submission); const minimumClusters = options.minimumClusters ?? 24, minimumEnvironments = options.minimumEnvironments ?? 2, minimumDecisive = options.minimumDecisive ?? 8;
  const preliminary = submissions.map(submission => {
    const rows = cases.filter(value => value.programHash === submission.programHash), successful = rows.filter(value => !value.technicalFailure), deltas = successful.map(value => value.interventionUtility - value.baselineUtility), wins = deltas.filter(value => value > 0).length, losses = deltas.filter(value => value < 0).length, decisive = wins + losses, environments = [...new Set(successful.map(value => value.environment))].sort(), byEnvironment = environments.map(environment => successful.filter(value => value.environment === environment).reduce((sum, value) => sum + value.interventionUtility - value.baselineUtility, 0));
    const reasons = [...submission.reasons]; if (!submission.eligible) reasons.push("stage4-not-eligible"); if (rows.some(value => value.technicalFailure)) reasons.push("technical-failure"); if (new Set(successful.map(value => value.clusterId)).size < minimumClusters) reasons.push("insufficient-independent-clusters"); if (environments.length < minimumEnvironments) reasons.push("insufficient-environments"); if (decisive < minimumDecisive) reasons.push("insufficient-decisive-cases"); if (losses > 0) reasons.push("formal-counterexample"); if (byEnvironment.some(value => value < 0)) reasons.push("environment-direction-conflict"); if (new Set(successful.map(value => value.sourceFingerprint)).size !== successful.length || successful.some(value => submission.ancestorSourceFingerprints.includes(value.sourceFingerprint)) || successful.some(value => submission.ancestorFamilyClusterIds.includes(value.clusterId))) reasons.push("formal-source-not-independent");
    return {programHash: submission.programHash, cases: successful.length, clusters: new Set(successful.map(value => value.clusterId)).size, environments, decisive, wins, losses, neutral: successful.length - decisive, rawP: exactOneSidedSignP(wins, losses), holmP: 1, environmentConsistent: byEnvironment.every(value => value >= 0), eligible: false, reasons: [...new Set(reasons)]};
  });
  const ordered = [...preliminary].sort((a, b) => a.rawP - b.rawP || a.programHash.localeCompare(b.programHash)); let prior = 0; ordered.forEach((value, index) => { value.holmP = round(Math.max(prior, Math.min(1, value.rawP * (ordered.length - index)))); prior = value.holmP; });
  return preliminary.map(value => { const corrected = ordered.find(row => row.programHash === value.programHash)!; const reasons = [...corrected.reasons]; if (corrected.holmP >= .05) reasons.push("holm-corrected-significance-not-met"); return {...corrected, eligible: !reasons.length, reasons}; });
}

export function buildRelationalCanaryHandoff(submission: RelationalStage4SubmissionV3, formal: RelationalFormalResultV3, formalEvidenceSha256: string): RelationalCanaryHandoffV3 {
  assertRelationalStage4Submission(submission); if (!submission.eligible || !formal.eligible || formal.programHash !== submission.programHash || !hex(formalEvidenceSha256)) throw new Error("Relational program has not passed formal validation");
  const core = {schemaVersion: 1 as const, version: RELATIONAL_VALIDATION_VERSION, authority: "controlled-canary-only" as const, domain: "switch" as const, seasons: 2 as const, applicationRate: .1 as const, programHash: submission.programHash, encoderVersion: RELATIONAL_ENCODER_VERSION, maximumControlledDecisions: 5 as const, ancestorSourceFingerprints: [...submission.ancestorSourceFingerprints], ancestorFamilyClusterIds: [...submission.ancestorFamilyClusterIds], formalEvidenceSha256}; return {...core, sha256: digest(core)};
}
export function relationalCanaryRegressionP(losses: number, wins: number): number { if (!Number.isInteger(losses) || losses < 0 || !Number.isInteger(wins) || wins < 0) throw new Error("Invalid Canary terminal counts"); return exactOneSidedSignP(losses, wins); }

export function buildRelationalResearchCycleHistory(cycles: readonly RelationalResearchCycleRecord[] = []): RelationalResearchCycleHistory { const core = {schemaVersion: 2 as const, encoderVersion: RELATIONAL_ENCODER_VERSION, cycles: cycles.map(value => ({...value, sourceFingerprints: [...value.sourceFingerprints], familyClusterIds: [...value.familyClusterIds], programHashes: [...value.programHashes]}))}; return {...core, sha256: digest(core)}; }
export function buildRelationalFormalHistory(campaigns: readonly RelationalFormalCampaignRecord[] = []): RelationalFormalHistory { const core = {schemaVersion: 1 as const, encoderVersion: RELATIONAL_ENCODER_VERSION, campaigns: campaigns.map(value => ({...value, programHashes: [...value.programHashes]}))}; return {...core, sha256: digest(core)}; }
export function buildRelationalResearchGeneration(historySha256: string): RelationalResearchGenerationState { if (!hex(historySha256)) throw new Error("Research generation requires a signed history"); return signedGeneration({schemaVersion: 2, encoderVersion: RELATIONAL_ENCODER_VERSION, historySha256, completedIndependentCycles: 0, failedCycles: 0, frozen: false, freezeReason: null, counterexampleAtlasRequired: false}); }
export function assertRelationalResearchCycleHistory(value: RelationalResearchCycleHistory): void { const {sha256, ...core} = value; if (value.schemaVersion !== 2 || value.encoderVersion !== RELATIONAL_ENCODER_VERSION || !hex(sha256) || digest(core) !== sha256 || !Array.isArray(value.cycles)) throw new Error("Invalid relational research cycle history signature"); }
export function assertRelationalResearchGeneration(value: RelationalResearchGenerationState): void { const {sha256, ...core} = value; if (value.schemaVersion !== 2 || value.encoderVersion !== RELATIONAL_ENCODER_VERSION || !hex(value.historySha256) || !hex(sha256) || digest(core) !== sha256 || value.completedIndependentCycles < 0 || value.failedCycles < 0 || value.failedCycles > value.completedIndependentCycles) throw new Error("Invalid relational research generation signature"); }
export function assertRelationalFormalHistory(value: RelationalFormalHistory): void { const {sha256, ...core} = value, sources = value.campaigns?.map(campaign => campaign.sourceIdentitySha256) ?? [], programs = value.campaigns?.flatMap(campaign => campaign.programHashes) ?? []; if (value.schemaVersion !== 1 || value.encoderVersion !== RELATIONAL_ENCODER_VERSION || !hex(sha256) || digest(core) !== sha256 || !Array.isArray(value.campaigns) || new Set(value.campaigns.map(campaign => campaign.id)).size !== value.campaigns.length || new Set(sources).size !== sources.length || new Set(programs).size !== programs.length || value.campaigns.some(campaign => !hex(campaign.id) || !hex(campaign.sourceIdentitySha256) || !hex(campaign.sourceAuthoritySha256) || !hex(campaign.archiveSha256) || !campaign.archiveFile || !campaign.programHashes.length || new Set(campaign.programHashes).size !== campaign.programHashes.length || campaign.programHashes.some(program => !hex(program)))) throw new Error("Invalid relational formal history signature"); }

export function updateRelationalResearchGeneration(state: RelationalResearchGenerationState | null, outcome: "candidate" | "no-candidate" | "falsified", historySha256: string): RelationalResearchGenerationState {
  if (!hex(historySha256)) throw new Error("Research generation requires a signed history"); if (state) assertRelationalResearchGeneration(state); const prior = state ?? buildRelationalResearchGeneration(historySha256); if (prior.frozen) return signedGeneration({...withoutSha(prior), historySha256});
  const failed = outcome === "candidate" ? 0 : prior.failedCycles + 1, completed = prior.completedIndependentCycles + 1, frozen = failed >= 2;
  return signedGeneration({schemaVersion: 2, encoderVersion: RELATIONAL_ENCODER_VERSION, historySha256, completedIndependentCycles: completed, failedCycles: failed, frozen, freezeReason: frozen ? "two-independent-v3-cycles-without-a-formal-candidate" : null, counterexampleAtlasRequired: frozen});
}

function exactOneSidedSignP(wins: number, losses: number): number { const n = wins + losses; if (!n) return 1; let sum = 0; for (let k = wins; k <= n; k += 1) sum += combination(n, k) * .5 ** n; return round(sum); }
function relationalStage4Reasons(value: Pick<RelationalStage4SubmissionV3, "programHash" | "ancestorSourceFingerprints" | "ancestorFamilyClusterIds" | "novel" | "supportingManagers" | "experiments">): string[] {
  const reasons: string[] = [], successful = value.experiments.filter(experiment => !experiment.technicalFailure), single = successful.filter(experiment => experiment.level === "single-action"), continuation = successful.filter(experiment => experiment.level === "continuation-program"), continuationSources = new Set(continuation.map(experiment => experiment.sourceFingerprint)), continuationClusters = new Set(continuation.map(experiment => experiment.familyClusterId)), continuationEnvironments = new Set(continuation.map(experiment => experiment.environment));
  if (value.experiments.some(experiment => experiment.technicalFailure)) reasons.push("technical-failure"); if (!value.novel) reasons.push("mechanism-not-novel"); if (new Set(value.supportingManagers).size < 2) reasons.push("fewer-than-two-supporting-managers");
  if (single.length < 4) reasons.push("fewer-than-four-single-action-replications"); if (continuation.length < 12 || continuationSources.size < 12 || continuationClusters.size < 12) reasons.push("fewer-than-twelve-independent-continuation-replications"); if (continuationEnvironments.size < 2) reasons.push("fewer-than-two-continuation-environments"); if (successful.some(experiment => experiment.terminalDelta < 0)) reasons.push("stage4-counterexample");
  if (average(continuation.map(experiment => experiment.shortDelta)) <= 0) reasons.push("continuation-short-horizon-not-positive"); if (continuation.reduce((sum, experiment) => sum + experiment.terminalDelta, 0) < 0) reasons.push("continuation-terminal-net-regression");
  if (new Set(single.map(experiment => experiment.sourceFingerprint)).size !== single.length || new Set(continuation.map(experiment => experiment.sourceFingerprint)).size !== continuation.length) reasons.push("duplicate-experiment-source-within-level"); if (value.experiments.some(experiment => experiment.programHash !== value.programHash || !experiment.id || !experiment.sourceFingerprint || !experiment.familyClusterId || !experiment.environment || !Number.isFinite(experiment.shortDelta) || ![-1, 0, 1].includes(experiment.terminalDelta) || experiment.evaluations < 0 || experiment.evaluations > 5 || experiment.applications < 0 || experiment.applications > experiment.evaluations)) reasons.push("program-freeze-or-scope-mismatch");
  if (value.experiments.some(experiment => value.ancestorSourceFingerprints.includes(experiment.sourceFingerprint))) reasons.push("ancestor-source-reuse"); if (value.experiments.some(experiment => value.ancestorFamilyClusterIds.includes(experiment.familyClusterId))) reasons.push("ancestor-family-cluster-reuse"); return reasons;
}
function combination(n: number, k: number): number { let value = 1; for (let index = 1; index <= Math.min(k, n - k); index += 1) value = value * (n - index + 1) / index; return value; }
function average(values: readonly number[]): number { return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; }
function round(value: number): number { return Math.round((value + Number.EPSILON) * 1e6) / 1e6; }
function digest(value: unknown): string { return crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function hex(value: string): boolean { return /^[a-f0-9]{64}$/.test(value); }
function withoutSha(value: RelationalResearchGenerationState): Omit<RelationalResearchGenerationState, "sha256"> { const {sha256: _sha256, ...core} = value; return core; }
function signedGeneration(core: Omit<RelationalResearchGenerationState, "sha256">): RelationalResearchGenerationState { return {...core, sha256: digest(core)}; }
