import type {WhiteBoxCandidateTrace} from "./decision";

export interface AcquisitionAssistGate {version:"white-box-acquisition-assist-v1";recommended:boolean;hardRejections:string[];metrics:{rationalDelta:number;finalDelta:number;strengthRegression:number;structuralDelta:number;improvedStructuralSignals:number};thresholds:{minimumRationalDelta:.03;minimumFinalDelta:.03;maximumStrengthRegression:.05;minimumStructuralDelta:0;minimumImprovedStructuralSignals:2}}

export function evaluateAcquisitionAssistGate(incumbent:WhiteBoxCandidateTrace|undefined,candidate:WhiteBoxCandidateTrace|undefined):AcquisitionAssistGate{const hardRejections:string[]=[],rationalDelta=delta(incumbent?.rationalScore,candidate?.rationalScore),finalDelta=delta(incumbent?.finalScore,candidate?.finalScore),strengthRegression=Math.max(0,contribution(incumbent,"acquire.strength")-contribution(candidate,"acquire.strength")),structuralIds=["acquire.rolefit","acquire.completion","acquire.system"],structuralDeltas=structuralIds.map(id=>contribution(candidate,id)-contribution(incumbent,id)),structuralDelta=sum(structuralDeltas),improvedStructuralSignals=structuralDeltas.filter(value=>value>1e-12).length;if(!incumbent||!candidate)hardRejections.push("missing-candidate-evidence");else{if(!incumbent.eligible||!candidate.eligible)hardRejections.push("ineligible-candidate");if(!candidate.reasonable)hardRejections.push("candidate-outside-reasonable-band");if(rationalDelta<.03)hardRejections.push("insufficient-rational-gain");if(finalDelta<.03)hardRejections.push("insufficient-final-gain");if(strengthRegression>.05+1e-12)hardRejections.push("excessive-strength-regression");if(structuralDelta<-1e-12)hardRejections.push("structural-regression");if(improvedStructuralSignals<2)hardRejections.push("insufficient-structural-signals");}return{version:"white-box-acquisition-assist-v1",recommended:hardRejections.length===0,hardRejections,metrics:{rationalDelta:round(rationalDelta),finalDelta:round(finalDelta),strengthRegression:round(strengthRegression),structuralDelta:round(structuralDelta),improvedStructuralSignals},thresholds:{minimumRationalDelta:.03,minimumFinalDelta:.03,maximumStrengthRegression:.05,minimumStructuralDelta:0,minimumImprovedStructuralSignals:2}};}
function contribution(value:WhiteBoxCandidateTrace|undefined,id:string):number{return value?.contributions.find(entry=>entry.id===id)?.value??0;}
function delta(before:number|null|undefined,after:number|null|undefined):number{return before==null||after==null?Number.NEGATIVE_INFINITY:after-before;}
function sum(values:number[]):number{return values.reduce((total,value)=>total+value,0);}
function round(value:number):number{return Number.isFinite(value)?Math.round((value+Number.EPSILON)*1e6)/1e6:value;}
