import path from "node:path";
import {classifyBattleFrontierContext,type BattleCandidateFrontierAudit,type BattleFrontierContext,type BattleFrontierMechanism} from "./battleCandidateFrontier";

export type BattleResearchDirection="better"|"neutral"|"worse";
export interface CompletedBattleResearchCase {id:string;managerId:string;mechanismId:string;game:string;decisionOrdinal:number;side:string;selected:string;alternative:string;direction:BattleResearchDirection}
type ContextAxis=keyof BattleFrontierContext;
interface Condition {axis:ContextAxis;value:string}
interface Candidate {mechanismId:string;baseMechanismId:string;baseMechanism:BattleFrontierMechanism;condition:Condition;caseIds:string[];decisiveCaseIds:string[];cases:number;managers:number;better:number;neutral:number;worse:number;decisive:number;informationScore:number;sensitivity:{minimumJaccard:number;minimumDecisiveRetention:number;variants:Array<{shift:-1|1;cases:number;managers:number;decisive:number;jaccard:number;decisiveRetention:number}>}}

export interface BattleConditionalWorkbench {
  schemaVersion:1;
  activationStatus:"shadow-only";
  evidenceStatus:"post-deployment-exploratory";
  authority:"no-activation-authority";
  inputs:{completedCases:number;excludedCases:number;matchedCases:number;unmatchedCases:number;evaluatedConditions:number;rejectedUnstableConditions:number};
  hypotheses:Array<{id:string;title:string;observationalCandidate:false;researchEligible:true;evidenceStatus:"post-deployment-exploratory";causalConclusion:null;eligibleManagerIds:string[];coverage:{cases:number;managers:number;better:number;neutral:number;worse:number};condition:{baseMechanismId:string;axis:ContextAxis;value:string}}>;
  managerMechanisms:Array<{managerId:string;mechanismId:string;baseMechanism:BattleFrontierMechanism;condition:Condition;examples:any[]}>;
  candidates:Candidate[];
  validity:{causalClaimsAllowed:false;activationAllowed:false;notes:string[]};
}

export function discoverBattleConditionalMechanisms(frontier:BattleCandidateFrontierAudit,cases:CompletedBattleResearchCase[],options:{excludedMechanismIds?:string[];minimumCases?:number;minimumManagers?:number;minimumDecisive?:number;maximumPerMechanism?:number;minimumBoundaryJaccard?:number}={}):BattleConditionalWorkbench{
  const excluded=new Set(options.excludedMechanismIds??[]),minimumCases=options.minimumCases??3,minimumManagers=options.minimumManagers??3,minimumDecisive=options.minimumDecisive??1,maximumPerMechanism=options.maximumPerMechanism??4,minimumBoundaryJaccard=options.minimumBoundaryJaccard??.5;
  const examples=new Map<string,any>();for(const row of frontier.managerMechanisms)for(const example of row.examples)examples.set(exampleKey(row.managerId,`battle-frontier-${row.mechanism}-v1`,path.resolve(frontier.source,example.game),example),example);
  const eligible=cases.filter(research=>baseMechanism(research.mechanismId)&&!excluded.has(baseMechanismId(research.mechanismId)!)),matched:Array<{research:CompletedBattleResearchCase;example:any;baseMechanism:BattleFrontierMechanism;baseMechanismId:string}>=[];
  for(const research of eligible){const base=baseMechanism(research.mechanismId)!,baseId=`battle-frontier-${base}-v1`,example=examples.get(exampleKey(research.managerId,baseId,path.resolve(research.game),research));if(example?.context&&example?.contextMetrics)matched.push({research,example,baseMechanism:base,baseMechanismId:baseId});}
  const groups=new Map<string,Array<typeof matched[number]>>();
  for(const row of matched)for(const [axis,value] of Object.entries(row.example.context) as Array<[ContextAxis,string]>){if(value==="unknown")continue;const key=`${row.baseMechanismId}|${axis}|${value}`,values=groups.get(key)??[];values.push(row);groups.set(key,values);}
  const candidates:Candidate[]=[],eligibleGroups=[...groups.entries()].filter(([,rows])=>rows.length>=minimumCases&&new Set(rows.map(row=>row.research.managerId)).size>=minimumManagers&&rows.filter(row=>row.research.direction!=="neutral").length>=minimumDecisive);let rejectedUnstableConditions=0;
  for(const [key,rows] of eligibleGroups){const [baseMechanismId,axis,value]=key.split("|") as [string,ContextAxis,string],managers=new Set(rows.map(row=>row.research.managerId)).size,better=rows.filter(row=>row.research.direction==="better").length,worse=rows.filter(row=>row.research.direction==="worse").length,neutral=rows.length-better-worse,decisive=better+worse,baseRows=matched.filter(row=>row.baseMechanismId===baseMechanismId),baseIds=new Set(rows.map(row=>row.research.id)),decisiveIds=new Set(rows.filter(row=>row.research.direction!=="neutral").map(row=>row.research.id));
    const variants=([-1,1] as const).map(shift=>{const shifted=baseRows.filter(row=>classifyBattleFrontierContext(row.example.contextMetrics,shift)[axis]===value),shiftedIds=new Set(shifted.map(row=>row.research.id)),intersection=[...baseIds].filter(id=>shiftedIds.has(id)).length,union=new Set([...baseIds,...shiftedIds]).size,retained=[...decisiveIds].filter(id=>shiftedIds.has(id)).length;return{shift,cases:shifted.length,managers:new Set(shifted.map(row=>row.research.managerId)).size,decisive:shifted.filter(row=>row.research.direction!=="neutral").length,jaccard:round(intersection/Math.max(1,union)),decisiveRetention:round(retained/Math.max(1,decisiveIds.size))};}),minimumJaccard=Math.min(...variants.map(row=>row.jaccard)),minimumDecisiveRetention=Math.min(...variants.map(row=>row.decisiveRetention));
    if(minimumJaccard<minimumBoundaryJaccard||minimumDecisiveRetention<minimumBoundaryJaccard||variants.some(row=>row.cases<minimumCases||row.managers<minimumManagers||row.decisive<minimumDecisive)){rejectedUnstableConditions+=1;continue;}const base=baseMechanism(baseMechanismId)!;candidates.push({mechanismId:`battle-context-${base}-${slug(axis)}-${slug(value)}-v1`,baseMechanismId,baseMechanism:base,condition:{axis,value},caseIds:[...baseIds].sort(),decisiveCaseIds:[...decisiveIds].sort(),cases:rows.length,managers,better,neutral,worse,decisive,informationScore:round(decisive/rows.length+Math.min(1,rows.length/10)*.25),sensitivity:{minimumJaccard,minimumDecisiveRetention,variants}});}
  const selected:Candidate[]=[];
  for(const baseMechanismId of [...new Set(candidates.map(value=>value.baseMechanismId))].sort()){const signatures=new Set<string>();for(const candidate of candidates.filter(value=>value.baseMechanismId===baseMechanismId).sort(compare)){const signature=candidate.decisiveCaseIds.join("|");if(signatures.has(signature))continue;signatures.add(signature);selected.push(candidate);if(selected.filter(value=>value.baseMechanismId===baseMechanismId).length>=maximumPerMechanism)break;}}
  const managerMechanisms:any[]=[];
  for(const candidate of selected)for(const row of frontier.managerMechanisms.filter(value=>value.mechanism===candidate.baseMechanism)){const filtered=row.examples.filter(example=>example.context?.[candidate.condition.axis]===candidate.condition.value);if(filtered.length)managerMechanisms.push({managerId:row.managerId,mechanismId:candidate.mechanismId,baseMechanism:candidate.baseMechanism,condition:candidate.condition,examples:filtered});}
  return{schemaVersion:1,activationStatus:"shadow-only",evidenceStatus:"post-deployment-exploratory",authority:"no-activation-authority",inputs:{completedCases:cases.length,excludedCases:cases.length-eligible.length,matchedCases:matched.length,unmatchedCases:eligible.length-matched.length,evaluatedConditions:eligibleGroups.length,rejectedUnstableConditions},hypotheses:selected.map(candidate=>({id:candidate.mechanismId,title:`Test ${title(candidate.baseMechanism)} when ${candidate.condition.axis} is ${candidate.condition.value}`,observationalCandidate:false,researchEligible:true,evidenceStatus:"post-deployment-exploratory",causalConclusion:null,eligibleManagerIds:managerMechanisms.filter(value=>value.mechanismId===candidate.mechanismId).map(value=>value.managerId).sort(),coverage:{cases:candidate.cases,managers:candidate.managers,better:candidate.better,neutral:candidate.neutral,worse:candidate.worse},condition:{baseMechanismId:candidate.baseMechanismId,...candidate.condition}})),managerMechanisms,candidates:selected,validity:{causalClaimsAllowed:false,activationAllowed:false,notes:["Conditions use decision-time context only; battle outcomes are never action features.","Subgroups are post-deployment discoveries and require fresh prospective evidence.","Adjacent threshold shifts must preserve sample, manager, decisive-case, and Jaccard gates.","Candidates sharing the same decisive cases are deduplicated before managers see the menu.","Candidate ranking controls research menu size and cannot activate battle behavior."]}};
}

function exampleKey(managerId:string,mechanismId:string,game:string,value:{decisionOrdinal:number;side:string;selected:string;alternative:string}):string{return[managerId,mechanismId,path.resolve(game).replaceAll("\\","/").toLowerCase(),value.decisionOrdinal,value.side,value.selected,value.alternative].join("|");}
function baseMechanism(mechanismId:string):BattleFrontierMechanism|null{const match=mechanismId.match(/^battle-(?:frontier|context)-(alternate-move|alternate-switch|move-to-switch|switch-to-move)(?:-|$)/);return(match?.[1] as BattleFrontierMechanism|undefined)??null;}
function baseMechanismId(mechanismId:string):string|null{const base=baseMechanism(mechanismId);return base?`battle-frontier-${base}-v1`:null;}
function compare(left:Candidate,right:Candidate):number{return right.informationScore-left.informationScore||right.decisive-left.decisive||right.cases-left.cases||left.mechanismId.localeCompare(right.mechanismId);}
function slug(value:string):string{return value.replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function title(value:BattleFrontierMechanism):string{return value.replaceAll("-"," ");}
function round(value:number):number{return Math.round((value+Number.EPSILON)*1e6)/1e6;}
