import crypto from "node:crypto";

export interface CausalBoundaryCase {evidenceId: string; managerId: string; mechanismId: string; season: number; sourceOutcome: "win" | "loss"; effect: -1 | 0 | 1}
export interface CausalBoundaryAuditResult {
  schemaVersion: 1; activationStatus: "shadow-only"; hypothesisId: "loss-conditioned-lineup-intervention-v1";
  conclusion: "retrospective-boundary-candidate" | "boundary-not-ready"; direction: "loss-higher" | "win-higher" | "neutral"; decisionTimeAvailable: false; activationEligible: false;
  metrics: {cases: number; managers: number; mechanisms: number; seasons: number; lossCases: number; winCases: number; lossMean: number; winMean: number; effectDifference: number; stratifiedPermutationP: number; matchedManagers: number; managerSignPermutationP: number};
  byMechanism: Array<{mechanismId: string; cases: number; lossMean: number; winMean: number; effectDifference: number}>;
  leaveOneMechanismOut: Array<{excludedMechanismId: string; effectDifference: number}>;
  thresholds: {minimumCases: number; minimumManagers: number; minimumMechanisms: number; minimumSeasons: number; minimumEffectDifference: number; maximumPermutationP: number; requireLeaveOneMechanismDirection: boolean};
}

export function auditCausalOutcomeBoundary(casesInput: readonly CausalBoundaryCase[], permutations = 10000): CausalBoundaryAuditResult {
  if (!Number.isInteger(permutations) || permutations < 100 || permutations > 100000) throw new Error("Boundary audit permutations must be 100..100000");
  const cases = [...casesInput]; validateCases(cases);
  const mechanisms = [...new Set(cases.map(value => value.mechanismId))].sort(), seasons = [...new Set(cases.map(value => value.season))].sort((a, b) => a - b), managers = new Set(cases.map(value => value.managerId));
  const observed = difference(cases), rng = random(`loss-conditioned-lineup-intervention-v1:${cases.map(value => value.evidenceId).sort().join("|")}`), strata = grouped(cases, value => `${value.mechanismId}:${value.season}`);
  let extreme = 1;
  for (let iteration = 0; iteration < permutations; iteration++) { const permuted = [...cases]; for (const indices of strata.values()) { const labels = indices.map(index => permuted[index].sourceOutcome); shuffle(labels, rng); indices.forEach((index, offset) => { permuted[index] = {...permuted[index], sourceOutcome: labels[offset]}; }); } if (Math.abs(difference(permuted)) + 1e-12 >= Math.abs(observed)) extreme++; }
  const managerGroups = grouped(cases, value => value.managerId), contrasts = [...managerGroups.values()].map(indices => difference(indices.map(index => cases[index]))).filter(Number.isFinite); let managerExtreme = 1; const observedManagerMean = mean(contrasts);
  for (let iteration = 0; iteration < permutations; iteration++) { const value = mean(contrasts.map(contrast => rng() < .5 ? contrast : -contrast)); if (Math.abs(value) + 1e-12 >= Math.abs(observedManagerMean)) managerExtreme++; }
  const byMechanism = mechanisms.map(mechanismId => summarizeMechanism(mechanismId, cases.filter(value => value.mechanismId === mechanismId))), leaveOneMechanismOut = mechanisms.map(excludedMechanismId => ({excludedMechanismId, effectDifference: round(difference(cases.filter(value => value.mechanismId !== excludedMechanismId)))}));
  const thresholds = {minimumCases: 48, minimumManagers: 20, minimumMechanisms: 3, minimumSeasons: 3, minimumEffectDifference: .2, maximumPermutationP: .05, requireLeaveOneMechanismDirection: true}, stratifiedPermutationP = round(extreme / (permutations + 1)), sameDirection = leaveOneMechanismOut.every(value => Math.sign(value.effectDifference) === Math.sign(observed) && Math.sign(observed) !== 0);
  const ready = cases.length >= thresholds.minimumCases && managers.size >= thresholds.minimumManagers && mechanisms.length >= thresholds.minimumMechanisms && seasons.length >= thresholds.minimumSeasons && Math.abs(observed) >= thresholds.minimumEffectDifference && stratifiedPermutationP <= thresholds.maximumPermutationP && sameDirection;
  const losses = cases.filter(value => value.sourceOutcome === "loss"), wins = cases.filter(value => value.sourceOutcome === "win");
  return {schemaVersion: 1, activationStatus: "shadow-only", hypothesisId: "loss-conditioned-lineup-intervention-v1", conclusion: ready ? "retrospective-boundary-candidate" : "boundary-not-ready", direction: observed > 0 ? "loss-higher" : observed < 0 ? "win-higher" : "neutral", decisionTimeAvailable: false, activationEligible: false, metrics: {cases: cases.length, managers: managers.size, mechanisms: mechanisms.length, seasons: seasons.length, lossCases: losses.length, winCases: wins.length, lossMean: round(mean(losses.map(value => value.effect))), winMean: round(mean(wins.map(value => value.effect))), effectDifference: round(observed), stratifiedPermutationP, matchedManagers: contrasts.length, managerSignPermutationP: round(managerExtreme / (permutations + 1))}, byMechanism, leaveOneMechanismOut, thresholds};
}

export interface ProspectiveBoundaryCase extends CausalBoundaryCase {previousLoss?: boolean; recentThreeLossRateHigh?: boolean; seasonLossRateHigh?: boolean}
export interface ProspectiveProxyScreen {schemaVersion: 1; activationStatus: "shadow-only"; conclusion: "exploratory-proxy-signal" | "no-prospective-proxy-ready"; activationEligible: false; screens: Array<{proxy: "previous-loss" | "recent-three-loss-rate-high" | "season-loss-rate-high"; cases: number; managers: number; high: number; low: number; highMean: number; lowMean: number; effectDifference: number; permutationP: number; adjustedQ: number}>}
export function auditProspectiveBoundaryProxies(cases: readonly ProspectiveBoundaryCase[], permutations = 10000): ProspectiveProxyScreen {
  validateCases([...cases]); const definitions = [{proxy: "previous-loss" as const, value: (item: ProspectiveBoundaryCase) => item.previousLoss}, {proxy: "recent-three-loss-rate-high" as const, value: (item: ProspectiveBoundaryCase) => item.recentThreeLossRateHigh}, {proxy: "season-loss-rate-high" as const, value: (item: ProspectiveBoundaryCase) => item.seasonLossRateHigh}];
  const screens = definitions.map(definition => { const eligible = cases.filter(item => definition.value(item) !== undefined), labels = eligible.map(item => Boolean(definition.value(item))), observed = binaryDifference(eligible, labels), strata = grouped(eligible, item => `${item.mechanismId}:${item.season}`), rng = random(`${definition.proxy}:${eligible.map(item => item.evidenceId).sort().join("|")}`); let extreme = 1; for (let iteration = 0; iteration < permutations; iteration++) { const permuted = [...labels]; for (const indices of strata.values()) { const values = indices.map(index => permuted[index]); shuffle(values, rng); indices.forEach((index, offset) => { permuted[index] = values[offset]; }); } if (Math.abs(binaryDifference(eligible, permuted)) + 1e-12 >= Math.abs(observed)) extreme++; } const high = eligible.filter((_, index) => labels[index]), low = eligible.filter((_, index) => !labels[index]); return {proxy: definition.proxy, cases: eligible.length, managers: new Set(eligible.map(item => item.managerId)).size, high: high.length, low: low.length, highMean: round(mean(high.map(item => item.effect))), lowMean: round(mean(low.map(item => item.effect))), effectDifference: round(observed), permutationP: round(extreme / (permutations + 1)), adjustedQ: 1}; });
  const ordered = [...screens].sort((left, right) => left.permutationP - right.permutationP); let prior = 1; for (let index = ordered.length - 1; index >= 0; index--) { prior = Math.min(prior, ordered[index].permutationP * ordered.length / (index + 1)); ordered[index].adjustedQ = round(prior); }
  const signal = screens.some(value => value.cases >= 48 && value.managers >= 20 && Math.abs(value.effectDifference) >= .2 && value.adjustedQ <= .1); return {schemaVersion: 1, activationStatus: "shadow-only", conclusion: signal ? "exploratory-proxy-signal" : "no-prospective-proxy-ready", activationEligible: false, screens};
}

function summarizeMechanism(mechanismId: string, cases: CausalBoundaryCase[]): {mechanismId: string; cases: number; lossMean: number; winMean: number; effectDifference: number} { const loss = cases.filter(value => value.sourceOutcome === "loss").map(value => value.effect), win = cases.filter(value => value.sourceOutcome === "win").map(value => value.effect); return {mechanismId, cases: cases.length, lossMean: round(mean(loss)), winMean: round(mean(win)), effectDifference: round(mean(loss) - mean(win))}; }
function difference(cases: CausalBoundaryCase[]): number { const loss = cases.filter(value => value.sourceOutcome === "loss").map(value => value.effect), win = cases.filter(value => value.sourceOutcome === "win").map(value => value.effect); return loss.length && win.length ? mean(loss) - mean(win) : Number.NaN; }
function binaryDifference(cases: readonly CausalBoundaryCase[], labels: readonly boolean[]): number { const high = cases.filter((_, index) => labels[index]).map(value => value.effect), low = cases.filter((_, index) => !labels[index]).map(value => value.effect); return high.length && low.length ? mean(high) - mean(low) : 0; }
function validateCases(cases: CausalBoundaryCase[]): void { if (!cases.length || new Set(cases.map(value => value.evidenceId)).size !== cases.length) throw new Error("Boundary audit requires unique evidence"); for (const value of cases) if (!value.evidenceId || !value.managerId || !/^[a-z0-9-]+-v\d+$/.test(value.mechanismId) || !Number.isInteger(value.season) || value.season < 1 || !["win", "loss"].includes(value.sourceOutcome) || ![-1, 0, 1].includes(value.effect)) throw new Error(`Invalid boundary evidence: ${value.evidenceId}`); }
function grouped<T>(values: T[], key: (value: T) => string): Map<string, number[]> { const result = new Map<string, number[]>(); values.forEach((value, index) => { const id = key(value), indices = result.get(id) ?? []; indices.push(index); result.set(id, indices); }); return result; }
function mean(values: number[]): number { return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : Number.NaN; }
function shuffle<T>(values: T[], rng: () => number): void { for (let index = values.length - 1; index > 0; index--) { const target = Math.floor(rng() * (index + 1)); [values[index], values[target]] = [values[target], values[index]]; } }
function random(seed: string): () => number { let state = Number.parseInt(crypto.createHash("sha256").update(seed).digest("hex").slice(0, 8), 16) || 1; return () => { state ^= state << 13; state ^= state >>> 17; state ^= state << 5; return (state >>> 0) / 0x100000000; }; }
function round(value: number): number { return Number.isFinite(value) ? Math.round((value + Number.EPSILON) * 1e6) / 1e6 : 0; }
