import fs from "node:fs";
import path from "node:path";
import type {WhiteBoxCandidateTrace,WhiteBoxShadowSummary} from "./decision";
import {evaluateLineupAssistGate,type WhiteBoxLineupAssistGate} from "./lineup";

export interface WhiteBoxOpportunityScenario {id:string;band:number;styleLimit:number;styleScale:number}
export interface WhiteBoxOpportunityCase {run:string;decisionId:string;actor:string;season:number|null;incumbent:string;selected:string;rationalDelta:number;styleDelta:number;assistGate:WhiteBoxLineupAssistGate|null}
export interface WhiteBoxOpportunitySummary {schemaVersion:1;runs:number;comparisons:number;completeComparisons:number;incompleteComparisons:number;completeByDomain:Record<string,number>;incompleteByDomain:Record<string,number>;scenarios:Array<WhiteBoxOpportunityScenario&{differences:number;assistApproved:number;rate:number;byDomain:Record<string,number>;cases:WhiteBoxOpportunityCase[]}>}

export function scanWhiteBoxOpportunities(inputs:string[],scenarios:WhiteBoxOpportunityScenario[],options:{maximumCasesPerScenario?:number;domains?:string[]}={}):WhiteBoxOpportunitySummary {
  const maximumCasesPerScenario=options.maximumCasesPerScenario??100;if(!Number.isInteger(maximumCasesPerScenario)||maximumCasesPerScenario<1)throw new Error("maximumCasesPerScenario must be positive");
  const domainFilter=options.domains?.length?new Set(options.domains):null;
  const roots=inputs.flatMap(discoverRuns),results=scenarios.map(scenario=>({...scenario,differences:0,assistApproved:0,rate:0,byDomain:{} as Record<string,number>,cases:[] as WhiteBoxOpportunityCase[]}));let comparisons=0,completeComparisons=0;const completeByDomain:Record<string,number>={},incompleteByDomain:Record<string,number>={};
  for(const root of roots)for(const {record,trace,season}of shadows(root)){const traceDomain=trace.decisionId.split(":",1)[0]||"unknown";if(domainFilter&&!domainFilter.has(traceDomain))continue;comparisons+=1;if(trace.candidateCount!==trace.candidates.length){incompleteByDomain[traceDomain]=(incompleteByDomain[traceDomain]??0)+1;continue;}completeComparisons+=1;completeByDomain[traceDomain]=(completeByDomain[traceDomain]??0)+1;const baseline=select(trace.candidates,trace.reasonableBand,trace.styleContributionLimit,1);if(baseline!==trace.comparison.shadow)throw new Error(`Stored white-box selection cannot be replayed: ${trace.decisionId}`);
    for(const result of results){const selected=select(trace.candidates,result.band,result.styleLimit,result.styleScale);if(!selected||selected===trace.comparison.incumbent)continue;result.differences+=1;const domain=trace.decisionId.split(":",1)[0]||"unknown";result.byDomain[domain]=(result.byDomain[domain]??0)+1;const incumbent=trace.candidates.find(candidate=>candidate.id===trace.comparison.incumbent),candidate=trace.candidates.find(entry=>entry.id===selected),assistGate=domain==="lineup"&&incumbent&&candidate?evaluateLineupAssistGate(scaleStyle(incumbent,result.styleScale),scaleStyle(candidate,result.styleScale)):null;if(assistGate?.recommended)result.assistApproved+=1;if(result.cases.length<maximumCasesPerScenario&&incumbent&&candidate)result.cases.push({run:path.basename(root),decisionId:trace.decisionId,actor:String(record.actor??"unknown"),season,incumbent:incumbent.id,selected,rationalDelta:round(candidate.rationalScore!-incumbent.rationalScore!),styleDelta:round(clamp(candidate.rawStyleScore!*result.styleScale,result.styleLimit)-clamp(incumbent.rawStyleScore!*result.styleScale,result.styleLimit)),assistGate});}}
  for(const result of results)result.rate=completeComparisons?result.differences/completeComparisons:0;return{schemaVersion:1,runs:roots.length,comparisons,completeComparisons,incompleteComparisons:comparisons-completeComparisons,completeByDomain,incompleteByDomain,scenarios:results};
}

export function whiteBoxOpportunityMarkdown(summary:WhiteBoxOpportunitySummary):string {const lines=["# 白箱 AI 人格参数机会扫描","",`- 运行：${summary.runs}`,`- 完整/全部决策：${summary.completeComparisons}/${summary.comparisons}`,"","| 场景 | 合理带 | 人格上限 | 人格倍率 | 差异 | 门禁通过 | 比率 | 领域 |","|---|---:|---:|---:|---:|---:|---:|---|"];for(const scenario of summary.scenarios)lines.push(`| ${scenario.id} | ${scenario.band} | ${scenario.styleLimit} | ${scenario.styleScale} | ${scenario.differences} | ${scenario.assistApproved} | ${(scenario.rate*100).toFixed(2)}% | ${Object.entries(scenario.byDomain).map(([key,value])=>`${key}:${value}`).join("、")||"无"} |`);lines.push("","这些差异仅表示可形成受控人格选择，不代表竞技收益，也不会自动激活。","");return lines.join("\n");}

function discoverRuns(input:string):string[]{const root=path.resolve(input);if(fs.existsSync(path.join(root,"dynasty-state.json")))return[root];if(!fs.existsSync(root))throw new Error(`Opportunity input does not exist: ${root}`);return fs.readdirSync(root,{withFileTypes:true}).filter(entry=>entry.isDirectory()&&fs.existsSync(path.join(root,entry.name,"dynasty-state.json"))).map(entry=>path.join(root,entry.name)).sort();}
function shadows(root:string):Array<{record:any;trace:WhiteBoxShadowSummary;season:number|null}>{const state=read<any>(path.join(root,"dynasty-state.json")),records=(state.decisionRecords??[]).map((record:any)=>({record,season:Number.isInteger(record.context?.season)?record.context.season:null}));for(const entry of fs.readdirSync(root,{withFileTypes:true}).filter(entry=>entry.isDirectory()&&/^season-\d+$/.test(entry.name))){const file=path.join(root,entry.name,"decision-ledger.json"),season=Number(entry.name.slice("season-".length));if(fs.existsSync(file))records.push(...(read<any>(file).records??[]).map((record:any)=>({record,season})));}const found:Array<{record:any;trace:WhiteBoxShadowSummary;season:number|null}>=[];for(const source of records)walk(source.record.context,value=>{if(isShadow(value))found.push({record:source.record,trace:value,season:source.season});});return found;}
function select(candidates:WhiteBoxCandidateTrace[],band:number,styleLimit:number,styleScale:number):string|null{const eligible=candidates.filter(candidate=>candidate.eligible&&candidate.rationalScore!==null&&candidate.rawStyleScore!==null),best=eligible.length?Math.max(...eligible.map(candidate=>candidate.rationalScore!)):null;if(best===null)return null;return eligible.filter(candidate=>best-candidate.rationalScore!<=band).map(candidate=>({candidate,final:round(candidate.rationalScore!+clamp(candidate.rawStyleScore!*styleScale,styleLimit))})).sort((left,right)=>right.final-left.final||right.candidate.rationalScore!-left.candidate.rationalScore!||left.candidate.id.localeCompare(right.candidate.id))[0]?.candidate.id??null;}
function scaleStyle(candidate:WhiteBoxCandidateTrace,scale:number):WhiteBoxCandidateTrace{return{...candidate,rawStyleScore:candidate.rawStyleScore===null?null:round(candidate.rawStyleScore*scale),contributions:candidate.contributions.map(entry=>(entry.source==="personality"||entry.source==="memory"||entry.source==="context")?{...entry,value:round(entry.value*scale)}:{...entry})};}
function isShadow(value:any):value is WhiteBoxShadowSummary{return Boolean(value?.version==="white-box-decision-v1"&&value.comparison&&Array.isArray(value.candidates)&&Number.isFinite(value.reasonableBand)&&Number.isFinite(value.styleContributionLimit));}
function walk(value:any,visit:(value:any)=>void):void{if(!value||typeof value!=="object")return;visit(value);if(isShadow(value))return;for(const child of Array.isArray(value)?value:Object.values(value))walk(child,visit);}
function clamp(value:number,limit:number):number{return Math.max(-limit,Math.min(limit,value));}
function round(value:number):number{return Math.round((value+Number.EPSILON)*1e6)/1e6;}
function read<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}
