import fs from "node:fs";
import path from "node:path";
import type {ProgramDecisionLabelDirection} from "./programDecisionLabels";

interface SeriesResult {id:string;left:string;right:string;leftPairs:number;rightPairs:number;splitPairs:number;games?:Array<{winner?:string|null}>}
interface SideResult {pairs:number;opponentPairs:number;splitPairs:number;gameWins:number;gameLosses:number;pairMargin:number;gameMargin:number}
export interface ProgramDecisionLocalOutcome {scope:"series";seriesId:string;control:SideResult;experiment:SideResult;delta:{pairMargin:number;gameMargin:number};direction:ProgramDecisionLabelDirection}
export function readLineupLocalOutcome(controlRoot:string,experimentRoot:string,season:number,decisionId:string,managerId:string):ProgramDecisionLocalOutcome{const suffix=`:${managerId}`;if(!decisionId.startsWith("lineup:")||!decisionId.endsWith(suffix))throw new Error(`Cannot parse lineup decision ${decisionId}`);const decisionSeriesId=decisionId.slice("lineup:".length,-suffix.length),seriesId=decisionSeriesId.replace(/-tiebreak-\d+$/,""),control=findSeries(controlRoot,season,seriesId),experiment=findSeries(experimentRoot,season,seriesId),left=side(control,managerId),right=side(experiment,managerId),pairMargin=right.pairMargin-left.pairMargin,gameMargin=right.gameMargin-left.gameMargin,direction:ProgramDecisionLabelDirection=pairMargin>0||pairMargin===0&&gameMargin>0?"better":pairMargin<0||pairMargin===0&&gameMargin<0?"worse":"neutral";return{scope:"series",seriesId,control:left,experiment:right,delta:{pairMargin,gameMargin},direction};}
function findSeries(root:string,season:number,id:string):SeriesResult{const file=path.join(root,`season-${String(season).padStart(2,"0")}`,"season.json"),value=JSON.parse(fs.readFileSync(file,"utf8")),playoffs=value.playoffs??{},series=[...(value.league??[]),...(playoffs.wildcards??[]),...(playoffs.playIns??[]),...(playoffs.quarters??[]),...(playoffs.semifinals??[]),...(playoffs.final?[playoffs.final]:[])].filter((entry:any)=>entry?.id===id);if(series.length!==1)throw new Error(`Expected one series ${id} in ${file}, found ${series.length}`);return series[0];}function side(series:SeriesResult,managerId:string):SideResult{const isLeft=series.left===managerId;if(!isLeft&&series.right!==managerId)throw new Error(`Manager ${managerId} did not play series ${series.id}`);const pairs=isLeft?series.leftPairs:series.rightPairs,opponentPairs=isLeft?series.rightPairs:series.leftPairs,gameWins=(series.games??[]).filter(game=>game.winner===managerId).length,gameLosses=(series.games??[]).filter(game=>game.winner&&game.winner!==managerId).length;return{pairs,opponentPairs,splitPairs:series.splitPairs,gameWins,gameLosses,pairMargin:pairs-opponentPairs,gameMargin:gameWins-gameLosses};}
